{
  "hash": "1d016a2e93bdc28e95312393ce5ebc9a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"7 · Compare two paired groups\"\ndescription: \"Paired t test, Wilcoxon signed-rank test, McNemar's test and stratified Cox regression: the same patients measured twice, or matched pairs.\"\nengine: knitr\ntoc-depth: 2\n---\n\n\n\n<!-- data-checksum: 7318dedd9cebb731bf62c12faf3ff8ee -->\n\n**Paired** data come in twos that belong together: the same patient before and after surgery, two raters measuring the same X-ray, or two patients matched to each other on age, sex and BMI. Paired tests compare each patient with themselves (or with their match), which removes the patient-to-patient variation that unpaired tests have to wade through. If your two groups are different patients, use [page 6](06-two-unpaired-groups.qmd) instead.\n\n::: {.callout-note}\n## 💡 How every section on this page works\nEach section answers one question about the practice data. Its first code block loads the packages and the data, so you can jump straight to the section you need. Run that section's blocks in order, top to bottom.\n\nTo keep the code short, the examples use every case, including the 80 patients who had both sides operated on. In a real study, decide how to handle them ([page 3](../foundations/03-distributions.qmd#paired)) and say what you did.\n:::\n\n::: {.callout-warning}\n## ⚠️ Watch out: only complete pairs count\nA paired test can only use patients measured at **both** times. Patients who missed a visit drop out, and if they differ from the rest (for example, the patients who did badly stop coming back), the result is biased. Always report how many patients had both measurements. [Mixed models](../beyond/16-mixed-models.qmd#why-mixed-models) can use everyone's data, including incomplete follow-up.\n:::\n\n## Paired t test {#paired-t}\n\n**The question:** Does patients' physical health, measured by the VR-12 physical component score (PCS), improve from before surgery to 1 year after?\n\n### When to use it\n\n- Each patient (or matched pair) gives **two measurements** of the same thing.\n- The **differences** between the two measurements are roughly normal, or there are about 30 or more pairs. The assumption is about the differences, not about each measurement on its own.\n- Pairs are independent of each other.\n- If the differences are skewed, or the measurements are bounded or ordinal → the [Wilcoxon signed-rank test](#wilcoxon-signed-rank).\n\n### Look at the data first\n\nPaired data need to be **wide**: one row per patient, with the two measurements side by side ([page 1](../foundations/01-tidy-data.qmd#reshaping) shows how to reshape).\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nproms <- read_csv(\"data/proms_long.csv\", show_col_types = FALSE)\n\npcs <- proms |>\n  filter(visit %in% c(\"preop\", \"1yr\")) |>\n  select(case_id, visit, vr12_pcs) |>\n  pivot_wider(names_from = visit, values_from = vr12_pcs, names_prefix = \"pcs_\") |>   # one row per patient\n  filter(!is.na(pcs_preop), !is.na(pcs_1yr)) |>                                       # complete pairs only\n  mutate(change = pcs_1yr - pcs_preop)\n\nnrow(pcs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 436\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(pcs, aes(change)) +\n  geom_histogram(binwidth = 2) +\n  geom_vline(xintercept = 0, linetype = \"dashed\") +   # no change\n  labs(x = \"Change in VR-12 PCS, 1 year minus pre-op\", y = \"Patients\")\n```\n\n::: {.cell-output-display}\n![](07-two-paired-groups_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom scipy import stats\n\nproms = pd.read_csv(\"data/proms_long.csv\")\n\npcs = (proms[proms[\"visit\"].isin([\"preop\", \"1yr\"])]\n       .pivot(index=\"case_id\", columns=\"visit\", values=\"vr12_pcs\")   # one row per patient\n       .dropna())                                                      # complete pairs only\npcs[\"change\"] = pcs[\"1yr\"] - pcs[\"preop\"]\n\nprint(len(pcs))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n436\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, ax = plt.subplots(figsize=(6, 3))\nax.hist(pcs[\"change\"], bins=range(-20, 46, 2))\nax.axvline(0, linestyle=\"--\")                                          # no change\nax.set_xlabel(\"Change in VR-12 PCS, 1 year minus pre-op\")\nax.set_ylabel(\"Patients\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](07-two-paired-groups_files/figure-html/unnamed-chunk-4-1.png)\n:::\n:::\n\n:::\n\n436 patients have both scores. The changes form a roughly symmetric bell, centered well to the right of zero.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npcs_test <- t.test(pcs$pcs_1yr, pcs$pcs_preop, paired = TRUE)   # 1 year minus pre-op\npcs_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  pcs$pcs_1yr and pcs$pcs_preop\nt = 31.201, df = 435, p-value < 2.2e-16\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 12.81701 14.54033\nsample estimates:\nmean difference \n       13.67867 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npcs_test = stats.ttest_rel(pcs[\"1yr\"], pcs[\"preop\"])           # 1 year minus pre-op\nprint(pcs_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTtestResult(statistic=np.float64(31.200689791705805), pvalue=np.float64(4.787953152473408e-113), df=np.int64(435))\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pcs[\"change\"].mean(), pcs_test.confidence_interval())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n13.678669724770641 ConfidenceInterval(low=np.float64(12.817006048756461), high=np.float64(14.54033340078482))\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **t = 31.2, df = 435:** the mean change is 31 standard errors away from zero; df is the number of pairs minus 1.\n- **p < 0.001** (R prints \"p < 2.2e-16\", the smallest p-value it displays): a change this large would be essentially impossible if PCS didn't change on average.\n- **mean difference 13.7:** PCS rose by 13.7 points on average.\n- **95% CI 12.8 to 14.5:** the CI for the mean change.\n\n### Effect size and 95% CI\n\n- The **mean change** with its CI, in points: 13.7 (95% CI 12.8 to 14.5).\n- **Cohen's d~z~** divides the mean change by the standard deviation of the changes: how consistent the improvement was across patients. The usual guide (0.2 small, 0.5 medium, 0.8 large) applies.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffectsize::repeated_measures_d(pcs$pcs_1yr, pcs$pcs_preop, method = \"z\", adjust = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nd (z) |       95% CI\n--------------------\n1.49  | [1.36, 1.63]\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nd_z = pcs[\"change\"].mean() / pcs[\"change\"].std()   # mean change / SD of the changes\nprint(d_z)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1.4942420399763536\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nd~z~ = 1.49 is a very large effect: 93% of patients' PCS went up.\n\n### How to report it\n\n> **Methods:** Change in VR-12 PCS from before surgery to 1 year was assessed with a paired t test in patients with both measurements.\n>\n> **Results:** Of 574 patients with a pre-op PCS, 436 also had a 1-year score. Mean PCS was 31.2 (SD 6.3) before surgery and 44.9 (SD 6.8) at 1 year (mean change 13.7 points, 95% CI 12.8 to 14.5; d~z~ = 1.49; p < 0.001).\n\n::: {.callout-warning}\n## ⚠️ Watch out: don't analyze paired data as unpaired\nRunning an unpaired t test on the pre-op and 1-year columns ignores which scores belong to the same patient. That's wrong even when it happens to give a similar answer, because the test's standard error assumes 872 independent patients when there are only 436. When the two measurements are correlated, as they usually are, the paired test is also more precise.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: paired effect sizes\npingouin's `compute_effsize(x, y, paired=True)` does **not** return d~z~: it returns d~av~ (the mean change divided by the average of the two SDs), 2.08 here. Both are legitimate, but they answer different questions and aren't interchangeable. We compute d~z~ directly so the two languages match; say which one you report.\n:::\n\n## Wilcoxon signed-rank test {#wilcoxon-signed-rank}\n\n**The question:** Did KOOS JR improve from before surgery to 1 year after knee replacement?\n\n### When to use it\n\n- Two paired measurements, and the outcome is **skewed** or has a **ceiling or floor**. The 1-year KOOS JR has a ceiling ([page 3](../foundations/03-distributions.qmd#transform)).\n- For an **ordinal** scale (satisfaction from 1 to 5), count the patients who went up and down and compare the two counts with a binomial test (the **sign test**, [page 5](05-one-group-vs-hypothetical.qmd#binomial-test)).\n- It ranks the sizes of the changes and compares the ranks of improvements with the ranks of declines.\n- Changes of exactly zero carry no information about direction and are dropped.\n- If the changes are roughly normal → the [paired t test](#paired-t).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nproms <- read_csv(\"data/proms_long.csv\", show_col_types = FALSE)\n\nkoos <- proms |>\n  filter(instrument == \"KOOS JR\", visit %in% c(\"preop\", \"1yr\")) |>\n  select(case_id, visit, prom_score) |>\n  pivot_wider(names_from = visit, values_from = prom_score, names_prefix = \"koos_\") |>\n  filter(!is.na(koos_preop), !is.na(koos_1yr)) |>\n  mutate(change = koos_1yr - koos_preop)\n\nggplot(koos, aes(change)) +\n  geom_histogram(binwidth = 2.5) +\n  geom_vline(xintercept = 0, linetype = \"dashed\") +\n  labs(x = \"Change in KOOS JR, 1 year minus pre-op\", y = \"Patients\")\n```\n\n::: {.cell-output-display}\n![](07-two-paired-groups_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\nkoos |> summarise(n = n(), improved = sum(change > 0),\n                  median_preop = median(koos_preop), median_1yr = median(koos_1yr))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n      n improved median_preop median_1yr\n  <int>    <int>        <dbl>      <dbl>\n1   246      246         50.0       85.8\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport pingouin as pg\nimport matplotlib.pyplot as plt\nfrom scipy import stats\n\nproms = pd.read_csv(\"data/proms_long.csv\")\n\nkoos = (proms[(proms[\"instrument\"] == \"KOOS JR\") & proms[\"visit\"].isin([\"preop\", \"1yr\"])]\n        .pivot(index=\"case_id\", columns=\"visit\", values=\"prom_score\")\n        .dropna())\nkoos[\"change\"] = koos[\"1yr\"] - koos[\"preop\"]\n\nfig, ax = plt.subplots(figsize=(6, 3))\nax.hist(koos[\"change\"], bins=np.arange(0, 72.5, 2.5))\nax.axvline(0, linestyle=\"--\")\nax.set_xlabel(\"Change in KOOS JR, 1 year minus pre-op\")\nax.set_ylabel(\"Patients\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](07-two-paired-groups_files/figure-html/unnamed-chunk-14-1.png)\n:::\n\n```{.python .cell-code}\nprint(len(koos), (koos[\"change\"] > 0).sum(), koos[\"preop\"].median(), koos[\"1yr\"].median())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n246 246 49.95 85.8\n```\n\n\n:::\n:::\n\n:::\n\nAll 246 patients with both scores improved. (Real data are rarely this tidy: usually a minority of patients get worse. These data are synthetic.)\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkoos_test <- wilcox.test(koos$koos_1yr, koos$koos_preop, paired = TRUE,\n                         exact = FALSE, correct = FALSE,   # see the R vs Python box\n                         conf.int = TRUE)                  # adds the Hodges-Lehmann estimate and CI\nkoos_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank test\n\ndata:  koos$koos_1yr and koos$koos_preop\nV = 30381, p-value < 2.2e-16\nalternative hypothesis: true location shift is not equal to 0\n95 percent confidence interval:\n 32.29998 35.90004\nsample estimates:\n(pseudo)median \n      34.10001 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# pg.wilcoxon() runs scipy's test and adds the rank-biserial effect size\nkoos_test = pg.wilcoxon(koos[\"1yr\"], koos[\"preop\"], method=\"approx\", correction=False)   # see the R vs Python box\nprint(koos_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          W_val alternative         p_val  RBC      CLES\nWilcoxon    0.0   two-sided  4.179101e-42  1.0  0.964621\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **V = 30381** (R): the sum of the ranks of the improvements. With 246 patients the ranks add up to 246 × 247 / 2 = 30381, so every rank belongs to an improvement. Python reports the smaller sum, the declines: **W_val = 0**.\n- **p < 0.001.**\n- **(pseudo)median 34.1, 95% CI 32.3 to 35.9:** the Hodges-Lehmann estimate of the typical change, below.\n- **RBC = 1.0** (Python): the rank-biserial effect size, below.\n\n### Effect size and 95% CI\n\n- The **Hodges-Lehmann estimate** of the change (the median of the averages of every pair of changes), with its CI, in points.\n- The **matched-pairs rank-biserial correlation (r)**: +1 if every patient improved, −1 if every patient got worse, 0 if improvements and declines balance out. Here it's exactly 1.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkoos_test$estimate                                                # Hodges-Lehmann estimate of the change\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(pseudo)median \n      34.10001 \n```\n\n\n:::\n\n```{.r .cell-code}\nkoos_test$conf.int                                                # its 95% CI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 32.29998 35.90004\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::rank_biserial(koos$koos_1yr, koos$koos_preop, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nr (rank biserial) |       95% CI\n--------------------------------\n1                 | [1.00, 1.00]\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Hodges-Lehmann estimate: the median of the averages of every pair of changes\ndef hodges_lehmann(x):\n    x = np.asarray(x)\n    i, j = np.triu_indices(len(x))          # every pair, including each change with itself\n    return np.median((x[i] + x[j]) / 2)\n\nprint(hodges_lehmann(koos[\"change\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n34.1\n```\n\n\n:::\n\n```{.python .cell-code}\n# scipy has no CI for it, so use a bootstrap: recompute it on 9999 resampled datasets\nboot = stats.bootstrap((koos[\"change\"].to_numpy(),), hodges_lehmann, vectorized=False,\n                       rng=np.random.default_rng(2026))\nprint(boot.confidence_interval)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfidenceInterval(low=np.float64(32.3), high=np.float64(35.900000000000006))\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(koos_test[\"RBC\"])                                           # rank-biserial r\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWilcoxon    1.0\nName: RBC, dtype: float64\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### How to report it\n\n> **Methods:** Because 1-year KOOS JR scores showed a ceiling effect, change from before surgery was assessed with the Wilcoxon signed-rank test, with the Hodges-Lehmann estimate of the change and its 95% CI as the effect size.\n>\n> **Results:** In all 246 patients with both scores, the change was positive. Median KOOS JR was 50.0 (IQR 40.8 to 58.2) before surgery and 85.8 (IQR 75.0 to 94.0) at 1 year (Hodges-Lehmann estimate of the change 34.1 points, 95% CI 32.3 to 35.9; p < 0.001).\n\n::: {.callout-warning}\n## ⚠️ Watch out: \"significant improvement\" isn't the whole story\nA tiny p-value says the scores went up on average; it doesn't say how many patients improved by a **meaningful** amount. For PROMs, also report the proportion of patients whose change reached the minimal clinically important difference (MCID), a within-patient threshold ([page 3](../foundations/03-distributions.qmd#effect-sizes)).\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: Wilcoxon defaults\n- **The statistic.** R reports V, the sum of the ranks of the positive changes. scipy (and pingouin) report the **smaller** of the two sums. The p-values agree.\n- **Exact or approximate.** R uses an exact p-value for fewer than 50 pairs without ties and adds a continuity correction to the normal approximation; scipy's defaults differ. We set `exact = FALSE, correct = FALSE` in R and `method=\"approx\", correction=False` in Python so they match.\n- **The Hodges-Lehmann CI.** R computes it by inverting the test; the Python code uses a bootstrap, a different method. Here they agree to two decimals (32.30 to 35.90); on [page 6](06-two-unpaired-groups.qmd#mann-whitney) they differ a little.\n:::\n\n## McNemar's test {#mcnemar}\n\n**The question:** Are patients more likely to use a walking aid 6 weeks after surgery than before it?\n\n### When to use it\n\n- A **yes/no** outcome measured **twice in the same patients** (or once in each member of a matched pair).\n- It uses only the **discordant pairs**: the patients who changed (no → yes, or yes → no). Patients who stayed the same tell you nothing about the direction of change.\n- The chi-square version needs at least about 10 discordant pairs in total. With fewer, use the **exact** version (see the R vs Python box).\n\n### Look at the data first\n\nFor paired yes/no data, \"looking\" means a 2 × 2 table of **before × after**: each patient appears once.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nproms <- read_csv(\"data/proms_long.csv\", show_col_types = FALSE)\n\naid <- proms |>\n  filter(visit %in% c(\"preop\", \"6wk\")) |>\n  select(case_id, visit, walking_aid) |>\n  pivot_wider(names_from = visit, values_from = walking_aid, names_prefix = \"aid_\") |>\n  filter(!is.na(aid_preop), !is.na(aid_6wk))\n\naid_table <- table(preop = aid$aid_preop, six_weeks = aid$aid_6wk)   # 1 = uses a walking aid\naid_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     six_weeks\npreop   0   1\n    0 134 193\n    1  70 108\n```\n\n\n:::\n\n```{.r .cell-code}\ncolMeans(aid[, c(\"aid_preop\", \"aid_6wk\")])                          # proportion using an aid\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\naid_preop   aid_6wk \n0.3524752 0.5960396 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nfrom scipy import stats\nfrom statsmodels.stats.contingency_tables import mcnemar\n\nproms = pd.read_csv(\"data/proms_long.csv\")\n\naid = (proms[proms[\"visit\"].isin([\"preop\", \"6wk\"])]\n       .pivot(index=\"case_id\", columns=\"visit\", values=\"walking_aid\")\n       .dropna())\n\naid_table = pd.crosstab(aid[\"preop\"], aid[\"6wk\"])   # 1 = uses a walking aid\nprint(aid_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n6wk    0.0  1.0\npreop          \n0.0    134  193\n1.0     70  108\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(aid[[\"preop\", \"6wk\"]].mean())                 # proportion using an aid\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nvisit\npreop    0.352475\n6wk      0.596040\ndtype: float64\n```\n\n\n:::\n:::\n\n:::\n\nOf 505 patients seen at both visits, 134 never used an aid and 108 used one at both times. The other 263 changed: **193 started** using an aid and **70 stopped**.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\naid_test <- mcnemar.test(aid_table)   # with a continuity correction, R's default\naid_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMcNemar's Chi-squared test with continuity correction\n\ndata:  aid_table\nMcNemar's chi-squared = 56.593, df = 1, p-value = 5.36e-14\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\naid_test = mcnemar(aid_table.to_numpy(), exact=False, correction=True)   # chi-square version, as in R\nprint(aid_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npvalue      5.3598068806119586e-14\nstatistic   56.59315589353612\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **McNemar's chi-squared = 56.6, df = 1:** how lopsided the 193 vs 70 split is, compared with the even split you'd expect if walking-aid use hadn't changed.\n- **p < 0.001.**\n\n### Effect size and 95% CI\n\nThe effect size for McNemar's test is the **discordant-pair odds ratio**: patients who started using an aid divided by patients who stopped, 193 / 70. Its exact CI comes from a binomial test on the discordant pairs.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstarted <- aid_table[\"0\", \"1\"]    # no aid before, aid at 6 weeks\nstopped <- aid_table[\"1\", \"0\"]    # aid before, no aid at 6 weeks\n\nstarted / stopped                                    # discordant-pair odds ratio\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.757143\n```\n\n\n:::\n\n```{.r .cell-code}\nci <- binom.test(started, started + stopped)$conf.int  # CI for the share of changers who started\nci / (1 - ci)                                        # turned into a CI for the odds ratio\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.087169 3.678298\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nstarted = int(aid_table.loc[0, 1])    # no aid before, aid at 6 weeks\nstopped = int(aid_table.loc[1, 0])    # aid before, no aid at 6 weeks\n\nprint(started / stopped)                                                # discordant-pair odds ratio\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2.757142857142857\n```\n\n\n:::\n\n```{.python .cell-code}\nci = stats.binomtest(started, started + stopped).proportion_ci(method=\"exact\")   # share of changers who started\nprint(ci.low / (1 - ci.low), ci.high / (1 - ci.high))                   # turned into a CI for the odds ratio\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2.0871688376583153 3.6782978561318966\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nPatients were 2.8 times as likely to start using an aid as to stop (95% CI 2.1 to 3.7).\n\n### How to report it\n\n> **Methods:** Walking-aid use before surgery and at 6 weeks was compared with McNemar's test, with the discordant-pair odds ratio and its exact 95% CI as the effect size.\n>\n> **Results:** Among 505 patients assessed at both visits, 35.2% used a walking aid before surgery and 59.6% at 6 weeks; 193 patients started and 70 stopped using an aid (discordant-pair odds ratio 2.76, 95% CI 2.09 to 3.68; p < 0.001).\n\n::: {.callout-warning}\n## ⚠️ Watch out: no chi-square or Fisher's test on paired yes/no data\nA common mistake is to tabulate \"aid yes/no\" against \"pre-op / 6 weeks\" and run an ordinary chi-square test. That table counts each patient twice, as if 1010 independent patients had been studied. McNemar's test uses each patient once, through the before × after table.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: chi-square or exact?\nR's `mcnemar.test()` gives the chi-square version, with a continuity correction unless `correct = FALSE`. statsmodels' `mcnemar()` gives the **exact** (binomial) version unless you set `exact=False`. With few discordant pairs (under about 10), the exact version is the right one: in R, run `binom.test(started, started + stopped)`.\n:::\n\n## Stratified Cox regression {#stratified-cox}\n\n**The question:** Among patients matched on procedure, age, sex, BMI and ASA class, is the revision risk higher with implant C than with implant A?\n\n### When to use it\n\n- The outcome is **time until an event**, and the patients come in **matched pairs** (or sets), or the two \"patients\" are the two joints of one person.\n- A Cox model **stratified** by pair lets each pair have its own baseline risk, and compares implants only **within** pairs. The decision table calls this *conditional proportional hazards regression*.\n- Only pairs in which one patient was revised while the other was still being followed tell the model anything; with few events, expect a wide CI.\n- [Page 14](../survival/14-cox-regression.qmd) covers Cox regression in full.\n\n### Look at the data first\n\nThe matched file has one row per patient and a `set_id` shared by each matched set. Each set holds one patient with each implant (A, B and C); here we keep A and C, which makes pairs.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(survival)\n\nmatched <- read_csv(\"data/matched_sets.csv\", show_col_types = FALSE)\n\npairs <- matched |>\n  filter(implant %in% c(\"A\", \"C\")) |>\n  mutate(revised = as.integer(event_status == 1))   # 1 = revised; deaths and censoring = 0\n\npairs |> select(set_id, implant, age, sex, bmi, followup_years, revised) |> head(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  set_id implant   age sex      bmi followup_years revised\n  <chr>  <chr>   <dbl> <chr>  <dbl>          <dbl>   <int>\n1 M001   C          67 Male    32.5           5.79       1\n2 M001   A          67 Male    35.3           2.44       0\n3 M002   C          64 Female  31.4           0.04       1\n4 M002   A          61 Female  31.3           8.67       0\n```\n\n\n:::\n\n```{.r .cell-code}\npairs |> group_by(implant) |> summarise(patients = n(), revisions = sum(revised))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  implant patients revisions\n  <chr>      <int>     <int>\n1 A             52         5\n2 C             52        17\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nfrom lifelines import CoxPHFitter\n\nmatched = pd.read_csv(\"data/matched_sets.csv\")\n\npairs = matched[matched[\"implant\"].isin([\"A\", \"C\"])].copy()\npairs[\"revised\"] = (pairs[\"event_status\"] == 1).astype(int)   # 1 = revised; deaths and censoring = 0\n\nprint(pairs[[\"set_id\", \"implant\", \"age\", \"sex\", \"bmi\", \"followup_years\", \"revised\"]].head(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  set_id implant  age     sex   bmi  followup_years  revised\n0   M001       C   67    Male  32.5            5.79        1\n1   M001       A   67    Male  35.3            2.44        0\n3   M002       C   64  Female  31.4            0.04        1\n4   M002       A   61  Female  31.3            8.67        0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pairs.groupby(\"implant\")[\"revised\"].agg([\"count\", \"sum\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         count  sum\nimplant            \nA           52    5\nC           52   17\n```\n\n\n:::\n:::\n\n:::\n\n52 pairs: 5 revisions with implant A and 17 with implant C.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npair_cox <- coxph(Surv(followup_years, revised) ~ implant + strata(set_id), data = pairs)\nsummary(pair_cox)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(followup_years, revised) ~ implant + strata(set_id), \n    data = pairs)\n\n  n= 104, number of events= 22 \n\n           coef exp(coef) se(coef)    z Pr(>|z|)  \nimplantC 1.2528    3.5000   0.5669 2.21   0.0271 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n         exp(coef) exp(-coef) lower .95 upper .95\nimplantC       3.5     0.2857     1.152     10.63\n\nConcordance= 0.778  (se = 0.139 )\nLikelihood ratio test= 5.88  on 1 df,   p=0.02\nWald test            = 4.88  on 1 df,   p=0.03\nScore (logrank) test = 5.56  on 1 df,   p=0.02\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npair_cox = CoxPHFitter().fit(\n    pairs[[\"followup_years\", \"revised\", \"implant\", \"set_id\"]],\n    duration_col=\"followup_years\", event_col=\"revised\",\n    formula=\"implant\", strata=[\"set_id\"],    # one stratum per matched pair\n    fit_options={\"precision\": 1e-9},         # stop only when fully converged; see the R vs Python box\n)\nprint(pair_cox.summary[[\"exp(coef)\", \"exp(coef) lower 95%\", \"exp(coef) upper 95%\", \"p\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              exp(coef)  exp(coef) lower 95%  exp(coef) upper 95%         p\ncovariate                                                                  \nimplant[T.C]        3.5             1.152079            10.632955  0.027128\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **n = 104, number of events = 22:** 52 pairs, 22 revisions.\n- **exp(coef) = 3.5:** the hazard ratio, implant C vs implant A, within pairs.\n- **lower .95 = 1.15, upper .95 = 10.63:** its 95% CI. Wide, because only 22 revisions inform it.\n- **Pr(>|z|) = 0.027:** the p-value for implant.\n- R also prints a likelihood ratio, Wald and score test for the whole model; with one predictor they all test the same thing.\n\n### Effect size and 95% CI\n\nThe **hazard ratio** is the effect size: within matched pairs, the hazard of revision was 3.5 times as high with implant C (95% CI 1.15 to 10.63).\n\n### How to report it\n\n> **Methods:** Revision risk was compared between implants in matched pairs using Cox regression stratified by pair.\n>\n> **Results:** In 52 pairs matched on procedure, age, sex, BMI and ASA class, 17 implant C and 5 implant A procedures were revised (hazard ratio for implant C vs A 3.50, 95% CI 1.15 to 10.63; p = 0.027).\n\n::: {.callout-warning}\n## ⚠️ Watch out: don't ignore the matching\nAn ordinary Cox model on the same 104 patients (without `strata()`) treats them as unrelated. That throws away the matching you worked to create. Here it gives a slightly different answer (hazard ratio 3.60); with stronger matching factors the difference can be large. Analyze matched data as matched.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: strata and convergence\nR puts `strata(set_id)` in the model formula; lifelines takes `strata=[\"set_id\"]` as a separate argument. With so few events and many strata, lifelines' default convergence rule stops a little early (a hazard ratio of 3.4997 instead of 3.5), so we tighten it with `fit_options={\"precision\": 1e-9}`.\n:::\n\n\n\n## Exercises {#exercises}\n\nThe solutions use the packages and data loaded in the sections above, so run the page from the top first.\n\n**1.** Repeat the paired t test for the VR-12 **mental** component score (`vr12_mcs`), pre-op vs 1 year. Report the mean change with its 95% CI and d~z~.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcs <- proms |>\n  filter(visit %in% c(\"preop\", \"1yr\")) |>\n  select(case_id, visit, vr12_mcs) |>\n  pivot_wider(names_from = visit, values_from = vr12_mcs, names_prefix = \"mcs_\") |>\n  filter(!is.na(mcs_preop), !is.na(mcs_1yr))\n\nt.test(mcs$mcs_1yr, mcs$mcs_preop, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  mcs$mcs_1yr and mcs$mcs_preop\nt = 5.8718, df = 435, p-value = 8.569e-09\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 2.290768 4.595930\nsample estimates:\nmean difference \n       3.443349 \n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::repeated_measures_d(mcs$mcs_1yr, mcs$mcs_preop, method = \"z\", adjust = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nd (z) |       95% CI\n--------------------\n0.28  | [0.19, 0.38]\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmcs = proms[proms[\"visit\"].isin([\"preop\", \"1yr\"])].pivot(index=\"case_id\", columns=\"visit\", values=\"vr12_mcs\").dropna()\nmcs_test = stats.ttest_rel(mcs[\"1yr\"], mcs[\"preop\"])\nchange = mcs[\"1yr\"] - mcs[\"preop\"]\nprint(mcs_test, change.mean(), mcs_test.confidence_interval(), change.mean() / change.std())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTtestResult(statistic=np.float64(5.871751242712465), pvalue=np.float64(8.569315094459763e-09), df=np.int64(435)) 3.4433486238532116 ConfidenceInterval(low=np.float64(2.290767601720787), high=np.float64(4.5959296459856365)) 0.281205884027498\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** The mean change in MCS from before surgery to 1 year was 3.4 points (95% CI 2.3 to 4.6; d~z~ = 0.28; p < 0.001).\n\nThat's a small effect, and much smaller than the physical component's 13.7 points.\n:::\n\n**2.** Two raters measured the hip-knee-ankle (HKA) angle on the same 60 knee X-rays (`radiographic_reliability.csv`, session 1). Does rater 2 measure systematically higher than rater 1? Choose the test and run it.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nTwo measurements of the same X-ray are **paired**, and HKA angles are measurements that are roughly normal: the **paired t test**.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreadings <- read_csv(\"data/radiographic_reliability.csv\", show_col_types = FALSE) |>\n  filter(session == 1) |>\n  select(knee_id, rater, hka_deg) |>\n  pivot_wider(names_from = rater, values_from = hka_deg)\n\nt.test(readings$R2, readings$R1, paired = TRUE)   # rater 2 minus rater 1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  readings$R2 and readings$R1\nt = 2.3578, df = 59, p-value = 0.02172\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 0.0761762 0.9304905\nsample estimates:\nmean difference \n      0.5033333 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nreadings = pd.read_csv(\"data/radiographic_reliability.csv\")\nreadings = readings[readings[\"session\"] == 1].pivot(index=\"knee_id\", columns=\"rater\", values=\"hka_deg\")\nhka_test = stats.ttest_rel(readings[\"R2\"], readings[\"R1\"])   # rater 2 minus rater 1\nprint(hka_test, (readings[\"R2\"] - readings[\"R1\"]).mean(), hka_test.confidence_interval())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTtestResult(statistic=np.float64(2.357838822993587), pvalue=np.float64(0.021716482126372363), df=np.int64(59)) 0.5033333333333336 ConfidenceInterval(low=np.float64(0.07617619951405519), high=np.float64(0.9304904671526121))\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** The mean difference between rater 2's and rater 1's readings was 0.50° (95% CI 0.08° to 0.93°; p = 0.022).\n\nA systematic difference this small may not matter clinically; [page 17](../beyond/17-agreement.qmd#bland-altman) shows how to judge agreement between raters properly.\n:::\n\n**3.** Patients improve a lot in the first 3 months. Do they keep improving between 3 months and 1 year? Test it for KOOS JR and write the Results sentence.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nKOOS JR has a ceiling at 1 year, so use the **Wilcoxon signed-rank test**.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlater <- proms |>\n  filter(instrument == \"KOOS JR\", visit %in% c(\"3mo\", \"1yr\")) |>\n  select(case_id, visit, prom_score) |>\n  pivot_wider(names_from = visit, values_from = prom_score, names_prefix = \"koos_\") |>\n  filter(!is.na(koos_3mo), !is.na(koos_1yr))\n\nwilcox.test(later$koos_1yr, later$koos_3mo, paired = TRUE, exact = FALSE, correct = FALSE, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank test\n\ndata:  later$koos_1yr and later$koos_3mo\nV = 21508, p-value < 2.2e-16\nalternative hypothesis: true location shift is not equal to 0\n95 percent confidence interval:\n  8.200009 11.600000\nsample estimates:\n(pseudo)median \n      9.949962 \n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::rank_biserial(later$koos_1yr, later$koos_3mo, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nr (rank biserial) |       95% CI\n--------------------------------\n0.74              | [0.66, 0.80]\n```\n\n\n:::\n\n```{.r .cell-code}\nlater |> summarise(n = n(), better = sum(koos_1yr > koos_3mo), worse = sum(koos_1yr < koos_3mo))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n      n better worse\n  <int>  <int> <int>\n1   225    176    46\n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(later$koos_3mo, c(0.25, 0.50, 0.75))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 25%  50%  75% \n65.4 73.1 81.5 \n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(later$koos_1yr, c(0.25, 0.50, 0.75))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 25%  50%  75% \n73.6 85.2 93.8 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nlater = (proms[(proms[\"instrument\"] == \"KOOS JR\") & proms[\"visit\"].isin([\"3mo\", \"1yr\"])]\n         .pivot(index=\"case_id\", columns=\"visit\", values=\"prom_score\").dropna())\nprint(pg.wilcoxon(later[\"1yr\"], later[\"3mo\"], method=\"approx\", correction=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           W_val alternative         p_val      RBC      CLES\nWilcoxon  3245.0   two-sided  1.556957e-21  0.73781  0.715032\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(len(later), (later[\"1yr\"] > later[\"3mo\"]).sum(), (later[\"1yr\"] < later[\"3mo\"]).sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n225 176 46\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(later[[\"3mo\", \"1yr\"]].quantile([0.25, 0.50, 0.75]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nvisit   3mo   1yr\n0.25   65.4  73.6\n0.50   73.1  85.2\n0.75   81.5  93.8\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Between 3 months and 1 year, the change in KOOS JR was positive in 176 of 225 patients and negative in 46. The median was 73.1 (IQR 65.4 to 81.5) at 3 months and 85.2 (IQR 73.6 to 93.8) at 1 year (Hodges-Lehmann estimate of the change 9.9 points, 95% CI 8.2 to 11.6; rank-biserial r = 0.74; p < 0.001).\n:::\n",
    "supporting": [
      "07-two-paired-groups_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}