{
  "hash": "fb448cb431d9723b1a1a059d61d466ea",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"3 · Distributions & choosing a test\"\ndescription: \"Check whether data look normal, decide which column of the decision table you're in, and understand p-values, effect sizes and confidence intervals.\"\nengine: knitr\n---\n\n\n\n<!-- data-checksum: ffc54e2ad996e1e61ad10ca520e4d588 -->\n\nThe [decision table](../choose-a-test.qmd) asks two questions: what's your **goal** (the row), and what **type of data** do you have (the column). This page is about the second question, especially the hardest part of it: is a measurement \"Gaussian\" (normally distributed) enough for the left-hand column?\n\n## Why the shape of your data matters {#why}\n\nThe tests in the first column (t tests, ANOVA, Pearson correlation) compare **means**, and they assume the data within each group follow a roughly bell-shaped, normal distribution. The tests in the second column (Mann-Whitney, Wilcoxon, Kruskal-Wallis, Spearman) work on **ranks**. They don't assume a normal distribution.\n\n::: {.callout-note}\n## 💡 In plain language\nA mean is a fair summary of a bell-shaped pile of numbers. It's a poor summary of a lopsided one: a few very long hospital stays drag the mean far away from what's typical. Tests built on means inherit that problem. Rank-based tests only ask \"which values are bigger?\", so a few extreme values can't dominate.\n:::\n\n## Look first: histograms and QQ plots {#look}\n\nAlways plot before you test. Here are three variables from the practice data: age, length of stay, and the 1-year PROM score.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort   <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\nproms    <- read_csv(\"data/proms_long.csv\", show_col_types = FALSE)\none_year <- proms |> filter(visit == \"1yr\", !is.na(prom_score))\n\nshapes <- bind_rows(\n  tibble(variable = \"Age, years\",           value = cohort$age),\n  tibble(variable = \"Length of stay, days\", value = cohort$los_days),\n  tibble(variable = \"1-year PROM score\",    value = one_year$prom_score)\n)\n\nggplot(shapes, aes(value)) +\n  geom_histogram(bins = 30) +\n  facet_wrap(~ variable, scales = \"free\")\n```\n\n::: {.cell-output-display}\n![](03-distributions_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom scipy import stats\n\ncohort = pd.read_csv(\"data/cohort.csv\")\nproms = pd.read_csv(\"data/proms_long.csv\")\none_year = proms[(proms[\"visit\"] == \"1yr\") & proms[\"prom_score\"].notna()]\n\nshapes = {\n    \"Age, years\": cohort[\"age\"],\n    \"Length of stay, days\": cohort[\"los_days\"],\n    \"1-year PROM score\": one_year[\"prom_score\"],\n}\n\nfig, axes = plt.subplots(1, 3, figsize=(10, 3))\nfor ax, (name, values) in zip(axes, shapes.items()):\n    ax.hist(values, bins=30)\n    ax.set_title(name)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](03-distributions_files/figure-html/unnamed-chunk-4-1.png)\n:::\n:::\n\n:::\n\n- **Age** is a fairly symmetric bell.\n- **Length of stay** piles up at 0 and 1 days and has a long tail to the right: **right-skewed**.\n- **1-year PROM** piles up against the top of the scale (100), with a tail to the left: a **ceiling effect**.\n\nA **QQ plot** makes the comparison with a normal distribution easier to see. If the data are normal, the points fall on the straight line.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(shapes, aes(sample = value)) +\n  geom_qq() +\n  geom_qq_line() +\n  facet_wrap(~ variable, scales = \"free\")\n```\n\n::: {.cell-output-display}\n![](03-distributions_files/figure-html/unnamed-chunk-5-3.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, axes = plt.subplots(1, 3, figsize=(10, 3))\nfor ax, (name, values) in zip(axes, shapes.items()):\n    stats.probplot(values, plot=ax)\n    ax.set_title(name)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](03-distributions_files/figure-html/unnamed-chunk-6-1.png)\n:::\n:::\n\n:::\n\nHow to read them:\n\n- Points **on the line**: close to normal (age).\n- Points **curving up at the right end**: right skew (length of stay). The flat steps are the many ties at 0, 1 and 2 days.\n- Points **flattening at the top**: a ceiling (the PROM). Many patients share the maximum score.\n\nA number for lopsidedness is the **skewness**: 0 for a symmetric shape, positive for a tail to the right, negative for a tail to the left.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskewness <- function(x) mean((x - mean(x))^3) / sd(x)^3\n\nc(age      = skewness(cohort$age),\n  los      = skewness(cohort$los_days),\n  prom_1yr = skewness(one_year$prom_score))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        age         los    prom_1yr \n-0.05351075  1.60890277 -0.72708937 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef skewness(x):\n    return ((x - x.mean()) ** 3).mean() / x.std() ** 3\n\nprint(pd.Series({\n    \"age\": skewness(cohort[\"age\"]),\n    \"los\": skewness(cohort[\"los_days\"]),\n    \"prom_1yr\": skewness(one_year[\"prom_score\"]),\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nage        -0.053511\nlos         1.608903\nprom_1yr   -0.727089\ndtype: float64\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n::: {.callout-tip}\n## 🔀 R vs Python: skewness functions\nPackages define skewness in slightly different ways (`scipy.stats.skew()` and the R package `e1071` each use their own formula), so the third decimal can differ between them. We wrote the formula out by hand in both languages so the numbers match exactly.\n:::\n\n## Formal tests: Shapiro-Wilk, and why not to trust it alone {#shapiro}\n\nThe **Shapiro-Wilk test** asks: \"Could these numbers plausibly come from a normal distribution?\" A small p-value means \"probably not\". It's tempting to let it decide: p < 0.05 → rank test, otherwise → t test. That rule fails in both directions.\n\n**It's too sensitive with large samples.** Our 600 ages look like a textbook bell curve, yet:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(cohort$age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  cohort$age\nW = 0.99131, p-value = 0.001361\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(stats.shapiro(cohort[\"age\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nShapiroResult(statistic=np.float64(0.991313509056761), pvalue=np.float64(0.001361050169338618))\n```\n\n\n:::\n:::\n\n:::\n\np = 0.001: \"not normal\". With 600 values the test can detect departures far too small to matter. A t test on these ages would be perfectly fine.\n\n**It's too weak with small samples.** Take just the first 10 patients' 1-year PROM scores, from a variable we *know* is skewed with a ceiling:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirst_ten <- head(one_year$prom_score, 10)\nfirst_ten\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 89.3 97.1 82.6 91.6 92.9 96.1 97.5 95.2 84.3 81.2\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(first_ten)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  first_ten\nW = 0.89073, p-value = 0.1728\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfirst_ten = one_year[\"prom_score\"].head(10)\nprint(first_ten.tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[89.3, 97.1, 82.6, 91.6, 92.9, 96.1, 97.5, 95.2, 84.3, 81.2]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(stats.shapiro(first_ten))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nShapiroResult(statistic=np.float64(0.8907320100006012), pvalue=np.float64(0.17282366095024826))\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\np = 0.173: \"no evidence against normality\". Ten values simply can't reveal the shape, which is exactly when the shape matters most.\n\n::: {.callout-warning}\n## ⚠️ Watch out: don't let one p-value choose your test\nDecide from the plots, from what you know about the measurement (a bounded score, a count of days), and from the sample size. Use Shapiro-Wilk as supporting evidence, not as the judge. Then say how you decided in your Methods.\n:::\n\n## Check within groups, not the pooled data {#within-groups}\n\nThe normality assumption is about the data **within each group** (or, for regression models, the **residuals**: what's left after the model's prediction). Pooling groups with different centers can make perfectly normal data look non-normal.\n\nHere's an extreme, made-up example: two groups of 200 values, each exactly normal, 4 standard deviations apart.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_a <- qnorm(ppoints(200), mean = 40, sd = 5)   # 200 perfectly normal values\ngroup_b <- qnorm(ppoints(200), mean = 60, sd = 5)\n\nshapiro.test(group_a)$p.value                       # one group alone\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(c(group_a, group_b))$p.value           # both groups pooled\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.267769e-11\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npoints = (np.arange(1, 201) - 0.5) / 200            # the same probabilities as R's ppoints(200)\ngroup_a = stats.norm.ppf(points, loc=40, scale=5)   # 200 perfectly normal values\ngroup_b = stats.norm.ppf(points, loc=60, scale=5)\n\nprint(stats.shapiro(group_a).pvalue)                              # one group alone\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.999999999999995\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(stats.shapiro(np.concatenate([group_a, group_b])).pvalue)   # both groups pooled\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n9.26776946181564e-11\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nEach group alone passes easily (p ≈ 1). Pooled, p < 0.001: the histogram of the pooled values has two humps, which is not what a normal distribution looks like.\n\nIn real data the groups are usually much closer together. BMI differs by only about a third of a standard deviation between THA and TKA patients, so pooling barely matters. What you see instead is Shapiro-Wilk's verdict bouncing around 0.05 depending on how you slice the same data:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(cohort$bmi)$p.value                         # pooled\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.04425462\n```\n\n\n:::\n\n```{.r .cell-code}\ncohort |>\n  group_by(procedure) |>\n  summarise(shapiro_p = shapiro.test(bmi)$p.value)       # each group on its own\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  procedure shapiro_p\n  <chr>         <dbl>\n1 THA          0.0513\n2 TKA          0.124 \n```\n\n\n:::\n\n```{.r .cell-code}\nfit <- lm(bmi ~ procedure, data = cohort)                # residual = BMI minus its group's mean\nshapiro.test(residuals(fit))$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.306292\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(tibble(residual = residuals(fit)), aes(sample = residual)) +\n  geom_qq() +\n  geom_qq_line()\n```\n\n::: {.cell-output-display}\n![](03-distributions_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(stats.shapiro(cohort[\"bmi\"]).pvalue)               # pooled\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.04425461560416669\n```\n\n\n:::\n\n```{.python .cell-code}\nfor procedure, group in cohort.groupby(\"procedure\"):     # each group on its own\n    print(procedure, stats.shapiro(group[\"bmi\"]).pvalue)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTHA 0.05134144815391971\nTKA 0.12354544393057915\n```\n\n\n:::\n\n```{.python .cell-code}\n# residual = BMI minus its group's mean\nresiduals = cohort[\"bmi\"] - cohort.groupby(\"procedure\")[\"bmi\"].transform(\"mean\")\nprint(stats.shapiro(residuals).pvalue)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.30629201181168864\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, ax = plt.subplots(figsize=(4, 3))\nqq = stats.probplot(residuals, plot=ax)                  # naming the result keeps its numbers out of the output\nplt.show()\n```\n\n::: {.cell-output-display}\n![](03-distributions_files/figure-html/unnamed-chunk-22-1.png)\n:::\n:::\n\n:::\n\n\n\n\n\nPooled p = 0.044, THA alone 0.051, TKA alone 0.124, residuals 0.306: four slices of the same data, on both sides of 0.05, while the QQ plot is a near-perfect straight line. That's the lesson of the previous section again: decide from the plots and what you know about the measurement, not from one p-value.\n\n## How much does normality matter? {#robustness}\n\nLess than you might think, once groups are reasonably large. Tests on means rely on the **average** being roughly normal, not on every individual value. Thanks to the *central limit theorem*, averages of about 30 or more values are close to normal even when the values themselves are skewed.\n\nA practical guide:\n\n- **About 30 or more per group, moderate skew, no wild outliers:** t tests and ANOVA are fine. With very skewed data, the rank test is still often the better summary.\n- **Strong skew or extreme outliers:** use the rank column.\n- **Small groups (under about 15 per group):** plots can't show the shape, and no test has much power. Choose from what you know about the measurement: the rank column for skewed or ordinal measures, the Gaussian column for measurements known to be roughly normal. Expect wide confidence intervals either way.\n- **Ordinal scales, or a ceiling or floor:** use the rank column whatever the sample size (below).\n\n::: {.callout-note collapse=\"true\"}\n## 🔍 Under the hood: the central limit theorem\nIf you take many random samples of size *n* from almost any distribution and compute each sample's mean, those means form a distribution that gets closer to normal as *n* grows. Its spread shrinks in proportion to 1/√n. t tests are built on the distribution of the mean, which is why they tolerate non-normal raw data when *n* is large. \"About 30\" is a rule of thumb, not a law: the more skewed the data, the larger *n* needs to be.\n:::\n\n## Skew, ceilings and transformations {#transform}\n\nA common fix for right skew is to analyze the **logarithm** of the values. For length of stay we have to use log(days + 1), because log(0) doesn't exist.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(skew_raw      = skewness(cohort$los_days),\n  skew_log      = skewness(log1p(cohort$los_days)),   # log1p(x) = log(1 + x)\n  share_zero    = mean(cohort$los_days == 0),\n  ceiling_1yr   = mean(one_year$prom_score == 100))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   skew_raw    skew_log  share_zero ceiling_1yr \n  1.6089028   0.5940202   0.4850000   0.1696035 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\n\nprint(pd.Series({\n    \"skew_raw\": skewness(cohort[\"los_days\"]),\n    \"skew_log\": skewness(np.log1p(cohort[\"los_days\"])),   # log1p(x) = log(1 + x)\n    \"share_zero\": (cohort[\"los_days\"] == 0).mean(),\n    \"ceiling_1yr\": (one_year[\"prom_score\"] == 100).mean(),\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nskew_raw       1.608903\nskew_log       0.594020\nshare_zero     0.485000\nceiling_1yr    0.169604\ndtype: float64\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nThe log helps (skewness falls from about 1.6 to 0.6), but nearly half the stays are 0 days and no transformation can spread out a pile of identical values. Results on a log scale are also harder to explain (\"a 0.3 difference in log(days + 1)\"). Here the rank-based tests are simpler and more honest.\n\nThe same goes for the **ceiling**: 17% of patients score the maximum at 1 year, and no transformation can tell those patients apart. Compare groups with rank-based tests, or report the proportion reaching the ceiling (or a clinically important improvement) as a yes/no outcome.\n\n## Ordinal data always go in the rank column {#ordinal}\n\n**Ordinal** data have an order but no fixed spacing: satisfaction from 1 (\"very dissatisfied\") to 5 (\"very satisfied\"), ASA class, pain \"none / mild / moderate / severe\". The step from 4 to 5 isn't necessarily the same size as the step from 1 to 2, so averages are hard to interpret.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount(cohort, satisfaction_1yr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  satisfaction_1yr     n\n             <dbl> <int>\n1                1    15\n2                2    23\n3                3    52\n4                4   162\n5                5   250\n6               NA    98\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(cohort[\"satisfaction_1yr\"].value_counts(dropna=False).sort_index())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsatisfaction_1yr\n1.0     15\n2.0     23\n3.0     52\n4.0    162\n5.0    250\nNaN     98\nName: count, dtype: int64\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nReport ordinal data as counts and percentages, or as a median (IQR), and compare groups with rank-based tests. Never compute a t test on Likert scores, however many patients you have.\n\n## Paired or unpaired? Matched or unmatched? {#paired}\n\nThe decision table's rows also ask whether your groups are **independent** or **paired/matched**.\n\n- **Unpaired (independent):** different patients in each group. THA vs TKA; Site A vs Site B; men vs women.\n- **Paired:** the same patients measured twice, or natural pairs. Pre-op vs 1-year PROM in the same patients; left vs right knee in bilateral patients; two raters measuring the same X-rays.\n- **Matched:** each patient in one group has been chosen to resemble a patient in the other group (by age, sex, BMI…). Treat matched sets like pairs.\n\n**Bilateral patients need care.** In our cohort, 80 patients appear twice, once for each side, usually in the same group. Their two procedures share the same person's age, sex and health, so they are not independent. Tests that treat every row as a separate patient are then a little overconfident (p-values too small, CIs too narrow). Either analyse one procedure per patient (for example, the first), or use methods built for clustered data, such as [mixed models](../beyond/16-mixed-models.qmd#bilateral). Say which you did.\n\nPairing matters because measurements on the same patient are related. A paired analysis uses each patient as their own control, which removes the patient-to-patient variation and usually gives a more precise answer. Analyzing paired data as if unpaired is one of the most common mistakes in the literature.\n\n## From your question to a test {#flowchart}\n\n```{mermaid}\nflowchart TD\n  A[What is your goal?] --> B[Describe one group]\n  A --> M[Compare one group to a hypothetical value]\n  A --> C[Compare groups or measurements]\n  A --> D[Association or prediction]\n  C --> E{Same patients or matched?}\n  E -->|No| F[Unpaired rows]\n  E -->|Yes| G[Paired / matched rows]\n  B --> H{What type of outcome?}\n  M --> H\n  F --> H\n  G --> H\n  D --> H\n  H -->|Measurement, roughly normal within groups| I[Gaussian column]\n  H -->|Strongly skewed, bounded, or ordinal| J[Rank column]\n  H -->|Yes / no| K[Binomial column]\n  H -->|Time until an event| L[Survival column]\n```\n\nThen find your row and column in the [decision table](../choose-a-test.qmd). Some worked examples from typical orthopaedic research questions:\n\n| Question | Row | Column | Test |\n|------|------|------|------|\n| Do TKA patients have a higher BMI than THA patients? | Two unpaired groups | Gaussian | [Unpaired t test](../catalog/06-two-unpaired-groups.qmd#unpaired-t) |\n| Is length of stay different between Site A and Site B? | Two unpaired groups | Rank (skewed) | [Mann-Whitney test](../catalog/06-two-unpaired-groups.qmd#mann-whitney) |\n| Did KOOS JR improve from pre-op to 1 year? | Two paired groups | Rank (ceiling) | [Wilcoxon signed-rank test](../catalog/07-two-paired-groups.qmd#wilcoxon-signed-rank) |\n| Is 90-day readmission more common in men? | Two unpaired groups | Binomial | [Fisher's exact test](../catalog/06-two-unpaired-groups.qmd#fisher-chi-square) |\n| Does satisfaction differ between surgeons S1, S2 and S3? | Three or more unmatched groups | Rank (ordinal) | [Kruskal-Wallis test](../catalog/08-three-plus-unmatched.qmd#kruskal-wallis) |\n| Does implant design affect revision-free survival? | Three or more unmatched groups | Survival | [Cox regression](../catalog/08-three-plus-unmatched.qmd#cox) |\n\n## p-values, effect sizes and confidence intervals {#effect-sizes}\n\nEvery test on this site reports three things. They answer different questions, and a good Results section gives all three.\n\n- The **effect size** answers *how big?* For example, the difference between two means.\n- The **95% confidence interval (CI)** answers *how sure are we about that size?* It's the range of effect sizes compatible with the data.\n- The **p-value** answers *how surprising would data like these be if there were really no difference at all?* It doesn't measure the size or importance of an effect.\n\nHere's all three for BMI in TKA vs THA, using the unpaired (Welch's) t test from [page 6](../catalog/06-two-unpaired-groups.qmd#unpaired-t):\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmi_test <- t.test(bmi ~ procedure, data = cohort)   # Welch's t test (R's default)\nbmi_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  bmi by procedure\nt = -4.0705, df = 580.09, p-value = 5.341e-05\nalternative hypothesis: true difference in means between group THA and group TKA is not equal to 0\n95 percent confidence interval:\n -2.647347 -0.924101\nsample estimates:\nmean in group THA mean in group TKA \n         29.46185          31.24758 \n```\n\n\n:::\n\n```{.r .cell-code}\ndifference <- unname(bmi_test$estimate[2] - bmi_test$estimate[1])   # TKA minus THA\nci <- -rev(bmi_test$conf.int)                                        # flip to TKA minus THA\ntibble(difference = difference, ci_low = ci[1], ci_high = ci[2], p = bmi_test$p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  difference ci_low ci_high         p\n       <dbl>  <dbl>   <dbl>     <dbl>\n1       1.79  0.924    2.65 0.0000534\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ntka = cohort.loc[cohort[\"procedure\"] == \"TKA\", \"bmi\"]\ntha = cohort.loc[cohort[\"procedure\"] == \"THA\", \"bmi\"]\n\nbmi_test = stats.ttest_ind(tka, tha, equal_var=False)   # Welch's t test\nci = bmi_test.confidence_interval()\n\nprint(pd.Series({\"difference\": tka.mean() - tha.mean(),\n                 \"ci_low\": ci.low, \"ci_high\": ci.high, \"p\": bmi_test.pvalue}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndifference    1.785724\nci_low        0.924101\nci_high       2.647347\np             0.000053\ndtype: float64\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n> TKA patients had a higher BMI than THA patients (mean difference 1.8 kg/m², 95% CI 0.9 to 2.6; p < 0.001).\n\nIs a difference of 1.8 kg/m² *clinically* important? The p-value can't tell you. Ask whether a difference anywhere in the CI (0.9 to 2.6 kg/m²) would change risk or management, for example complication rates. That's clinical judgment, not statistics. **Statistically significant** means only that data like these would be unusual if there were really no difference. It doesn't mean the difference is large or important.\n\n::: {.callout-warning}\n## ⚠️ Watch out: two classic misreadings\n- **\"p = 0.20, so there's no difference.\"** No. It means the data couldn't rule out zero. Look at the CI: if it runs from \"harmful\" to \"very helpful\", the study was too small to say.\n- **\"p < 0.001, so the effect is large.\"** No. With enough patients, tiny differences get tiny p-values. Look at the effect size and CI.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: which group comes first\nR's `t.test(bmi ~ procedure)` subtracts in alphabetical order of the groups (THA minus TKA). `scipy`'s `ttest_ind(tka, tha)` subtracts the second argument from the first. Same answer, opposite sign. Always say which group was subtracted from which, as we did above.\n:::\n\nFor PROMs, judge differences against the **minimal clinically important difference (MCID)**: the smallest change patients notice as meaningful. Published MCIDs vary with the study and the method used to derive them, so cite the one you use. Be careful how you use it: an MCID is a *within-patient* threshold for one person's change. A difference between two groups' averages that is smaller than the MCID doesn't prove no patient benefited, and a larger one doesn't mean every patient did. Comparing the proportion of patients in each group who reached the MCID is often the clearer analysis.\n\n\n\n## Exercises {#exercises}\n\n**1.** Draw a histogram and a QQ plot of the **pre-op** PROM score. Is it closer to normal than the 1-year score? Why might that be?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreop <- proms |> filter(visit == \"preop\", !is.na(prom_score))\nggplot(preop, aes(prom_score)) + geom_histogram(bins = 30)\n```\n\n::: {.cell-output-display}\n![](03-distributions_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(preop, aes(sample = prom_score)) + geom_qq() + geom_qq_line()\n```\n\n::: {.cell-output-display}\n![](03-distributions_files/figure-html/unnamed-chunk-39-2.png){width=672}\n:::\n\n```{.r .cell-code}\nskewness(preop$prom_score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1431982\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npreop = proms[(proms[\"visit\"] == \"preop\") & proms[\"prom_score\"].notna()]\nfig, axes = plt.subplots(1, 2, figsize=(8, 3))\naxes[0].hist(preop[\"prom_score\"], bins=30)\nqq = stats.probplot(preop[\"prom_score\"], plot=axes[1])   # naming the result keeps its numbers out of the output\nplt.show()\n```\n\n::: {.cell-output-display}\n![](03-distributions_files/figure-html/unnamed-chunk-40-1.png)\n:::\n\n```{.python .cell-code}\nprint(skewness(preop[\"prom_score\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.14319820568938835\n```\n\n\n:::\n:::\n\n:::\n\nMuch closer to normal: skewness about 0.1 and the QQ points follow the line. Before surgery, scores sit in the middle of the scale, far from the ceiling. After a successful operation many patients hit the maximum, which creates the ceiling.\n:::\n\n**2.** A fellow wants to compare operative time between surgeons S1 and S2, about 40 cases each. The histogram is fairly symmetric, with a few long cases. Which column of the decision table would you use, and how would you justify it in the Methods?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nThe Gaussian column (an unpaired t test, Welch's version) is reasonable. With about 40 cases per group and a roughly symmetric shape, the t test is robust. Check the QQ plot within each surgeon, and check that the few long cases aren't extreme outliers. Methods: \"Operative time was approximately normally distributed within each group on visual inspection of histograms and QQ plots, and was compared with Welch's t test.\" If the long cases were extreme, a Mann-Whitney test would be the safer choice; say so.\n:::\n\n**3.** A study reports: \"1-year KOOS JR was 2.1 points higher with the new implant (95% CI −1.5 to 5.7; p = 0.25).\" Suppose the MCID for KOOS JR is 14 points. Write one sentence interpreting this result.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\"The study found no clear difference in 1-year KOOS JR between implants: the estimate (2.1 points) and the whole 95% CI (−1.5 to 5.7) are far smaller than the 14-point MCID, so a large average benefit of the new implant is unlikely.\"\n\nThis is stronger than \"not significant\": the CI rules out a large average difference. Strictly, the MCID is a within-patient threshold, so the clearest follow-up analysis compares the proportion of patients in each group who improved by at least 14 points.\n:::\n",
    "supporting": [
      "03-distributions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}