{
  "hash": "ea082faccd915d34ae8f05bc4de9d89b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"12 · Predict a value from several variables\"\ndescription: \"Multiple linear and nonlinear regression, multiple logistic regression and Cox regression: the effect of each predictor, adjusted for the others.\"\nengine: knitr\ntoc-depth: 2\n---\n\n\n\n<!-- data-checksum: 9e548efb7ad4232927ffa99aa2cdeca7 -->\n\nOutcomes rarely depend on one thing. Heavier patients may take longer to operate on, but so may older ones, and knees take longer than hips. **Multiple regression** puts several predictors in one model, so each coefficient is that predictor's effect **with the others held fixed**: adjusted for them. The regressions are the same four as on [page 11](11-predict-from-one.qmd), with more than one predictor.\n\n::: {.callout-note}\n## 💡 How every section on this page works\nEach section answers one question about the practice cohort. Its first code block loads the packages and the data, so you can jump straight to the section you need. Run that section's blocks in order, top to bottom.\n\nTo keep the code short, the examples use every case, including the 80 patients who had both sides operated on. In a real study, decide how to handle them ([page 3](../foundations/03-distributions.qmd#paired)) and say what you did.\n:::\n\n## Multiple linear regression {#multiple-linear-regression}\n\n**The question:** Does BMI still predict operative time once age, sex and procedure are taken into account?\n\n### When to use it\n\n- The outcome is a **measurement**, and you want the effect of each of **several predictors**, adjusted for the others.\n- The assumptions of [simple linear regression](11-predict-from-one.qmd#linear-regression) still apply: straight-line effects, independent patients, and residuals that are roughly normal with an even spread.\n- Choose the predictors **before** looking at the results, from what you know clinically. As a rule of thumb, allow at least 10 to 20 patients per predictor.\n- If an effect may bend → [splines](#multiple-nonlinear-regression). If the outcome is yes/no → [multiple logistic regression](#multiple-logistic-regression).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\n\nggplot(cohort, aes(bmi, op_time_min, colour = procedure)) +\n  geom_point(alpha = 0.5) +\n  labs(x = \"BMI, kg/m²\", y = \"Operative time, minutes\", colour = \"Procedure\")\n```\n\n::: {.cell-output-display}\n![](12-predict-from-several_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncohort |>\n  group_by(procedure) |>\n  summarise(n = n(), mean = mean(op_time_min), sd = sd(op_time_min))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  procedure     n  mean    sd\n  <chr>     <int> <dbl> <dbl>\n1 THA         270  79.8  15.5\n2 TKA         330  88.3  16.2\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport statsmodels.formula.api as smf\n\ncohort = pd.read_csv(\"data/cohort.csv\")\n\nfig, ax = plt.subplots(figsize=(6, 3.5))\nfor procedure, group in cohort.groupby(\"procedure\"):\n    ax.scatter(group[\"bmi\"], group[\"op_time_min\"], alpha=0.5, label=procedure)\nax.set_xlabel(\"BMI, kg/m²\")\nax.set_ylabel(\"Operative time, minutes\")\nlegend = ax.legend(title=\"Procedure\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](12-predict-from-several_files/figure-html/unnamed-chunk-4-1.png)\n:::\n\n```{.python .cell-code}\nprint(cohort.groupby(\"procedure\")[\"op_time_min\"].agg([\"count\", \"mean\", \"std\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           count       mean        std\nprocedure                             \nTHA          270  79.796296  15.457556\nTKA          330  88.312121  16.240485\n```\n\n\n:::\n:::\n\n:::\n\nOperative time rises with BMI for both procedures, and TKAs take longer than THAs on average: 88.3 minutes (SD 16.2) against 79.8 (SD 15.5).\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntime_model <- lm(op_time_min ~ bmi + age + sex + procedure, data = cohort)   # predictors joined with +\nsummary(time_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = op_time_min ~ bmi + age + sex + procedure, data = cohort)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-38.701 -10.381   0.339   8.906  43.672 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  24.68046    5.30829   4.649 4.10e-06 ***\nbmi           1.27441    0.10792  11.809  < 2e-16 ***\nage           0.27368    0.06135   4.461 9.77e-06 ***\nsexMale      -1.48362    1.18255  -1.255     0.21    \nprocedureTKA  6.73655    1.19120   5.655 2.42e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 14.13 on 595 degrees of freedom\nMultiple R-squared:  0.2662,\tAdjusted R-squared:  0.2613 \nF-statistic: 53.97 on 4 and 595 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(time_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  2.5 %     97.5 %\n(Intercept)  14.2551922 35.1057290\nbmi           1.0624624  1.4863624\nage           0.1531853  0.3941807\nsexMale      -3.8060917  0.8388530\nprocedureTKA  4.3970716  9.0760223\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ntime_model = smf.ols(\"op_time_min ~ bmi + age + sex + procedure\", data=cohort).fit()   # predictors joined with +\nprint(time_model.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:            op_time_min   R-squared:                       0.266\nModel:                            OLS   Adj. R-squared:                  0.261\nMethod:                 Least Squares   F-statistic:                     53.97\nDate:                Tue, 06 Oct 2026   Prob (F-statistic):           8.05e-39\nTime:                        16:01:47   Log-Likelihood:                -2437.7\nNo. Observations:                 600   AIC:                             4885.\nDf Residuals:                     595   BIC:                             4907.\nDf Model:                           4                                         \nCovariance Type:            nonrobust                                         \n====================================================================================\n                       coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------------\nIntercept           24.6805      5.308      4.649      0.000      14.255      35.106\nsex[T.Male]         -1.4836      1.183     -1.255      0.210      -3.806       0.839\nprocedure[T.TKA]     6.7365      1.191      5.655      0.000       4.397       9.076\nbmi                  1.2744      0.108     11.809      0.000       1.062       1.486\nage                  0.2737      0.061      4.461      0.000       0.153       0.394\n==============================================================================\nOmnibus:                        2.620   Durbin-Watson:                   2.003\nProb(Omnibus):                  0.270   Jarque-Bera (JB):                2.197\nSkew:                           0.005   Prob(JB):                        0.333\nKurtosis:                       2.704   Cond. No.                         670.\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\nEach coefficient is the change in operative time for one unit of that predictor, **with the other predictors held fixed**:\n\n- **bmi = 1.27:** 1.27 more minutes per kg/m² (95% CI 1.06 to 1.49), for patients of the same age, sex and procedure.\n- **age = 0.27:** 0.27 more minutes per year of age (95% CI 0.15 to 0.39).\n- **sexMale** (R) or **sex[T.Male]** (Python) **= −1.48:** men took 1.48 minutes less than women, but the CI (−3.81 to 0.84) includes 0. Women are the reference group because \"Female\" comes first alphabetically.\n- **procedureTKA = 6.74:** TKAs took 6.74 minutes longer than THAs (95% CI 4.40 to 9.08).\n- **Multiple R-squared = 0.27, adjusted R-squared = 0.26:** the four predictors together explain about a quarter of the variation. The adjusted value is penalized for the number of predictors.\n- **F-statistic, p < 0.001:** the test that all four predictors together explain nothing.\n\n### Effect size and 95% CI\n\nThe **adjusted coefficients** with their 95% CIs are the effect sizes, with **R²** for the model as a whole. BMI's coefficient fell only a little after adjustment, from 1.37 minutes per kg/m² on its own ([page 11](11-predict-from-one.qmd#linear-regression)) to 1.27: age, sex and procedure explain little of BMI's link with operative time.\n\n### How to report it\n\n> **Methods:** Operative time was modeled with multiple linear regression on BMI, age, sex and procedure, chosen before the analysis.\n>\n> **Results:** Adjusted for age, sex and procedure, the coefficient for BMI was 1.27 minutes of operative time per kg/m² (95% CI 1.06 to 1.49; p < 0.001). The coefficient for TKA (vs THA) was 6.74 minutes (95% CI 4.40 to 9.08) and for age 0.27 minutes per year (95% CI 0.15 to 0.39). The model explained 27% of the variation in operative time (R² = 0.27).\n\n::: {.callout-warning}\n## ⚠️ Watch out: \"adjusted\" isn't \"caused\", and more predictors isn't better\nAdjusting removes the part of an effect explained by the variables **in** the model, not by the ones you left out or never measured, so an adjusted coefficient still isn't proof of cause. Choose the predictors in advance and stop there: adding variables until something becomes significant, or dropping those that don't (stepwise selection), gives results that won't replicate.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: names for the same coefficients\nBoth programs use the first category alphabetically as the reference (Female, THA). R names the coefficients `sexMale` and `procedureTKA`; statsmodels names them `sex[T.Male]` and `procedure[T.TKA]` (T for \"treatment\" coding). The numbers are the same.\n:::\n\n## Multiple nonlinear regression {#multiple-nonlinear-regression}\n\n**The question:** Do hips recover faster than knees after joint replacement?\n\n### When to use it\n\n- **The curve's shape is known, but its numbers may depend on other variables.** Extend the [recovery curve](11-predict-from-one.qmd#nonlinear-regression) so that each of its numbers can differ between hips and knees, and fit one model with nonlinear least squares.\n- **The shape isn't known.** Let a measured predictor's effect bend with a **spline**: a flexible curve made of short cubic pieces joined smoothly at points called knots. A **natural** (or **restricted**) cubic spline is a straight line beyond the outer knots, which keeps it from flailing at the ends. Splines fit inside an ordinary linear, logistic or Cox model, and they're the usual way to check whether a straight line is good enough.\n- If every effect is a straight line → [multiple linear regression](#multiple-linear-regression).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(splines)\n\nproms <- read_csv(\"data/proms_long.csv\", show_col_types = FALSE)\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\n\nrecovery_data <- proms |>\n  filter(!is.na(prom_score)) |>\n  mutate(days = pmax(visit_days, 0),                        # pre-op visits count as day 0\n         joint = if_else(instrument == \"HOOS JR\", \"hip\", \"knee\"),\n         knee = as.numeric(joint == \"knee\"))                # 1 = knee, 0 = hip\n\nggplot(recovery_data, aes(days, prom_score, colour = joint)) +\n  geom_point(alpha = 0.15) +\n  labs(x = \"Days since surgery\", y = \"HOOS JR (hips) or KOOS JR (knees)\", colour = \"Joint\")\n```\n\n::: {.cell-output-display}\n![](12-predict-from-several_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncount(recovery_data, joint)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  joint     n\n  <chr> <int>\n1 hip     906\n2 knee   1146\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport statsmodels.formula.api as smf\nfrom scipy import stats\nfrom scipy.optimize import curve_fit\nfrom statsmodels.stats.anova import anova_lm\n\nproms = pd.read_csv(\"data/proms_long.csv\")\ncohort = pd.read_csv(\"data/cohort.csv\")\n\nrecovery_data = proms.dropna(subset=[\"prom_score\"]).copy()\nrecovery_data[\"days\"] = recovery_data[\"visit_days\"].clip(lower=0)             # pre-op visits count as day 0\nrecovery_data[\"knee\"] = (recovery_data[\"instrument\"] == \"KOOS JR\").astype(int)   # 1 = knee, 0 = hip\n\nfig, ax = plt.subplots(figsize=(6, 3.5))\nfor knee, group in recovery_data.groupby(\"knee\"):\n    ax.scatter(group[\"days\"], group[\"prom_score\"], alpha=0.15, label=\"knee\" if knee else \"hip\")\nax.set_xlabel(\"Days since surgery\")\nax.set_ylabel(\"HOOS JR (hips) or KOOS JR (knees)\")\nlegend = ax.legend(title=\"Joint\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](12-predict-from-several_files/figure-html/unnamed-chunk-10-1.png)\n:::\n\n```{.python .cell-code}\nprint(recovery_data[\"knee\"].value_counts())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nknee\n1    1146\n0     906\nName: count, dtype: int64\n```\n\n\n:::\n:::\n\n:::\n\n2052 scores: 906 from hips and 1146 from knees. Both rise and level off; the hip scores seem to get there sooner.\n\n### Run it\n\nEach of the curve's three numbers gets a value for hips and a difference for knees: for a knee, `plateau = plateau_hip + plateau_diff`, and the same for `start` and `tau`.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrecovery_by_joint <- function(days, knee, plateau_hip, plateau_diff, start_hip, start_diff, tau_hip, tau_diff) {\n  plateau <- plateau_hip + plateau_diff * knee   # knee = 0 for hips, 1 for knees\n  start <- start_hip + start_diff * knee\n  tau <- tau_hip + tau_diff * knee\n  plateau - (plateau - start) * exp(-days / tau)\n}\n\njoint_recovery <- nls(\n  prom_score ~ recovery_by_joint(days, knee, plateau_hip, plateau_diff, start_hip, start_diff, tau_hip, tau_diff),\n  data = recovery_data,\n  start = list(plateau_hip = 85, plateau_diff = 0, start_hip = 50, start_diff = 0, tau_hip = 60, tau_diff = 0)\n)\nsummary(joint_recovery)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFormula: prom_score ~ recovery_by_joint(days, knee, plateau_hip, plateau_diff, \n    start_hip, start_diff, tau_hip, tau_diff)\n\nParameters:\n             Estimate Std. Error t value Pr(>|t|)    \nplateau_hip   87.8634     0.8374 104.918  < 2e-16 ***\nplateau_diff  -3.6573     1.1645  -3.141  0.00171 ** \nstart_hip     45.5733     0.7310  62.343  < 2e-16 ***\nstart_diff     4.2545     0.9818   4.333 1.54e-05 ***\ntau_hip       53.3741     3.1349  17.026  < 2e-16 ***\ntau_diff      27.4899     6.2229   4.418 1.05e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 11.91 on 2046 degrees of freedom\n\nNumber of iterations to convergence: 4 \nAchieved convergence tolerance: 7.988e-07\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef recovery_by_joint(x, plateau_hip, plateau_diff, start_hip, start_diff, tau_hip, tau_diff):\n    days, knee = x\n    plateau = plateau_hip + plateau_diff * knee   # knee = 0 for hips, 1 for knees\n    start = start_hip + start_diff * knee\n    tau = tau_hip + tau_diff * knee\n    return plateau - (plateau - start) * np.exp(-days / tau)\n\nnames = [\"plateau_hip\", \"plateau_diff\", \"start_hip\", \"start_diff\", \"tau_hip\", \"tau_diff\"]\nestimates, covariance = curve_fit(recovery_by_joint, (recovery_data[\"days\"], recovery_data[\"knee\"]),\n                                  recovery_data[\"prom_score\"], p0=[85, 0, 50, 0, 60, 0])\nstandard_errors = np.sqrt(np.diag(covariance))\nprint(pd.DataFrame({\"estimate\": estimates, \"std_error\": standard_errors}, index=names))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               estimate  std_error\nplateau_hip   87.863423   0.837445\nplateau_diff  -3.657309   1.164522\nstart_hip     45.573264   0.731013\nstart_diff     4.254487   0.981786\ntau_hip       53.374147   3.134911\ntau_diff      27.489912   6.222619\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nWhen you don't know the shape, use a spline instead. Here a natural cubic spline lets BMI's effect on operative time bend, and an F test asks whether the bend improves on the straight line of the [multiple linear regression](#multiple-linear-regression).\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstraight <- lm(op_time_min ~ bmi + age + sex + procedure, data = cohort)\nbendy <- lm(op_time_min ~ ns(bmi, df = 3) + age + sex + procedure, data = cohort)   # ns(): natural cubic spline\nanova(straight, bendy)   # does the bend improve the fit?\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: op_time_min ~ bmi + age + sex + procedure\nModel 2: op_time_min ~ ns(bmi, df = 3) + age + sex + procedure\n  Res.Df    RSS Df Sum of Sq      F Pr(>F)\n1    595 118735                           \n2    593 118504  2    230.57 0.5769 0.5619\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nbmi_knots = list(cohort[\"bmi\"].quantile([1/3, 2/3]))         # the same knots R's ns(df = 3) uses\nbmi_low, bmi_high = cohort[\"bmi\"].min(), cohort[\"bmi\"].max()\n\nstraight = smf.ols(\"op_time_min ~ bmi + age + sex + procedure\", data=cohort).fit()\nbendy = smf.ols(\"op_time_min ~ cr(bmi, knots=bmi_knots, lower_bound=bmi_low, upper_bound=bmi_high, constraints='center')\"\n                \" + age + sex + procedure\", data=cohort).fit()   # cr(): natural cubic spline\nprint(anova_lm(straight, bendy))   # does the bend improve the fit?\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   df_resid            ssr  df_diff     ss_diff         F    Pr(>F)\n0     595.0  118734.576022      0.0         NaN       NaN       NaN\n1     593.0  118504.000895      2.0  230.575127  0.576905  0.561949\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\nThe recovery curve:\n\n- **plateau_hip, start_hip, tau_hip:** the hip curve, the same as fitting hips alone ([page 11, exercise 3](11-predict-from-one.qmd#exercises)): τ = 53.4 days.\n- **tau_diff = 27.5:** knees' time constant is 27.5 days longer, so knees recover more slowly.\n- **plateau_diff = −3.66, start_diff = 4.25:** the knee curve starts 4.25 points higher and levels off 3.66 points lower; see the warning below before reading anything into these.\n\nThe spline:\n\n- **F = 0.58, p = 0.562:** no clear evidence that letting BMI's effect bend improves the fit, so keep the straight line.\n\n### Effect size and 95% CI\n\nThe **differences between hips and knees**, with their 95% CIs, are the effect sizes.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(joint_recovery)                                          # profile CIs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  2.5%     97.5%\nplateau_hip  86.229940 89.522974\nplateau_diff -5.928152 -1.374496\nstart_hip    44.138167 47.006912\nstart_diff    2.331989  6.176612\ntau_hip      47.441593 59.843813\ntau_diff     15.919497 40.145708\n```\n\n\n:::\n\n```{.r .cell-code}\nlog(2) * c(hip = coef(joint_recovery)[[\"tau_hip\"]],\n           knee = coef(joint_recovery)[[\"tau_hip\"]] + coef(joint_recovery)[[\"tau_diff\"]])   # days to half the gain\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     hip     knee \n36.99614 56.05070 \n```\n\n\n:::\n\n```{.r .cell-code}\nlog(2) * confint(joint_recovery)[\"tau_diff\", ]                   # difference in days to half the gain\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5%    97.5% \n11.03455 27.82688 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nt_crit = stats.t.ppf(0.975, df=len(recovery_data) - 6)   # 6 parameters\nprint(pd.DataFrame({\"low\": estimates - t_crit * standard_errors, \"high\": estimates + t_crit * standard_errors}, index=names))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    low       high\nplateau_hip   86.221089  89.505757\nplateau_diff  -5.941080  -1.373537\nstart_hip     44.139657  47.006871\nstart_diff     2.329083   6.179891\ntau_hip       47.226198  59.522096\ntau_diff      15.286584  39.693240\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(np.log(2) * estimates[4], np.log(2) * (estimates[4] + estimates[5]))   # days to half the gain: hips, knees\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n36.996139463485335 56.05069471443701\n```\n\n\n:::\n:::\n\n:::\n\nThe time constant was 27.5 days longer for knees (95% CI 15.9 to 40.1). Half of the eventual gain took about 37 days after a hip replacement and 56 days after a knee replacement, a difference of 19 days (95% CI 11 to 28).\n\n### How to report it\n\n> **Methods:** HOOS JR (hips) and KOOS JR (knees) were modeled against days since surgery with an exponential recovery curve whose start, plateau and time constant could differ between hips and knees, fitted by nonlinear least squares. Whether BMI's effect on operative time was linear was checked by adding a natural cubic spline (3 degrees of freedom) and comparing the models with an F test.\n>\n> **Results:** The difference in the time constant between knees and hips was 27.5 days (95% CI 15.9 to 40.1); half of the change was reached at about 56 days after knee replacement and 37 days after hip replacement. For BMI and operative time, comparing a spline with a straight line gave F = 0.58 (df = 2 and 593, p = 0.562).\n\n::: {.callout-warning}\n## ⚠️ Watch out: two questionnaires, and repeated scores\nHips answer HOOS JR and knees KOOS JR. A point on one isn't guaranteed to equal a point on the other, so the differences in start and plateau mix up the joints with the questionnaires. The time constant is measured in days, not points, so it compares more fairly, as long as both questionnaires track recovery in a similar way. As on [page 11](11-predict-from-one.qmd#nonlinear-regression), each joint contributes up to four related scores, so these CIs can't be trusted: some may be too narrow and others too wide. A mixed model ([page 16](../beyond/16-mixed-models.qmd#random-intercept)) handles that.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: splines and CIs\n- R's `ns()` and Python's `cr()` (from patsy, the formula library statsmodels uses) build the same natural cubic spline only when the knots match. `ns(df = 3)` puts knots at the 1/3 and 2/3 quantiles and at the minimum and maximum, so the Python code sets those explicitly. Other tools, like `rms::rcs()`, place the knots elsewhere and give slightly different curves.\n- As on [page 11](11-predict-from-one.qmd#nonlinear-regression), R's `confint()` profiles the nonlinear fit, while the Python code uses estimate ± t × standard error, so the CIs differ slightly (τ difference: 15.3 to 39.7 days in Python).\n:::\n\n## Multiple logistic regression {#multiple-logistic-regression}\n\n**The question:** Which patient factors predict a complication within 90 days?\n\n### When to use it\n\n- The outcome is **yes/no**, and you want the **odds ratio** for each of several predictors, adjusted for the others.\n- The assumptions of [simple logistic regression](11-predict-from-one.qmd#logistic-regression) still apply, for every measured predictor.\n- **Events limit predictors.** A common rule of thumb is at least 10 patients **with** the outcome per predictor. With 51 complications, this model can afford about five.\n- If the outcome is time until an event → [Cox regression](#cox).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE) |>\n  mutate(age_10 = age / 10,   # per 10 years\n         bmi_5 = bmi / 5)     # per 5 kg/m²\n\ncohort |>\n  group_by(complication_90d) |>\n  summarise(n = n(), age = mean(age), bmi = mean(bmi), asa = mean(asa),\n            diabetes_percent = 100 * mean(diabetes), male_percent = 100 * mean(sex == \"Male\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  complication_90d     n   age   bmi   asa diabetes_percent male_percent\n             <dbl> <int> <dbl> <dbl> <dbl>            <dbl>        <dbl>\n1                0   549  65.0  30.3  2.39             9.11         43.2\n2                1    51  71.2  32.3  2.67            11.8          39.2\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport statsmodels.formula.api as smf\n\ncohort = pd.read_csv(\"data/cohort.csv\")\ncohort[\"age_10\"] = cohort[\"age\"] / 10   # per 10 years\ncohort[\"bmi_5\"] = cohort[\"bmi\"] / 5     # per 5 kg/m²\ncohort[\"male\"] = (cohort[\"sex\"] == \"Male\").astype(int)\n\nprint(cohort.groupby(\"complication_90d\")[[\"age\", \"bmi\", \"asa\", \"diabetes\", \"male\"]].mean())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        age        bmi       asa  diabetes      male\ncomplication_90d                                                    \n0                 64.989071  30.274863  2.386157  0.091075  0.431694\n1                 71.235294  32.264706  2.666667  0.117647  0.392157\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(cohort[\"complication_90d\"].value_counts())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncomplication_90d\n0    549\n1     51\nName: count, dtype: int64\n```\n\n\n:::\n:::\n\n:::\n\nThe 51 patients with a complication were older on average (71.2 against 65.0 years), with a higher BMI (32.3 against 30.3) and a slightly higher ASA class. Diabetes was a little more common (11.8% against 9.1%), and men a little less common (39.2% against 43.2%).\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomplication_model <- glm(complication_90d ~ age_10 + bmi_5 + asa + diabetes + sex,\n                          family = binomial, data = cohort)\nsummary(complication_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = complication_90d ~ age_10 + bmi_5 + asa + diabetes + \n    sex, family = binomial, data = cohort)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -9.74187    1.56724  -6.216 5.10e-10 ***\nage_10       0.73287    0.18507   3.960 7.49e-05 ***\nbmi_5        0.32580    0.14956   2.178   0.0294 *  \nasa          0.14732    0.27474   0.536   0.5918    \ndiabetes    -0.13122    0.49113  -0.267   0.7893    \nsexMale     -0.05909    0.30955  -0.191   0.8486    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 348.98  on 599  degrees of freedom\nResidual deviance: 320.57  on 594  degrees of freedom\nAIC: 332.57\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ncomplication_model = smf.logit(\"complication_90d ~ age_10 + bmi_5 + asa + diabetes + sex\",\n                               data=cohort).fit(disp=False)\nprint(complication_model.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                           Logit Regression Results                           \n==============================================================================\nDep. Variable:       complication_90d   No. Observations:                  600\nModel:                          Logit   Df Residuals:                      594\nMethod:                           MLE   Df Model:                            5\nDate:                Tue, 06 Oct 2026   Pseudo R-squ.:                 0.08141\nTime:                        16:01:49   Log-Likelihood:                -160.28\nconverged:                       True   LL-Null:                       -174.49\nCovariance Type:            nonrobust   LLR p-value:                 3.027e-05\n===============================================================================\n                  coef    std err          z      P>|z|      [0.025      0.975]\n-------------------------------------------------------------------------------\nIntercept      -9.7419      1.567     -6.216      0.000     -12.814      -6.670\nsex[T.Male]    -0.0591      0.310     -0.191      0.849      -0.666       0.548\nage_10          0.7329      0.185      3.960      0.000       0.370       1.096\nbmi_5           0.3258      0.150      2.178      0.029       0.033       0.619\nasa             0.1473      0.275      0.536      0.592      -0.391       0.686\ndiabetes       -0.1312      0.491     -0.267      0.789      -1.094       0.831\n===============================================================================\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- Each **coefficient** is the change in the log odds of a complication per unit of that predictor, adjusted for the others; the next step turns them into odds ratios.\n- **age_10: p < 0.001** and **bmi_5: p = 0.029:** age and BMI each predict complications, even allowing for the other.\n- **asa (p = 0.592), diabetes (p = 0.789), sexMale (p = 0.849):** no clear evidence for these, once age and BMI are in the model.\n- ASA class is entered as a number (1 to 4), so it counts as one predictor with one odds ratio per class. As four separate groups it would use three of the model's five or so predictors.\n\n### Effect size and 95% CI\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(cbind(odds_ratio = coef(complication_model), confint(complication_model)))   # profile CIs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              odds_ratio        2.5 %      97.5 %\n(Intercept) 5.877081e-05 2.440774e-06 0.001156722\nage_10      2.081044e+00 1.459241e+00 3.019356277\nbmi_5       1.385134e+00 1.034551e+00 1.862534147\nasa         1.158728e+00 6.781744e-01 1.996738385\ndiabetes    8.770249e-01 3.051467e-01 2.149150151\nsexMale     9.426266e-01 5.075409e-01 1.719253419\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nodds_ratios = np.exp(pd.concat([complication_model.params, complication_model.conf_int()], axis=1))   # Wald CIs\nodds_ratios.columns = [\"odds_ratio\", \"low\", \"high\"]\nprint(odds_ratios)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             odds_ratio       low      high\nIntercept      0.000059  0.000003  0.001268\nsex[T.Male]    0.942627  0.513864  1.729143\nage_10         2.081044  1.447945  2.990961\nbmi_5          1.385134  1.033206  1.856934\nasa            1.158728  0.676275  1.985361\ndiabetes       0.877025  0.334938  2.296460\n```\n\n\n:::\n:::\n\n:::\n\nThe **adjusted odds ratios** are the effect sizes: 2.08 per 10 years of age (95% CI 1.46 to 3.02) and 1.39 per 5 kg/m² of BMI (95% CI 1.03 to 1.86). The CIs for ASA class (1.16 per class, 0.68 to 2.00), diabetes (0.88, 0.31 to 2.15) and male sex (0.94, 0.51 to 1.72) are wide.\n\n### How to report it\n\n> **Methods:** Complications within 90 days were modeled with multiple logistic regression on age (per 10 years), BMI (per 5 kg/m²), ASA class, diabetes and sex, chosen before the analysis.\n>\n> **Results:** Complications followed 51 of 600 procedures (8.5%). In the multivariable model, the odds ratios for a complication were 2.08 per 10 years of age (95% CI 1.46 to 3.02), 1.39 per 5 kg/m² of BMI (95% CI 1.03 to 1.86), 1.16 per ASA class (95% CI 0.68 to 2.00), 0.88 for diabetes (95% CI 0.31 to 2.15) and 0.94 for male sex (95% CI 0.51 to 1.72).\n\n::: {.callout-warning}\n## ⚠️ Watch out: too few events\nWith 51 complications, five predictors is already at the limit. Add more and the odds ratios become unstable: their CIs balloon, and some may shoot off toward 0 or infinity. If you have more candidate predictors than events allow, choose the most important ones clinically, in advance; don't let p-values choose them for you.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: profile and Wald CIs, again\nAs on [page 11](11-predict-from-one.qmd#logistic-regression), R's `confint()` profiles the likelihood and statsmodels uses Wald CIs. With few events the two can differ in the second decimal: for diabetes, 0.31 to 2.15 in R and 0.33 to 2.30 in Python. Say which you used.\n:::\n\n## Cox regression {#cox}\n\n**The question:** Does implant C still carry a higher hazard of revision after adjusting for age, sex and BMI?\n\n### When to use it\n\n- The outcome is **time until an event** (revision), and you want each predictor's **hazard ratio**, adjusted for the others.\n- **Events limit predictors**, as in logistic regression: about 10 events per predictor. 81 revisions allow about eight; implant (which uses two, B and C against A), age, sex and BMI use five.\n- Proportional hazards must hold for every predictor. [Page 14](../survival/14-cox-regression.qmd#proportional-hazards) shows how to check it and covers Cox regression in full.\n\n### Look at the data first\n\nAdjusting matters when the groups differ in other ways. Compare the implants:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(survival)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE) |>\n  mutate(age_10 = age / 10, bmi_5 = bmi / 5)   # per 10 years, per 5 kg/m²\n\ncohort |>\n  group_by(implant) |>\n  summarise(n = n(), revised = sum(revised), age = mean(age), male_percent = 100 * mean(sex == \"Male\"), bmi = mean(bmi))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 6\n  implant     n revised   age male_percent   bmi\n  <chr>   <int>   <dbl> <dbl>        <dbl> <dbl>\n1 A         246      25  65.2         42.7  30.6\n2 B         217      18  65.5         42.4  30.1\n3 C         137      38  66.0         43.8  30.7\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nfrom lifelines import CoxPHFitter\n\ncohort = pd.read_csv(\"data/cohort.csv\")\ncohort[\"age_10\"] = cohort[\"age\"] / 10   # per 10 years\ncohort[\"bmi_5\"] = cohort[\"bmi\"] / 5     # per 5 kg/m²\ncohort[\"male\"] = (cohort[\"sex\"] == \"Male\").astype(int)\n\nprint(cohort.groupby(\"implant\").agg(n=(\"case_id\", \"count\"), revised=(\"revised\", \"sum\"), age=(\"age\", \"mean\"),\n                                    male=(\"male\", \"mean\"), bmi=(\"bmi\", \"mean\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           n  revised        age      male        bmi\nimplant                                              \nA        246       25  65.243902  0.426829  30.626016\nB        217       18  65.548387  0.423963  30.073733\nC        137       38  65.970803  0.437956  30.703650\n```\n\n\n:::\n:::\n\n:::\n\n38 of 137 implant C procedures were revised, against 25 of 246 for A and 18 of 217 for B. The three groups are alike in age (65 to 66 years on average), sex (42% to 44% men) and BMI (about 30 to 31), so adjustment shouldn't change much.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadjusted_cox <- coxph(Surv(followup_years, revised) ~ implant + age_10 + sex + bmi_5, data = cohort)\nsummary(adjusted_cox)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(followup_years, revised) ~ implant + age_10 + \n    sex + bmi_5, data = cohort)\n\n  n= 600, number of events= 81 \n\n             coef exp(coef) se(coef)      z Pr(>|z|)    \nimplantB -0.18740   0.82912  0.30950 -0.605  0.54486    \nimplantC  1.15953   3.18844  0.25853  4.485 7.29e-06 ***\nage_10    0.20263   1.22462  0.12557  1.614  0.10660    \nsexMale  -0.68010   0.50657  0.24180 -2.813  0.00491 ** \nbmi_5     0.03038   1.03084  0.10529  0.289  0.77296    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n         exp(coef) exp(-coef) lower .95 upper .95\nimplantB    0.8291     1.2061    0.4520    1.5208\nimplantC    3.1884     0.3136    1.9210    5.2922\nage_10      1.2246     0.8166    0.9574    1.5664\nsexMale     0.5066     1.9741    0.3154    0.8137\nbmi_5       1.0308     0.9701    0.8386    1.2671\n\nConcordance= 0.682  (se = 0.035 )\nLikelihood ratio test= 39.14  on 5 df,   p=2e-07\nWald test            = 40.65  on 5 df,   p=1e-07\nScore (logrank) test = 44.68  on 5 df,   p=2e-08\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nadjusted_cox = CoxPHFitter().fit(\n    cohort[[\"followup_years\", \"revised\", \"implant\", \"age_10\", \"sex\", \"bmi_5\"]],\n    duration_col=\"followup_years\", event_col=\"revised\", formula=\"implant + age_10 + sex + bmi_5\",\n    fit_options={\"precision\": 1e-9},   # stop only when fully converged; see the R vs Python box\n)\nprint(adjusted_cox.summary[[\"exp(coef)\", \"exp(coef) lower 95%\", \"exp(coef) upper 95%\", \"p\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              exp(coef)  exp(coef) lower 95%  exp(coef) upper 95%         p\ncovariate                                                                  \nimplant[T.B]   0.829116             0.452030             1.520769  0.544863\nimplant[T.C]   3.188436             1.920970             5.292184  0.000007\nage_10         1.224622             0.957444             1.566358  0.106603\nsex[T.Male]    0.506569             0.315367             0.813692  0.004914\nbmi_5          1.030844             0.838625             1.267121  0.772960\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(adjusted_cox.log_likelihood_ratio_test().test_statistic)   # overall likelihood ratio test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n39.13907300661026\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **implantC = 3.19 (95% CI 1.92 to 5.29):** adjusted for age, sex and BMI, implant C carried about three times the hazard of revision of implant A, almost the same as without adjustment (3.07, [page 8](08-three-plus-unmatched.qmd#cox)).\n- **implantB = 0.83 (95% CI 0.45 to 1.52):** imprecise, as before.\n- **sexMale = 0.51 (95% CI 0.32 to 0.81, p = 0.005):** men had about half the hazard of revision of women.\n- **age_10 = 1.22 (95% CI 0.96 to 1.57)** and **bmi_5 = 1.03 (95% CI 0.84 to 1.27):** imprecise.\n- **Likelihood ratio test = 39.1 on 5 df, p < 0.001:** the five terms together predict revision.\n\n### Effect size and 95% CI\n\nThe **adjusted hazard ratios** with their 95% CIs are the effect sizes. The one the question asks about: implant C against A, 3.19 (95% CI 1.92 to 5.29).\n\n### How to report it\n\n> **Methods:** Revision was modeled with Cox proportional hazards regression on implant (reference A), age (per 10 years), sex and BMI (per 5 kg/m²), chosen before the analysis.\n>\n> **Results:** After adjustment for age, sex and BMI, the hazard ratio for revision compared with implant A was 3.19 (95% CI 1.92 to 5.29; p < 0.001) for implant C and 0.83 (95% CI 0.45 to 1.52) for implant B. In an unplanned, exploratory analysis, the hazard ratio for men compared with women was 0.51 (95% CI 0.32 to 0.81).\n\n::: {.callout-warning}\n## ⚠️ Watch out: the unexpected finding\nThe sex difference wasn't the question; the model was built to adjust for sex, not to test it. An unplanned finding like this is a reason for a new study, not a conclusion: report it as exploratory. And check proportional hazards for every predictor before trusting any of them ([page 14](../survival/14-cox-regression.qmd#proportional-hazards)).\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: convergence and names\nAs on [page 8](08-three-plus-unmatched.qmd#cox), lifelines' default convergence rule stops a little early (a hazard ratio of 0.82915 for implant B instead of 0.82912), so the Python code tightens it with `fit_options={\"precision\": 1e-9}`. lifelines names the terms `implant[T.C]` and `sex[T.Male]`; R names them `implantC` and `sexMale`.\n:::\n\n\n\n## Exercises {#exercises}\n\nThe solutions use the packages and data loaded in the sections above, so run the page from the top first.\n\n**1.** Add **surgeon** to the multiple linear regression for operative time. Does it improve the model, and does BMI's coefficient change?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwith_surgeon <- lm(op_time_min ~ bmi + age + sex + procedure + surgeon, data = cohort)\nanova(time_model, with_surgeon)                            # does surgeon add anything?\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: op_time_min ~ bmi + age + sex + procedure\nModel 2: op_time_min ~ bmi + age + sex + procedure + surgeon\n  Res.Df    RSS Df Sum of Sq      F Pr(>F)\n1    595 118735                           \n2    593 118697  2    37.343 0.0933  0.911\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(with_surgeon)[c(\"bmi\", \"surgeonS2\", \"surgeonS3\"), ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              2.5 %   97.5 %\nbmi        1.059957 1.485242\nsurgeonS2 -2.572906 2.718553\nsurgeonS3 -2.277658 3.476199\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(with_surgeon)[c(\"bmi\", \"surgeonS2\", \"surgeonS3\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       bmi  surgeonS2  surgeonS3 \n1.27259954 0.07282373 0.59927031 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom statsmodels.stats.anova import anova_lm\n\nwith_surgeon = smf.ols(\"op_time_min ~ bmi + age + sex + procedure + surgeon\", data=cohort).fit()\nprint(anova_lm(time_model, with_surgeon))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   df_resid            ssr  df_diff   ss_diff         F    Pr(>F)\n0     595.0  118734.576022      0.0       NaN       NaN       NaN\n1     593.0  118697.232892      2.0  37.34313  0.093281  0.910951\n```\n\n\n:::\n\n```{.python .cell-code}\nsurgeon_table = pd.concat([with_surgeon.params, with_surgeon.conf_int()], axis=1)\nsurgeon_table.columns = [\"estimate\", \"low\", \"high\"]\nprint(surgeon_table.loc[[\"bmi\", \"surgeon[T.S2]\", \"surgeon[T.S3]\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               estimate       low      high\nbmi            1.272600  1.059957  1.485242\nsurgeon[T.S2]  0.072824 -2.572906  2.718553\nsurgeon[T.S3]  0.599270 -2.277658  3.476199\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Compared with surgeon S1, the coefficients were 0.07 minutes for S2 (95% CI −2.57 to 2.72) and 0.60 minutes for S3 (95% CI −2.28 to 3.48) (F test for adding surgeon, F = 0.09, df = 2 and 593, p = 0.911). The coefficient for BMI was 1.27 minutes per kg/m² (95% CI 1.06 to 1.49).\n\nThere's no clear evidence that adding surgeon improves the model, and BMI's coefficient doesn't change.\n:::\n\n**2.** A colleague wants to know which patient factors predict discharge to a facility rather than home. Only 30 patients went to a facility. Which model would you use, how many predictors can it take, and what do you find with age, sex and ASA class?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nThe outcome is yes/no: **multiple logistic regression**. With 30 events, the rule of thumb allows about three predictors, so choose them in advance; age, sex and ASA class are reasonable choices.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfacility_model <- glm(I(discharge == \"facility\") ~ age_10 + sex + asa, family = binomial, data = cohort)\nexp(cbind(odds_ratio = coef(facility_model), confint(facility_model)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              odds_ratio        2.5 %      97.5 %\n(Intercept) 0.0002667508 9.764501e-06 0.005505898\nage_10      2.0785382823 1.337132e+00 3.310496477\nsexMale     1.3565761813 6.322409e-01 2.890402008\nasa         1.0616886463 5.833373e-01 1.944293430\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ncohort[\"facility\"] = (cohort[\"discharge\"] == \"facility\").astype(int)\nfacility_model = smf.logit(\"facility ~ age_10 + sex + asa\", data=cohort).fit(disp=False)\nfacility_ors = np.exp(pd.concat([facility_model.params, facility_model.conf_int()], axis=1))\nfacility_ors.columns = [\"odds_ratio\", \"low\", \"high\"]\nprint(facility_ors)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             odds_ratio       low      high\nIntercept      0.000267  0.000011  0.006271\nsex[T.Male]    1.356576  0.638915  2.880352\nage_10         2.078538  1.323112  3.265274\nasa            1.061689  0.582593  1.934767\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** The odds ratios for discharge to a facility were 2.08 per 10 years of age (95% CI 1.34 to 3.31), 1.36 for male sex (95% CI 0.63 to 2.89) and 1.06 per ASA class (95% CI 0.58 to 1.94).\n\nThe CIs are R's profile CIs. Only age's CI excludes 1.\n:::\n\n**3.** On [page 11](11-predict-from-one.qmd#logistic-regression), complications seemed to jump after age 80. Fit age as a natural cubic spline (3 degrees of freedom) in the logistic regression, compare it with the straight line, and write the Results sentence.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nline_model <- glm(complication_90d ~ age, family = binomial, data = cohort)\nbend_model <- glm(complication_90d ~ ns(age, df = 3), family = binomial, data = cohort)\nanova(line_model, bend_model, test = \"LRT\")   # likelihood ratio test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: complication_90d ~ age\nModel 2: complication_90d ~ ns(age, df = 3)\n  Resid. Df Resid. Dev Df Deviance Pr(>Chi)\n1       598     327.77                     \n2       596     324.28  2   3.4911   0.1745\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nage_knots = list(cohort[\"age\"].quantile([1/3, 2/3]))\nage_low, age_high = cohort[\"age\"].min(), cohort[\"age\"].max()\nline_model = smf.logit(\"complication_90d ~ age\", data=cohort).fit(disp=False)\nbend_model = smf.logit(\"complication_90d ~ cr(age, knots=age_knots, lower_bound=age_low, upper_bound=age_high,\"\n                       \" constraints='center')\", data=cohort).fit(disp=False)\nlr = 2 * (bend_model.llf - line_model.llf)    # likelihood ratio statistic\nprint(lr, stats.chi2.sf(lr, df=2))           # 2 extra degrees of freedom\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3.4911141973881854 0.17454772156781373\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Comparing a natural cubic spline for age with a straight line gave a likelihood ratio χ² of 3.49 (df = 2, p = 0.175). With age modeled as linear, the odds ratio for a complication per 10 years of age was 2.12 (95% CI 1.53 to 2.98).\n\nThe jump after 80 rests on 14 complications in 53 patients, too few to pin down a curve.\n:::\n",
    "supporting": [
      "12-predict-from-several_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}