{
  "hash": "aa60cbf06e32b7c213210ff9c58154a9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"1 · Tidy data\"\ndescription: \"What tidy data is, how to collect it, how to tidy messy spreadsheets, and how to prove nothing changed.\"\nengine: knitr\n---\n\n\n\n<!-- data-checksum: ffc54e2ad996e1e61ad10ca520e4d588 -->\n\nMost of the time in a research project goes into getting the data into shape, not into the statistics. Mistakes made here are the dangerous kind: the code runs, the tables look fine, and the numbers are wrong. This page shows how to collect data so it arrives clean, how to clean it when it doesn't, and how to prove your cleaning didn't change anything it shouldn't have.\n\n## What tidy data means {#what-tidy-means}\n\nData are **tidy** when:\n\n1. every **variable** is a column,\n2. every **observation** is a row, and\n3. every **kind of observational unit** gets its own table.\n\n::: {.callout-note}\n## 💡 In plain language\nOne fact per cell, one patient-thing per row, and never two kinds of rows mixed in one table. A spreadsheet that's easy for a person to read is often hard for a computer to analyze, and the other way round. Statistics software wants the second kind.\n:::\n\nHere's a typical untidy PROM sheet: one row per patient, with a column for each visit. The *visit* is a variable, but it's hiding in the column names.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nwide <- tibble(\n  case_id = c(\"C0001\", \"C0002\", \"C0003\"),\n  preop   = c(41.2, 55.0, 38.7),\n  `6wk`   = c(60.1, NA,   58.3),\n  `1yr`   = c(88.0, 92.4, 79.5)\n)\nwide\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  case_id preop `6wk` `1yr`\n  <chr>   <dbl> <dbl> <dbl>\n1 C0001    41.2  60.1  88  \n2 C0002    55    NA    92.4\n3 C0003    38.7  58.3  79.5\n```\n\n\n:::\n\n```{.r .cell-code}\n# Tidy: one row per case per visit\nlong <- wide |>\n  pivot_longer(-case_id, names_to = \"visit\", values_to = \"prom_score\")\nlong\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 3\n  case_id visit prom_score\n  <chr>   <chr>      <dbl>\n1 C0001   preop       41.2\n2 C0001   6wk         60.1\n3 C0001   1yr         88  \n4 C0002   preop       55  \n5 C0002   6wk         NA  \n6 C0002   1yr         92.4\n7 C0003   preop       38.7\n8 C0003   6wk         58.3\n9 C0003   1yr         79.5\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\n\nwide = pd.DataFrame({\n    \"case_id\": [\"C0001\", \"C0002\", \"C0003\"],\n    \"preop\":   [41.2, 55.0, 38.7],\n    \"6wk\":     [60.1, None, 58.3],\n    \"1yr\":     [88.0, 92.4, 79.5],\n})\nprint(wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  case_id  preop   6wk   1yr\n0   C0001   41.2  60.1  88.0\n1   C0002   55.0   NaN  92.4\n2   C0003   38.7  58.3  79.5\n```\n\n\n:::\n\n```{.python .cell-code}\n# Tidy: one row per case per visit\nlong = wide.melt(id_vars=\"case_id\", var_name=\"visit\", value_name=\"prom_score\")\nprint(long)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  case_id  visit  prom_score\n0   C0001  preop        41.2\n1   C0002  preop        55.0\n2   C0003  preop        38.7\n3   C0001    6wk        60.1\n4   C0002    6wk         NaN\n5   C0003    6wk        58.3\n6   C0001    1yr        88.0\n7   C0002    1yr        92.4\n8   C0003    1yr        79.5\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nIn the long version, \"Is the 6-week score missing?\" is just a row with a blank, and \"average score at each visit\" is one line of code. In the wide version, every new visit means a new column and rewritten code.\n\nUntidy patterns we see most often in abstraction sheets, and the tidy fix for each:\n\n| You see | Problem | Tidy fix |\n|------|------|------|\n| `DM, HTN, OSA` in one cell | Several values in one cell | One yes/no column per condition |\n| `R TKA` | Two variables in one cell | Separate `side` and `procedure` columns |\n| `32.1 kg/m2` | Units typed into a number | A number column; units go in the data dictionary |\n| Red-filled cells mean \"revised\" | Color as data (invisible to software) | A `revised` column |\n| `Date`, `Score`, `Date`, `Score` | Repeated columns per visit | Long format: one row per visit |\n| `N/A`, `unk`, `-`, `999`, blank | Five ways to say \"missing\" | One: an empty cell |\n| A title row, a totals row | Not data | Delete them; keep notes elsewhere |\n\n## Collecting tidy data {#collecting}\n\nThe cheapest cleaning is the cleaning you never have to do. Before anyone abstracts a single chart, write the **data dictionary**: every variable's name, meaning, type, units and allowed values. Then build the collection sheet from the dictionary.\n\nThis site includes a template you can copy: [`templates/data-collection-template.xlsx`](https://github.com/hfr-ortho/stats-formation/raw/main/templates/data-collection-template.xlsx). It has four sheets:\n\n- **README** — the rules below, for whoever does the abstraction.\n- **data** — one header row, and dropdowns or range checks on every column except the study ID, so typos can't get in.\n- **dictionary** — what each column means.\n- **missing_codes** — exactly what to enter when a value isn't in the chart.\n\nThe rules the template enforces:\n\n1. One row per procedure, one column per variable, one value per cell.\n2. A study ID, never the MRN or name. The MRN-to-study-ID crosswalk lives in a separate, secured file.\n3. Categories from dropdowns only (no `F` vs `female`).\n4. Numbers only in number columns; units live in the dictionary.\n5. Real dates, not text.\n6. Missing means: dropdown \"Not recorded\", or an empty number/date cell.\n7. No colors, bold, comments, merged cells, title rows or totals rows.\n\nYou can read the dictionary sheet like any other data:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\n\ndictionary <- read_excel(\"templates/data-collection-template.xlsx\", sheet = \"dictionary\")\ndictionary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 13 × 5\n   variable     label                    type        units allowed              \n   <chr>        <chr>                    <chr>       <chr> <chr>                \n 1 study_id     Study ID (never the MRN) id          <NA>  e.g. C0001           \n 2 surgery_date Date of surgery          date        <NA>  2000-01-01 to 2030-1…\n 3 procedure    Procedure                categorical <NA>  THA, TKA, Not record…\n 4 side         Operative side           categorical <NA>  L, R, Not recorded   \n 5 age          Age at surgery           integer     years 18 to 110            \n 6 sex          Sex                      categorical <NA>  Female, Male, Not re…\n 7 bmi          Body mass index          numeric     kg/m2 10 to 80             \n 8 asa          ASA class                categorical <NA>  1, 2, 3, 4, Not reco…\n 9 diabetes     Diabetes mellitus        categorical <NA>  Yes, No, Not recorded\n10 hypertension Hypertension             categorical <NA>  Yes, No, Not recorded\n11 sleep_apnea  Obstructive sleep apnea  categorical <NA>  Yes, No, Not recorded\n12 los_days     Length of stay           integer     days  0 to 60              \n13 revised      Revised during follow-up categorical <NA>  Yes, No, Not recorded\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndictionary = pd.read_excel(\"templates/data-collection-template.xlsx\", sheet_name=\"dictionary\")\nprint(dictionary.to_string())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        variable                     label         type  units                     allowed\n0       study_id  Study ID (never the MRN)           id    NaN                  e.g. C0001\n1   surgery_date           Date of surgery         date    NaN    2000-01-01 to 2030-12-31\n2      procedure                 Procedure  categorical    NaN      THA, TKA, Not recorded\n3           side            Operative side  categorical    NaN          L, R, Not recorded\n4            age            Age at surgery      integer  years                   18 to 110\n5            sex                       Sex  categorical    NaN  Female, Male, Not recorded\n6            bmi           Body mass index      numeric  kg/m2                    10 to 80\n7            asa                 ASA class  categorical    NaN    1, 2, 3, 4, Not recorded\n8       diabetes         Diabetes mellitus  categorical    NaN       Yes, No, Not recorded\n9   hypertension              Hypertension  categorical    NaN       Yes, No, Not recorded\n10   sleep_apnea   Obstructive sleep apnea  categorical    NaN       Yes, No, Not recorded\n11      los_days            Length of stay      integer   days                     0 to 60\n12       revised  Revised during follow-up  categorical    NaN       Yes, No, Not recorded\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n## Tidying a messy workbook {#tidying}\n\nReal abstraction sheets rarely follow those rules. `data/messy_abstraction_workbook.xlsx` copies the problems we see in real abstraction sheets. Open it in Excel and look before you run any code:\n\n- two tabs, **Site A** and **Site B**, whose columns don't line up (Site B has an extra `MUA` column in the middle)\n- two banner rows and a row of merged group headers above the real header\n- a **TOTAL** row at the bottom of each tab\n- two `Date` and two `Score` columns (pre-op and 1-year PROMs)\n- mixed date formats, units in number cells, Roman-numeral ASA classes, five spellings of \"missing\"\n- revisions marked only by a red fill on the Study ID cell\n- duplicated rows\n\nWe'll fix it one step at a time. Every step is small enough to check. Run the steps in order: each one starts from the result of the step before.\n\n### Step 1: read both tabs, as text\n\nRead everything as text first. If you let the software guess types, it silently turns `32.1 kg/m2` into a missing value, and you never find out. We'll convert types deliberately in step 5.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npath <- \"data/messy_abstraction_workbook.xlsx\"\n\nread_site <- function(sheet) {\n  # skip = 3 jumps over the two banner rows and the group-header row\n  raw <- read_excel(path, sheet = sheet, skip = 3, col_types = \"text\",\n                    .name_repair = \"minimal\")\n  names(raw) <- str_trim(names(raw))   # \"Study ID \" has a trailing space on Site B\n\n  # The two Date/Score pairs: the group header says pre-op first, then 1 year\n  names(raw)[names(raw) == \"Date\"]  <- c(\"prom_preop_date\", \"prom_1yr_date\")\n  names(raw)[names(raw) == \"Score\"] <- c(\"prom_preop\", \"prom_1yr\")\n\n  raw |>\n    janitor::clean_names() |> # \"Pt Name\" -> pt_name, \"Study ID\" -> study_id\n    mutate(site = sheet)      # remember which tab each row came from\n}\n\nraw <- bind_rows(read_site(\"Site A\"), read_site(\"Site B\"))   # matches columns by name\nnrow(raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 126\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"pt_name\"         \"mrn\"             \"study_id\"        \"dos\"            \n [5] \"age\"             \"sex\"             \"bmi\"             \"asa\"            \n [9] \"comorbidities\"   \"procedure\"       \"los\"             \"prom_preop_date\"\n[13] \"prom_preop\"      \"prom_1yr_date\"   \"prom_1yr\"        \"notes\"          \n[17] \"site\"            \"mua\"            \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport re\n\npath = \"data/messy_abstraction_workbook.xlsx\"\n\ndef read_site(sheet):\n    # header=3 uses the 4th row as column names (after banners and group headers)\n    raw = pd.read_excel(path, sheet_name=sheet, header=3, dtype=str)\n    names = [str(c).strip() for c in raw.columns]   # \"Study ID \" has a trailing space on Site B\n\n    # pandas renames repeated headers to \"Date.1\" and \"Score.1\"\n    pairs = {\"Date\": \"prom_preop_date\", \"Score\": \"prom_preop\",\n             \"Date.1\": \"prom_1yr_date\", \"Score.1\": \"prom_1yr\"}\n    names = [pairs.get(n, n) for n in names]\n\n    # \"Pt Name\" -> pt_name, \"Study ID\" -> study_id\n    raw.columns = [re.sub(r\"[^0-9a-z]+\", \"_\", n.lower()).strip(\"_\") for n in names]\n    return raw.assign(site=sheet)   # remember which tab each row came from\n\nraw = pd.concat([read_site(\"Site A\"), read_site(\"Site B\")], ignore_index=True)  # matches by name\nprint(len(raw))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n126\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(list(raw.columns))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n['pt_name', 'mrn', 'study_id', 'dos', 'age', 'sex', 'bmi', 'asa', 'comorbidities', 'procedure', 'los', 'prom_preop_date', 'prom_preop', 'prom_1yr_date', 'prom_1yr', 'notes', 'site', 'mua']\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n126 rows: 60 patients per tab, plus 2 duplicates and a totals row in each. Because we stacked the tabs **by column name**, Site B's extra `MUA` column didn't shift anything. Site A rows simply have `mua` missing. Copying cells by position would have put LOS values under the wrong heading.\n\nIn R we call `janitor::clean_names()` with the package name in front instead of loading janitor with `library()`. Loading janitor *masks* R's own `chisq.test()` and `fisher.test()` with janitor's versions. They give the same answers for ordinary tables, but the masking message is confusing, and it becomes harder to tell which function you're actually calling.\n\n::: {.callout-tip}\n## 🔀 R vs Python: the same Excel file, read differently\n- **Repeated headers.** R (with `.name_repair = \"minimal\"`) keeps both `Date` columns as `Date`. pandas renames the second to `Date.1`.\n- **Real Excel dates.** Read as text, R gives the Excel serial number (`42010` means 6 Jan 2015). pandas gives `2015-01-06 00:00:00`. Step 5 handles both.\n:::\n\n### Step 2: drop rows and columns that aren't data\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstep2 <- raw |>\n  filter(is.na(pt_name) | pt_name != \"TOTAL\") |>   # the totals rows\n  distinct() |>                                      # exact duplicate rows\n  select(-pt_name, -mrn, -mua)                       # identifiers, and a column we don't need\n\nnrow(step2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nstep2 = (raw[raw[\"pt_name\"] != \"TOTAL\"]           # the totals rows\n         .drop_duplicates()                        # exact duplicate rows\n         .drop(columns=[\"pt_name\", \"mrn\", \"mua\"])) # identifiers, and a column we don't need\nprint(len(step2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n120\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nNames and MRNs go as early as possible. Everything after this point works on a study ID only.\n\n### Step 3: one way to say \"missing\"\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmissing_codes <- c(\"N/A\", \"unk\", \"-\", \"999\")\n\nstep3 <- step2 |>\n  mutate(across(everything(), \\(x) if_else(x %in% missing_codes, NA, x)))\n\n# How many BMI values are missing now?\nsum(is.na(step3$bmi))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmissing_codes = [\"N/A\", \"unk\", \"-\", \"999\"]\n\nstep3 = step2.replace(missing_codes, pd.NA)\n\n# How many BMI values are missing now?\nprint(step3[\"bmi\"].isna().sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n8\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n::: {.callout-warning}\n## ⚠️ Watch out: `999` is only a missing code if your dictionary says so\nIn this sheet `999` means \"missing\" in number columns. In another sheet it could be a real value. Write every missing code into the data dictionary *before* collection starts.\n:::\n\n### Step 4: recover the color-coded revisions\n\nThe sheet marks revised cases only with a red fill on the Study ID cell. Most software reading a spreadsheet can't see colors at all, which is exactly why color must never carry data. Here we have to dig it out.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyxl)\n\ncells   <- xlsx_cells(path)                                 # one row per spreadsheet cell\nfills   <- xlsx_formats(path)$local$fill$patternFill$fgColor$rgb  # fill color of each format\n\nrevised_ids <- cells |>\n  filter(fills[local_format_id] %in% \"FFFF9999\") |>         # the red fill\n  pull(character) |>\n  str_trim() |>\n  unique()\n\nlength(revised_ids)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport openpyxl\n\nworkbook = openpyxl.load_workbook(path)\n\nrevised_ids = set()\nfor sheet in workbook.worksheets:\n    for row in sheet.iter_rows(min_row=5):        # data starts on row 5\n        for cell in row:\n            if cell.fill.fgColor.rgb == \"FFFF9999\":   # the red fill\n                revised_ids.add(str(cell.value).strip())\n\nprint(len(revised_ids))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n18\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nThe `Notes` column mentions some revisions (\"revised 2021 for loosening\"), but not all of them. If we had trusted the notes we would have missed cases. Only the colors were complete.\n\n### Step 5: give every column its real type\n\nNow convert each text column into what it really is. One small function handles the mixed date formats. Each recode lists the values it expects and turns anything else into a missing value, so a surprise like `U` for sex shows up instead of silently becoming \"Male\".\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dates arrive as Excel serial numbers (\"42010\"), ISO dates (\"2015-04-21\"),\n# or Swiss day-first text (\"13.01.15\", \"13.1.2015\"). Handle the serial\n# numbers, then the ISO dates, then read the rest day-first.\nparse_messy_date <- function(x, day_first = TRUE) {\n  serial <- !is.na(x) & str_detect(x, \"^\\\\d{5}$\")\n  iso    <- !is.na(x) & str_detect(x, \"^\\\\d{4}-\\\\d{2}-\\\\d{2}$\")\n  rest   <- !is.na(x) & !serial & !iso\n  out <- as.Date(rep(NA, length(x)))\n  out[serial] <- janitor::excel_numeric_to_date(as.numeric(x[serial]))\n  out[iso]    <- ymd(x[iso])\n  out[rest]   <- if (day_first) dmy(x[rest], quiet = TRUE) else mdy(x[rest], quiet = TRUE)\n  out\n}\n\ntidy <- step3 |>\n  rename(procedure_text = procedure) |>   # keep the raw text until we've split it\n  transmute(\n    case_id      = str_trim(study_id),\n    site,\n    surgery_date = parse_messy_date(dos),\n    age          = parse_number(age),            # \"67 yo\"      -> 67\n    sex          = case_when(str_detect(sex, regex(\"^f\", ignore_case = TRUE)) ~ \"Female\",\n                             str_detect(sex, regex(\"^m\", ignore_case = TRUE)) ~ \"Male\"),  # anything else -> NA\n    bmi          = parse_number(bmi),            # \"BMI 31.2\"   -> 31.2\n    asa          = as.integer(as.roman(str_remove(asa, \"^ASA \"))),  # \"II\", \"ASA 2\", \"2\" -> 2\n    diabetes     = as.integer(str_detect(comorbidities, regex(\"\\\\bDM\\\\b\", ignore_case = TRUE))),\n    hypertension = as.integer(str_detect(comorbidities, regex(\"\\\\bHTN\\\\b\", ignore_case = TRUE))),\n    sleep_apnea  = as.integer(str_detect(comorbidities, regex(\"\\\\bOSA\\\\b\", ignore_case = TRUE))),\n    procedure    = case_when(str_detect(procedure_text, regex(\"TKA|knee\", ignore_case = TRUE)) ~ \"TKA\",\n                             str_detect(procedure_text, regex(\"THA|hip\", ignore_case = TRUE)) ~ \"THA\"),\n    side         = case_when(str_detect(procedure_text, \"\\\\b(L|Left)\\\\b\") ~ \"L\",\n                             str_detect(procedure_text, \"\\\\b(R|Right)\\\\b\") ~ \"R\"),\n    los_days     = parse_number(los),            # \"0 (same day)\" -> 0\n    revised      = as.integer(case_id %in% revised_ids),\n    prom_preop_date = parse_messy_date(prom_preop_date),\n    prom_preop      = parse_number(prom_preop),\n    prom_1yr_date   = parse_messy_date(prom_1yr_date),\n    prom_1yr        = parse_number(prom_1yr)\n  ) |>\n  arrange(site, case_id)\n\nglimpse(tidy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 120\nColumns: 18\n$ case_id         <chr> \"C0004\", \"C0007\", \"C0017\", \"C0034\", \"C0035\", \"C0045\", …\n$ site            <chr> \"Site A\", \"Site A\", \"Site A\", \"Site A\", \"Site A\", \"Sit…\n$ surgery_date    <date> 2015-01-22, 2015-02-08, 2015-05-14, 2015-08-20, 2015-…\n$ age             <dbl> 66, 50, 53, 71, 52, 60, 59, 66, 68, 61, 71, 50, 61, 68…\n$ sex             <chr> \"Male\", \"Male\", \"Female\", \"Male\", \"Female\", \"Male\", \"F…\n$ bmi             <dbl> 24.2, 35.3, 34.7, 22.2, 33.5, 35.9, 29.8, 25.5, 30.2, …\n$ asa             <int> 2, 3, 2, 3, 1, 3, 2, 2, 3, 3, 2, 2, 2, 3, 2, 1, 3, 3, …\n$ diabetes        <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ hypertension    <int> 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, …\n$ sleep_apnea     <int> 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ procedure       <chr> \"TKA\", \"TKA\", \"THA\", \"THA\", \"THA\", \"TKA\", \"THA\", \"THA\"…\n$ side            <chr> \"L\", \"L\", \"L\", \"L\", \"R\", \"R\", \"R\", \"L\", \"R\", \"R\", \"L\",…\n$ los_days        <dbl> 0, 0, 0, 2, 0, 1, 1, 0, 2, 0, 4, 1, 3, 0, 2, 0, 1, 1, …\n$ revised         <int> 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, …\n$ prom_preop_date <date> 2015-01-08, 2015-01-25, 2015-05-07, 2015-08-09, 2015-…\n$ prom_preop      <dbl> 49.9, 61.7, 36.3, 45.5, 33.8, 36.2, 46.4, 44.2, 33.8, …\n$ prom_1yr_date   <date> 2016-01-16, NA, 2016-06-09, 2016-08-15, 2016-08-22, 2…\n$ prom_1yr        <dbl> 91.6, NA, 99.7, 82.1, 85.5, 63.6, 68.2, 74.0, NA, NA, …\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\n\ndef number(text):\n    # The first number in each cell: \"67 yo\" -> 67, \"BMI 31.2\" -> 31.2\n    return pd.to_numeric(text.str.extract(r\"(\\d+\\.?\\d*)\")[0])\n\nasa_roman = {\"I\": \"1\", \"II\": \"2\", \"III\": \"3\", \"IV\": \"4\"}\nprocedure_text = step3[\"procedure\"]   # keep the raw text until we've split it\n\ndef parse_messy_date(col, dayfirst=True):\n    \"\"\"Every cell arrives as text: ISO dates (\"2015-04-21\", and real Excel dates as\n    \"2015-01-06 00:00:00\") or Swiss day-first dates (\"13.01.15\", \"13.1.2015\").\n    dayfirst=True would also flip ISO dates, so they're read on their own.\"\"\"\n    iso = col.str.match(r\"\\d{4}-\\d{2}-\\d{2}\", na=False)\n    swiss = col.notna() & ~iso\n    dates = pd.concat([pd.to_datetime(col[iso], format=\"ISO8601\"),\n                       pd.to_datetime(col[swiss], format=\"mixed\", dayfirst=dayfirst)])\n    return dates.reindex(col.index)   # back in row order; empty cells stay missing (NaT)\n\ntidy = pd.DataFrame({\n    \"case_id\":      step3[\"study_id\"].str.strip(),\n    \"site\":         step3[\"site\"],\n    \"surgery_date\": parse_messy_date(step3[\"dos\"]),\n    \"age\":          number(step3[\"age\"]),\n    \"sex\":          step3[\"sex\"].str[0].str.lower().map({\"f\": \"Female\", \"m\": \"Male\"}),\n    \"bmi\":          number(step3[\"bmi\"]),\n    \"asa\":          pd.to_numeric(step3[\"asa\"].str.replace(\"ASA \", \"\").replace(asa_roman)),\n    \"diabetes\":     step3[\"comorbidities\"].str.contains(r\"\\bDM\\b\", case=False).astype(int),\n    \"hypertension\": step3[\"comorbidities\"].str.contains(r\"\\bHTN\\b\", case=False).astype(int),\n    \"sleep_apnea\":  step3[\"comorbidities\"].str.contains(r\"\\bOSA\\b\", case=False).astype(int),\n    \"procedure\":    np.select([procedure_text.str.contains(r\"TKA|knee\", case=False),\n                               procedure_text.str.contains(r\"THA|hip\", case=False)],\n                              [\"TKA\", \"THA\"], default=None),          # anything else -> missing\n    \"side\":         np.select([procedure_text.str.contains(r\"\\b(?:L|Left)\\b\"),\n                               procedure_text.str.contains(r\"\\b(?:R|Right)\\b\")],\n                              [\"L\", \"R\"], default=None),\n    \"los_days\":     number(step3[\"los\"]),\n    \"revised\":      step3[\"study_id\"].str.strip().isin(revised_ids).astype(int),\n    \"prom_preop_date\": parse_messy_date(step3[\"prom_preop_date\"]),\n    \"prom_preop\":      number(step3[\"prom_preop\"]),\n    \"prom_1yr_date\":   parse_messy_date(step3[\"prom_1yr_date\"]),\n    \"prom_1yr\":        number(step3[\"prom_1yr\"]),\n}).sort_values([\"site\", \"case_id\"]).reset_index(drop=True)\n\ntidy.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<class 'pandas.DataFrame'>\nRangeIndex: 120 entries, 0 to 119\nData columns (total 18 columns):\n #   Column           Non-Null Count  Dtype         \n---  ------           --------------  -----         \n 0   case_id          120 non-null    str           \n 1   site             120 non-null    str           \n 2   surgery_date     120 non-null    datetime64[us]\n 3   age              120 non-null    int64         \n 4   sex              120 non-null    str           \n 5   bmi              112 non-null    float64       \n 6   asa              117 non-null    float64       \n 7   diabetes         120 non-null    int64         \n 8   hypertension     120 non-null    int64         \n 9   sleep_apnea      120 non-null    int64         \n 10  procedure        120 non-null    str           \n 11  side             120 non-null    str           \n 12  los_days         117 non-null    float64       \n 13  revised          120 non-null    int64         \n 14  prom_preop_date  115 non-null    datetime64[us]\n 15  prom_preop       115 non-null    float64       \n 16  prom_1yr_date    98 non-null     datetime64[us]\n 17  prom_1yr         98 non-null     float64       \ndtypes: datetime64[us](3), float64(5), int64(5), str(5)\nmemory usage: 17.0 KB\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n\n\n\n\n::: {.callout-tip}\n## 🔀 R vs Python: dates\nR needs a separate step for Excel serial numbers (`janitor::excel_numeric_to_date()`). pandas already turned those cells into date-time text (`2015-01-06 00:00:00`), which its `parse_messy_date()` reads with the other ISO dates. Both read `\"13.01.15\"` day-first: Swiss style, which is what HFR sheets use. Both read ISO dates on their own, because pandas' `dayfirst=True` would also flip them (`2015-11-02` would become 11 February).\n:::\n\n## Reshaping a survey export {#reshaping}\n\n`data/messy_survey_export.csv` is what survey platforms produce: one row per patient, one column per question per visit (`KOOS_Q3_6wk`), and a second header row of question labels. To analyze it we need one row per patient, visit and item.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey_path <- \"data/messy_survey_export.csv\"\n\nheader <- read_lines(survey_path, n_max = 1) |> str_split_1(\",\")\nwide <- read_csv(survey_path, skip = 2, col_names = header,          # skip both header rows\n                 col_types = cols(.default = \"c\"))\n\nitems <- wide |>\n  pivot_longer(\n    -c(ResponseId, case_id, instrument),\n    names_to = c(\"inst\", \"item\", \"visit\"),\n    names_pattern = \"(KOOS|HOOS)_Q(\\\\d)_(.*)\",       # \"KOOS_Q3_6wk\" -> KOOS, 3, 6wk\n    values_to = \"response\"\n  ) |>\n  filter(substr(instrument, 1, 4) == inst) |>         # keep each patient's own instrument\n  mutate(item = as.integer(item), response = as.integer(response),\n         visit_order = match(visit, c(\"preop\", \"6wk\", \"3mo\", \"1yr\"))) |>\n  arrange(case_id, visit_order, item) |>\n  select(case_id, instrument, visit, item, response)\n\nitems\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,928 × 5\n   case_id instrument visit  item response\n   <chr>   <chr>      <chr> <int>    <int>\n 1 C0004   KOOS JR    preop     1        3\n 2 C0004   KOOS JR    preop     2        3\n 3 C0004   KOOS JR    preop     3        2\n 4 C0004   KOOS JR    preop     4        3\n 5 C0004   KOOS JR    preop     5        2\n 6 C0004   KOOS JR    preop     6        2\n 7 C0004   KOOS JR    preop     7        2\n 8 C0004   KOOS JR    6wk       1        1\n 9 C0004   KOOS JR    6wk       2        1\n10 C0004   KOOS JR    6wk       3        3\n# ℹ 3,918 more rows\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nsurvey_path = \"data/messy_survey_export.csv\"\n\nwide = pd.read_csv(survey_path, skiprows=[1], dtype=str)   # skip the question-label row\n\nitems = wide.melt(id_vars=[\"ResponseId\", \"case_id\", \"instrument\"],\n                  var_name=\"column\", value_name=\"response\")\nparts = items[\"column\"].str.extract(r\"(?P<inst>KOOS|HOOS)_Q(?P<item>\\d)_(?P<visit>.+)\")\nitems = pd.concat([items, parts], axis=1)\nitems = items[items[\"instrument\"].str[:4] == items[\"inst\"]]   # keep each patient's own instrument\n\nvisit_order = {\"preop\": 0, \"6wk\": 1, \"3mo\": 2, \"1yr\": 3}\nitems = (items.assign(item=items[\"item\"].astype(int),\n                      response=pd.to_numeric(items[\"response\"]),\n                      order=items[\"visit\"].map(visit_order))\n              .sort_values([\"case_id\", \"order\", \"item\"])\n              [[\"case_id\", \"instrument\", \"visit\", \"item\", \"response\"]]\n              .reset_index(drop=True))\nprint(items)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     case_id instrument  visit  item  response\n0      C0004    KOOS JR  preop     1       3.0\n1      C0004    KOOS JR  preop     2       3.0\n2      C0004    KOOS JR  preop     3       2.0\n3      C0004    KOOS JR  preop     4       3.0\n4      C0004    KOOS JR  preop     5       2.0\n...      ...        ...    ...   ...       ...\n3923   C0600    KOOS JR    1yr     3       1.0\n3924   C0600    KOOS JR    1yr     4       0.0\n3925   C0600    KOOS JR    1yr     5       0.0\n3926   C0600    KOOS JR    1yr     6       0.0\n3927   C0600    KOOS JR    1yr     7       0.0\n\n[3928 rows x 5 columns]\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n\n\nA KOOS JR patient now has 7 items × 4 visits = 28 rows. A missed visit still has its rows, with the response blank, so \"expected but not answered\" stays visible.\n\n## Checking nothing changed {#integrity}\n\nOn a real project nobody hands you an answer key. These checks need nothing but the raw sheet and your result. Run them after every cleaning job.\n\n**1. Rows and IDs.** You should have exactly one row per case, and the count should match what you expect.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(tidy)                       # 60 per site\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n\n```{.r .cell-code}\nn_distinct(tidy$case_id)         # must equal nrow: no duplicate IDs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n\n```{.r .cell-code}\ncount(tidy, site)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  site       n\n  <chr>  <int>\n1 Site A    60\n2 Site B    60\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(len(tidy))                       # 60 per site\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n120\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(tidy[\"case_id\"].nunique())       # must equal len: no duplicate IDs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n120\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(tidy[\"site\"].value_counts())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsite\nSite A    60\nSite B    60\nName: count, dtype: int64\n```\n\n\n:::\n:::\n\n:::\n\n**2. Missing values didn't appear or disappear.** Every missing BMI in the result should trace back to a missing code or blank in the sheet.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmissing_in_sheet  <- sum(is.na(step2$bmi) | step2$bmi %in% missing_codes)\nmissing_in_result <- sum(is.na(tidy$bmi))\nc(sheet = missing_in_sheet, result = missing_in_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n sheet result \n     8      8 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmissing_in_sheet = (step2[\"bmi\"].isna() | step2[\"bmi\"].isin(missing_codes)).sum()\nmissing_in_result = tidy[\"bmi\"].isna().sum()\nprint(missing_in_sheet, missing_in_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n8 8\n```\n\n\n:::\n:::\n\n:::\n\n**3. Cross-tab every recode.** Put each raw value next to the value that ended up in the finished table (matched by case ID). Each messy spelling should map to exactly one clean value, and nothing should map to missing by accident. Comparing with `tidy` itself, rather than re-running the recode, is what lets this check catch a mistake in step 5.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstep3 |>\n  transmute(case_id = str_trim(study_id), raw = sex) |>\n  left_join(select(tidy, case_id, clean = sex), by = \"case_id\") |>\n  count(raw, clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 3\n  raw    clean      n\n  <chr>  <chr>  <int>\n1 F      Female    16\n2 Female Female    17\n3 M      Male      19\n4 Male   Male      12\n5 f      Female    20\n6 female Female    18\n7 male   Male      18\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nraw_sex = pd.DataFrame({\"case_id\": step3[\"study_id\"].str.strip(), \"raw\": step3[\"sex\"]})\nrecode = raw_sex.merge(tidy[[\"case_id\", \"sex\"]].rename(columns={\"sex\": \"clean\"}), on=\"case_id\")\nprint(recode.groupby([\"raw\", \"clean\"], dropna=False).size())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nraw     clean \nF       Female    16\nFemale  Female    17\nM       Male      19\nMale    Male      12\nf       Female    20\nfemale  Female    18\nmale    Male      18\ndtype: int64\n```\n\n\n:::\n:::\n\n:::\n\n**4. Range and logic checks.** Values a person can't have, and dates in the wrong order.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy |>\n  summarise(\n    age_out_of_range  = sum(age < 18 | age > 110, na.rm = TRUE),\n    bmi_out_of_range  = sum(bmi < 10 | bmi > 80, na.rm = TRUE),\n    prom_out_of_range = sum(prom_preop < 0 | prom_preop > 100 | prom_1yr < 0 | prom_1yr > 100, na.rm = TRUE),\n    preop_after_surgery = sum(prom_preop_date > surgery_date, na.rm = TRUE),\n    one_year_before_surgery = sum(prom_1yr_date < surgery_date, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  age_out_of_range bmi_out_of_range prom_out_of_range preop_after_surgery\n             <int>            <int>             <int>               <int>\n1                0                0                 0                   0\n# ℹ 1 more variable: one_year_before_surgery <int>\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nchecks = {\n    \"age_out_of_range\": ((tidy[\"age\"] < 18) | (tidy[\"age\"] > 110)).sum(),\n    \"bmi_out_of_range\": ((tidy[\"bmi\"] < 10) | (tidy[\"bmi\"] > 80)).sum(),\n    \"prom_out_of_range\": ((tidy[\"prom_preop\"] < 0) | (tidy[\"prom_preop\"] > 100) |\n                          (tidy[\"prom_1yr\"] < 0) | (tidy[\"prom_1yr\"] > 100)).sum(),\n    \"preop_after_surgery\": (tidy[\"prom_preop_date\"] > tidy[\"surgery_date\"]).sum(),\n    \"one_year_before_surgery\": (tidy[\"prom_1yr_date\"] < tidy[\"surgery_date\"]).sum(),\n}\nprint(pd.Series(checks))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nage_out_of_range           0\nbmi_out_of_range           0\nprom_out_of_range          0\npreop_after_surgery        0\none_year_before_surgery    0\ndtype: int64\n```\n\n\n:::\n:::\n\n:::\n\nAll zeros: good.\n\n**5. Spot-check against the sheet.** Pick a few random rows and compare them, by eye, with the workbook.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\ntidy |> slice_sample(n = 3) |> select(case_id, site, surgery_date, age, bmi, procedure, side)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  case_id site   surgery_date   age   bmi procedure side \n  <chr>   <chr>  <date>       <dbl> <dbl> <chr>     <chr>\n1 C0064   Site B 2016-02-07      51  34.1 THA       R    \n2 C0332   Site A 2020-01-01      65  30.6 TKA       L    \n3 C0004   Site A 2015-01-22      66  24.2 TKA       L    \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(tidy.sample(n=3, random_state=1)[[\"case_id\", \"site\", \"surgery_date\", \"age\", \"bmi\", \"procedure\", \"side\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   case_id    site surgery_date  age   bmi procedure side\n95   C0353  Site B   2020-04-13   72  22.7       THA    R\n54   C0451  Site A   2021-11-08   65  18.0       TKA    R\n59   C0557  Site A   2023-06-08   59  28.3       THA    R\n```\n\n\n:::\n:::\n\n:::\n\n### What a failing check looks like\n\nSuppose we had parsed the surgery dates month-first (US style, as many online examples do) by mistake. Nothing crashes. Two checks catch it: a missing count (check 2, applied to the dates) and a new logic check that every pre-op PROM falls within a month before surgery.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrong <- parse_messy_date(step3$dos, day_first = FALSE)   # the mistake\npreop <- parse_messy_date(step3$prom_preop_date)\n\noutside_window <- function(surgery) {\n  days_before <- as.numeric(surgery - preop)\n  sum(days_before < 0 | days_before > 31, na.rm = TRUE)\n}\nc(missing_correct     = sum(is.na(tidy$surgery_date)),\n  missing_month_first = sum(is.na(wrong)),\n  window_correct      = outside_window(parse_messy_date(step3$dos)),\n  window_month_first  = outside_window(wrong))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    missing_correct missing_month_first      window_correct  window_month_first \n                  0                  30                   0                  12 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nwrong = parse_messy_date(step3[\"dos\"], dayfirst=False)   # the mistake\npreop = parse_messy_date(step3[\"prom_preop_date\"])\n\ndef outside_window(surgery):\n    days_before = (surgery - preop).dt.days\n    return int(((days_before < 0) | (days_before > 31)).sum())\n\nprint(pd.Series({\n    \"missing_correct\": tidy[\"surgery_date\"].isna().sum(),\n    \"missing_month_first\": wrong.isna().sum(),\n    \"window_correct\": outside_window(parse_messy_date(step3[\"dos\"])),\n    \"window_month_first\": outside_window(wrong),\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmissing_correct         0\nmissing_month_first     0\nwindow_correct          0\nwindow_month_first     12\ndtype: int64\n```\n\n\n:::\n:::\n\n:::\n\n\n\nWith the correct parse, nothing is missing and every pre-op PROM falls in its window. The month-first versions go wrong in different ways:\n\n- **R** can't read dates like `\"13.01.15\"` month-first (there's no 13th month), so 30 surgery dates go missing. Others, like `\"04.03.24\"`, parse \"successfully\" as 3 April instead of 4 March, and the window check flags 12 of them.\n- **pandas** never returns a missing date here: when month-first is impossible it quietly switches to day-first, so `\"13.01.15\"` comes out right by luck while `\"04.03.24\"` becomes 3 April. Only the window check notices: it flags 12 dates.\n\n::: {.callout-warning}\n## ⚠️ Watch out: one check is never enough\nNever parse a column that mixes formats with one setting: read each format on its own, as `parse_messy_date()` does. And notice that the missing count caught this bug in R but not in Python, while the logic check caught it in both. Run all the checks every time; they catch different mistakes.\n:::\n\n### Finally: compare with the answer key\n\nBecause this is a teaching dataset, there *is* a known right answer: `data/answer-keys/abstraction_workbook_tidy.csv`. Our result matches it exactly.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanswer <- read_csv(\"data/answer-keys/abstraction_workbook_tidy.csv\", show_col_types = FALSE)\nall.equal(as.data.frame(tidy), as.data.frame(answer), check.attributes = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nanswer = pd.read_csv(\"data/answer-keys/abstraction_workbook_tidy.csv\",\n                     parse_dates=[\"surgery_date\", \"prom_preop_date\", \"prom_1yr_date\"])\npd.testing.assert_frame_equal(tidy, answer, check_dtype=False)   # silent means identical\nprint(\"identical\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nidentical\n```\n\n\n:::\n:::\n\n:::\n\n\n\n## Exercises {#exercises}\n\n**1.** Use a cross-tab (check 3) to confirm the ASA recode: every raw spelling should map to one class from 1 to 4.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstep3 |>\n  transmute(case_id = str_trim(study_id), raw = asa) |>\n  left_join(select(tidy, case_id, clean = asa), by = \"case_id\") |>\n  count(raw, clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 3\n   raw   clean     n\n   <chr> <int> <int>\n 1 1         1     7\n 2 2         2    43\n 3 3         3    24\n 4 ASA 1     1     3\n 5 ASA 2     2     4\n 6 ASA 3     3     3\n 7 I         1     2\n 8 II        2    14\n 9 III       3    17\n10 <NA>     NA     3\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nraw_asa = pd.DataFrame({\"case_id\": step3[\"study_id\"].str.strip(), \"raw\": step3[\"asa\"]})\nasa = raw_asa.merge(tidy[[\"case_id\", \"asa\"]].rename(columns={\"asa\": \"clean\"}), on=\"case_id\")\nprint(asa.groupby([\"raw\", \"clean\"], dropna=False).size())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nraw    clean\n1      1.0       7\n2      2.0      43\n3      3.0      24\nASA 1  1.0       3\nASA 2  2.0       4\nASA 3  3.0       3\nI      1.0       2\nII     2.0      14\nIII    3.0      17\nNaN    NaN       3\ndtype: int64\n```\n\n\n:::\n:::\n\n:::\n\n`2`, `II` and `ASA 2` all become 2, and the missing codes stay missing.\n:::\n\n**2.** A colleague's sheet has one row per patient and the columns `koos_left_preop`, `koos_left_1yr`, `koos_right_preop`, `koos_right_1yr`. Is it tidy? If not, what should one row be?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nNot tidy: *side* and *visit* are hiding in the column names. One row should be one knee at one visit, with columns `patient_id`, `side`, `visit`, `koos`. Reshape it with `pivot_longer()` (R) or `melt()` (Python), splitting each column name into side and visit, as we did for the survey export.\n:::\n\n**3.** How many cases have a 1-year PROM recorded but no pre-op PROM? Why would that matter for an analysis of improvement?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy |> filter(!is.na(prom_1yr), is.na(prom_preop)) |> nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(((tidy[\"prom_1yr\"].notna()) & (tidy[\"prom_preop\"].isna())).sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n5\n```\n\n\n:::\n:::\n\n:::\n\nThose patients have no baseline, so their improvement can't be computed. An analysis of change silently drops them. Report how many, so readers know.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}