{
  "hash": "27395cb652ab1ec6c9436a4e086f8e8a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"9 · Compare three or more matched groups\"\ndescription: \"Repeated-measures ANOVA, Friedman test, Cochran's Q and stratified Cox regression: the same patients measured three or more times, or matched sets.\"\nengine: knitr\ntoc-depth: 2\n---\n\n\n\n<!-- data-checksum: ffc54e2ad996e1e61ad10ca520e4d588 -->\n\nThe same patients measured **three or more times** (before surgery, then at 6 weeks, 3 months and 1 year), or **matched sets** of three or more patients. This is [page 7](07-two-paired-groups.qmd) extended past two measurements. As on [page 8](08-three-plus-unmatched.qmd), each test asks one question first: **does the outcome differ anywhere among the visits (or groups)?** [Which visits differ?](#which-groups-differ) explains what to do next.\n\n::: {.callout-note}\n## 💡 How every section on this page works\nEach section answers one question about the practice data. Its first code block loads the packages and the data, so you can jump straight to the section you need. Run that section's blocks in order, top to bottom.\n\nTo keep the code short, the examples use every case, including the 80 patients who had both sides operated on. In a real study, decide how to handle them ([page 3](../foundations/03-distributions.qmd#paired)) and say what you did.\n:::\n\n::: {.callout-warning}\n## ⚠️ Watch out: these tests drop anyone with a missed visit\nRepeated-measures ANOVA, the Friedman test and Cochran's Q need every patient measured at **every** visit. A patient who missed one visit is dropped completely, along with their other measurements. Below, 574 patients had a pre-op VR-12 score, but only 328 had all four, so the analysis loses 246 patients (43%). If the patients who miss visits differ from those who don't, the result is biased. [Mixed models](../beyond/16-mixed-models.qmd#why-mixed-models) use everyone's available data, and are usually the better choice for repeated PROMs.\n:::\n\n## Repeated-measures ANOVA {#repeated-measures-anova}\n\n**The question:** Does patients' physical health (the VR-12 physical component score, PCS) change over the first year after surgery?\n\n### When to use it\n\n- A **measurement** taken **three or more times** on the same patients (or once on each member of a matched set).\n- The changes between visits are roughly normal, or there are plenty of patients.\n- **Sphericity:** the spread of the changes is similar for every pair of visits. Mauchly's test checks it; if it fails, the **Greenhouse-Geisser** correction adjusts the degrees of freedom. Both programs below report both.\n- Only patients measured at **every** visit are included (see the warning above).\n- If the outcome is skewed, bounded or ordinal → the [Friedman test](#friedman).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nproms <- read_csv(\"data/proms_long.csv\", show_col_types = FALSE)\n\npcs <- proms |>\n  select(case_id, visit, vr12_pcs) |>\n  group_by(case_id) |>\n  filter(all(!is.na(vr12_pcs))) |>     # keep patients measured at all four visits\n  ungroup() |>\n  mutate(visit = factor(visit, levels = c(\"preop\", \"6wk\", \"3mo\", \"1yr\")))   # in time order\n\nn_distinct(pcs$case_id)                # patients with complete data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 328\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(pcs, aes(visit, vr12_pcs)) +\n  geom_boxplot() +\n  labs(x = \"Visit\", y = \"VR-12 physical component score\")\n```\n\n::: {.cell-output-display}\n![](09-three-plus-matched_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\npcs |>\n  group_by(visit) |>\n  summarise(mean = mean(vr12_pcs), sd = sd(vr12_pcs))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  visit  mean    sd\n  <fct> <dbl> <dbl>\n1 preop  31.2  6.10\n2 6wk    34.9  6.15\n3 3mo    41.0  6.23\n4 1yr    44.9  6.77\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport pingouin as pg\nimport matplotlib.pyplot as plt\n\nproms = pd.read_csv(\"data/proms_long.csv\")\nvisits = [\"preop\", \"6wk\", \"3mo\", \"1yr\"]   # in time order\n\npcs = proms[[\"case_id\", \"visit\", \"vr12_pcs\"]]\ncomplete = pcs.groupby(\"case_id\")[\"vr12_pcs\"].transform(lambda scores: scores.notna().all())\npcs = pcs[complete]                        # keep patients measured at all four visits\n\nprint(pcs[\"case_id\"].nunique())            # patients with complete data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n328\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, ax = plt.subplots(figsize=(6, 3))\nparts = ax.boxplot([pcs.loc[pcs[\"visit\"] == v, \"vr12_pcs\"] for v in visits], tick_labels=visits)   # naming the result keeps it out of the output\nax.set_xlabel(\"Visit\")\nax.set_ylabel(\"VR-12 physical component score\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](09-three-plus-matched_files/figure-html/unnamed-chunk-4-1.png)\n:::\n\n```{.python .cell-code}\nprint(pcs.groupby(\"visit\")[\"vr12_pcs\"].agg([\"mean\", \"std\"]).loc[visits])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            mean       std\nvisit                     \npreop  31.236585  6.097004\n6wk    34.903354  6.152841\n3mo    40.985671  6.234869\n1yr    44.879268  6.772751\n```\n\n\n:::\n:::\n\n:::\n\n328 patients were measured at all four visits. Their mean PCS climbs at every visit, and the spreads stay similar.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npcs_anova <- rstatix::anova_test(data = pcs, dv = vr12_pcs, wid = case_id, within = visit,\n                                 effect.size = c(\"pes\", \"ges\"))   # partial and generalized eta squared\npcs_anova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nANOVA Table (type III tests)\n\n$ANOVA\n  Effect DFn DFd       F         p p<.05   pes   ges\n1  visit   3 981 317.067 7.07e-144     * 0.492 0.412\n\n$`Mauchly's Test for Sphericity`\n  Effect     W     p p<.05\n1  visit 0.982 0.324      \n\n$`Sphericity Corrections`\n  Effect   GGe       DF[GG]     p[GG] p[GG]<.05   HFe      DF[HF]     p[HF]\n1  visit 0.988 2.96, 969.07 3.63e-142         * 0.998 2.99, 978.9 1.41e-143\n  p[HF]<.05\n1         *\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npcs_anova = pg.rm_anova(data=pcs, dv=\"vr12_pcs\", within=\"visit\", subject=\"case_id\",\n                        correction=True, effsize=\"np2\", detailed=True)   # np2 = partial eta squared\nprint(pcs_anova.T)    # .T turns the wide table on its side, so it fits\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       0             1\nSource             visit         Error\nSS          36595.469085  37741.935915\nDF                     3           981\nMS          12198.489695     38.472921\nF             317.066894           NaN\np_unc                0.0           NaN\np_GG_corr            0.0           NaN\nnp2             0.492289           NaN\neps             0.987839           NaN\nsphericity          True           NaN\nW_spher         0.982302           NaN\np_spher           0.3245           NaN\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **F = 317.1, with 3 and 981 degrees of freedom** (DFn/DFd in R, DF in Python): how much the visit means differ, compared with how much each patient's scores bounce around their own average. 3 = four visits minus one; 981 = 3 × (328 patients − 1).\n- **p** (R prints `7.07e-144`; pingouin's table rounds it to `0.0` in the `p_unc` row): far below 0.001.\n- **Mauchly's test, W = 0.982, p = 0.324:** no evidence that sphericity is violated, so the uncorrected result stands.\n- **Sphericity corrections** (R) or **eps** and **p_GG_corr** (Python): the Greenhouse-Geisser epsilon is 0.988 (1 means perfect sphericity), and the corrected p-value is still far below 0.001.\n- **pes = 0.492** (R) or **np2** (Python): partial eta squared, below.\n\n### Effect size and 95% CI\n\n**Partial eta squared (η²~p~)** is the share of the within-patient variation that the visits account for. As a rough guide, 0.01 is small, 0.06 medium and 0.14 large. **Generalized eta squared** (ges = 0.412 in R) also counts the differences *between* patients, which makes it comparable with designs that aren't repeated measures; report it when readers will compare studies of different designs.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npcs_model <- aov(vr12_pcs ~ visit + Error(case_id / visit), data = pcs)   # the same ANOVA in base R\neffectsize::eta_squared(pcs_model, partial = TRUE)                         # with a 95% CI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA (Type I)\n\nGroup         | Parameter | Eta2 (partial) |       95% CI\n---------------------------------------------------------\ncase_id:visit |     visit |           0.49 | [0.46, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(pcs_anova.loc[0, \"np2\"])    # pingouin doesn't compute a CI for it\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.4922887621025491\n```\n\n\n:::\n:::\n\n:::\n\nη²~p~ = 0.49: a very large effect. The visits account for about half of the variation in each patient's scores over the year.\n\n### How to report it\n\n> **Methods:** VR-12 PCS across the four visits was compared with one-way repeated-measures ANOVA in patients with all four measurements. Sphericity was assessed with Mauchly's test, with the Greenhouse-Geisser correction planned if it was violated. Partial eta squared (η²~p~) is reported as the effect size.\n>\n> **Results:** Of 574 patients with a pre-op PCS, 328 had all four measurements. Their mean PCS was 31.2 (SD 6.1) before surgery, 34.9 (SD 6.2) at 6 weeks, 41.0 (SD 6.2) at 3 months and 44.9 (SD 6.8) at 1 year (F(3, 981) = 317.1, p < 0.001; η²~p~ = 0.49, one-sided 95% CI 0.46 to 1.00; Mauchly's test of sphericity p = 0.324).\n\n::: {.callout-warning}\n## ⚠️ Watch out: a significant F doesn't say which visits differ\nThe ANOVA says PCS changed somewhere over the year. To say *when*, compare the visits with paired tests and a correction for multiple comparisons ([page 15](../beyond/15-post-hoc.qmd#after-repeated-measures-anova)). And remember who's missing: the 246 patients without complete data may have recovered differently.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: which tools check sphericity\n- **R:** base `aov(... + Error(case_id / visit))` gives the same F test but ignores sphericity; `rstatix::anova_test()` adds Mauchly's test and the corrections. rstatix rounds its numbers to 3 decimals.\n- **Python:** pingouin's `rm_anova(correction=True)` reports Mauchly's test and the Greenhouse-Geisser correction. statsmodels' `AnovaRM` gives the F test only.\n- **Effect sizes:** pingouin returns either partial (`effsize=\"np2\"`) or generalized (`effsize=\"ng2\"`) eta squared; rstatix returns both if asked.\n:::\n\n## Friedman test {#friedman}\n\n**The question:** After knee replacement, does KOOS JR keep changing between 6 weeks, 3 months and 1 year?\n\n### When to use it\n\n- An outcome measured **three or more times** on the same patients, when it's **skewed**, **ordinal** or has a **ceiling or floor**. The 1-year KOOS JR has a ceiling ([page 3](../foundations/03-distributions.qmd#transform)).\n- It ranks each patient's own scores (1st, 2nd, 3rd) and asks whether some visits tend to rank higher than others.\n- Only patients measured at **every** visit are included.\n- If the outcome is a roughly normal measurement → [repeated-measures ANOVA](#repeated-measures-anova).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nproms <- read_csv(\"data/proms_long.csv\", show_col_types = FALSE)\n\nkoos <- proms |>\n  filter(instrument == \"KOOS JR\", visit %in% c(\"6wk\", \"3mo\", \"1yr\")) |>\n  select(case_id, visit, prom_score) |>\n  group_by(case_id) |>\n  filter(all(!is.na(prom_score))) |>     # keep patients measured at all three visits\n  ungroup() |>\n  mutate(visit = factor(visit, levels = c(\"6wk\", \"3mo\", \"1yr\")))\n\nn_distinct(koos$case_id)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 205\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(koos, aes(visit, prom_score)) +\n  geom_boxplot() +\n  labs(x = \"Visit\", y = \"KOOS JR\")\n```\n\n::: {.cell-output-display}\n![](09-three-plus-matched_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\nkoos |>\n  group_by(visit) |>\n  summarise(median = median(prom_score), q1 = quantile(prom_score, 0.25), q3 = quantile(prom_score, 0.75))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  visit median    q1    q3\n  <fct>  <dbl> <dbl> <dbl>\n1 6wk     62.6  53.9  70.3\n2 3mo     73.1  65.7  81.5\n3 1yr     85.7  73.6  94  \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport pingouin as pg\nimport matplotlib.pyplot as plt\n\nproms = pd.read_csv(\"data/proms_long.csv\")\nvisits = [\"6wk\", \"3mo\", \"1yr\"]\n\nkoos = proms[(proms[\"instrument\"] == \"KOOS JR\") & proms[\"visit\"].isin(visits)][[\"case_id\", \"visit\", \"prom_score\"]]\ncomplete = koos.groupby(\"case_id\")[\"prom_score\"].transform(lambda scores: scores.notna().all())\nkoos = koos[complete]                     # keep patients measured at all three visits\n\nprint(koos[\"case_id\"].nunique())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n205\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, ax = plt.subplots(figsize=(6, 3))\nparts = ax.boxplot([koos.loc[koos[\"visit\"] == v, \"prom_score\"] for v in visits], tick_labels=visits)\nax.set_xlabel(\"Visit\")\nax.set_ylabel(\"KOOS JR\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](09-three-plus-matched_files/figure-html/unnamed-chunk-12-1.png)\n:::\n\n```{.python .cell-code}\nprint(koos.groupby(\"visit\")[\"prom_score\"].describe()[[\"25%\", \"50%\", \"75%\"]].loc[visits])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        25%   50%   75%\nvisit                  \n6wk    53.9  62.6  70.3\n3mo    65.7  73.1  81.5\n1yr    73.6  85.7  94.0\n```\n\n\n:::\n:::\n\n:::\n\n205 TKA patients were measured at all three visits. Scores rise at each visit, and by 1 year they're crowding the ceiling of 100.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkoos_test <- friedman.test(prom_score ~ visit | case_id, data = koos)   # outcome ~ visit | patient\nkoos_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFriedman rank sum test\n\ndata:  prom_score and visit and case_id\nFriedman chi-squared = 253.56, df = 2, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nkoos_test = pg.friedman(data=koos, dv=\"prom_score\", within=\"visit\", subject=\"case_id\")\nprint(koos_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Source         W  ddof1           Q         p_unc\nFriedman  visit  0.618437      2  253.559364  8.715329e-56\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **Friedman chi-squared = 253.6** (R) or **Q** (Python): how consistently the visits rank in the same order across patients.\n- **df = 2:** three visits minus one.\n- **p < 0.001** (R prints \"p < 2.2e-16\").\n- **W = 0.618** (Python): Kendall's W, below.\n\n### Effect size and 95% CI\n\n**Kendall's W** measures how consistently patients' scores rank the visits in the same order: 0 means no agreement at all, 1 means every patient's scores rank the three visits identically. As a rough guide, 0.1 is small, 0.3 moderate and 0.5 large.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# kendalls_w() warns when a patient has the same score at two visits; the tie correction already handles that\nset.seed(2026)   # its CI comes from a bootstrap (random resampling); a seed makes it repeatable\neffectsize::kendalls_w(prom_score ~ visit | case_id, data = koos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKendall's W |       95% CI\n--------------------------\n0.62        | [0.55, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(koos_test[\"W\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFriedman    0.618437\nName: W, dtype: float64\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nW = 0.62: a large effect. Most patients improved from each visit to the next. R's CI comes from a bootstrap, which is why the code sets a seed; pingouin doesn't compute one.\n\n### How to report it\n\n> **Methods:** Because KOOS JR scores showed a ceiling effect, scores at 6 weeks, 3 months and 1 year were compared with the Friedman test in patients with all three measurements, with Kendall's W as the effect size.\n>\n> **Results:** Among 205 patients with all three measurements, median KOOS JR was 62.6 (IQR 53.9 to 70.3) at 6 weeks, 73.1 (IQR 65.7 to 81.5) at 3 months and 85.7 (IQR 73.6 to 94.0) at 1 year (Friedman χ² = 253.6, df = 2, p < 0.001; Kendall's W = 0.62, one-sided 95% CI 0.55 to 1.00).\n\n::: {.callout-warning}\n## ⚠️ Watch out: the Friedman test ignores how big the changes are\nIt only uses each patient's ranking of the visits. A patient who gained 1 point and one who gained 30 count the same. Report the medians (or the changes) so readers can see the size of the improvement, and judge it against the MCID ([page 3](../foundations/03-distributions.qmd#effect-sizes)).\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: data formats\nR's `friedman.test()` takes a formula, `outcome ~ visit | patient`, on long data. pingouin's `friedman()` also takes long data; scipy's `friedmanchisquare()` instead wants one column per visit in wide data. All three correct for tied scores within a patient, so they agree.\n:::\n\n## Cochran's Q test {#cochran-q}\n\n**The question:** Does walking-aid use change over the first year after surgery?\n\n### When to use it\n\n- A **yes/no** outcome measured **three or more times** on the same patients (or once on each member of a matched set).\n- It extends [McNemar's test](07-two-paired-groups.qmd#mcnemar) to more than two visits, and, like McNemar's, it only learns from patients whose answer changed.\n- Only patients measured at **every** visit are included.\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nproms <- read_csv(\"data/proms_long.csv\", show_col_types = FALSE)\n\naid <- proms |>\n  select(case_id, visit, walking_aid) |>\n  group_by(case_id) |>\n  filter(all(!is.na(walking_aid))) |>    # keep patients measured at all four visits\n  ungroup() |>\n  mutate(visit = factor(visit, levels = c(\"preop\", \"6wk\", \"3mo\", \"1yr\")))\n\naid |>\n  group_by(visit) |>\n  summarise(patients = n(), using_aid = sum(walking_aid), percent = 100 * mean(walking_aid))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  visit patients using_aid percent\n  <fct>    <int>     <dbl>   <dbl>\n1 preop      328       114    34.8\n2 6wk        328       194    59.1\n3 3mo        328        80    24.4\n4 1yr        328        34    10.4\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport pingouin as pg\nfrom scipy import stats\n\nproms = pd.read_csv(\"data/proms_long.csv\")\nvisits = [\"preop\", \"6wk\", \"3mo\", \"1yr\"]\n\naid = proms[[\"case_id\", \"visit\", \"walking_aid\"]]\ncomplete = aid.groupby(\"case_id\")[\"walking_aid\"].transform(lambda answers: answers.notna().all())\naid = aid[complete]                     # keep patients measured at all four visits\n\nprint(aid.groupby(\"visit\")[\"walking_aid\"].agg([\"count\", \"sum\", \"mean\"]).loc[visits])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       count    sum      mean\nvisit                        \npreop    328  114.0  0.347561\n6wk      328  194.0  0.591463\n3mo      328   80.0  0.243902\n1yr      328   34.0  0.103659\n```\n\n\n:::\n:::\n\n:::\n\n328 patients answered at all four visits. A third used a walking aid before surgery, more than half at 6 weeks, and one in ten at 1 year.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\naid_test <- DescTools::CochranQTest(walking_aid ~ visit | case_id, data = aid)   # outcome ~ visit | patient\naid_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tCochran's Q test\n\ndata:  walking_aid and visit and case_id\nQ = 186.79, df = 3, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\naid_test = pg.cochran(data=aid, dv=\"walking_aid\", within=\"visit\", subject=\"case_id\")\nprint(aid_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Source  dof           Q         p_unc\ncochran  visit    3  186.792711  3.008880e-40\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **Q = 186.8, df = 3:** Cochran's Q statistic, with four visits minus one degrees of freedom.\n- **p < 0.001** (R prints \"p < 2.2e-16\"): walking-aid use this different across visits would be very unlikely if it hadn't changed.\n\n### Effect size and 95% CI\n\nCochran's Q has no standard single effect size. Describe the **proportion at each visit**, with its 95% CI (the Wilson interval from [page 4](04-describe-one-group.qmd#proportion)), and the changes between visits in percentage points.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\naid_by_visit <- aid |> group_by(visit) |> summarise(using = sum(walking_aid), patients = n())\naid_ci <- mapply(function(k, n) prop.test(k, n, correct = FALSE)$conf.int, aid_by_visit$using, aid_by_visit$patients)\n\naid_by_visit |>\n  mutate(percent = 100 * using / patients, ci_low = 100 * aid_ci[1, ], ci_high = 100 * aid_ci[2, ])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 6\n  visit using patients percent ci_low ci_high\n  <fct> <dbl>    <int>   <dbl>  <dbl>   <dbl>\n1 preop   114      328    34.8  29.8     40.1\n2 6wk     194      328    59.1  53.8     64.3\n3 3mo      80      328    24.4  20.1     29.3\n4 1yr      34      328    10.4   7.51    14.1\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ncounts = aid.groupby(\"visit\")[\"walking_aid\"].agg([\"sum\", \"count\"]).loc[visits]\ncis = [stats.binomtest(int(k), int(n)).proportion_ci(method=\"wilson\") for k, n in zip(counts[\"sum\"], counts[\"count\"])]\n\nprint(pd.DataFrame({\"percent\": 100 * counts[\"sum\"] / counts[\"count\"],\n                    \"ci_low\": [100 * ci.low for ci in cis], \"ci_high\": [100 * ci.high for ci in cis]}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         percent     ci_low    ci_high\nvisit                                 \npreop  34.756098  29.806008  40.059120\n6wk    59.146341  53.750541  64.330383\n3mo    24.390244  20.056804  29.316611\n1yr    10.365854   7.513119  14.136213\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nUse rose by 24.4 percentage points from pre-op to 6 weeks, then fell well below its pre-op level by 1 year (24.4 points lower).\n\n### How to report it\n\n> **Methods:** Walking-aid use at the four visits was compared with Cochran's Q test in patients assessed at all four. Proportions are reported with Wilson 95% CIs.\n>\n> **Results:** Among 328 patients assessed at all four visits, walking-aid use was 34.8% (95% CI 29.8% to 40.1%) before surgery, 59.1% (95% CI 53.8% to 64.3%) at 6 weeks, 24.4% (95% CI 20.1% to 29.3%) at 3 months and 10.4% (95% CI 7.5% to 14.1%) at 1 year (Cochran's Q = 186.8, df = 3, p < 0.001).\n\n::: {.callout-warning}\n## ⚠️ Watch out: Q doesn't tell you the direction\nUse went **up** and then **down**. Cochran's Q only says it wasn't the same at every visit. To say which changes are real, compare pairs of visits with McNemar's test and a correction for multiple comparisons ([page 15](../beyond/15-post-hoc.qmd#after-cochran-q)).\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: where to find Cochran's Q\nBase R doesn't have Cochran's Q; `DescTools::CochranQTest()` (or `rstatix::cochran_qtest()`) does. In Python, pingouin's `cochran()` takes long data; statsmodels' `cochrans_q()` takes a wide array with one column per visit. All give the same Q.\n:::\n\n## Stratified Cox regression {#stratified-cox}\n\n**The question:** In sets of three patients matched on procedure, age, sex, BMI and ASA class, does the risk of revision differ between implants A, B and C?\n\n### When to use it\n\n- The outcome is **time until an event**, and the patients come in **matched sets** of three or more.\n- A Cox model **stratified** by matched set compares the implants only **within** sets, as on [page 7](07-two-paired-groups.qmd#stratified-cox), which used just the A and C patients from the same sets.\n- With few events, expect wide CIs. [Page 14](../survival/14-cox-regression.qmd) covers Cox regression in full.\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(survival)\n\nmatched <- read_csv(\"data/matched_sets.csv\", show_col_types = FALSE) |>\n  mutate(revised = as.integer(event_status == 1))   # 1 = revised; deaths and censoring = 0\n\nmatched |> select(set_id, implant, age, sex, bmi, followup_years, revised) |> head(6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  set_id implant   age sex      bmi followup_years revised\n  <chr>  <chr>   <dbl> <chr>  <dbl>          <dbl>   <int>\n1 M001   C          67 Male    32.5           5.79       1\n2 M001   A          67 Male    35.3           2.44       0\n3 M001   B          68 Male    32             6.38       0\n4 M002   C          64 Female  31.4           0.04       1\n5 M002   A          61 Female  31.3           8.67       0\n6 M002   B          64 Female  28.9           7.41       0\n```\n\n\n:::\n\n```{.r .cell-code}\nmatched |> group_by(implant) |> summarise(patients = n(), revisions = sum(revised))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  implant patients revisions\n  <chr>      <int>     <int>\n1 A             52         5\n2 B             52         2\n3 C             52        17\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nfrom lifelines import CoxPHFitter\n\nmatched = pd.read_csv(\"data/matched_sets.csv\")\nmatched[\"revised\"] = (matched[\"event_status\"] == 1).astype(int)   # 1 = revised; deaths and censoring = 0\n\nprint(matched[[\"set_id\", \"implant\", \"age\", \"sex\", \"bmi\", \"followup_years\", \"revised\"]].head(6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  set_id implant  age     sex   bmi  followup_years  revised\n0   M001       C   67    Male  32.5            5.79        1\n1   M001       A   67    Male  35.3            2.44        0\n2   M001       B   68    Male  32.0            6.38        0\n3   M002       C   64  Female  31.4            0.04        1\n4   M002       A   61  Female  31.3            8.67        0\n5   M002       B   64  Female  28.9            7.41        0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(matched.groupby(\"implant\")[\"revised\"].agg([\"count\", \"sum\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         count  sum\nimplant            \nA           52    5\nB           52    2\nC           52   17\n```\n\n\n:::\n:::\n\n:::\n\n52 matched sets of three: 5 revisions with implant A, 2 with B and 17 with C.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset_cox <- coxph(Surv(followup_years, revised) ~ implant + strata(set_id), data = matched)\nsummary(set_cox)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(followup_years, revised) ~ implant + strata(set_id), \n    data = matched)\n\n  n= 156, number of events= 24 \n\n            coef exp(coef) se(coef)      z Pr(>|z|)  \nimplantB -0.8371    0.4330   0.8414 -0.995   0.3198  \nimplantC  1.3640    3.9119   0.5696  2.395   0.0166 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n         exp(coef) exp(-coef) lower .95 upper .95\nimplantB     0.433     2.3097   0.08322     2.253\nimplantC     3.912     0.2556   1.28105    11.946\n\nConcordance= 0.816  (se = 0.093 )\nLikelihood ratio test= 13.48  on 2 df,   p=0.001\nWald test            = 10.48  on 2 df,   p=0.005\nScore (logrank) test = 13.5  on 2 df,   p=0.001\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nset_cox = CoxPHFitter().fit(\n    matched[[\"followup_years\", \"revised\", \"implant\", \"set_id\"]],\n    duration_col=\"followup_years\", event_col=\"revised\",\n    formula=\"implant\", strata=[\"set_id\"],    # one stratum per matched set\n)\nprint(set_cox.summary[[\"exp(coef)\", \"exp(coef) lower 95%\", \"exp(coef) upper 95%\", \"p\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              exp(coef)  exp(coef) lower 95%  exp(coef) upper 95%         p\ncovariate                                                                  \nimplant[T.B]   0.432957             0.083215             2.252616  0.319809\nimplant[T.C]   3.911913             1.281047            11.945745  0.016629\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(set_cox.log_likelihood_ratio_test().test_statistic)   # overall test, all implants\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n13.482363098251813\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **n = 156, number of events = 24:** 52 sets of three patients, 24 revisions.\n- **exp(coef):** the hazard ratio of each implant against implant A, within matched sets. Implant B: 0.43; implant C: 3.91.\n- **lower .95 / upper .95:** implant B's CI (0.08 to 2.25) is very wide and includes 1; implant C's (1.28 to 11.95) doesn't.\n- **Likelihood ratio test = 13.5 on 2 df, p = 0.001:** the overall test that implant matters at all. Python prints it last.\n\n### Effect size and 95% CI\n\nThe **hazard ratios** with their 95% CIs: within matched sets, implant C carried about four times the hazard of revision of implant A (3.91, 95% CI 1.28 to 11.95). The estimate for implant B (0.43, 95% CI 0.08 to 2.25) is too imprecise to interpret.\n\n### How to report it\n\n> **Methods:** Revision risk was compared between implants in matched sets using Cox regression stratified by set, with implant A as the reference.\n>\n> **Results:** In 52 sets of three patients matched on procedure, age, sex, BMI and ASA class, the hazard ratio for revision compared with implant A was 3.91 (95% CI 1.28 to 11.95) for implant C and 0.43 (95% CI 0.08 to 2.25) for implant B (likelihood ratio test for implant type, χ² = 13.5, df = 2, p = 0.001).\n\n::: {.callout-warning}\n## ⚠️ Watch out: only 24 events\nA Cox model needs events, not just patients. With 24 revisions across three implants, the CIs are wide and the model can't support adjustment for anything else. [Page 14](../survival/14-cox-regression.qmd#choosing-covariates) covers how many events a model needs.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: strata and convergence\nAs on [page 7](07-two-paired-groups.qmd#stratified-cox), R puts `strata(set_id)` in the formula while lifelines takes `strata=[\"set_id\"]`. Here lifelines' default convergence matches R exactly; with page 7's pairs it stopped a little early and needed `fit_options={\"precision\": 1e-9}`. If the two programs disagree in the fourth decimal, tighten it.\n:::\n\n## Which visits differ? {#which-groups-differ}\n\nEach test above answers \"is there any difference among the visits (or implants)?\". When the answer is yes, the next question is which pairs differ. Comparing every pair with an ordinary paired test inflates the chance of a false positive: four visits make six pairs.\n\n| After | Use | Page |\n|---|---|---|\n| Repeated-measures ANOVA | Paired t tests with Holm's adjustment | [15](../beyond/15-post-hoc.qmd#after-repeated-measures-anova) |\n| Friedman | Pairwise Wilcoxon signed-rank (or Conover) tests with Holm's adjustment | [15](../beyond/15-post-hoc.qmd#after-friedman) |\n| Cochran's Q | Pairwise McNemar tests with Holm's adjustment | [15](../beyond/15-post-hoc.qmd#after-cochran-q) |\n| Stratified Cox | Hazard ratios against a chosen reference | [14](../survival/14-cox-regression.qmd) |\n\nFor repeated PROMs, a [mixed model](../beyond/16-mixed-models.qmd#why-mixed-models) answers both questions at once (does the score change, and at which visits?) while keeping patients who missed a visit.\n\n\n\n## Exercises {#exercises}\n\nThe solutions use the packages and data loaded in the sections above, so run the page from the top first.\n\n**1.** Repeat the repeated-measures ANOVA for the VR-12 **mental** component score (`vr12_mcs`) across the four visits.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcs <- proms |>\n  select(case_id, visit, vr12_mcs) |>\n  group_by(case_id) |>\n  filter(all(!is.na(vr12_mcs))) |>\n  ungroup() |>\n  mutate(visit = factor(visit, levels = c(\"preop\", \"6wk\", \"3mo\", \"1yr\")))\n\nrstatix::anova_test(data = mcs, dv = vr12_mcs, wid = case_id, within = visit, effect.size = \"pes\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nANOVA Table (type III tests)\n\n$ANOVA\n  Effect DFn DFd     F       p p<.05   pes\n1  visit   3 981 9.326 4.4e-06     * 0.028\n\n$`Mauchly's Test for Sphericity`\n  Effect     W     p p<.05\n1  visit 0.993 0.814      \n\n$`Sphericity Corrections`\n  Effect   GGe       DF[GG]   p[GG] p[GG]<.05   HFe       DF[HF]   p[HF]\n1  visit 0.995 2.99, 976.46 4.6e-06         * 1.006 3.02, 986.45 4.4e-06\n  p[HF]<.05\n1         *\n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::eta_squared(aov(vr12_mcs ~ visit + Error(case_id / visit), data = mcs), partial = TRUE, verbose = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA (Type I)\n\nGroup         | Parameter | Eta2 (partial) |       95% CI\n---------------------------------------------------------\ncase_id:visit |     visit |           0.03 | [0.01, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n\n```{.r .cell-code}\nmcs |> group_by(visit) |> summarise(mean = mean(vr12_mcs), sd = sd(vr12_mcs))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  visit  mean    sd\n  <fct> <dbl> <dbl>\n1 preop  49.7  8.96\n2 6wk    51.1  8.68\n3 3mo    51.7  8.67\n4 1yr    53.3  9.03\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmcs = proms[[\"case_id\", \"visit\", \"vr12_mcs\"]]\nmcs = mcs[mcs.groupby(\"case_id\")[\"vr12_mcs\"].transform(lambda scores: scores.notna().all())]\nprint(pg.rm_anova(data=mcs, dv=\"vr12_mcs\", within=\"visit\", subject=\"case_id\", correction=True, effsize=\"np2\").T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   0\nSource         visit\nddof1              3\nddof2            981\nF            9.32639\np_unc       0.000004\np_GG_corr   0.000005\nnp2          0.02773\neps         0.995371\nsphericity      True\nW_spher     0.993122\np_spher     0.813884\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(mcs.groupby(\"visit\")[\"vr12_mcs\"].agg([\"mean\", \"std\"]).loc[[\"preop\", \"6wk\", \"3mo\", \"1yr\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            mean       std\nvisit                     \npreop  49.692378  8.963021\n6wk    51.052744  8.679269\n3mo    51.742378  8.674850\n1yr    53.261585  9.025444\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Mean MCS was 49.7 (SD 9.0) before surgery and 53.3 (SD 9.0) at 1 year (F(3, 981) = 9.33, p < 0.001; η²~p~ = 0.03, one-sided 95% CI 0.01 to 1.00; Mauchly's test of sphericity p = 0.814).\n\nThe mental component changed far less than the physical one: a small effect, against a large one for the physical component.\n:::\n\n**2.** A colleague wants to know whether **HOOS JR** (hip patients) keeps changing between 6 weeks, 3 months and 1 year. Which test would you use, and what do you find?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nHOOS JR, like KOOS JR, has a ceiling at 1 year, and the same patients are measured three times: the **Friedman test**.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhoos <- proms |>\n  filter(instrument == \"HOOS JR\", visit %in% c(\"6wk\", \"3mo\", \"1yr\")) |>\n  select(case_id, visit, prom_score) |>\n  group_by(case_id) |>\n  filter(all(!is.na(prom_score))) |>\n  ungroup() |>\n  mutate(visit = factor(visit, levels = c(\"6wk\", \"3mo\", \"1yr\")))\n\nfriedman.test(prom_score ~ visit | case_id, data = hoos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFriedman rank sum test\n\ndata:  prom_score and visit and case_id\nFriedman chi-squared = 159.7, df = 2, p-value < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(2026)\neffectsize::kendalls_w(prom_score ~ visit | case_id, data = hoos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKendall's W |       95% CI\n--------------------------\n0.57        | [0.48, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n\n```{.r .cell-code}\nhoos |> group_by(visit) |> summarise(median = median(prom_score), q1 = quantile(prom_score, 0.25), q3 = quantile(prom_score, 0.75))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  visit median    q1    q3\n  <fct>  <dbl> <dbl> <dbl>\n1 6wk     68.2  61.3  74.1\n2 3mo     79.8  71.6  90.3\n3 1yr     89.2  81.1  97.4\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nhoos = proms[(proms[\"instrument\"] == \"HOOS JR\") & proms[\"visit\"].isin([\"6wk\", \"3mo\", \"1yr\"])][[\"case_id\", \"visit\", \"prom_score\"]]\nhoos = hoos[hoos.groupby(\"case_id\")[\"prom_score\"].transform(lambda scores: scores.notna().all())]\nprint(pg.friedman(data=hoos, dv=\"prom_score\", within=\"visit\", subject=\"case_id\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Source        W  ddof1           Q         p_unc\nFriedman  visit  0.57036      2  159.700901  2.095994e-35\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(hoos.groupby(\"visit\")[\"prom_score\"].describe()[[\"25%\", \"50%\", \"75%\"]].loc[[\"6wk\", \"3mo\", \"1yr\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          25%    50%     75%\nvisit                       \n6wk    61.275  68.20  74.150\n3mo    71.600  79.75  90.275\n1yr    81.125  89.20  97.350\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Among 140 hip patients with all three scores, median HOOS JR was 68.2 (IQR 61.3 to 74.2) at 6 weeks, 79.8 (IQR 71.6 to 90.3) at 3 months and 89.2 (IQR 81.1 to 97.4) at 1 year (Friedman χ² = 159.7, df = 2, p < 0.001; Kendall's W = 0.57, one-sided 95% CI 0.48 to 1.00).\n\nR's table shows the 6-week upper quartile as 74.1. The exact value is 74.15, which the computer stores as 74.1499…, so R rounds it down; Python prints 74.150.\n:::\n\n**3.** Leaving out the pre-op visit, does walking-aid use change between 6 weeks, 3 months and 1 year? Run the test and write the Results sentence.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nafter_surgery <- proms |>\n  filter(visit %in% c(\"6wk\", \"3mo\", \"1yr\")) |>\n  select(case_id, visit, walking_aid) |>\n  group_by(case_id) |>\n  filter(all(!is.na(walking_aid))) |>\n  ungroup() |>\n  mutate(visit = factor(visit, levels = c(\"6wk\", \"3mo\", \"1yr\")))\n\nDescTools::CochranQTest(walking_aid ~ visit | case_id, data = after_surgery)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tCochran's Q test\n\ndata:  walking_aid and visit and case_id\nQ = 185.95, df = 2, p-value < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nafter_counts <- after_surgery |> group_by(visit) |> summarise(using = sum(walking_aid), patients = n())\nafter_counts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  visit using patients\n  <fct> <dbl>    <int>\n1 6wk     203      345\n2 3mo      87      345\n3 1yr      37      345\n```\n\n\n:::\n\n```{.r .cell-code}\nmapply(function(k, n) prop.test(k, n, correct = FALSE)$conf.int, after_counts$using, after_counts$patients)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1]      [,2]       [,3]\n[1,] 0.5357806 0.2092508 0.07881396\n[2,] 0.6390839 0.3005552 0.14432884\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nafter = proms[proms[\"visit\"].isin([\"6wk\", \"3mo\", \"1yr\"])][[\"case_id\", \"visit\", \"walking_aid\"]]\nafter = after[after.groupby(\"case_id\")[\"walking_aid\"].transform(lambda answers: answers.notna().all())]\nprint(pg.cochran(data=after, dv=\"walking_aid\", within=\"visit\", subject=\"case_id\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Source  dof           Q         p_unc\ncochran  visit    2  185.948718  4.185515e-41\n```\n\n\n:::\n\n```{.python .cell-code}\ncounts = after.groupby(\"visit\")[\"walking_aid\"].agg([\"sum\", \"count\"]).loc[[\"6wk\", \"3mo\", \"1yr\"]]\nprint(counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         sum  count\nvisit              \n6wk    203.0    345\n3mo     87.0    345\n1yr     37.0    345\n```\n\n\n:::\n\n```{.python .cell-code}\nprint([stats.binomtest(int(k), int(n)).proportion_ci(method=\"wilson\") for k, n in zip(counts[\"sum\"], counts[\"count\"])])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[ConfidenceInterval(low=np.float64(0.5357806069444521), high=np.float64(0.6390839295307099)), ConfidenceInterval(low=np.float64(0.2092507746792112), high=np.float64(0.3005551968412363)), ConfidenceInterval(low=np.float64(0.07881395916574538), high=np.float64(0.14432883780525613))]\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Among 345 patients assessed at all three post-operative visits, walking-aid use was 58.8% (95% CI 53.6% to 63.9%) at 6 weeks, 25.2% (95% CI 20.9% to 30.1%) at 3 months and 10.7% (95% CI 7.9% to 14.4%) at 1 year (Cochran's Q = 185.9, df = 2, p < 0.001).\n\nMore patients are included here (345 vs 328) because patients who missed only the pre-op visit now count.\n:::\n",
    "supporting": [
      "09-three-plus-matched_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}