{
  "hash": "56d5388a7a86b9bb8e2558672daa199b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"15 · Post-hoc tests & multiple comparisons\"\ndescription: \"Which groups differ after ANOVA, Kruskal-Wallis, chi-square, repeated-measures tests or a log-rank test, and how to keep false positives in check.\"\nengine: knitr\n---\n\n\n\n<!-- data-checksum: 7318dedd9cebb731bf62c12faf3ff8ee -->\n\nA test for three or more groups asks one question: \"is there any difference among them?\". When the answer is yes, the next question is which groups differ from which. Answering it means running several tests at once, and every extra test is another chance of a false positive. This page shows how to compare groups in pairs while keeping that chance under control. Each \"After …\" section picks up an example from [page 8](../catalog/08-three-plus-unmatched.qmd), [page 9](../catalog/09-three-plus-matched.qmd) or [page 13](../survival/13-kaplan-meier.qmd).\n\n::: {.callout-note}\n## 💡 How this page works\nRun the code blocks in order, from the top: later blocks use the packages and data loaded in the first one.\n\nAs on the pages these examples come from, the code uses every case, including the 80 patients who had both sides operated on.\n:::\n\n## Why many tests mislead {#why-adjust}\n\nA test at the 5% level has a 5% chance of a false positive when there is truly no difference. Run several tests and those chances add up. The chance of **at least one** false positive across a set of tests is the **family-wise error rate**. For independent tests at the 5% level it's 1 − 0.95^k^, where k is the number of tests:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(survival)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\nproms <- read_csv(\"data/proms_long.csv\", show_col_types = FALSE)\n\ntests <- c(1, 3, 6, 10, 20)\nfalse_positives <- tibble(tests, chance_of_a_false_positive = round(1 - 0.95^tests, 2))\nfalse_positives\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  tests chance_of_a_false_positive\n  <dbl>                      <dbl>\n1     1                       0.05\n2     3                       0.14\n3     6                       0.26\n4    10                       0.4 \n5    20                       0.64\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport itertools\nimport numpy as np\nimport pandas as pd\nimport pingouin as pg\nimport scikit_posthocs as sp\nfrom scipy import stats\nfrom statsmodels.stats.multitest import multipletests\nfrom statsmodels.stats.multicomp import pairwise_tukeyhsd\nfrom statsmodels.stats.contingency_tables import mcnemar\nfrom lifelines import CoxPHFitter\nfrom lifelines.statistics import pairwise_logrank_test\n\ncohort = pd.read_csv(\"data/cohort.csv\")\nproms = pd.read_csv(\"data/proms_long.csv\")\n\ntests = np.array([1, 3, 6, 10, 20])\nfalse_positives = pd.DataFrame({\"tests\": tests, \"chance_of_a_false_positive\": (1 - 0.95**tests).round(2)})\nprint(false_positives)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   tests  chance_of_a_false_positive\n0      1                        0.05\n1      3                        0.14\n2      6                        0.26\n3     10                        0.40\n4     20                        0.64\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nFour groups make six pairs. Six independent tests at the 5% level give a 26% chance of at least one false alarm, even when nothing is going on; twenty tests give 64%. Pairwise comparisons aren't independent, because each group appears in three of the six pairs, so for four groups of equal size the chance is a little lower: about 20%. That's still four times the 5% you meant to allow. Comparing pairs therefore needs an **adjustment**: a stricter rule that keeps the chance of any false positive across the whole set of comparisons at 5%.\n\n::: {.callout-note}\n## 💡 In plain language\nBuy one lottery ticket and you'll almost certainly lose. Buy twenty and your chance of winning something goes up. Each p-value below 0.05 is a small \"win\", and with enough tests one will turn up by luck alone. Adjusting the p-values makes each win harder to get, so the overall chance stays where you set it.\n:::\n\n## Adjusting p-values: Bonferroni, Holm and Benjamini-Hochberg {#adjusting-p-values}\n\n[Page 8](../catalog/08-three-plus-unmatched.qmd#one-way-anova) found that age differs across the four ASA classes. Here are the six pairwise comparisons, each a Welch t test, with the p-values left as they are (**unadjusted**) and then adjusted three ways:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_pairs <- pairwise.t.test(cohort$age, cohort$asa, pool.sd = FALSE,      # Welch t tests\n                             p.adjust.method = \"none\")\nunadjusted <- age_pairs$p.value[lower.tri(age_pairs$p.value, diag = TRUE)]  # the six p-values, in pair order\n\nadjusted <- tibble(pair = c(\"1 vs 2\", \"1 vs 3\", \"1 vs 4\", \"2 vs 3\", \"2 vs 4\", \"3 vs 4\"),\n                   unadjusted,\n                   bonferroni = p.adjust(unadjusted, method = \"bonferroni\"),\n                   holm = p.adjust(unadjusted, method = \"holm\"),\n                   bh = p.adjust(unadjusted, method = \"BH\"))\nadjusted |> mutate(across(-pair, \\(p) round(p, 4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  pair   unadjusted bonferroni   holm     bh\n  <chr>       <dbl>      <dbl>  <dbl>  <dbl>\n1 1 vs 2     0.022      0.132  0.0439 0.0263\n2 1 vs 3     0          0      0      0     \n3 1 vs 4     0          0      0      0     \n4 2 vs 3     0          0      0      0     \n5 2 vs 4     0.0002     0.0013 0.0007 0.0003\n6 3 vs 4     0.0298     0.179  0.0439 0.0298\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nasa_pairs = list(itertools.combinations([1, 2, 3, 4], 2))\nunadjusted = [stats.ttest_ind(cohort.loc[cohort[\"asa\"] == a, \"age\"], cohort.loc[cohort[\"asa\"] == b, \"age\"],\n                              equal_var=False).pvalue                    # Welch t tests\n              for a, b in asa_pairs]\n\nadjusted = pd.DataFrame({\n    \"pair\": [f\"{a} vs {b}\" for a, b in asa_pairs],\n    \"unadjusted\": unadjusted,\n    \"bonferroni\": multipletests(unadjusted, method=\"bonferroni\")[1],\n    \"holm\": multipletests(unadjusted, method=\"holm\")[1],\n    \"bh\": multipletests(unadjusted, method=\"fdr_bh\")[1],\n})\nprint(adjusted.round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     pair  unadjusted  bonferroni    holm      bh\n0  1 vs 2      0.0220      0.1317  0.0439  0.0263\n1  1 vs 3      0.0000      0.0000  0.0000  0.0000\n2  1 vs 4      0.0000      0.0000  0.0000  0.0000\n3  2 vs 3      0.0000      0.0000  0.0000  0.0000\n4  2 vs 4      0.0002      0.0013  0.0007  0.0003\n5  3 vs 4      0.0298      0.1790  0.0439  0.0298\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nFollow the ASA 1 vs ASA 2 comparison across the row:\n- **Unadjusted, p = 0.022:** \"significant\" on its own, but it's one of six tests.\n- **Bonferroni, p = 0.132:** multiplies every p-value by the number of tests (here 6). Simple, but the strictest: it often throws away real differences.\n- **Holm, p = 0.044:** a step-down version of Bonferroni. It multiplies the smallest p-value by 6, the next smallest by 5, and so on, but an adjusted p-value can't be smaller than the one before it in that order. ASA 3 vs 4 has the largest unadjusted p-value (0.030), so it's multiplied by 1, but it takes 0.044 from ASA 1 vs 2, the one before it. It controls the family-wise error rate just as well as Bonferroni and is never less powerful, so **use Holm rather than Bonferroni**.\n- **Benjamini-Hochberg (BH), p = 0.026:** controls something different, the **false discovery rate**: the expected share of false positives among the results you call significant. It's the most lenient of the three. It suits screening many outcomes for leads, not confirming a claim.\n\n::: {.callout-warning}\n## ⚠️ Watch out: decide the adjustment before you see the p-values\nPicking whichever adjustment keeps your favourite result significant is p-hacking. Choose in advance: Holm (or a method built for the test, like Tukey's below) for comparisons you'll report as findings, Benjamini-Hochberg only for exploratory screening. Say in the Methods which you used and how many comparisons it covered.\n:::\n\n## After ANOVA: Tukey's HSD and Games-Howell {#after-anova}\n\nAfter a one-way ANOVA, **Tukey's honestly significant difference** (HSD) compares every pair of group means. It adjusts for all the pairs at once, and gives each difference a CI that's adjusted too. It assumes the groups have similar spreads, like the ANOVA. When they don't (the largest SD is more than about twice the smallest), use **Games-Howell**, the Welch version of Tukey's test.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_anova <- aov(age ~ factor(asa), data = cohort)\nage_tukey <- TukeyHSD(age_anova)                          # diff, adjusted 95% CI, adjusted p\nage_tukey\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = age ~ factor(asa), data = cohort)\n\n$`factor(asa)`\n         diff       lwr       upr     p adj\n2-1  3.646667 -0.414298  7.707631 0.0960950\n3-1  8.607724  4.499281 12.716166 0.0000006\n4-1 13.916667  7.270353 20.562980 0.0000006\n3-2  4.961057  2.980718  6.941396 0.0000000\n4-2 10.270000  4.682878 15.857122 0.0000162\n4-3  5.308943 -0.312782 10.930668 0.0720848\n```\n\n\n:::\n\n```{.r .cell-code}\ngames_howell <- rstatix::games_howell_test(cohort |> mutate(asa = factor(asa)), age ~ asa)\ngames_howell |> select(group1, group2, estimate, conf.low, conf.high, p.adj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  group1 group2 estimate conf.low conf.high         p.adj\n  <chr>  <chr>     <dbl>    <dbl>     <dbl>         <dbl>\n1 1      2          3.65   -0.452      7.75 0.0970       \n2 1      3          8.61    4.48      12.7  0.00000764   \n3 1      4         13.9     6.80      21.0  0.0000473    \n4 2      3          4.96    2.99       6.94 0.00000000162\n5 2      4         10.3     3.93      16.6  0.00114      \n6 3      4          5.31   -1.05      11.7  0.122        \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nage_tukey = pairwise_tukeyhsd(cohort[\"age\"], cohort[\"asa\"])\nprint(age_tukey.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMultiple Comparison of Means - Tukey HSD, FWER=0.05 \n====================================================\ngroup1 group2 meandiff p-adj   lower   upper  reject\n----------------------------------------------------\n     1      2   3.6467 0.0961 -0.4143  7.7076  False\n     1      3   8.6077    0.0  4.4993 12.7162   True\n     1      4  13.9167    0.0  7.2704  20.563   True\n     2      3   4.9611    0.0  2.9807  6.9414   True\n     2      4    10.27    0.0  4.6829 15.8571   True\n     3      4   5.3089 0.0721 -0.3128 10.9307  False\n----------------------------------------------------\n```\n\n\n:::\n\n```{.python .cell-code}\ngames_howell = pg.pairwise_gameshowell(data=cohort, dv=\"age\", between=\"asa\")\nprint(games_howell[[\"A\", \"B\", \"diff\", \"se\", \"pval\"]].round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   A  B     diff      se    pval\n0  1  2  -3.6467  1.5361  0.0970\n1  1  3  -8.6077  1.5483  0.0000\n2  1  4 -13.9167  2.6259  0.0000\n3  2  3  -4.9611  0.7665  0.0000\n4  2  4 -10.2700  2.2551  0.0011\n5  3  4  -5.3089  2.2634  0.1222\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n- **diff / meandiff:** the difference in mean age between two ASA classes, in years.\n- **lwr, upr / lower, upper:** the 95% CI of that difference, adjusted for all six comparisons.\n- **p adj / p-adj:** the adjusted p-value.\n\nFour of the six pairs differ clearly (p < 0.001 or, for ASA 2 vs 4 in the Games-Howell test, p = 0.001). Two don't: ASA 2 patients were 3.6 years older than ASA 1 patients (95% CI −0.4 to 7.7, p = 0.096), and ASA 4 patients 5.3 years older than ASA 3 patients (95% CI −0.3 to 10.9, p = 0.072). Both CIs include 0, and both comparisons involve one of the two small classes. The SDs are similar (8.7 to 9.3 years), so Games-Howell reaches the same conclusions.\n\n> **Methods:** Age was compared across ASA classes with one-way ANOVA, followed by Tukey's honestly significant difference test for pairwise comparisons.\n>\n> **Results:** Across ASA classes, one-way ANOVA gave F(3, 596) = 23.9 (p < 0.001). In pairwise comparisons, the difference in mean age was 5.0 years between ASA 3 and ASA 2 (95% CI 3.0 to 6.9; p < 0.001), 3.6 years between ASA 2 and ASA 1 (95% CI −0.4 to 7.7; p = 0.096) and 5.3 years between ASA 4 and ASA 3 (95% CI −0.3 to 10.9; p = 0.072). Table 2 gives all six pairwise comparisons.\n\n::: {.callout-tip}\n## 🔀 R vs Python: Tukey and Games-Howell\nR's `TukeyHSD()` and statsmodels' `pairwise_tukeyhsd()` give identical results; R writes the pairs as \"2-1\" (second group minus first), statsmodels as group1, group2 with meandiff = group2 − group1. For Games-Howell, R needs the rstatix package; in Python, pingouin's `pairwise_gameshowell()` reports `diff` as A − B, so its signs are the reverse of R's estimates. The p-values agree.\n:::\n\n## After Kruskal-Wallis: Dunn's test {#after-kruskal-wallis}\n\n**Dunn's test** follows a Kruskal-Wallis test. It compares the groups' mean ranks from the Kruskal-Wallis ranking, so it measures every pair on the same scale. Use it with Holm's adjustment. Running separate Mann-Whitney tests instead re-ranks the data for each pair and needs an adjustment of its own.\n\nLength of stay (LOS) is skewed (most patients go home on day 0 or 1), so it belongs in the rank column. Does it differ across ASA classes?\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohort |>\n  group_by(asa) |>\n  summarise(n = n(), median = median(los_days),\n            q1 = quantile(los_days, 0.25), q3 = quantile(los_days, 0.75))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n    asa     n median    q1    q3\n  <dbl> <int>  <dbl> <dbl> <dbl>\n1     1    36      0  0      0  \n2     2   300      0  0      1  \n3     3   246      1  0      2  \n4     4    18      1  0.25   3.5\n```\n\n\n:::\n\n```{.r .cell-code}\nlos_kw <- kruskal.test(los_days ~ factor(asa), data = cohort)\nlos_kw\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  los_days by factor(asa)\nKruskal-Wallis chi-squared = 24.286, df = 3, p-value = 2.177e-05\n```\n\n\n:::\n\n```{.r .cell-code}\ndunn <- rstatix::dunn_test(cohort, los_days ~ asa, p.adjust.method = \"holm\")\ndunn |> select(group1, group2, statistic, p, p.adj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  group1 group2 statistic         p    p.adj\n  <chr>  <chr>      <dbl>     <dbl>    <dbl>\n1 1      2           2.99 0.00277   0.0111  \n2 1      3           4.05 0.0000510 0.000261\n3 1      4           4.09 0.0000435 0.000261\n4 2      3           2.27 0.0233    0.0467  \n5 2      4           2.69 0.00718   0.0216  \n6 3      4           1.87 0.0611    0.0611  \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(cohort.groupby(\"asa\")[\"los_days\"].describe()[[\"count\", \"25%\", \"50%\", \"75%\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     count   25%  50%  75%\nasa                       \n1     36.0  0.00  0.0  0.0\n2    300.0  0.00  0.0  1.0\n3    246.0  0.00  1.0  2.0\n4     18.0  0.25  1.0  3.5\n```\n\n\n:::\n\n```{.python .cell-code}\nlos_kw = stats.kruskal(*[group[\"los_days\"] for _, group in cohort.groupby(\"asa\")])\nprint(los_kw.statistic, los_kw.pvalue)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n24.285994027836807 2.1770634905599066e-05\n```\n\n\n:::\n\n```{.python .cell-code}\ndunn = sp.posthoc_dunn(cohort, val_col=\"los_days\", group_col=\"asa\", p_adjust=\"holm\")\nprint(dunn.round(4))                                           # adjusted p-values\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1       2       3       4\n1  1.0000  0.0111  0.0003  0.0003\n2  0.0111  1.0000  0.0467  0.0216\n3  0.0003  0.0467  1.0000  0.0611\n4  0.0003  0.0216  0.0611  1.0000\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n- **Kruskal-Wallis H = 24.3, df = 3, p < 0.001:** LOS differs somewhere across the classes.\n- **Dunn's test:** ASA 1 differs from every other class (adjusted p = 0.011 against ASA 2, p < 0.001 against ASAs 3 and 4), and ASA 2 differs from ASAs 3 (p = 0.047) and 4 (p = 0.022). There was no clear evidence of a difference between ASA 3 and 4 (p = 0.061).\n- **The statistic** in R's output is a z score: positive means the second group's ranks are higher (longer stays).\n\n> **Results:** The median length of stay was 0 days (IQR 0 to 0) in ASA 1 and 1 day (IQR 0.25 to 3.5) in ASA 4 (Kruskal-Wallis H = 24.3, df = 3, p < 0.001). In Dunn's tests with Holm's adjustment, p ≤ 0.011 for ASA 1 against each other class and p = 0.061 for ASA 3 against ASA 4.\n\n::: {.callout-tip}\n## 🔀 R vs Python: Dunn's test\nBoth correct the z scores for tied ranks, which matter here because many patients share a LOS of 0 or 1 day, and both give the same adjusted p-values. R's rstatix returns one row per pair; scikit-posthocs' `posthoc_dunn()` returns a square table of p-values with the groups on both sides.\n:::\n\n## After chi-square: pairwise Fisher's exact tests {#after-chi-square}\n\nAfter a chi-square (or Fisher) test on a table with three or more groups, compare the groups two at a time with **Fisher's exact test**, then adjust with Holm. [Page 8's exercise 3](../catalog/08-three-plus-unmatched.qmd#exercises) found that 90-day complications differ across ASA classes:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomplications <- table(asa = cohort$asa, complication = cohort$complication_90d)\ncomplications\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   complication\nasa   0   1\n  1  36   0\n  2 279  21\n  3 220  26\n  4  14   4\n```\n\n\n:::\n\n```{.r .cell-code}\nfisher_overall <- fisher.test(complications)      # overall: expected counts are too small for chi-square\nfisher_overall\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  complications\np-value = 0.01587\nalternative hypothesis: two.sided\n```\n\n\n:::\n\n```{.r .cell-code}\npairwise_fisher <- rstatix::pairwise_fisher_test(complications, p.adjust.method = \"holm\")\npairwise_fisher\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  group1 group2     n       p  p.adj p.adj.signif\n* <chr>  <chr>  <int>   <dbl>  <dbl> <chr>       \n1 1      2        336 0.146   0.399  ns          \n2 1      3        282 0.0566  0.226  ns          \n3 1      4         54 0.00968 0.0581 ns          \n4 2      3        546 0.168   0.399  ns          \n5 2      4        318 0.0429  0.214  ns          \n6 3      4        264 0.133   0.399  ns          \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ncomplications = pd.crosstab(cohort[\"asa\"], cohort[\"complication_90d\"])\nprint(complications)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncomplication_90d    0   1\nasa                      \n1                  36   0\n2                 279  21\n3                 220  26\n4                  14   4\n```\n\n\n:::\n\n```{.python .cell-code}\nfisher_p = []\nfor a, b in asa_pairs:\n    two_classes = complications.loc[[a, b]]                     # a 2 x 2 table for this pair\n    fisher_p.append(stats.fisher_exact(two_classes).pvalue)\nfisher_holm = multipletests(fisher_p, method=\"holm\")[1]\nprint(pd.DataFrame({\"pair\": [f\"{a} vs {b}\" for a, b in asa_pairs], \"p\": fisher_p, \"p_holm\": fisher_holm}).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     pair       p  p_holm\n0  1 vs 2  0.1460  0.3987\n1  1 vs 3  0.0566  0.2265\n2  1 vs 4  0.0097  0.0581\n3  2 vs 3  0.1675  0.3987\n4  2 vs 4  0.0429  0.2143\n5  3 vs 4  0.1329  0.3987\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nThe overall Fisher test says the complication rate differs across ASA classes (p = 0.016). But no single pair differs clearly after Holm's adjustment: the closest is ASA 1 vs ASA 4 (0 of 36 vs 4 of 18 patients; p = 0.010 unadjusted, 0.058 adjusted). [A later section](#overall-test-first) explains why that can happen.\n\n## After repeated-measures ANOVA: paired t tests {#after-repeated-measures-anova}\n\n[Page 9](../catalog/09-three-plus-matched.qmd#repeated-measures-anova) found that the VR-12 physical component score (PCS) changed over the first year, in 328 patients measured at all four visits. To say *when* it changed, compare every pair of visits with a **paired t test** and adjust with Holm:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npcs <- proms |>\n  select(case_id, visit, vr12_pcs) |>\n  group_by(case_id) |>\n  filter(all(!is.na(vr12_pcs))) |>                  # patients measured at all four visits\n  ungroup() |>\n  mutate(visit = factor(visit, levels = c(\"preop\", \"6wk\", \"3mo\", \"1yr\"))) |>\n  arrange(case_id, visit)                           # paired tests match rows by position\n\npcs_pairs <- rstatix::pairwise_t_test(pcs, vr12_pcs ~ visit, paired = TRUE, p.adjust.method = \"holm\")\npcs_pairs |> select(group1, group2, n1, statistic, df, p.adj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  group1 group2    n1 statistic    df    p.adj\n  <chr>  <chr>  <int>     <dbl> <dbl>    <dbl>\n1 preop  6wk      328     -7.99   327 4.60e-14\n2 preop  3mo      328    -20.8    327 4.34e-61\n3 preop  1yr      328    -27.6    327 9.57e-87\n4 6wk    3mo      328    -12.8    327 3.51e-30\n5 6wk    1yr      328    -20.3    327 3.05e-59\n6 3mo    1yr      328     -7.55   327 4.30e-13\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npcs = proms[[\"case_id\", \"visit\", \"vr12_pcs\"]]\npcs = pcs[pcs.groupby(\"case_id\")[\"vr12_pcs\"].transform(lambda scores: scores.notna().all())]\n\npcs_pairs = pg.pairwise_tests(data=pcs, dv=\"vr12_pcs\", within=\"visit\", subject=\"case_id\", padjust=\"holm\")\nprint(pcs_pairs[[\"A\", \"B\", \"T\", \"dof\", \"p_corr\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     A      B          T    dof        p_corr\n0  1yr    3mo   7.552682  327.0  4.301383e-13\n1  1yr    6wk  20.295973  327.0  3.051381e-59\n2  1yr  preop  27.630125  327.0  9.573204e-87\n3  3mo    6wk  12.792308  327.0  3.512779e-30\n4  3mo  preop  20.793837  327.0  4.342607e-61\n5  6wk  preop   7.992004  327.0  4.603569e-14\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nEvery pair of visits differs (all adjusted p < 0.001): PCS improved between each visit and the next, from pre-op to 6 weeks (t = 8.0) through to 3 months and 1 year (t = 7.6 for the last step). With 328 patients and changes this large, the adjustment changes nothing. It matters most when results sit near p = 0.05.\n\n::: {.callout-tip}\n## 🔀 R vs Python: which way round\npingouin sorts the visits alphabetically and subtracts the second from the first, so its t statistics are negative where R's are positive, or the other way round. Compare their sizes. rstatix needs the rows in the same patient order within every visit, so sort by patient first.\n:::\n\n## After Friedman: pairwise Wilcoxon or Conover tests {#after-friedman}\n\nAfter a Friedman test, compare pairs of visits with **Wilcoxon signed-rank tests** and Holm's adjustment, or with **Conover's test**, which reuses the Friedman ranks (as Dunn's test does after Kruskal-Wallis) and is often more powerful. [Page 9](../catalog/09-three-plus-matched.qmd#friedman) found that KOOS JR changed between 6 weeks, 3 months and 1 year in 205 knees:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkoos <- proms |>\n  filter(instrument == \"KOOS JR\", visit != \"preop\") |>\n  select(case_id, visit, prom_score) |>\n  group_by(case_id) |>\n  filter(n() == 3, all(!is.na(prom_score))) |>         # knees scored at all three visits\n  ungroup() |>\n  mutate(visit = factor(visit, levels = c(\"6wk\", \"3mo\", \"1yr\"))) |>\n  arrange(case_id, visit)\n\nkoos_pairs <- rstatix::pairwise_wilcox_test(koos, prom_score ~ visit, paired = TRUE, exact = FALSE, correct = FALSE,\n                                            p.adjust.method = \"holm\")\nkoos_pairs |> select(group1, group2, statistic, p, p.adj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  group1 group2 statistic        p    p.adj\n  <chr>  <chr>      <dbl>    <dbl>    <dbl>\n1 6wk    3mo        1698. 2.06e-25 4.13e-25\n2 6wk    1yr         130  1.45e-34 4.36e-34\n3 3mo    1yr        2611  4.12e-20 4.12e-20\n```\n\n\n:::\n\n```{.r .cell-code}\nkoos_conover <- PMCMRplus::frdAllPairsConoverTest(y = koos$prom_score, groups = koos$visit, blocks = koos$case_id,\n                                                  p.adjust.method = \"holm\")\nsignif(koos_conover$p.value, 3)          # printing koos_conover itself shows these only as \"<2e-16\"\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         6wk      3mo\n3mo 8.85e-36       NA\n1yr 8.54e-87 6.01e-28\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nkoos = proms[(proms[\"instrument\"] == \"KOOS JR\") & (proms[\"visit\"] != \"preop\")]\nkoos_wide = koos.pivot(index=\"case_id\", columns=\"visit\", values=\"prom_score\")[[\"6wk\", \"3mo\", \"1yr\"]].dropna()\nprint(len(koos_wide))                                    # knees scored at all three visits\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n205\n```\n\n\n:::\n\n```{.python .cell-code}\nwilcoxon = {}\nfor a, b in [(\"6wk\", \"3mo\"), (\"6wk\", \"1yr\"), (\"3mo\", \"1yr\")]:\n    wilcoxon[(a, b)] = stats.wilcoxon(koos_wide[a], koos_wide[b], method=\"approx\", correction=False)\n    print(a, b, wilcoxon[(a, b)].statistic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n6wk 3mo 1698.5\n6wk 1yr 130.0\n3mo 1yr 2611.0\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(multipletests([test.pvalue for test in wilcoxon.values()], method=\"holm\")[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[4.12877449e-25 4.35503019e-34 4.11590264e-20]\n```\n\n\n:::\n\n```{.python .cell-code}\nkoos_conover = sp.posthoc_conover_friedman(koos_wide, p_adjust=\"holm\")\nprint(koos_conover)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              6wk           3mo           1yr\n6wk  1.000000e+00  8.852642e-36  8.540342e-87\n3mo  8.852642e-36  1.000000e+00  6.005858e-28\n1yr  8.540342e-87  6.005858e-28  1.000000e+00\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nAll three pairs differ (adjusted p < 0.001 with either method): KOOS JR rose between 6 weeks and 3 months and again between 3 months and 1 year.\n\n::: {.callout-tip}\n## 🔀 R vs Python: the statistic\nR's `wilcox.test()` reports V, the sum of the positive ranks; scipy reports the smaller of the two rank sums. Here both are the same number, because the later visit scores higher for most knees. Conover's test needs the PMCMRplus package in R and scikit-posthocs in Python; they give the same p-values. Printing PMCMRplus's result shows any p-value below 2 × 10⁻¹⁶ only as \"<2e-16\", so print its `$p.value` table to see them.\n:::\n\n## After Cochran's Q: pairwise McNemar tests {#after-cochran-q}\n\nAfter Cochran's Q, compare pairs of visits with **McNemar's test** and adjust with Holm. [Page 9](../catalog/09-three-plus-matched.qmd#cochran-q) found that walking-aid use changed over the year in 328 patients assessed at all four visits:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\naid <- proms |>\n  select(case_id, visit, walking_aid) |>\n  group_by(case_id) |>\n  filter(all(!is.na(walking_aid))) |>               # patients assessed at all four visits\n  ungroup() |>\n  pivot_wider(names_from = visit, values_from = walking_aid)\n\nvisit_pairs <- combn(c(\"preop\", \"6wk\", \"3mo\", \"1yr\"), 2)    # six pairs, one per column\nmcnemar_p <- apply(visit_pairs, 2, function(pair) {\n  mcnemar.test(table(factor(aid[[pair[1]]], levels = 0:1), factor(aid[[pair[2]]], levels = 0:1)))$p.value\n})\nmcnemar_results <- tibble(first = visit_pairs[1, ], second = visit_pairs[2, ],\n                          p = mcnemar_p, p_holm = p.adjust(mcnemar_p, method = \"holm\"))\nmcnemar_results\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  first second        p   p_holm\n  <chr> <chr>     <dbl>    <dbl>\n1 preop 6wk    2.60e- 9 7.81e- 9\n2 preop 3mo    4.66e- 3 4.66e- 3\n3 preop 1yr    8.53e-13 3.41e-12\n4 6wk   3mo    6.80e-19 3.40e-18\n5 6wk   1yr    4.30e-31 2.58e-30\n6 3mo   1yr    3.46e- 6 6.92e- 6\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\naid = proms.pivot(index=\"case_id\", columns=\"visit\", values=\"walking_aid\").dropna()   # assessed at all four visits\n\nmcnemar_p = []\nvisit_pairs = list(itertools.combinations([\"preop\", \"6wk\", \"3mo\", \"1yr\"], 2))\nfor first, second in visit_pairs:\n    pair_table = pd.crosstab(aid[first], aid[second]).reindex(index=[0, 1], columns=[0, 1], fill_value=0)\n    mcnemar_p.append(mcnemar(pair_table, exact=False, correction=True).pvalue)   # as R's mcnemar.test()\nmcnemar_holm = multipletests(mcnemar_p, method=\"holm\")[1]\nprint(pd.DataFrame({\"pair\": visit_pairs, \"p\": mcnemar_p, \"p_holm\": mcnemar_holm}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           pair             p        p_holm\n0  (preop, 6wk)  2.603120e-09  7.809359e-09\n1  (preop, 3mo)  4.658779e-03  4.658779e-03\n2  (preop, 1yr)  8.532093e-13  3.412837e-12\n3    (6wk, 3mo)  6.800079e-19  3.400039e-18\n4    (6wk, 1yr)  4.304488e-31  2.582693e-30\n5    (3mo, 1yr)  3.460638e-06  6.921277e-06\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nEvery pair of visits differs after adjustment. Use rose from pre-op to 6 weeks and fell at each visit after that; by 3 months it was already below its pre-op level (adjusted p = 0.005), and by 1 year lower still.\n\n## After a log-rank test: pairwise survival comparisons {#after-log-rank}\n\n[Page 13](../survival/13-kaplan-meier.qmd#log-rank) found that revision-free survival differs across implants A, B and C. To say which implants differ, run the **log-rank test for each pair** and adjust with Holm. A Cox model gives the matching effect sizes: refit it with a different reference group to get the hazard ratio for any pair.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimplant_pairs <- combn(c(\"A\", \"B\", \"C\"), 2)\nlogrank <- apply(implant_pairs, 2, function(pair) {\n  two_implants <- cohort |> filter(implant %in% pair)\n  test <- survdiff(Surv(followup_years, revised) ~ implant, data = two_implants)\n  c(chisq = test$chisq, p = test$pvalue)\n})\nlogrank_results <- tibble(first = implant_pairs[1, ], second = implant_pairs[2, ], chisq = logrank[\"chisq\", ],\n                          p = logrank[\"p\", ], p_holm = p.adjust(logrank[\"p\", ], method = \"holm\"))\nlogrank_results\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  first second  chisq           p     p_holm\n  <chr> <chr>   <dbl>       <dbl>      <dbl>\n1 A     B       0.414 0.520       0.520     \n2 A     C      20.5   0.00000586  0.0000117 \n3 B     C      24.7   0.000000659 0.00000198\n```\n\n\n:::\n\n```{.r .cell-code}\n# hazard ratios against implant B instead of A\ncohort <- cohort |> mutate(implant_vs_b = relevel(factor(implant), ref = \"B\"))\nimplant_vs_b_model <- coxph(Surv(followup_years, revised) ~ implant_vs_b, data = cohort)\nsummary(implant_vs_b_model)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              exp(coef) exp(-coef) lower .95 upper .95\nimplant_vs_bA  1.223854  0.8170908 0.6676703  2.243351\nimplant_vs_bC  3.753982  0.2663838 2.1413307  6.581132\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npairwise_logrank = pairwise_logrank_test(cohort[\"followup_years\"], cohort[\"implant\"], cohort[\"revised\"])\nlogrank_p = pairwise_logrank.summary[\"p\"]\nlogrank_holm = multipletests(logrank_p, method=\"holm\")[1]\nprint(pd.DataFrame({\"chisq\": pairwise_logrank.summary[\"test_statistic\"], \"p\": logrank_p, \"p_holm\": logrank_holm}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         chisq             p    p_holm\nA B   0.414318  5.197859e-01  0.519786\n  C  20.534618  5.856248e-06  0.000012\nB C  24.730823  6.592144e-07  0.000002\n```\n\n\n:::\n\n```{.python .cell-code}\n# hazard ratios against implant B instead of A: the first category is the reference\ncohort[\"implant_vs_b\"] = pd.Categorical(cohort[\"implant\"], categories=[\"B\", \"A\", \"C\"])\nimplant_vs_b = CoxPHFitter().fit(cohort[[\"followup_years\", \"revised\", \"implant_vs_b\"]],\n                                 duration_col=\"followup_years\", event_col=\"revised\", formula=\"implant_vs_b\",\n                                 fit_options={\"precision\": 1e-12})\nprint(implant_vs_b.summary[[\"exp(coef)\", \"exp(coef) lower 95%\", \"exp(coef) upper 95%\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   exp(coef)  exp(coef) lower 95%  exp(coef) upper 95%\ncovariate                                                             \nimplant_vs_b[T.A]   1.223854             0.667670             2.243351\nimplant_vs_b[T.C]   3.753982             2.141331             6.581132\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nImplant C differs from both A and B (adjusted p < 0.001 for each). There was no clear evidence of a difference between A and B (p = 0.520). Against implant B, implant C's hazard ratio was 3.75 (95% CI 2.14 to 6.58); against implant A it was 3.07 (95% CI 1.85 to 5.09; [page 8](../catalog/08-three-plus-unmatched.qmd#cox)).\n\n> **Results:** The log-rank test for revision-free survival across implants gave χ² = 33.5 (df = 2, p < 0.001). In pairwise log-rank tests with Holm's adjustment, p < 0.001 for implant C against implant A and against implant B, and p = 0.520 for implant A against implant B.\n\n::: {.callout-tip}\n## 🔀 R vs Python: pairwise log-rank tests\nlifelines has `pairwise_logrank_test()`, which runs every pair at once and leaves the adjustment to you. lifelines' Cox model stops iterating slightly early by default, so, as on [page 14](../survival/14-cox-regression.qmd), the Python Cox fit passes `fit_options={\"precision\": 1e-12}` to match R's hazard ratios. R's survival package has no pairwise function, so the R code loops over the pairs; the survminer package's `pairwise_survdiff()` does the same in one call. To change the reference group, R uses `relevel()`; lifelines uses the first category of a pandas `Categorical`.\n:::\n\n## Do you need a significant overall test first? {#overall-test-first}\n\nA common rule says: only run post-hoc tests if the overall test (the ANOVA, Kruskal-Wallis or chi-square) is significant. It comes from **Fisher's least significant difference** method, which runs unadjusted pairwise tests and relies on the overall test as a gate. That gate only fully protects you with three groups.\n\nThe tests on this page don't need the gate. Tukey's HSD and Games-Howell control the family-wise error rate on their own, and so do Dunn's test and any other set of pairwise tests once Holm's adjustment is applied. Requiring a significant overall test first just makes them stricter than they need to be.\n\nThe two kinds of test can also disagree, and that's not a contradiction:\n- **A significant overall test with no significant pair**, as with complications by ASA class above (overall p = 0.016; no pair below 0.05 after adjustment). The overall test pools the evidence from all four classes, while each pair uses only two of them, and the ASA 1 and ASA 4 groups are small. Report it as it is: complication rates differed across ASA classes overall, but no single pair of classes differed clearly.\n- **A significant pair with no significant overall test.** This can happen when one pair differs and the others don't, diluting the overall test.\n\nWhat to do:\n1. **Decide before you look at the data** which comparisons you'll make: every pair, or a few planned ones.\n2. **If your question is about pairs, go straight to an adjusted pairwise method.** The overall test is optional; report it if your readers expect it.\n3. **Never run unadjusted pairwise tests you didn't plan**, whatever the overall test says.\n4. **Say what you did** in the Methods.\n\n## Planned comparisons and how to report them {#planned-comparisons}\n\nNot every comparison is a fishing trip. A study comparing a new implant with the standard one has one **pre-specified** comparison, named in the protocol before any data were collected. It needs no adjustment, because it isn't one of many. If you planned three comparisons, adjust for three, not for every possible pair.\n\nEverything else is **exploratory**: comparisons chosen after seeing the data, or a scan across many outcomes. Adjust for every comparison you looked at, not only the ones you report, and label the results exploratory: they suggest questions for the next study, not conclusions.\n\n> **Methods:** Pairwise comparisons after the omnibus tests used Tukey's honestly significant difference test (after ANOVA), Dunn's test (after Kruskal-Wallis) and Fisher's exact tests (after chi-square), with Holm's adjustment for multiple comparisons where the method did not adjust itself. All pairwise comparisons were exploratory.\n>\n> **Results:** Across ASA classes, one-way ANOVA gave F(3, 596) = 23.9 (p < 0.001); in pairwise comparisons, the difference in mean age between ASA 3 and ASA 2 was 5.0 years (95% CI 3.0 to 6.9; p < 0.001). Table 2 gives all six pairwise comparisons.\n\n::: {.callout-warning}\n## ⚠️ Watch out: report every comparison you ran\nRunning ten comparisons and reporting the two significant ones hides how many chances you had. Give the number of comparisons and the adjustment in the Methods, and put the full set of pairwise results in a table or supplement.\n:::\n\n\n\n## Exercises {#exercises}\n\nThe solutions use the packages and data loaded in the sections above, so run the page from the top first.\n\n**1.** [Page 8's exercise 1](../catalog/08-three-plus-unmatched.qmd#exercises) found that BMI differs across ASA classes. Which pairs of classes differ? Use Tukey's HSD.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(aov(bmi ~ factor(asa), data = cohort))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = bmi ~ factor(asa), data = cohort)\n\n$`factor(asa)`\n        diff       lwr       upr     p adj\n2-1 2.874778 0.5750771  5.174478 0.0073588\n3-1 5.824526 3.4979388  8.151113 0.0000000\n4-1 9.877778 6.1140091 13.641546 0.0000000\n3-2 2.949748 1.8282934  4.071203 0.0000000\n4-2 7.003000 3.8390455 10.166954 0.0000001\n4-3 4.053252 0.8697018  7.236802 0.0060316\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(pairwise_tukeyhsd(cohort[\"bmi\"], cohort[\"asa\"]).summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMultiple Comparison of Means - Tukey HSD, FWER=0.05\n===================================================\ngroup1 group2 meandiff p-adj  lower   upper  reject\n---------------------------------------------------\n     1      2   2.8748 0.0074 0.5751  5.1745   True\n     1      3   5.8245    0.0 3.4979  8.1511   True\n     1      4   9.8778    0.0  6.114 13.6415   True\n     2      3   2.9497    0.0 1.8283  4.0712   True\n     2      4    7.003    0.0  3.839  10.167   True\n     3      4   4.0533  0.006 0.8697  7.2368   True\n---------------------------------------------------\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** In Tukey's HSD, all six pairwise differences in mean BMI had adjusted p < 0.01, including ASA 2 vs 1 (2.9 kg/m², 95% CI 0.6 to 5.2; p = 0.007) and ASA 4 vs 3 (4.1 kg/m², 95% CI 0.9 to 7.2; p = 0.006).\n\nEvery pair differs, and mean BMI rises with each step in ASA class. The least certain differences involve the two small classes, ASA 1 and ASA 4.\n:::\n\n**2.** A colleague compares men and women on six yes/no characteristics (diabetes, hypertension, sleep apnea, readmission, complications and discharge to a rehabilitation clinic) with Fisher's exact test. Which adjustment fits, and which differences survive it?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nThis is a screen across several outcomes with no single planned comparison, so the results are exploratory. Holm's adjustment keeps the chance of any false positive at 5%; Benjamini-Hochberg is acceptable for a screen, as long as the results are labeled exploratory.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyes_no <- cohort |> mutate(rehab = as.integer(discharge == \"rehabilitation clinic\"))\ncharacteristics <- c(\"diabetes\", \"hypertension\", \"sleep_apnea\", \"readmit_90d\", \"complication_90d\", \"rehab\")\nby_sex_p <- sapply(characteristics, function(v) fisher.test(table(yes_no$sex, yes_no[[v]]))$p.value)\nround(cbind(unadjusted = by_sex_p, holm = p.adjust(by_sex_p, \"holm\"), bh = p.adjust(by_sex_p, \"BH\")), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 unadjusted   holm     bh\ndiabetes             0.3209 1.0000 0.6418\nhypertension         0.1346 0.6729 0.4038\nsleep_apnea          0.0000 0.0001 0.0001\nreadmit_90d          1.0000 1.0000 1.0000\ncomplication_90d     0.6582 1.0000 0.8487\nrehab                0.7072 1.0000 0.8487\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ncohort[\"rehab\"] = (cohort[\"discharge\"] == \"rehabilitation clinic\").astype(int)\ncharacteristics = [\"diabetes\", \"hypertension\", \"sleep_apnea\", \"readmit_90d\", \"complication_90d\", \"rehab\"]\nby_sex_p = [stats.fisher_exact(pd.crosstab(cohort[\"sex\"], cohort[v])).pvalue for v in characteristics]\nprint(pd.DataFrame({\"unadjusted\": by_sex_p, \"holm\": multipletests(by_sex_p, method=\"holm\")[1],\n                    \"bh\": multipletests(by_sex_p, method=\"fdr_bh\")[1]}, index=characteristics).round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  unadjusted    holm      bh\ndiabetes              0.3209  1.0000  0.6418\nhypertension          0.1346  0.6729  0.4038\nsleep_apnea           0.0000  0.0001  0.0001\nreadmit_90d           1.0000  1.0000  1.0000\ncomplication_90d      0.6582  1.0000  0.8487\nrehab                 0.7072  1.0000  0.8487\n```\n\n\n:::\n:::\n\n:::\n\nOnly sleep apnea differs between men and women after either adjustment (adjusted p < 0.001). Hypertension's unadjusted p = 0.135 was never close, and every other characteristic's Benjamini-Hochberg p-value is above 0.4.\n:::\n\n**3.** Leaving out the pre-op visit, which pairs of visits differ in walking-aid use (6 weeks, 3 months, 1 year)? Write the Results sentence.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlater <- proms |>\n  filter(visit != \"preop\") |>\n  select(case_id, visit, walking_aid) |>\n  group_by(case_id) |>\n  filter(all(!is.na(walking_aid))) |>\n  ungroup() |>\n  pivot_wider(names_from = visit, values_from = walking_aid)\nnrow(later)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 345\n```\n\n\n:::\n\n```{.r .cell-code}\ncolSums(later[, c(\"6wk\", \"3mo\", \"1yr\")])                     # walking-aid users at each visit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n6wk 3mo 1yr \n203  87  37 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(100 * colMeans(later[, c(\"6wk\", \"3mo\", \"1yr\")]), 1)    # the same, as percentages\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 6wk  3mo  1yr \n58.8 25.2 10.7 \n```\n\n\n:::\n\n```{.r .cell-code}\nlater_pairs <- combn(c(\"6wk\", \"3mo\", \"1yr\"), 2)\nlater_p <- apply(later_pairs, 2, function(pair) {\n  mcnemar.test(table(factor(later[[pair[1]]], levels = 0:1), factor(later[[pair[2]]], levels = 0:1)))$p.value\n})\np.adjust(later_p, method = \"holm\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.287205e-18 1.387448e-31 1.223935e-06\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nlater = proms[proms[\"visit\"] != \"preop\"].pivot(index=\"case_id\", columns=\"visit\", values=\"walking_aid\").dropna()\nprint(len(later), later[[\"6wk\", \"3mo\", \"1yr\"]].sum().astype(int).to_list())    # walking-aid users at each visit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n345 [203, 87, 37]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint((100 * later[[\"6wk\", \"3mo\", \"1yr\"]].mean()).round(1).to_list())             # the same, as percentages\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[58.8, 25.2, 10.7]\n```\n\n\n:::\n\n```{.python .cell-code}\nlater_p = []\nfor first, second in itertools.combinations([\"6wk\", \"3mo\", \"1yr\"], 2):\n    pair_table = pd.crosstab(later[first], later[second]).reindex(index=[0, 1], columns=[0, 1], fill_value=0)\n    later_p.append(mcnemar(pair_table, exact=False, correction=True).pvalue)\nprint(multipletests(later_p, method=\"holm\")[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[2.28720462e-18 1.38744786e-31 1.22393512e-06]\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Among 345 patients assessed at all three visits, 203 (58.8%) used a walking aid at 6 weeks, 87 (25.2%) at 3 months and 37 (10.7%) at 1 year; in McNemar tests with Holm's adjustment, p < 0.001 for every pair of visits.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}