{
  "hash": "f27b04c16cb08c045f249de591161787",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"17 · Agreement & reliability\"\ndescription: \"ICC, Bland-Altman limits of agreement, and kappa for radiographic measurements: how well two raters, or one rater on two days, agree.\"\nengine: knitr\n---\n\n\n\n<!-- data-checksum: 9e548efb7ad4232927ffa99aa2cdeca7 -->\n\nBefore a measurement goes into a study, someone should ask: if it were measured again, would you get the same answer? Alignment angles on long-leg radiographs are a good example. Two surgeons can place the same landmarks a little differently, and one surgeon can place them differently on another day. This page shows how to measure that, using the practice data's reliability study: 60 knees, each measured by two raters (R1 and R2), twice, at least two weeks apart.\n\n::: {.callout-note}\n## 💡 How this page works\nRun the code blocks in order, from the top: later blocks use the packages and data loaded in the first one.\n:::\n\n## Reliability or agreement? {#reliability-vs-agreement}\n\nThe two words are often used as if they meant the same thing. They don't:\n- **Reliability** asks whether a measurement can tell patients apart: are the real differences between knees large compared with the disagreement between readings? It's measured with the **intraclass correlation coefficient** (ICC), a number from 0 to 1. Because it compares the disagreement with how much the knees differ, the same raters look more reliable in a cohort with a wider range of deformities.\n- **Agreement** asks how close two readings are, in the measurement's own units. If rater 2 reads every knee 3° higher than rater 1, that's poor agreement, even though the two raters put the knees in exactly the same order. It's measured with the **Bland-Altman limits of agreement**, in degrees.\n\nReport both. A clinician deciding whether a knee is in varus needs to know the agreement in degrees, not only that the ICC was 0.9.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nreadings <- read_csv(\"data/radiographic_reliability.csv\", show_col_types = FALSE)\nreadings |> head(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  knee_id rater session hka_deg mpta_deg ldfa_deg cpak_class\n  <chr>   <chr>   <dbl>   <dbl>    <dbl>    <dbl> <chr>     \n1 K001    R1          1    172.     86.8     89.7 I         \n2 K001    R1          2    172.     85.7     90.8 I         \n3 K001    R2          1    174.     86.7     91.2 IV        \n4 K001    R2          2    173.     85.8     90.6 I         \n```\n\n\n:::\n\n```{.r .cell-code}\nreadings |> count(rater, session)                      # 60 knees in every rater x session\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  rater session     n\n  <chr>   <dbl> <int>\n1 R1          1    60\n2 R1          2    60\n3 R2          1    60\n4 R2          2    60\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport pingouin as pg\nimport matplotlib.pyplot as plt\nfrom scipy import stats\nfrom statsmodels.stats.inter_rater import cohens_kappa\n\nreadings = pd.read_csv(\"data/radiographic_reliability.csv\")\nprint(readings.head(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  knee_id rater  session  hka_deg  mpta_deg  ldfa_deg cpak_class\n0    K001    R1        1    171.7      86.8      89.7          I\n1    K001    R1        2    172.1      85.7      90.8          I\n2    K001    R2        1    174.1      86.7      91.2         IV\n3    K001    R2        2    173.4      85.8      90.6          I\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(readings.groupby([\"rater\", \"session\"]).size())     # 60 knees in every rater x session\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrater  session\nR1     1          60\n       2          60\nR2     1          60\n       2          60\ndtype: int64\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nThe data are long: one row per knee, rater and session, with the hip-knee-ankle angle (HKA, 180° is neutral, below 180° is varus), the medial proximal tibial angle (MPTA), the lateral distal femoral angle (LDFA) and the CPAK class those angles give.\n\n## The intraclass correlation coefficient {#icc}\n\nThere are several ICCs, and the right one depends on the design. Three choices define it (Koo & Li, 2016):\n- **Model:** are the raters a random sample of the raters who might use this measurement (**two-way random**), or the only raters you care about (**two-way mixed**)? For a measurement other surgeons will use, choose random.\n- **Type:** should a rater who always reads higher count against the measurement (**absolute agreement**) or not (**consistency**)? For angles that feed clinical decisions, it should: choose absolute agreement.\n- **Unit:** will the study use one rater's reading (**single**) or the average of several (**average**)? Usually single.\n\nFor inter-rater reliability of HKA, that gives a two-way random, absolute-agreement, single-rater ICC, written ICC(A,1) (or ICC(2,1) in Shrout and Fleiss's older naming). Using each rater's first-session readings:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninter_hka <- readings |>\n  filter(session == 1) |>\n  select(knee_id, rater, hka_deg) |>\n  pivot_wider(names_from = rater, values_from = hka_deg)     # one column per rater\n\ninter_icc <- irr::icc(inter_hka[, c(\"R1\", \"R2\")], model = \"twoway\", type = \"agreement\", unit = \"single\")\ninter_icc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Single Score Intraclass Correlation\n\n   Model: twoway \n   Type : agreement \n\n   Subjects = 60 \n     Raters = 2 \n   ICC(A,1) = 0.889\n\n F-Test, H0: r0 = 0 ; H1: r0 > 0 \n   F(59,59) = 18.3 , p = 8.19e-23 \n\n 95%-Confidence Interval for ICC Population Values:\n  0.816 < ICC < 0.934\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfirst_session = readings[readings[\"session\"] == 1]\ninter_icc = pg.intraclass_corr(data=first_session, targets=\"knee_id\", raters=\"rater\", ratings=\"hka_deg\")\nprint(inter_icc[[\"Type\", \"ICC\", \"CI95\"]])     # ICC(A,1): two-way random, absolute agreement, single rater\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Type       ICC          CI95\n0  ICC(1,1)  0.888950  [0.82, 0.93]\n1  ICC(A,1)  0.889383  [0.82, 0.93]\n2  ICC(C,1)  0.896386  [0.83, 0.94]\n3  ICC(1,k)  0.941211   [0.9, 0.96]\n4  ICC(A,k)  0.941454   [0.9, 0.97]\n5  ICC(C,k)  0.945362  [0.91, 0.97]\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n- **ICC(A,1) = 0.889** (Python's `ICC(A,1)` row; R prints 0.889).\n- **95% CI 0.82 to 0.93.** Koo and Li's guide: below 0.5 poor, 0.5 to 0.75 moderate, 0.75 to 0.9 good, above 0.9 excellent. Judge by the CI, not the point estimate: this one runs from good to excellent.\n- **The F test** (R) tests whether the ICC is above 0. It nearly always is, so it's rarely worth reporting.\n\n::: {.callout-warning}\n## ⚠️ Watch out: always say which ICC\nThe same data give a different ICC for every model, type and unit: here 0.889 for absolute agreement and 0.896 for consistency, and 0.94 for the average of the two raters. \"ICC = 0.94\" with no form named can't be interpreted. Write the form out in the Methods.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: one ICC or all of them\nR's `irr::icc()` computes the one ICC you ask for. pingouin's `intraclass_corr()` computes all six forms at once; pick the row. It labels them two ways: `ICC(A,1)` in McGraw and Wong's naming, which matches R's arguments, or `ICC2` in older pingouin versions. pingouin rounds the CI to 2 decimals.\n:::\n\n## Inter-rater and intra-rater reliability {#inter-intra-rater}\n\nThe ICC above is **inter-rater** reliability: two raters, same films. **Intra-rater** (test-retest) reliability uses one rater reading the same films twice, far enough apart that they don't remember their first answers. The same ICC form applies, with the two sessions in place of the two raters:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintra_hka <- readings |>\n  filter(rater == \"R1\") |>\n  select(knee_id, session, hka_deg) |>\n  pivot_wider(names_from = session, values_from = hka_deg, names_prefix = \"session_\")\n\nintra_icc <- irr::icc(intra_hka[, c(\"session_1\", \"session_2\")], model = \"twoway\", type = \"agreement\", unit = \"single\")\nintra_icc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Single Score Intraclass Correlation\n\n   Model: twoway \n   Type : agreement \n\n   Subjects = 60 \n     Raters = 2 \n   ICC(A,1) = 0.915\n\n F-Test, H0: r0 = 0 ; H1: r0 > 0 \n   F(59,59) = 22.8 , p = 2.25e-25 \n\n 95%-Confidence Interval for ICC Population Values:\n  0.862 < ICC < 0.948\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nrater_1 = readings[readings[\"rater\"] == \"R1\"]\nintra_icc = pg.intraclass_corr(data=rater_1, targets=\"knee_id\", raters=\"session\", ratings=\"hka_deg\")\nprint(intra_icc.set_index(\"Type\").loc[\"ICC(A,1)\", [\"ICC\", \"CI95\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nICC         0.914844\nCI95    [0.86, 0.95]\nName: ICC(A,1), dtype: object\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nRater 1 agreed with themselves a little better than with rater 2: intra-rater ICC(A,1) = 0.915 (95% CI 0.86 to 0.95), excellent at its point estimate and good to excellent across its CI.\n\n## Bland-Altman: how far apart are the readings? {#bland-altman}\n\nThe ICC is a ratio and has no units. To see how far apart two readings can be, in degrees, plot the **difference** between them against their **mean**, one point per knee. Then add three lines:\n- **The bias:** the mean difference, showing whether one rater reads systematically higher.\n- **The 95% limits of agreement:** bias ± 1.96 × SD of the differences. For 95% of knees, rater 2's reading will fall between these limits relative to rater 1's.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninter_hka <- inter_hka |> mutate(difference = R2 - R1, mean = (R1 + R2) / 2)\n\nn_knees <- nrow(inter_hka)\nbias <- mean(inter_hka$difference)\nsd_diff <- sd(inter_hka$difference)\nlimits <- bias + c(-1.96, 1.96) * sd_diff\nse_limit <- sqrt(3 * sd_diff^2 / n_knees)                      # Bland and Altman's SE for each limit\nlimit_cis <- rbind(lower = limits[1] + c(-1, 1) * qt(0.975, n_knees - 1) * se_limit,\n                   upper = limits[2] + c(-1, 1) * qt(0.975, n_knees - 1) * se_limit)\n\nbias_ci <- t.test(inter_hka$difference)$conf.int                # the CI of the mean difference\nc(bias = bias, bias_ci = bias_ci, sd = sd_diff, limits = limits)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      bias   bias_ci1   bias_ci2         sd    limits1    limits2 \n 0.5033333  0.0761762  0.9304905  1.6535495 -2.7376237  3.7442904 \n```\n\n\n:::\n\n```{.r .cell-code}\nlimit_cis\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           [,1]      [,2]\nlower -3.477482 -1.997766\nupper  3.004433  4.484148\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(inter_hka, aes(mean, difference)) +\n  geom_point() +\n  geom_hline(yintercept = bias) +\n  geom_hline(yintercept = limits, linetype = \"dashed\") +\n  labs(x = \"Mean of the two readings (°)\", y = \"Rater 2 − rater 1 (°)\")\n```\n\n::: {.cell-output-display}\n![](17-agreement_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ninter = first_session.pivot(index=\"knee_id\", columns=\"rater\", values=\"hka_deg\")\ndifference = inter[\"R2\"] - inter[\"R1\"]\nmean = (inter[\"R1\"] + inter[\"R2\"]) / 2\n\nn_knees = len(difference)\nbias = difference.mean()\nsd_diff = difference.std()                                     # pandas uses n - 1, like R\nlimits = bias + np.array([-1.96, 1.96]) * sd_diff\nse_limit = np.sqrt(3 * sd_diff**2 / n_knees)                   # Bland and Altman's SE for each limit\nt_crit = stats.t.ppf(0.975, n_knees - 1)\nbias_ci = stats.ttest_1samp(difference, 0).confidence_interval()\nprint(round(bias, 3), round(float(bias_ci.low), 3), round(float(bias_ci.high), 3), round(sd_diff, 3), limits.round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.503 0.076 0.93 1.654 [-2.738  3.744]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint((limits - t_crit * se_limit).round(3), (limits + t_crit * se_limit).round(3))   # CI of each limit: lower ends, upper ends\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[-3.477  3.004] [-1.998  4.484]\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, ax = plt.subplots(figsize=(7, 4))\nax.scatter(mean, difference)\nax.axhline(bias)\nfor limit in limits:\n    ax.axhline(limit, linestyle=\"--\")\nax.set_xlabel(\"Mean of the two readings (°)\")\nax.set_ylabel(\"Rater 2 − rater 1 (°)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](17-agreement_files/figure-html/unnamed-chunk-16-1.png)\n:::\n:::\n\n:::\n\n\n\n\n\n- **Bias = 0.50°** (95% CI 0.08° to 0.93°): rater 2 reads half a degree higher than rater 1 on average, the same difference [page 7's exercise 2](../catalog/07-two-paired-groups.qmd#exercises) found with a paired t test.\n- **Limits of agreement, −2.74° to 3.74°:** for 95% of knees, rater 2's reading will be between 2.7° below and 3.7° above rater 1's.\n- **The CIs of the limits** (−3.48° to −2.00° and 3.00° to 4.48°) show how precisely 60 knees pin the limits down.\n- **The plot:** the points scatter evenly around the bias line, with no trend up or down as the mean angle changes. A trend would mean the raters disagree more for some knees (more varus, say) than others, and a single pair of limits wouldn't describe them.\n\nWhether limits of ±3.7° are good enough is a clinical question, not a statistical one. If a 3° difference moves a knee from \"neutral\" to \"varus\" in your study, it matters. Decide the acceptable limits **before** you run the reliability study, and compare the limits (and their CIs) with them.\n\n## Kappa for categories {#kappa}\n\nFor a category, like CPAK class, use **Cohen's kappa**: the agreement between two raters beyond what chance alone would produce. Kappa is 1 for perfect agreement and 0 for agreement no better than chance.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncpak_levels <- c(\"I\", \"II\", \"III\", \"IV\", \"V\", \"VI\", \"VII\", \"VIII\", \"IX\")\ncpak <- readings |>\n  filter(session == 1) |>\n  select(knee_id, rater, cpak_class) |>\n  pivot_wider(names_from = rater, values_from = cpak_class) |>\n  mutate(R1 = factor(R1, levels = cpak_levels), R2 = factor(R2, levels = cpak_levels))\n\nmean(cpak$R1 == cpak$R2)                                     # simple percentage agreement\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6666667\n```\n\n\n:::\n\n```{.r .cell-code}\ncpak_kappa <- DescTools::CohenKappa(cpak$R1, cpak$R2, conf.level = 0.95)\ncpak_kappa\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    kappa    lwr.ci    upr.ci \n0.5830438 0.4352380 0.7308495 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ncpak_levels = [\"I\", \"II\", \"III\", \"IV\", \"V\", \"VI\", \"VII\", \"VIII\", \"IX\"]\ncpak = first_session.pivot(index=\"knee_id\", columns=\"rater\", values=\"cpak_class\")\nprint((cpak[\"R1\"] == cpak[\"R2\"]).mean())                       # simple percentage agreement\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.6666666666666666\n```\n\n\n:::\n\n```{.python .cell-code}\ncpak_table = pd.crosstab(pd.Categorical(cpak[\"R1\"], categories=cpak_levels),\n                         pd.Categorical(cpak[\"R2\"], categories=cpak_levels), dropna=False)\ncpak_kappa = cohens_kappa(cpak_table.to_numpy())\nprint(cpak_kappa.kappa, cpak_kappa.kappa_low, cpak_kappa.kappa_upp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.5830437804030576 0.4352380334984082 0.7308495273077069\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nThe raters gave the same CPAK class to 40 of the 60 knees (66.7%), but some of that would happen by chance. Kappa = 0.58 (95% CI 0.44 to 0.73): moderate agreement at its point estimate on Landis and Koch's scale (0.41 to 0.60 moderate, 0.61 to 0.80 substantial, above 0.80 almost perfect). As with the ICC, judge it by the CI: moderate to substantial.\n\n**Weighted kappa for ordered categories.** Plain kappa treats every disagreement as equally bad. When the categories have an order, a near miss should count less than a big miss. CPAK class has no single order (it's a 3 × 3 grid of two angles), but each axis does. The arithmetic HKA group goes varus, neutral, valgus. A **weighted kappa** gives a disagreement between varus and neutral half the penalty of one between varus and valgus (linear weights):\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhka_group <- function(cpak_class) {\n  # CPAK classes I-III, IV-VI and VII-IX each run varus, neutral, valgus\n  factor(c(\"varus\", \"neutral\", \"valgus\")[(as.integer(cpak_class) - 1) %% 3 + 1],\n         levels = c(\"varus\", \"neutral\", \"valgus\"))                # in order\n}\nhka_table <- table(R1 = hka_group(cpak$R1), R2 = hka_group(cpak$R2))\nhka_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         R2\nR1        varus neutral valgus\n  varus      16       4      0\n  neutral     5      23      1\n  valgus      0       2      9\n```\n\n\n:::\n\n```{.r .cell-code}\nunweighted_kappa <- DescTools::CohenKappa(hka_table, conf.level = 0.95)                            # unweighted\nweighted_kappa <- DescTools::CohenKappa(hka_table, weights = \"Equal-Spacing\", conf.level = 0.95)   # linear weights\nrbind(unweighted = unweighted_kappa, weighted = weighted_kappa)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               kappa    lwr.ci    upr.ci\nunweighted 0.6769852 0.5098602 0.8441102\nweighted   0.7293233 0.5843821 0.8742645\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nhka_group = {cls: [\"varus\", \"neutral\", \"valgus\"][i % 3] for i, cls in enumerate(cpak_levels)}   # I-III, IV-VI, VII-IX\norder = [\"varus\", \"neutral\", \"valgus\"]\nhka_table = pd.crosstab(pd.Categorical(cpak[\"R1\"].map(hka_group), categories=order),\n                        pd.Categorical(cpak[\"R2\"].map(hka_group), categories=order), dropna=False)\nprint(hka_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncol_0    varus  neutral  valgus\nrow_0                          \nvarus       16        4       0\nneutral      5       23       1\nvalgus       0        2       9\n```\n\n\n:::\n\n```{.python .cell-code}\nunweighted = cohens_kappa(hka_table.to_numpy())\nweighted = cohens_kappa(hka_table.to_numpy(), wt=\"linear\")     # linear weights\nprint(unweighted.kappa, weighted.kappa, weighted.kappa_low, weighted.kappa_upp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.6769851951547781 0.7293233082706767 0.5843821108979698 0.8742645056433836\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nThe raters agreed on the HKA group for 48 of 60 knees, and every disagreement was a near miss: no knee was called varus by one rater and valgus by the other. Unweighted kappa is 0.68; the weighted kappa, which gives near misses partial credit, is 0.73 (95% CI 0.58 to 0.87): substantial at its point estimate, moderate to almost perfect across its CI.\n\n::: {.callout-warning}\n## ⚠️ Watch out: weighted kappa needs the categories in order\nThe weights depend on the order of the categories. Put them in their real order (varus, neutral, valgus) yourself. Some functions sort categories alphabetically, which would put \"neutral\" before \"valgus\" before \"varus\" and weight the wrong disagreements: `irr::kappa2(weight = \"equal\")` does, and gives 0.63 here instead of 0.73. Never use weighted kappa for categories with no order, like CPAK class itself.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: kappa and its CI\nDescTools' `CohenKappa()` and statsmodels' `cohens_kappa()` give the same kappa and the same CI. DescTools calls linear weights \"Equal-Spacing\" and quadratic weights \"Fleiss-Cohen\"; statsmodels uses `wt=\"linear\"` and `wt=\"quadratic\"`. scikit-learn's `cohen_kappa_score()` gives the kappa but no CI, and for weighted kappa it sorts the categories alphabetically unless you pass them in order with `labels=`.\n:::\n\n## How to report it {#reporting}\n\n> **Methods:** Two raters measured the hip-knee-ankle angle, MPTA and LDFA on 60 long-leg radiographs, twice, at least 2 weeks apart. Inter- and intra-rater reliability were assessed with two-way random-effects, absolute-agreement, single-rater intraclass correlation coefficients (ICC(A,1)) and interpreted according to Koo and Li. Inter-rater reliability used each rater's first reading; intra-rater reliability compared rater 1's two readings. Agreement was assessed with Bland-Altman 95% limits of agreement. Agreement on CPAK class was assessed with Cohen's kappa, and on the ordered arithmetic HKA group with linearly weighted kappa.\n>\n> **Results:** For the hip-knee-ankle angle, the inter-rater ICC was 0.89 (95% CI 0.82 to 0.93) and rater 1's intra-rater ICC 0.91 (95% CI 0.86 to 0.95). The mean difference between rater 2 and rater 1 was 0.50° (95% CI 0.08° to 0.93°), with 95% limits of agreement from −2.74° (95% CI −3.48° to −2.00°) to 3.74° (95% CI 3.00° to 4.48°). For CPAK class, κ = 0.58 (95% CI 0.44 to 0.73); for the arithmetic HKA group, weighted κ = 0.73 (95% CI 0.58 to 0.87).\n\n\n\n## Exercises {#exercises}\n\nThe solutions use the packages and data loaded in the sections above, so run the page from the top first.\n\n**1.** Calculate the inter-rater ICC for the MPTA, using each rater's first-session readings, and describe it with Koo and Li's guide.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpta <- readings |>\n  filter(session == 1) |>\n  select(knee_id, rater, mpta_deg) |>\n  pivot_wider(names_from = rater, values_from = mpta_deg)\nirr::icc(mpta[, c(\"R1\", \"R2\")], model = \"twoway\", type = \"agreement\", unit = \"single\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Single Score Intraclass Correlation\n\n   Model: twoway \n   Type : agreement \n\n   Subjects = 60 \n     Raters = 2 \n   ICC(A,1) = 0.935\n\n F-Test, H0: r0 = 0 ; H1: r0 > 0 \n   F(59,59) = 29.2 , p = 2.56e-28 \n\n 95%-Confidence Interval for ICC Population Values:\n  0.893 < ICC < 0.961\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nmpta_icc = pg.intraclass_corr(data=first_session, targets=\"knee_id\", raters=\"rater\", ratings=\"mpta_deg\")\nprint(mpta_icc.set_index(\"Type\").loc[\"ICC(A,1)\", [\"ICC\", \"CI95\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nICC         0.934769\nCI95    [0.89, 0.96]\nName: ICC(A,1), dtype: object\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** The inter-rater ICC(A,1) for the MPTA was 0.93 (95% CI 0.89 to 0.96).\n\nOn Koo and Li's guide, that's excellent at the point estimate, and the CI runs from good to excellent.\n:::\n\n**2.** Using rater 1's two sessions, calculate the Bland-Altman bias and 95% limits of agreement for HKA, and write the Results sentence.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nretest <- intra_hka$session_2 - intra_hka$session_1\nc(bias = mean(retest), t.test(retest)$conf.int, limits = mean(retest) + c(-1.96, 1.96) * sd(retest))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      bias                          limits1    limits2 \n-0.2650000 -0.6520625  0.1220625 -3.2017481  2.6717481 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nsessions = rater_1.pivot(index=\"knee_id\", columns=\"session\", values=\"hka_deg\")\nretest = sessions[2] - sessions[1]\nretest_ci = stats.ttest_1samp(retest, 0).confidence_interval()\nprint(retest.mean(), retest_ci.low, retest_ci.high, retest.mean() + np.array([-1.96, 1.96]) * retest.std())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-0.2649999999999987 -0.6520624952918566 0.1220624952918592 [-3.20174815  2.67174815]\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** The mean difference between rater 1's second and first readings was −0.26° (95% CI −0.65° to 0.12°), with 95% limits of agreement from −3.20° to 2.67°.\n:::\n\n**3.** A colleague reports that the two raters' HKA readings correlate well (Pearson's r = 0.90, 95% CI 0.83 to 0.94) as evidence that they agree. What's wrong with that? Show it by adding 5° to every one of rater 2's readings and recalculating r and the ICC.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nCorrelation measures whether two readings rise and fall together, not whether they're equal. A rater who reads every knee 5° too high correlates perfectly well with an accurate one.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(inter_hka$R1, inter_hka$R2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  inter_hka$R1 and inter_hka$R2\nt = 15.404, df = 58, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.8318567 0.9370562\nsample estimates:\n      cor \n0.8964295 \n```\n\n\n:::\n\n```{.r .cell-code}\nshifted <- inter_hka |> mutate(R2_shifted = R2 + 5)\ncor(shifted$R1, shifted$R2_shifted)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8964295\n```\n\n\n:::\n\n```{.r .cell-code}\nirr::icc(shifted[, c(\"R1\", \"R2_shifted\")], model = \"twoway\", type = \"agreement\", unit = \"single\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Single Score Intraclass Correlation\n\n   Model: twoway \n   Type : agreement \n\n   Subjects = 60 \n     Raters = 2 \n   ICC(A,1) = 0.418\n\n F-Test, H0: r0 = 0 ; H1: r0 > 0 \n   F(59,59) = 18.3 , p = 8.19e-23 \n\n 95%-Confidence Interval for ICC Population Values:\n  -0.039 < ICC < 0.778\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npearson = stats.pearsonr(inter[\"R1\"], inter[\"R2\"])\npearson_ci = pearson.confidence_interval()\nprint(round(pearson.statistic, 3), round(float(pearson_ci.low), 3), round(float(pearson_ci.high), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.896 0.832 0.937\n```\n\n\n:::\n\n```{.python .cell-code}\nshifted = first_session.copy()\nshifted.loc[shifted[\"rater\"] == \"R2\", \"hka_deg\"] += 5\nshifted_wide = shifted.pivot(index=\"knee_id\", columns=\"rater\", values=\"hka_deg\")\nprint(stats.pearsonr(shifted_wide[\"R1\"], shifted_wide[\"R2\"]).statistic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.8964295305654308\n```\n\n\n:::\n\n```{.python .cell-code}\nshifted_icc = pg.intraclass_corr(data=shifted, targets=\"knee_id\", raters=\"rater\", ratings=\"hka_deg\")\nprint(shifted_icc.set_index(\"Type\").loc[\"ICC(A,1)\", [\"ICC\", \"CI95\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nICC          0.417703\nCI95    [-0.04, 0.78]\nName: ICC(A,1), dtype: object\n```\n\n\n:::\n:::\n\n:::\n\nPearson's r is 0.90 (95% CI 0.83 to 0.94) before and after the shift: it can't see a systematic difference. The absolute-agreement ICC drops from 0.89 to 0.42 (95% CI −0.04 to 0.78), because a 5° disagreement on every knee is poor agreement. Report the ICC and the Bland-Altman limits, not r.\n:::\n",
    "supporting": [
      "17-agreement_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}