{
  "hash": "c47a1ce53ad834444deb96c96fefb897",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"4 · Describe one group\"\ndescription: \"Mean and SD, median and IQR, a proportion, and a Kaplan-Meier survival curve, each with a 95% confidence interval.\"\nengine: knitr\ntoc-depth: 2\n---\n\n\n\n<!-- data-checksum: ffc54e2ad996e1e61ad10ca520e4d588 -->\n\nBefore you compare anything, describe it. This page covers the first row of the [decision table](../choose-a-test.qmd): one number (or one curve) that sums up a group of patients, with a 95% confidence interval that says how precisely you know it. Which summary you use depends on the column, the type of data you have. [Page 3](../foundations/03-distributions.qmd) explains how to choose.\n\n::: {.callout-note}\n## 💡 How every section on this page works\nEach section answers one question about the practice cohort. Its first code block loads the packages and the data, so you can jump straight to the section you need. Run that section's blocks in order, top to bottom.\n\nTo keep the code short, the examples use every case, including the 80 patients who had both sides operated on. In a real study, decide how to handle them ([page 3](../foundations/03-distributions.qmd#paired)) and say what you did.\n:::\n\n## Mean and standard deviation {#mean-sd}\n\n**The question:** How old are our patients, and how much do their ages vary?\n\n### When to use it\n\n- The variable is a **measurement** (age, BMI, operative time), not a category.\n- Its distribution is **roughly symmetric**, without extreme outliers. Check with a histogram ([page 3](../foundations/03-distributions.qmd#look)).\n- If it's **skewed**, has a **ceiling or floor**, or is **ordinal** → use the [median and IQR](#median-iqr) instead.\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\n\nggplot(cohort, aes(age)) +\n  geom_histogram(binwidth = 2) +\n  geom_vline(xintercept = mean(cohort$age), linetype = \"dashed\") +   # the mean\n  labs(x = \"Age at surgery, years\", y = \"Patients\")\n```\n\n::: {.cell-output-display}\n![](04-describe-one-group_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom scipy import stats\n\ncohort = pd.read_csv(\"data/cohort.csv\")\n\nfig, ax = plt.subplots(figsize=(6, 3))\nax.hist(cohort[\"age\"], bins=range(40, 90, 2))\nax.axvline(cohort[\"age\"].mean(), linestyle=\"--\")       # the mean\nax.set_xlabel(\"Age at surgery, years\")\nax.set_ylabel(\"Patients\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](04-describe-one-group_files/figure-html/unnamed-chunk-4-1.png)\n:::\n:::\n\n:::\n\nA single, roughly symmetric hump: the mean sits in the middle of it, so it's a fair summary.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_summary <- cohort |>\n  summarise(n = n(), mean = mean(age), sd = sd(age))\nage_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n      n  mean    sd\n  <int> <dbl> <dbl>\n1   600  65.5  9.44\n```\n\n\n:::\n\n```{.r .cell-code}\nage_ci <- t.test(cohort$age)$conf.int   # 95% CI for the mean\nage_ci\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 64.76351 66.27649\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nn = cohort[\"age\"].count()\nmean = cohort[\"age\"].mean()\nsd = cohort[\"age\"].std()                 # pandas divides by n - 1, like R\n\n# 95% CI for the mean: mean ± t × (SD / √n)\nage_ci = stats.t.interval(0.95, df=n - 1, loc=mean, scale=sd / n ** 0.5)\n\nprint(f\"n = {n}, mean = {mean:.2f}, sd = {sd:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn = 600, mean = 65.52, sd = 9.44\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"95% CI {age_ci[0]:.2f} to {age_ci[1]:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI 64.76 to 66.28\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **n = 600:** the number of cases with an age recorded.\n- **Mean = 65.5 years:** the average age.\n- **SD = 9.4 years:** the standard deviation, the typical distance of a patient's age from the mean. In a bell-shaped distribution about 95% of patients lie within 2 SDs of the mean, here roughly 47 to 84 years.\n- **95% CI 64.8 to 66.3:** the confidence interval for the **mean**. It tells you how precisely 600 patients pin down the average age of patients like ours. It says nothing about how spread out individual patients are; that's the SD's job.\n\n::: {.callout-note collapse=\"true\"}\n## 🔍 Under the hood: the CI for a mean\nThe **standard error** of the mean is SD / √n = 9.4 / √600 ≈ 0.39 years. The 95% CI is the mean ± *t* × standard error, where *t* ≈ 1.96 for large samples (it's a little bigger for small ones). Quadruple the sample size and the standard error halves; the SD stays about the same.\n:::\n\n### How to report it\n\n> **Methods:** Continuous variables are reported as mean (standard deviation, SD) when approximately normally distributed.\n>\n> **Results:** The mean age at surgery was 65.5 years (SD 9.4; 95% CI for the mean 64.8 to 66.3).\n\n::: {.callout-warning}\n## ⚠️ Watch out: SD or SEM?\nThe **standard error of the mean (SEM)** is much smaller than the SD (0.39 vs 9.4 years here), which is why some papers report \"mean ± SEM\": it looks tidier. But it describes the precision of the mean, not your patients. Use the **SD** to describe patients and a **95% CI** to show the precision of an estimate. Never report a bare \"±\" without saying which one it is.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: dividing by n or n − 1\nR's `sd()` and pandas' `.std()` divide by n − 1 (the \"sample\" SD), which is what you want. **NumPy's `np.std()` divides by n** unless you write `np.std(x, ddof=1)`. With 600 patients the difference is tiny; with 10 it isn't.\n:::\n\n## Median and interquartile range {#median-iqr}\n\n**The question:** What's a typical KOOS JR score 1 year after knee replacement, and how much do scores vary?\n\n### When to use it\n\n- The variable is **skewed**, has a **ceiling or floor**, has **outliers**, or is **ordinal** (an ordered scale such as satisfaction from 1 to 5).\n- The median is the middle value: half the patients are above it and half below. The **interquartile range (IQR)** runs from the 25th to the 75th percentile (the first and third quartiles), so it holds the middle half of the patients.\n- If the variable is a roughly symmetric measurement → the [mean and SD](#mean-sd) are fine and more familiar.\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nproms <- read_csv(\"data/proms_long.csv\", show_col_types = FALSE)\nkoos_1yr <- proms |>\n  filter(instrument == \"KOOS JR\", visit == \"1yr\", !is.na(prom_score)) |>\n  pull(prom_score)\n\nggplot(tibble(score = koos_1yr), aes(score)) +\n  geom_histogram(binwidth = 2.5) +\n  labs(x = \"KOOS JR at 1 year (100 = best)\", y = \"Patients\")\n```\n\n::: {.cell-output-display}\n![](04-describe-one-group_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom scipy import stats\n\nproms = pd.read_csv(\"data/proms_long.csv\")\nkoos_1yr = proms.loc[(proms[\"instrument\"] == \"KOOS JR\") & (proms[\"visit\"] == \"1yr\"),\n                     \"prom_score\"].dropna()\n\nfig, ax = plt.subplots(figsize=(6, 3))\nax.hist(koos_1yr, bins=np.arange(35, 102.5, 2.5))\nax.set_xlabel(\"KOOS JR at 1 year (100 = best)\")\nax.set_ylabel(\"Patients\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](04-describe-one-group_files/figure-html/unnamed-chunk-10-1.png)\n:::\n:::\n\n:::\n\nScores pile up against the maximum of 100 (a **ceiling**), with a long tail of patients who did less well. A mean would be dragged down by that tail; the median isn't.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(koos_1yr)                                # how many patients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 260\n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(koos_1yr, probs = c(0.25, 0.50, 0.75)) # first quartile, median, third quartile\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   25%    50%    75% \n74.700 85.750 93.925 \n```\n\n\n:::\n\n```{.r .cell-code}\nDescTools::MedianCI(koos_1yr, method = \"exact\") # the median with its 95% CI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmedian lwr.ci upr.ci \n 85.75  84.00  88.20 \nattr(,\"conf.level\")\n[1] 0.959506\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(len(koos_1yr))                                     # how many patients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n260\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(np.quantile(koos_1yr, [0.25, 0.50, 0.75]))         # first quartile, median, third quartile\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[74.7   85.75  93.925]\n```\n\n\n:::\n\n```{.python .cell-code}\n# scipy has no \"median CI\" function, but quantile_test() reports one.\n# Its q argument is the value it would test against; it doesn't change the CI.\nmedian_ci = stats.quantile_test(koos_1yr, q=koos_1yr.median(), p=0.5).confidence_interval()\nprint(median_ci)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfidenceInterval(low=np.float64(84.0), high=np.float64(88.2))\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **n = 260:** TKA patients with a 1-year KOOS JR score.\n- **Median = 85.8:** half the patients scored above 85.8, half below.\n- **IQR 74.7 to 93.9:** the middle half of patients scored between these two values. A quarter scored below 74.7.\n- **95% CI for the median 84.0 to 88.2:** how precisely 260 patients pin down the median.\n\n::: {.callout-note collapse=\"true\"}\n## 🔍 Under the hood: where the median's CI comes from\nThe CI for a median uses no formula with an SD in it. It counts instead. Sort the scores, then pick two positions such that, if the study were repeated many times, the true median would fall between the scores at those positions at least 95% of the time. The binomial distribution says which positions those are, and the CI is the pair of scores sitting there. Because positions are whole numbers, the actual confidence is a little over 95% (R reports 0.9595 here). This \"exact\" method needs no assumption about the shape of the data.\n:::\n\n### How to report it\n\n> **Methods:** Continuous variables that were skewed or bounded are reported as median (interquartile range, IQR).\n>\n> **Results:** The median 1-year KOOS JR was 85.8 points (IQR 74.7 to 93.9; 95% CI for the median 84.0 to 88.2).\n\n::: {.callout-warning}\n## ⚠️ Watch out: report the IQR as two numbers\nWrite \"IQR 74.7 to 93.9\", not \"IQR 19.2\" (the width). Readers want to know where the middle half of patients sits, not just how wide it is. And don't report a median with an SD: they belong to different summaries.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: quartiles\nR's `quantile()` and NumPy's `np.quantile()` use the same default method (R calls it \"type 7\"), so they agree. Other software doesn't always: gtsummary, SPSS and SAS can give slightly different quartiles on the same data ([page 2](../foundations/02-demographics.qmd#which-summary) shows an example). Say which software you used.\n:::\n\n## Proportion {#proportion}\n\n**The question:** What proportion of procedures were followed by a complication within 90 days?\n\n### When to use it\n\n- The outcome is **yes/no** (binomial): complication, readmission, discharge home.\n- Report the count, the percentage, and a 95% CI for the percentage.\n- If patients were followed for **different lengths of time** and the event can happen at any time (revision, death) → use a [Kaplan-Meier curve](#kaplan-meier) instead.\n\n### Look at the data first\n\nFor a yes/no variable, \"looking\" means counting, including the missing values.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\n\ncount(cohort, complication_90d)   # 1 = yes, 0 = no\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  complication_90d     n\n             <dbl> <int>\n1                0   549\n2                1    51\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nfrom scipy import stats\n\ncohort = pd.read_csv(\"data/cohort.csv\")\n\nprint(cohort[\"complication_90d\"].value_counts(dropna=False))   # 1 = yes, 0 = no\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncomplication_90d\n0    549\n1     51\nName: count, dtype: int64\n```\n\n\n:::\n:::\n\n:::\n\nNo missing values, and only the two codes the codebook allows (0 and 1).\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nevents   <- sum(cohort$complication_90d == 1)\npatients <- nrow(cohort)\n\nevents / patients                                           # the proportion\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.085\n```\n\n\n:::\n\n```{.r .cell-code}\n# Wilson 95% CI: prop.test() without the continuity correction\nprop.test(events, patients, correct = FALSE)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0652403 0.1100399\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nevents = int((cohort[\"complication_90d\"] == 1).sum())\npatients = len(cohort)\n\nprint(events / patients)                                    # the proportion\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.085\n```\n\n\n:::\n\n```{.python .cell-code}\n# Wilson 95% CI\nprint(stats.binomtest(events, patients).proportion_ci(method=\"wilson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfidenceInterval(low=np.float64(0.06524029664442159), high=np.float64(0.11003991519695004))\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **51 of 600 = 0.085:** a complication followed 8.5% of procedures.\n- **95% CI 0.065 to 0.110:** the true complication rate for patients like ours is plausibly anywhere from 6.5% to 11.0%.\n\n### How to report it\n\n> **Methods:** Categorical variables are reported as number (percentage). 95% confidence intervals for proportions were calculated with the Wilson score method.\n>\n> **Results:** A complication within 90 days followed 51 of 600 procedures (8.5%; 95% CI 6.5% to 11.0%).\n\n::: {.callout-warning}\n## ⚠️ Watch out: percent of what?\n- **Say what the denominator is.** Here it's 600 *procedures*. Our 80 bilateral patients count twice, so it isn't a percentage of patients. If some outcomes were missing, the denominator is the patients with a known outcome; say how many were missing.\n- **Don't use the simple \"± 1.96 standard errors\" CI** (the Wald interval) for proportions. For rare events it can dip below 0%. The Wilson interval doesn't.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: which CI for a proportion?\nR's `prop.test()` gives the Wilson interval, but adds a continuity correction unless you set `correct = FALSE`. scipy's `proportion_ci()` calls the uncorrected version `\"wilson\"` and the corrected one `\"wilsoncc\"`. R's `binom.test()` and scipy's `method=\"exact\"` give the more conservative Clopper-Pearson interval ([page 5](05-one-group-vs-hypothetical.qmd#binomial-test) uses it). All are acceptable; say which you used.\n:::\n\n## Kaplan-Meier survival curve {#kaplan-meier}\n\n**The question:** What proportion of implants are still unrevised 5 years after surgery?\n\n### When to use it\n\n- The outcome is **time until an event** (revision, death), and patients were followed for **different lengths of time**.\n- Some patients are **censored**: their follow-up ended (the study closed, they moved away, they died) before any revision. We know they went *at least* that long without one.\n- A plain percentage (\"13.5% were revised\") ignores follow-up time: a patient operated on last year hasn't had time to need a revision. The Kaplan-Meier method uses each patient's follow-up for as long as it lasts.\n\n[Page 13](../survival/13-kaplan-meier.qmd) covers survival analysis in depth. This section shows the basic curve.\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(survival)\nlibrary(ggsurvfit)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\n\n# followup_years: time from surgery to revision or censoring; revised: 1 = revised, 0 = censored\ncohort |> select(case_id, followup_years, revised) |> head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  case_id followup_years revised\n  <chr>            <dbl>   <dbl>\n1 C0001             6.23       0\n2 C0002             3.27       0\n3 C0003            11.0        0\n4 C0004            10.9        0\n5 C0005             5.79       1\n```\n\n\n:::\n\n```{.r .cell-code}\ncohort |> summarise(patients = n(), revisions = sum(revised),\n                    median_followup = median(followup_years))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  patients revisions median_followup\n     <int>     <dbl>           <dbl>\n1      600        81            4.36\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom lifelines import KaplanMeierFitter\nfrom lifelines.plotting import add_at_risk_counts\n\ncohort = pd.read_csv(\"data/cohort.csv\")\n\n# followup_years: time from surgery to revision or censoring; revised: 1 = revised, 0 = censored\nprint(cohort[[\"case_id\", \"followup_years\", \"revised\"]].head(5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  case_id  followup_years  revised\n0   C0001            6.23        0\n1   C0002            3.27        0\n2   C0003           10.96        0\n3   C0004           10.94        0\n4   C0005            5.79        1\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(len(cohort), cohort[\"revised\"].sum(), cohort[\"followup_years\"].median())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n600 81 4.365\n```\n\n\n:::\n:::\n\n:::\n\nEach row needs exactly two things: **how long** the patient was followed and **whether** the follow-up ended with the event (1) or was censored (0). The first case was followed for 6.2 years without a revision; the fifth was revised at 5.8 years.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkm <- survfit2(Surv(followup_years, revised) ~ 1, data = cohort,\n               conf.type = \"log-log\")              # the CI method lifelines uses\n\nkm |>\n  ggsurvfit() +\n  add_confidence_interval() +\n  add_risktable() +\n  scale_ggsurvfit() +\n  labs(x = \"Years since surgery\", y = \"Revision-free survival\")\n```\n\n::: {.cell-output-display}\n![](04-describe-one-group_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n\n```{.r .cell-code}\nsummary(km, times = 5)                             # the estimate at 5 years\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(followup_years, revised) ~ 1, data = cohort, \n    conf.type = \"log-log\")\n\n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    5    263      66    0.863  0.0162        0.828        0.892\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nkm = KaplanMeierFitter()\nkm.fit(cohort[\"followup_years\"], event_observed=cohort[\"revised\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<lifelines.KaplanMeierFitter:\"KM_estimate\", fitted with 600 total observations, 519 right-censored observations>\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, ax = plt.subplots(figsize=(7, 4.5))\nkm.plot_survival_function(ax=ax, legend=False)\nax.set_xlabel(\"Years since surgery\")\nax.set_ylabel(\"Revision-free survival\")\nadd_at_risk_counts(km, ax=ax)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](04-describe-one-group_files/figure-html/unnamed-chunk-24-1.png)\n:::\n\n```{.python .cell-code}\n# the estimate and its 95% CI at 5 years\nat_5 = km.survival_function_at_times(5).iloc[0]\nci_5 = km.confidence_interval_survival_function_.loc[:5].iloc[-1]   # last step at or before 5 years\nprint(at_5, ci_5.to_list())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.8630934920484908 [0.8278279294142131, 0.891611047941076]\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **The curve** starts at 100% and steps down at each revision. Censored patients don't make it step; they just leave the group \"at risk\".\n- **The shaded band** is the 95% CI. It widens to the right as fewer patients remain under follow-up.\n- **The numbers at risk** under the plot show how many patients were still being followed at each time. Trust the right-hand end of the curve less: by 10 years only a handful remain.\n- **At 5 years:** survival 0.863 (95% CI 0.828 to 0.892), with 263 patients still at risk.\n\n### How to report it\n\n> **Methods:** Implant survivorship was estimated with the Kaplan-Meier method, with revision for any reason as the end point. Patients were censored at death or at their last follow-up.\n>\n> **Results:** Revision-free survival at 5 years was 86.3% (95% CI 82.8% to 89.2%; 263 patients at risk).\n\n::: {.callout-warning}\n## ⚠️ Watch out: death isn't just \"lost to follow-up\"\nTreating deaths as censored, as here, assumes the patients who died would have gone on to be revised at the same rate as everyone else. They can't be: a patient who has died can never be revised. When many patients die during follow-up, 1 minus the Kaplan-Meier estimate **overstates** the risk of revision. [Page 13](../survival/13-kaplan-meier.qmd#competing-risks) shows the competing-risks method that fixes this.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: the confidence band\nR's `survfit()` uses a \"log\" CI by default; lifelines uses \"log-log\". The estimates are identical but the CIs differ slightly. We set `conf.type = \"log-log\"` in R so the two match. Log-log keeps the CI between 0% and 100%; say which you used.\n:::\n\n\n\n## Exercises {#exercises}\n\nThe solutions use the packages and data loaded in the sections above, so run the page from the top first.\n\n**1.** Describe **BMI** in the cohort with a mean, SD and 95% CI for the mean. Check the histogram first: is the mean a fair summary?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(cohort, aes(bmi)) + geom_histogram(binwidth = 1)\n```\n\n::: {.cell-output-display}\n![](04-describe-one-group_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncohort |> summarise(n = n(), mean = mean(bmi), sd = sd(bmi))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n      n  mean    sd\n  <int> <dbl> <dbl>\n1   600  30.4  5.43\n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(cohort$bmi)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 30.00875 30.87925\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, ax = plt.subplots(figsize=(6, 3))\nax.hist(cohort[\"bmi\"], bins=range(18, 46))\nplt.show()\n```\n\n::: {.cell-output-display}\n![](04-describe-one-group_files/figure-html/unnamed-chunk-29-1.png)\n:::\n\n```{.python .cell-code}\nn, mean, sd = cohort[\"bmi\"].count(), cohort[\"bmi\"].mean(), cohort[\"bmi\"].std()\nprint(n, mean, sd, stats.t.interval(0.95, df=n - 1, loc=mean, scale=sd / n ** 0.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n600 30.444000000000003 5.428579906353605 (np.float64(30.008751672242138), np.float64(30.879248327757868))\n```\n\n\n:::\n:::\n\n:::\n\nThe histogram is roughly symmetric, so the mean is a fair summary.\n\n> **Results:** Mean BMI was 30.4 kg/m² (SD 5.4; 95% CI for the mean 30.0 to 30.9).\n:::\n\n**2.** A resident wants to summarize **length of stay** in a Table 1 as \"0.9 ± 1.1 days\". What would you suggest instead, and why? Compute it.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nLength of stay is strongly right-skewed (most patients go home on day 0 or 1, a few stay 4 to 6 days), so report the median (IQR). \"±\" is also ambiguous: SD or SEM?\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(cohort$los_days, probs = c(0.25, 0.50, 0.75))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n25% 50% 75% \n  0   1   1 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nprint(np.quantile(cohort[\"los_days\"], [0.25, 0.50, 0.75]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[0. 1. 1.]\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** The median length of stay was 1 day (IQR 0 to 1).\n:::\n\n**3.** Twenty-seven of the 600 procedures were followed by a readmission within 90 days. Write the Results sentence, with a Wilson 95% CI.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(27, 600, correct = FALSE)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03110849 0.06468066\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(stats.binomtest(27, 600).proportion_ci(method=\"wilson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfidenceInterval(low=np.float64(0.031108488667728345), high=np.float64(0.0646806592547393))\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Readmission within 90 days followed 27 of 600 procedures (4.5%; 95% CI 3.1% to 6.5%).\n:::\n",
    "supporting": [
      "04-describe-one-group_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}