{
  "hash": "ab74688b56e4012642123d2ab5793513",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"10 · Quantify association between two variables\"\ndescription: \"Pearson correlation, Spearman correlation and contingency coefficients: how strongly two things go together.\"\nengine: knitr\ntoc-depth: 2\n---\n\n\n\n<!-- data-checksum: 9e548efb7ad4232927ffa99aa2cdeca7 -->\n\nTwo things measured on the same patients: BMI and operative time, PROM improvement and satisfaction, ASA class and hypertension. The tests on this page don't compare groups. They put **one number on how strongly the two go together**, with a 95% CI. If you want to **predict** one from the other, use regression ([page 11](11-predict-from-one.qmd)).\n\n::: {.callout-note}\n## 💡 How every section on this page works\nEach section answers one question about the practice cohort. Its first code block loads the packages and the data, so you can jump straight to the section you need. Run that section's blocks in order, top to bottom.\n\nTo keep the code short, the examples use every case, including the 80 patients who had both sides operated on. In a real study, decide how to handle them ([page 3](../foundations/03-distributions.qmd#paired)) and say what you did.\n:::\n\n## Pearson correlation {#pearson}\n\n**The question:** How closely does operative time track BMI?\n\n### When to use it\n\n- Two **measurements** on the same patients, and you want one number for how closely they move together along a **straight line**.\n- Both are roughly normal, without extreme outliers, and the scatter plot looks like a cloud stretched along a line.\n- If either is skewed or ordinal, has outliers, or the points follow a curve → [Spearman correlation](#spearman).\n- If you want to predict one from the other, or adjust for other variables → [linear regression](11-predict-from-one.qmd#linear-regression).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\n\nggplot(cohort, aes(bmi, op_time_min)) +\n  geom_point(alpha = 0.4) +   # see-through points show where they pile up\n  labs(x = \"BMI, kg/m²\", y = \"Operative time, minutes\")\n```\n\n::: {.cell-output-display}\n![](10-association_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom scipy import stats\n\ncohort = pd.read_csv(\"data/cohort.csv\")\n\nfig, ax = plt.subplots(figsize=(6, 3.5))\nax.scatter(cohort[\"bmi\"], cohort[\"op_time_min\"], alpha=0.4)   # see-through points show where they pile up\nax.set_xlabel(\"BMI, kg/m²\")\nax.set_ylabel(\"Operative time, minutes\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](10-association_files/figure-html/unnamed-chunk-4-1.png)\n:::\n:::\n\n:::\n\nThe points drift upward from left to right, along a rough line, with no extreme outliers.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmi_corr <- cor.test(cohort$bmi, cohort$op_time_min)   # Pearson is the default\nbmi_corr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  cohort$bmi and cohort$op_time_min\nt = 12.385, df = 598, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.3857355 0.5133091\nsample estimates:\n      cor \n0.4518292 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nbmi_corr = stats.pearsonr(cohort[\"bmi\"], cohort[\"op_time_min\"])\nprint(bmi_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPearsonRResult(statistic=np.float64(0.45182923461553826), pvalue=np.float64(1.600468008421371e-31))\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(bmi_corr.confidence_interval(confidence_level=0.95))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfidenceInterval(low=np.float64(0.3857355205072664), high=np.float64(0.5133090740097993))\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **cor** (R) or **statistic** (Python): Pearson's **r = 0.45**. It runs from −1 (a perfect falling line) through 0 (no straight-line relationship) to +1 (a perfect rising line).\n- **t = 12.4, df = 598:** the test statistic, with 600 procedures minus two degrees of freedom. Python doesn't print it.\n- **p < 0.001** (R prints `< 2.2e-16`): a correlation this strong would be very unlikely if BMI and operative time were unrelated.\n- **95% CI 0.39 to 0.51.**\n\n### Effect size and 95% CI\n\n**r is the effect size**: r = 0.45 (95% CI 0.39 to 0.51). As a rough guide, 0.1 is small, 0.3 medium and 0.5 large. Squaring it gives the share of the variation in operative time that goes with BMI: r² = 0.20, about a fifth.\n\n### How to report it\n\n> **Methods:** The association between BMI and operative time was measured with Pearson's correlation coefficient (r).\n>\n> **Results:** The correlation between BMI and operative time was r = 0.45 (Pearson; 95% CI 0.39 to 0.51; p < 0.001; n = 600 procedures).\n\n::: {.callout-warning}\n## ⚠️ Watch out: r only sees straight lines, and isn't cause\nA relationship that rises and then falls can have r close to 0, and one outlier can create or hide a correlation, so always look at the scatter plot first. And a correlation doesn't say which causes which, or whether something else (procedure type, surgeon) drives both. To adjust for other variables, use [multiple regression](12-predict-from-several.qmd#multiple-linear-regression).\n:::\n\n## Spearman correlation {#spearman}\n\n**The question:** Are patients whose HOOS JR or KOOS JR improved more from before surgery to 1 year also more satisfied?\n\n### When to use it\n\n- Two variables on the same patients, at least one of them **ordinal** (satisfaction from 1 to 5), **skewed**, or with **outliers**.\n- The relationship goes one way (always up, or always down) but needn't be a straight line. Spearman's ρ (rho) is Pearson's r calculated on the **ranks**.\n- If both are roughly normal and the relationship is a straight line → [Pearson correlation](#pearson).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\nproms <- read_csv(\"data/proms_long.csv\", show_col_types = FALSE)\n\nchange <- proms |>\n  filter(visit %in% c(\"preop\", \"1yr\")) |>\n  select(case_id, visit, prom_score) |>\n  pivot_wider(names_from = visit, values_from = prom_score) |>   # one row per case: preop and 1yr side by side\n  mutate(improvement = `1yr` - preop) |>\n  inner_join(select(cohort, case_id, satisfaction_1yr), by = \"case_id\") |>\n  filter(!is.na(improvement), !is.na(satisfaction_1yr))          # both answers needed\n\nggplot(change, aes(factor(satisfaction_1yr), improvement)) +\n  geom_boxplot() +\n  labs(x = \"Satisfaction at 1 year (1 = very dissatisfied, 5 = very satisfied)\", y = \"Improvement, points\")\n```\n\n::: {.cell-output-display}\n![](10-association_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\nchange |>\n  group_by(satisfaction_1yr) |>\n  summarise(n = n(), median_improvement = median(improvement))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  satisfaction_1yr     n median_improvement\n             <dbl> <int>              <dbl>\n1                1    14               25.4\n2                2    18               29.1\n3                3    43               33.8\n4                4   131               35  \n5                5   198               43.8\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom scipy import stats\n\ncohort = pd.read_csv(\"data/cohort.csv\")\nproms = pd.read_csv(\"data/proms_long.csv\")\n\nwide = proms[proms[\"visit\"].isin([\"preop\", \"1yr\"])].pivot(index=\"case_id\", columns=\"visit\", values=\"prom_score\")\nwide[\"improvement\"] = wide[\"1yr\"] - wide[\"preop\"]   # one row per case: preop and 1yr side by side\nchange = wide.join(cohort.set_index(\"case_id\")[\"satisfaction_1yr\"]).dropna(subset=[\"improvement\", \"satisfaction_1yr\"])\n\nlevels = [1, 2, 3, 4, 5]\nfig, ax = plt.subplots(figsize=(6, 3))\nparts = ax.boxplot([change.loc[change[\"satisfaction_1yr\"] == level, \"improvement\"] for level in levels], tick_labels=levels)\nax.set_xlabel(\"Satisfaction at 1 year (1 = very dissatisfied, 5 = very satisfied)\")\nax.set_ylabel(\"Improvement, points\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](10-association_files/figure-html/unnamed-chunk-10-1.png)\n:::\n\n```{.python .cell-code}\nprint(change.groupby(\"satisfaction_1yr\")[\"improvement\"].agg([\"count\", \"median\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  count  median\nsatisfaction_1yr               \n1.0                  14   25.35\n2.0                  18   29.10\n3.0                  43   33.80\n4.0                 131   35.00\n5.0                 198   43.75\n```\n\n\n:::\n:::\n\n:::\n\n404 procedures have both a pre-op and a 1-year score and a satisfaction answer. The median improvement climbs with each satisfaction level, from 25.4 points among the 14 very dissatisfied to 43.8 among the 198 very satisfied. Satisfaction has only five values, so there are many ties.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsatisfaction_corr <- cor.test(change$improvement, change$satisfaction_1yr,\n                              method = \"spearman\", exact = FALSE)   # ties: no exact p-value\nsatisfaction_corr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  change$improvement and change$satisfaction_1yr\nS = 6764534, p-value = 1.111e-15\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n      rho \n0.3844721 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nsatisfaction_corr = stats.spearmanr(change[\"improvement\"], change[\"satisfaction_1yr\"])\nprint(satisfaction_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSignificanceResult(statistic=np.float64(0.3844721170232049), pvalue=np.float64(1.1107631277074974e-15))\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **rho** (R) or **statistic** (Python): **ρ = 0.38**. Like r, it runs from −1 to +1; here it says patients with larger improvements tend to give higher satisfaction scores.\n- **S = 6764534** (R only): the test statistic, built from the differences between the two rankings. You don't need to report it.\n- **p < 0.001** (R prints `1.111e-15`): a correlation this strong would be very unlikely if improvement and satisfaction were unrelated.\n\n### Effect size and 95% CI\n\n**ρ is the effect size.** Neither `cor.test()` nor scipy gives its 95% CI, so R uses DescTools and Python uses the formula behind it (Fisher's z transformation).\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDescTools::SpearmanRho(change$improvement, change$satisfaction_1yr, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      rho    lwr.ci    upr.ci \n0.3844721 0.2980891 0.4646088 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nrho, n = satisfaction_corr.statistic, len(change)\nz = np.arctanh(rho)                                 # Fisher's z: makes the CI symmetric\nhalf_width = stats.norm.ppf(0.975) / np.sqrt(n - 3)\nprint(rho, np.tanh(z - half_width), np.tanh(z + half_width))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.3844721170232049 0.29808911349981776 0.4646088227466071\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nρ = 0.38 (95% CI 0.30 to 0.46): a moderate association, using the same rough guide as for r.\n\n### How to report it\n\n> **Methods:** The association between improvement in HOOS JR or KOOS JR from before surgery to 1 year and satisfaction at 1 year was measured with Spearman's rank correlation coefficient (ρ).\n>\n> **Results:** Among 404 procedures with both scores and a satisfaction answer, the correlation between the change in HOOS JR or KOOS JR and satisfaction was ρ = 0.38 (Spearman; 95% CI 0.30 to 0.46; p < 0.001).\n\n::: {.callout-warning}\n## ⚠️ Watch out: two instruments in one number\nHip patients answer HOOS JR and knee patients KOOS JR. Both run from 0 to 100, but a point on one isn't guaranteed to mean the same as a point on the other. Pooling them is fine for a first look; in a paper, analyze hips and knees separately or say why you pooled them.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: ties and the CI\n- With fewer than 1290 patients, R's `cor.test()` tries an **exact** p-value. With ties it can't compute one, so it warns and falls back to the usual approximation, the one scipy always uses. `exact = FALSE` asks for the approximation directly, without the warning.\n- Neither gives a CI for ρ. DescTools' `SpearmanRho()` and the Python formula use the same method: Fisher's z with a standard error of 1/√(n − 3).\n:::\n\n## Contingency coefficients {#contingency-coefficients}\n\n**The question:** How strongly is ASA class linked with hypertension?\n\n### When to use it\n\n- Two **categorical** variables on the same patients. The chi-square test ([page 8](08-three-plus-unmatched.qmd#chi-square)) asks whether they're linked at all; a contingency coefficient says **how strongly**.\n- **Phi (φ)** is for 2 × 2 tables. **Cramér's V** works for any table size and equals φ (without its sign) on a 2 × 2 table. Both run from 0 (no link) to 1 (each category of one predicts the other exactly).\n- **Pearson's contingency coefficient (C)** is older. Its maximum is below 1 and depends on the table's size (0.71 for a table with two columns), which makes it hard to read, so prefer V.\n- The chi-square p-value needs every **expected** count to be at least 5.\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\n\nasa_hypertension <- table(asa = cohort$asa, hypertension = cohort$hypertension)   # 1 = hypertension\nasa_hypertension\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   hypertension\nasa   0   1\n  1  24  12\n  2 145 155\n  3  90 156\n  4   2  16\n```\n\n\n:::\n\n```{.r .cell-code}\nround(100 * prop.table(asa_hypertension, margin = 1), 1)   # row percentages\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   hypertension\nasa    0    1\n  1 66.7 33.3\n  2 48.3 51.7\n  3 36.6 63.4\n  4 11.1 88.9\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nfrom scipy import stats\n\ncohort = pd.read_csv(\"data/cohort.csv\")\n\nasa_hypertension = pd.crosstab(cohort[\"asa\"], cohort[\"hypertension\"])   # 1 = hypertension\nprint(asa_hypertension)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nhypertension    0    1\nasa                   \n1              24   12\n2             145  155\n3              90  156\n4               2   16\n```\n\n\n:::\n\n```{.python .cell-code}\nprint((100 * pd.crosstab(cohort[\"asa\"], cohort[\"hypertension\"], normalize=\"index\")).round(1))   # row percentages\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nhypertension     0     1\nasa                     \n1             66.7  33.3\n2             48.3  51.7\n3             36.6  63.4\n4             11.1  88.9\n```\n\n\n:::\n:::\n\n:::\n\nHypertension becomes more common with each ASA class: from 12 of 36 (33.3%) in ASA 1 to 16 of 18 (88.9%) in ASA 4.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nasa_test <- chisq.test(asa_hypertension)\nasa_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  asa_hypertension\nX-squared = 23.181, df = 3, p-value = 3.702e-05\n```\n\n\n:::\n\n```{.r .cell-code}\nmin(asa_test$expected)   # smallest expected count\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.83\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nasa_test = stats.chi2_contingency(asa_hypertension)\nprint(asa_test.statistic, asa_test.dof, asa_test.pvalue)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n23.181303321526755 3 3.701714266100449e-05\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(asa_test.expected_freq.min())   # smallest expected count\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n7.83\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **X-squared = 23.18:** the chi-square statistic. **df = 3:** (4 ASA classes − 1) × (2 columns − 1).\n- **p < 0.001** (R prints `3.702e-05`): a link this strong would be very unlikely if hypertension were equally common in every ASA class.\n- **Smallest expected count 7.83** (ASA 4 without hypertension): every expected count is at least 5, so the p-value is reliable.\n\n### Effect size and 95% CI\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffectsize::cramers_v(asa_hypertension, adjust = FALSE)   # see the R vs Python box\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCramer's V |       95% CI\n-------------------------\n0.20       | [0.12, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::pearsons_c(asa_hypertension)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPearson's C |       95% CI\n--------------------------\n0.19        | [0.12, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(stats.contingency.association(asa_hypertension, method=\"cramer\"))    # Cramér's V\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.19655916548428345\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(stats.contingency.association(asa_hypertension, method=\"pearson\"))   # Pearson's C\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.19286868402903107\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n**Cramér's V = 0.20**, a small-to-medium association (as a rough guide for tables with two rows or columns, 0.1 is small, 0.3 medium and 0.5 large). R also prints a one-sided 95% CI (0.12 to 1.00): V can't be negative, so only its lower bound is informative. scipy doesn't compute this CI. Pearson's C is 0.19 here, but its ceiling for this table is 0.71, not 1, so the same number means more than it seems: one more reason to report V.\n\n### How to report it\n\n> **Methods:** The association between ASA class and hypertension was tested with the chi-square test, with Cramér's V as the effect size.\n>\n> **Results:** Hypertension was present in 12 of 36 procedures (33.3%) in ASA 1 and 16 of 18 (88.9%) in ASA 4 (χ² = 23.2, df = 3, p < 0.001; Cramér's V = 0.20, one-sided 95% CI 0.12 to 1.00).\n\n::: {.callout-warning}\n## ⚠️ Watch out: V gives the strength, not the pattern\nShuffling the rows of the table doesn't change V, so V can't say that hypertension rises **steadily** with ASA class. The row percentages show the pattern; put them in your Results. If the categories are ordered and you expect a trend, a test for trend can be more powerful than the plain chi-square test.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: Cramér's V has two versions\neffectsize's `cramers_v()` and `phi()` apply a small-sample bias correction by default (here V = 0.18), while scipy's `association()` doesn't. `adjust = FALSE` turns it off so the two match; whichever you use, say which in your Methods. On a 2 × 2 table, `association(method=\"cramer\")` gives φ without its sign.\n:::\n\n\n\n## Exercises {#exercises}\n\nThe solutions use the packages and data loaded in the sections above, so run the page from the top first.\n\n**1.** How strongly is operative time linked with **age**? Report Pearson's r with its 95% CI.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(cohort$age, cohort$op_time_min)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  cohort$age and cohort$op_time_min\nt = 3.4542, df = 598, p-value = 0.0005911\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.06049575 0.21747258\nsample estimates:\n      cor \n0.1398629 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nage_corr = stats.pearsonr(cohort[\"age\"], cohort[\"op_time_min\"])\nprint(age_corr, age_corr.confidence_interval(confidence_level=0.95))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPearsonRResult(statistic=np.float64(0.13986286334794956), pvalue=np.float64(0.000591061227095167)) ConfidenceInterval(low=np.float64(0.06049575269507875), high=np.float64(0.21747258144105114))\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** The correlation between age and operative time was r = 0.14 (Pearson; 95% CI 0.06 to 0.22; p < 0.001).\n\nThe association is clear but weak: age goes with about 2% of the variation in operative time (r² = 0.02), against 20% for BMI.\n:::\n\n**2.** A colleague asks whether older patients stay in hospital longer. Which correlation would you use, and what do you find?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nLength of stay is strongly right-skewed with many ties ([page 3](../foundations/03-distributions.qmd#transform)): **Spearman correlation**.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(cohort$los_days, cohort$age, method = \"spearman\", exact = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  cohort$los_days and cohort$age\nS = 30777868, p-value = 0.0003644\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n      rho \n0.1450568 \n```\n\n\n:::\n\n```{.r .cell-code}\nDescTools::SpearmanRho(cohort$los_days, cohort$age, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       rho     lwr.ci     upr.ci \n0.14505684 0.06577619 0.22251757 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nlos_corr = stats.spearmanr(cohort[\"los_days\"], cohort[\"age\"])\nz, half_width = np.arctanh(los_corr.statistic), stats.norm.ppf(0.975) / np.sqrt(len(cohort) - 3)\nprint(los_corr, np.tanh(z - half_width), np.tanh(z + half_width))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSignificanceResult(statistic=np.float64(0.14505684292632762), pvalue=np.float64(0.0003643931688756085)) 0.0657761944392072 0.22251756976389372\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** The correlation between age and length of stay was ρ = 0.15 (Spearman; 95% CI 0.07 to 0.22; p < 0.001).\n\nOlder patients tended to stay slightly longer, but the association is weak.\n:::\n\n**3.** Is sleep apnea more common in men than in women, and how strongly is it linked with sex? Write the Results sentence with φ.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\napnea <- table(sex = cohort$sex, sleep_apnea = cohort$sleep_apnea)\napnea\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        sleep_apnea\nsex        0   1\n  Female 300  43\n  Male   188  69\n```\n\n\n:::\n\n```{.r .cell-code}\nchisq.test(apnea, correct = FALSE)   # no continuity correction, to match phi\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  apnea\nX-squared = 19.821, df = 1, p-value = 8.504e-06\n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::phi(apnea, adjust = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPhi  |       95% CI\n-------------------\n0.18 | [0.11, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\napnea = pd.crosstab(cohort[\"sex\"], cohort[\"sleep_apnea\"])\nprint(apnea)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsleep_apnea    0   1\nsex                 \nFemale       300  43\nMale         188  69\n```\n\n\n:::\n\n```{.python .cell-code}\napnea_test = stats.chi2_contingency(apnea, correction=False)\nprint(apnea_test.statistic, apnea_test.dof, apnea_test.pvalue)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n19.82118079959507 1 8.50351511285585e-06\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(stats.contingency.association(apnea, method=\"cramer\"))   # phi without its sign, on a 2 × 2 table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.18175615899511754\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Sleep apnea was present in 69 of 257 men (26.8%) and 43 of 343 women (12.5%) (χ² = 19.8, df = 1, p < 0.001; φ = 0.18, one-sided 95% CI 0.11 to 1.00).\n:::\n",
    "supporting": [
      "10-association_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}