{
  "hash": "89c3a078d0f3cacd5f539c28e47d6ce6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"16 · Mixed models for repeated PROMs\"\ndescription: \"PROMs at several visits, including patients who missed some: random intercepts, time as categories or a curve, group × time, and estimated marginal means.\"\nengine: knitr\n---\n\n\n\n<!-- data-checksum: 7318dedd9cebb731bf62c12faf3ff8ee -->\n\nPROMs are collected at several visits, and patients miss some of them. [Page 9](../catalog/09-three-plus-matched.qmd#repeated-measures-anova) analyzed repeated scores with repeated-measures ANOVA, which only uses patients measured at every visit. A **linear mixed model** uses every score from every patient, and answers the questions a PROM study usually asks: how much do patients improve, by when, and does recovery differ between groups?\n\nThe examples use KOOS JR, the knee score, in the 330 total knee replacements. Hips answer a different questionnaire (HOOS JR), and a point on one isn't guaranteed to equal a point on the other, so the two aren't mixed in one model.\n\n::: {.callout-note}\n## 💡 How this page works\nRun the code blocks in order, from the top: later blocks use the packages, data and models made earlier.\n\nEach knee is treated as its own patient until the section on [bilateral patients](#bilateral).\n:::\n\n## Why not repeated-measures ANOVA? {#why-mixed-models}\n\nCount how many of the four visits each knee has a score for:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(lmerTest)        # lme4's lmer(), plus p-values for its fixed effects\nlibrary(emmeans)         # estimated marginal means\nlibrary(splines)         # natural cubic splines, for time as a curve\n\nproms <- read_csv(\"data/proms_long.csv\", show_col_types = FALSE)\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\n\nknees <- proms |>\n  filter(instrument == \"KOOS JR\", !is.na(prom_score)) |>          # every knee score that exists\n  left_join(select(cohort, case_id, sex, age), by = \"case_id\") |>\n  mutate(visit = factor(visit, levels = c(\"preop\", \"6wk\", \"3mo\", \"1yr\")))\n\nknees |>\n  count(case_id, name = \"visits\") |>            # scores per knee\n  count(visits, name = \"knees\")                 # knees with 1, 2, 3 or 4 scores\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  visits knees\n   <int> <int>\n1      1     4\n2      2    28\n3      3   106\n4      4   192\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport patsy\nimport matplotlib.pyplot as plt\nimport statsmodels.formula.api as smf\n\nproms = pd.read_csv(\"data/proms_long.csv\")\ncohort = pd.read_csv(\"data/cohort.csv\")\n\nknees = proms[(proms[\"instrument\"] == \"KOOS JR\") & proms[\"prom_score\"].notna()]    # every knee score that exists\nknees = knees.merge(cohort[[\"case_id\", \"sex\", \"age\"]], on=\"case_id\")\nvisits = [\"preop\", \"6wk\", \"3mo\", \"1yr\"]\nknees[\"visit\"] = pd.Categorical(knees[\"visit\"], categories=visits)               # pre-op first: the reference\n\nprint(knees.groupby(\"case_id\").size().value_counts().sort_index())   # knees with 1, 2, 3 or 4 scores\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1      4\n2     28\n3    106\n4    192\nName: count, dtype: int64\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nAll 330 knees have at least one score, 1146 scores in all, but only 192 knees have all four. Repeated-measures ANOVA would drop the other 138 knees (42%) together with every score they did give. A mixed model keeps all 1146 scores.\n\nDropping patients isn't only wasteful. It can bias the result, and that depends on why scores are missing:\n- **Missing completely at random:** a missed visit has nothing to do with the patient's recovery (the clinic rescheduled, the patient moved). Both methods are unbiased; the mixed model is more precise because it uses more data.\n- **Missing at random:** missing depends on things you measured, such as an earlier score. A patient who scored badly at 6 weeks is less likely to return at 3 months. Repeated-measures ANOVA is then biased, because the patients it keeps recovered better; a mixed model is still unbiased, as long as the model describes how a knee's scores are related, because it uses the earlier scores to fill the picture in.\n- **Missing not at random:** missing depends on the score that wasn't collected (patients stay away *because* their knee is worse that week). Nothing fixes this from the data alone. Say so as a limitation.\n\n## A random intercept for each knee {#random-intercept}\n\nScores from the same knee are related: a knee that starts low tends to stay lower than average. A mixed model handles this with a **random intercept**: each knee gets its own baseline level, shifted up or down from the average. The **fixed effects** (here, the visits) describe the average patient; the random intercepts describe how much knees differ from that average.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknee_model <- lmer(prom_score ~ visit + (1 | case_id), data = knees)   # (1 | case_id): an intercept per knee\nprint(summary(knee_model), correlation = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: prom_score ~ visit + (1 | case_id)\n   Data: knees\n\nREML criterion at convergence: 8673.7\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.94682 -0.58192  0.00759  0.61247  2.36932 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n case_id  (Intercept) 78.10    8.837   \n Residual             73.45    8.570   \nNumber of obs: 1146, groups:  case_id, 330\n\nFixed effects:\n            Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)  49.9946     0.6882 708.3560   72.64   <2e-16 ***\nvisit6wk     12.5402     0.7050 829.7306   17.79   <2e-16 ***\nvisit3mo     24.2186     0.7169 834.1177   33.78   <2e-16 ***\nvisit1yr     33.8988     0.7335 838.0791   46.22   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nknee_model = smf.mixedlm(\"prom_score ~ visit\", knees, groups=\"case_id\").fit(reml=True)   # groups: an intercept per knee\nprint(knee_model.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Mixed Linear Model Regression Results\n========================================================\nModel:            MixedLM Dependent Variable: prom_score\nNo. Observations: 1146    Method:             REML      \nNo. Groups:       330     Scale:              73.4507   \nMin. group size:  1       Log-Likelihood:     -4336.8570\nMax. group size:  4       Converged:          Yes       \nMean group size:  3.5                                   \n--------------------------------------------------------\n              Coef.  Std.Err.   z    P>|z| [0.025 0.975]\n--------------------------------------------------------\nIntercept     49.995    0.688 72.641 0.000 48.646 51.344\nvisit[T.6wk]  12.540    0.705 17.788 0.000 11.158 13.922\nvisit[T.3mo]  24.219    0.717 33.776 0.000 22.813 25.624\nvisit[T.1yr]  33.899    0.734 46.210 0.000 32.461 35.337\ncase_id Var   78.098    1.078                           \n========================================================\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nReading the output:\n- **Fixed effects:** the average KOOS JR was 50.0 before surgery (the intercept), and higher by 12.5 points at 6 weeks, 24.2 at 3 months and 33.9 at 1 year. Each visit's coefficient is its difference from pre-op.\n- **Random effects:** knees' own baseline levels vary around the average with an SD of 8.8 points (R's \"case_id (Intercept)\" row; Python's \"case_id Var\" row gives the variance, 8.84² = 78.1). The scores also vary from visit to visit within a knee with a residual SD of 8.6 points.\n- **How much of the variation is between knees:** 78.1 / (78.1 + 73.5) = 0.52, the intraclass correlation ([page 17](17-agreement.qmd#icc) uses the same idea for raters). About half of the spread in scores comes from knees differing from each other; that's why the scores can't be treated as independent.\n- **REML:** both programs fit the model by restricted maximum likelihood, the standard choice for estimating it.\n\n::: {.callout-tip}\n## 🔀 R vs Python: degrees of freedom\nThe estimates agree. The standard errors agree to three or four significant figures: lme4 computes them with the knee and residual variances held at their estimates, statsmodels from the curvature of the whole likelihood. The p-values and CIs differ a little more. lmerTest gives each fixed effect a t test with **Satterthwaite** degrees of freedom, an approximation to how much information the estimate rests on. statsmodels uses a z test, as if the degrees of freedom were infinite. With 330 knees the difference is in the third decimal place; with a small study, trust R's.\n:::\n\n## Estimated marginal means {#estimated-marginal-means}\n\nReport the model's estimate at each visit, with its 95% CI. These are the **estimated marginal means** (EMMs): the average score the model expects at each visit, using every knee, including those with missed visits.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknee_means <- emmeans(knee_model, ~ visit, lmer.df = \"satterthwaite\")\nknee_means\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n visit emmean    SE  df lower.CL upper.CL\n preop   50.0 0.688 708     48.6     51.3\n 6wk     62.5 0.704 745     61.2     63.9\n 3mo     74.2 0.716 772     72.8     75.6\n 1yr     83.9 0.733 811     82.5     85.3\n\nDegrees-of-freedom method: satterthwaite \nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\n# the planned comparison: 1 year minus pre-op (one comparison, so no adjustment; page 15)\nconfint(contrast(knee_means, method = list(\"1yr - preop\" = c(-1, 0, 0, 1))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast    estimate    SE  df lower.CL upper.CL\n 1yr - preop     33.9 0.734 838     32.5     35.3\n\nDegrees-of-freedom method: satterthwaite \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef marginal_means(model, grid):\n    \"\"\"The model's average score for each row of grid (fixed effects only), with its standard error and 95% CI.\"\"\"\n    X = patsy.build_design_matrices([model.model.data.model_spec], grid, return_type=\"dataframe\")[0]\n    beta = model.fe_params\n    cov = model.cov_params().loc[beta.index, beta.index]\n    means = grid.copy()\n    means[\"emmean\"] = X @ beta\n    means[\"se\"] = np.sqrt(np.diag(X @ cov @ X.T))\n    means[\"lower\"] = means[\"emmean\"] - 1.96 * means[\"se\"]\n    means[\"upper\"] = means[\"emmean\"] + 1.96 * means[\"se\"]\n    return means\n\nvisit_grid = pd.DataFrame({\"visit\": pd.Categorical(visits, categories=visits)})\nknee_means = marginal_means(knee_model, visit_grid)\nprint(knee_means.round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   visit  emmean    se  lower  upper\n0  preop   49.99  0.69  48.65  51.34\n1    6wk   62.53  0.70  61.15  63.92\n2    3mo   74.21  0.72  72.81  75.62\n3    1yr   83.89  0.73  82.46  85.33\n```\n\n\n:::\n\n```{.python .cell-code}\n# the planned comparison: 1 year minus pre-op\nprint(knee_model.fe_params[\"visit[T.1yr]\"], knee_model.conf_int().loc[\"visit[T.1yr]\"].to_list())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n33.898828315446195 [32.461019988411564, 35.336636642480826]\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n- **emmean, lower.CL / upper.CL:** KOOS JR averaged 50.0 (95% CI 48.6 to 51.3) before surgery, 62.5 at 6 weeks, 74.2 at 3 months and 83.9 (95% CI 82.5 to 85.3) at 1 year.\n- **The contrast:** the planned comparison, the improvement from pre-op to 1 year: 33.9 points (95% CI 32.5 to 35.3). Choose such comparisons in advance; comparing every pair of visits would need an adjustment ([page 15](15-post-hoc.qmd#planned-comparisons)).\n\nThe 192 knees with all four scores average 49.2 before surgery and 84.0 at 1 year. That's close to the mixed model, as expected here: in this synthetic cohort, visits were missed almost entirely at random: by chance, or because follow-up had ended. With real patients you can't count on that, and the mixed model's answer, which uses all 330 knees, is the one to report.\n\n## Time: categories or a curve? {#time}\n\nSo far each visit has its own mean: **time as categories**. That fits when everyone is seen at the same few scheduled visits, and it makes no assumption about the shape of recovery. The alternative is **time as a number**, days since surgery, with a curve. That suits many or irregular visits, but the curve's shape must be right. Recovery isn't a straight line, so use a natural cubic spline ([page 12](../catalog/12-predict-from-several.qmd#multiple-nonlinear-regression) explains splines):\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve_model <- lmer(prom_score ~ ns(visit_days, df = 3) + (1 | case_id), data = knees)\n\ndays <- tibble(visit_days = c(-14, 42, 90, 365))           # the scheduled visit days\non_days <- predict(curve_model, newdata = days, re.form = NA)   # re.form = NA: the average knee\non_days\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1        2        3        4 \n50.10003 62.67787 73.98054 84.07408 \n```\n\n\n:::\n\n```{.r .cell-code}\ncurve <- tibble(visit_days = -27:395)\ncurve$prom_score <- predict(curve_model, newdata = curve, re.form = NA)\nggplot(curve, aes(visit_days, prom_score)) +\n  geom_line() +\n  geom_point(data = summary(knee_means) |> mutate(visit_days = c(-14, 42, 90, 365)), aes(y = emmean)) +\n  labs(x = \"Days since surgery\", y = \"KOOS JR\")\n```\n\n::: {.cell-output-display}\n![](16-mixed-models_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nday_knots = list(knees[\"visit_days\"].quantile([1/3, 2/3]))     # the same knots R's ns(df = 3) uses\nday_low, day_high = knees[\"visit_days\"].min(), knees[\"visit_days\"].max()\ncurve_model = smf.mixedlm(\"prom_score ~ cr(visit_days, knots=day_knots, lower_bound=day_low, upper_bound=day_high,\"\n                          \" constraints='center')\", knees, groups=\"case_id\").fit(reml=True)\n\ndays = pd.DataFrame({\"visit_days\": [-14, 42, 90, 365]})        # the scheduled visit days\non_days = curve_model.predict(days)                            # the average knee\nprint(on_days.round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0    50.10\n1    62.68\n2    73.98\n3    84.07\ndtype: float64\n```\n\n\n:::\n\n```{.python .cell-code}\ncurve = pd.DataFrame({\"visit_days\": np.arange(-27, 396)})\nfig, ax = plt.subplots(figsize=(7, 3.5))\nax.plot(curve[\"visit_days\"], curve_model.predict(curve))\nax.scatter(days[\"visit_days\"], knee_means[\"emmean\"])\nax.set_xlabel(\"Days since surgery\")\nax.set_ylabel(\"KOOS JR\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](16-mixed-models_files/figure-html/unnamed-chunk-16-1.png)\n:::\n:::\n\n:::\n\n\n\n\n\nThe curve passes close to the visit means (the points): 62.7 at 6 weeks and 84.1 at 1 year, against 62.5 and 83.9. But look between 3 months and 1 year. No knee was scored there, and the curve invents a peak of about 89 points at around 8 months, then falls. With a few fixed visits, a curve has nothing to follow between them. Categories are simpler, make no such claims, and are what the rest of this page uses.\n\n::: {.callout-warning}\n## ⚠️ Watch out: a straight line for time\n`prom_score ~ visit_days` would force recovery to be a straight line: as steep between 3 months and 1 year as in the first 6 weeks. Always plot the visit means first. If you use time as a number, let it bend.\n:::\n\n## Does recovery differ between groups? {#group-by-time}\n\nTo ask whether men and women recover differently, add sex and its **interaction** with visit. The interaction lets each sex have its own pattern of change. Its test asks whether the patterns differ, which is the question; the main effect of sex alone only compares the average levels.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsex_model <- lmer(prom_score ~ visit * sex + (1 | case_id), data = knees)\nsex_anova <- anova(sex_model)                           # F tests, Satterthwaite degrees of freedom\nsex_anova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nType III Analysis of Variance Table with Satterthwaite's method\n          Sum Sq Mean Sq NumDF  DenDF  F value Pr(>F)    \nvisit     178113   59371     3 831.68 812.3992 <2e-16 ***\nsex           52      52     1 327.09   0.7179 0.3975    \nvisit:sex    458     153     3 831.68   2.0886 0.1002    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsex_means <- emmeans(sex_model, ~ visit | sex, lmer.df = \"satterthwaite\")\nsex_means\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsex = Female:\n visit emmean    SE  df lower.CL upper.CL\n preop   49.6 0.967 696     47.7     51.5\n 6wk     61.2 0.990 733     59.2     63.1\n 3mo     74.7 1.020 788     72.7     76.7\n 1yr     83.4 1.040 808     81.3     85.4\n\nsex = Male:\n visit emmean    SE  df lower.CL upper.CL\n preop   50.4 0.981 710     48.5     52.3\n 6wk     63.9 1.000 746     62.0     65.9\n 3mo     73.8 1.000 746     71.8     75.8\n 1yr     84.4 1.040 802     82.4     86.4\n\nDegrees-of-freedom method: satterthwaite \nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\nemmip(sex_model, sex ~ visit, CIs = TRUE) +            # the two recovery patterns, with 95% CIs\n  labs(x = \"Visit\", y = \"KOOS JR\")\n```\n\n::: {.cell-output-display}\n![](16-mixed-models_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nsex_model = smf.mixedlm(\"prom_score ~ visit * sex\", knees, groups=\"case_id\").fit(reml=True)\n\ninteraction = [name for name in sex_model.fe_params.index if \":\" in name]     # the three visit x sex terms\nsex_wald = sex_model.wald_test(\" = 0, \".join(interaction) + \" = 0\", scalar=True)   # do the patterns differ?\nprint(sex_wald.statistic, sex_wald.pvalue)                                          # chi-square on 3 df, p-value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n6.2636809563597895 0.09946304267009223\n```\n\n\n:::\n\n```{.python .cell-code}\nsex_grid = pd.DataFrame([(visit, sex) for sex in [\"Female\", \"Male\"] for visit in visits], columns=[\"visit\", \"sex\"])\nsex_grid[\"visit\"] = pd.Categorical(sex_grid[\"visit\"], categories=visits)\nsex_means = marginal_means(sex_model, sex_grid)\nprint(sex_means.round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   visit     sex  emmean    se  lower  upper\n0  preop  Female   49.59  0.97  47.69  51.48\n1    6wk  Female   61.18  0.99  59.24  63.12\n2    3mo  Female   74.69  1.02  72.69  76.69\n3    1yr  Female   83.36  1.04  81.33  85.39\n4  preop    Male   50.41  0.98  48.49  52.33\n5    6wk    Male   63.93  1.00  61.97  65.90\n6    3mo    Male   73.81  1.00  71.84  75.77\n7    1yr    Male   84.41  1.04  82.38  86.44\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, ax = plt.subplots(figsize=(7, 3.5))\nfor sex, rows in sex_means.groupby(\"sex\"):\n    ax.errorbar(rows[\"visit\"].astype(str), rows[\"emmean\"], yerr=1.96 * rows[\"se\"], marker=\"o\", capsize=3, label=sex)\nax.set_xlabel(\"Visit\")\nax.set_ylabel(\"KOOS JR\")\nlegend = ax.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](16-mixed-models_files/figure-html/unnamed-chunk-20-1.png)\n:::\n:::\n\n:::\n\n\n\n\n\n- **visit:sex, F = 2.09 on 3 and 832 df, p = 0.100:** no clear evidence that recovery differs between men and women. Python's Wald test gives the undivided statistic, 6.26 on 3 degrees of freedom, with a chi-square p-value of 0.099.\n- **The EMMs** show why: the two patterns cross back and forth by a point or two. Men were 2.7 points ahead at 6 weeks (63.9 vs 61.2), women 0.9 points ahead at 3 months, and they were within about a point of each other at 1 year (84.4 vs 83.4).\n\n::: {.callout-warning}\n## ⚠️ Watch out: a non-significant interaction isn't \"the same recovery\"\np = 0.100 means the data can't show a difference in recovery between the sexes; it doesn't show the recoveries are the same. Report the EMMs with their CIs so readers can see how big a difference the data still allow.\n:::\n\n## Bilateral patients {#bilateral}\n\n46 of the knee patients had both knees replaced, so 92 of the 330 knees come in pairs. The two knees share the same person, so their scores may be related beyond what each knee's own intercept captures. The standard fix is a second random intercept, for the patient, with knees **nested** in patients: in lme4, `(1 | patient_id/case_id)`; in statsmodels, `groups=\"patient_id\"` with a variance component for `case_id`.\n\nIn this cohort the patient-level intercept comes out at almost exactly zero (lme4 warns that the fit is \"singular\"), so the simpler model above is enough. In your data, fit the nested model and report it unless it is singular. [Page 3](../foundations/03-distributions.qmd#paired) explains why bilateral patients need care, and [page 14](../survival/14-cox-regression.qmd#stratified-cox) shows the survival-analysis version.\n\n## How to report it {#reporting}\n\n> **Methods:** KOOS JR scores before surgery and at 6 weeks, 3 months and 1 year were analyzed with a linear mixed model, with visit as a categorical fixed effect and a random intercept for each knee, fitted by restricted maximum likelihood. All available scores were used, including those from knees that missed a visit. Differences between men and women in the pattern of recovery were tested with a visit × sex interaction (Satterthwaite degrees of freedom). The planned comparison was the change from before surgery to 1 year. Estimated marginal means are reported with 95% CIs.\n>\n> **Results:** Of 330 knees, 192 (58.2%) had all four scores; all 1146 scores were analyzed. The estimated mean KOOS JR was 50.0 (95% CI 48.6 to 51.3) before surgery and 83.9 (95% CI 82.5 to 85.3) at 1 year; change 33.9 points (95% CI 32.5 to 35.3). For the visit × sex interaction, F(3, 832) = 2.09 (p = 0.100); at 1 year the estimated mean was 84.4 (95% CI 82.4 to 86.4) in men and 83.4 (95% CI 81.3 to 85.4) in women.\n\n\n\n## Exercises {#exercises}\n\nThe solutions use the packages, data and functions loaded in the sections above, so run the page from the top first.\n\n**1.** Fit the same random-intercept model to HOOS JR in the total hip replacements and report the estimated mean at each visit.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhips <- proms |>\n  filter(instrument == \"HOOS JR\", !is.na(prom_score)) |>\n  mutate(visit = factor(visit, levels = c(\"preop\", \"6wk\", \"3mo\", \"1yr\")))\nc(hips = n_distinct(hips$case_id), scores = nrow(hips), complete = sum(table(hips$case_id) == 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    hips   scores complete \n     270      906      136 \n```\n\n\n:::\n\n```{.r .cell-code}\nhip_model <- lmer(prom_score ~ visit + (1 | case_id), data = hips)\nemmeans(hip_model, ~ visit, lmer.df = \"satterthwaite\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n visit emmean    SE  df lower.CL upper.CL\n preop   45.5 0.698 577     44.1     46.9\n 6wk     68.6 0.720 617     67.2     70.0\n 3mo     80.1 0.745 660     78.6     81.5\n 1yr     88.2 0.772 703     86.7     89.7\n\nDegrees-of-freedom method: satterthwaite \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nhips = proms[(proms[\"instrument\"] == \"HOOS JR\") & proms[\"prom_score\"].notna()].copy()\nhips[\"visit\"] = pd.Categorical(hips[\"visit\"], categories=visits)\nprint(hips[\"case_id\"].nunique(), len(hips), (hips.groupby(\"case_id\").size() == 4).sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n270 906 136\n```\n\n\n:::\n\n```{.python .cell-code}\nhip_model = smf.mixedlm(\"prom_score ~ visit\", hips, groups=\"case_id\").fit(reml=True)\nprint(marginal_means(hip_model, visit_grid).round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   visit  emmean    se  lower  upper\n0  preop   45.50  0.70  44.13  46.86\n1    6wk   68.63  0.72  67.22  70.04\n2    3mo   80.05  0.75  78.59  81.51\n3    1yr   88.20  0.77  86.69  89.71\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Of 270 hips, 136 had all four scores; all 906 scores were used. The estimated mean HOOS JR was 45.5 before surgery, 68.6 at 6 weeks, 80.1 at 3 months and 88.2 (95% CI 86.7 to 89.7) at 1 year.\n:::\n\n**2.** [Page 9](../catalog/09-three-plus-matched.qmd#repeated-measures-anova) analyzed the VR-12 physical component score (PCS) with repeated-measures ANOVA in the 328 joint replacements measured at all four visits. Fit a mixed model with every PCS score instead. How many joint replacements does it use, and do the visit means change?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\npcs_all <- proms |>\n  filter(!is.na(vr12_pcs)) |>\n  mutate(visit = factor(visit, levels = c(\"preop\", \"6wk\", \"3mo\", \"1yr\")))\nc(joint_replacements = n_distinct(pcs_all$case_id), scores = nrow(pcs_all))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\njoint_replacements             scores \n               600               2052 \n```\n\n\n:::\n\n```{.r .cell-code}\npcs_model <- lmer(vr12_pcs ~ visit + (1 | case_id), data = pcs_all)\nemmeans(pcs_model, ~ visit, lmer.df = \"satterthwaite\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n visit emmean    SE   df lower.CL upper.CL\n preop   31.2 0.265 2043     30.6     31.7\n 6wk     35.3 0.275 2044     34.8     35.8\n 3mo     41.0 0.285 2045     40.4     41.5\n 1yr     44.9 0.298 2046     44.3     45.5\n\nDegrees-of-freedom method: satterthwaite \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\npcs_all = proms[proms[\"vr12_pcs\"].notna()].copy()\npcs_all[\"visit\"] = pd.Categorical(pcs_all[\"visit\"], categories=visits)\nprint(pcs_all[\"case_id\"].nunique(), len(pcs_all))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n600 2052\n```\n\n\n:::\n\n```{.python .cell-code}\npcs_model = smf.mixedlm(\"vr12_pcs ~ visit\", pcs_all, groups=\"case_id\").fit(reml=True)\nprint(marginal_means(pcs_model, visit_grid).round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   visit  emmean    se  lower  upper\n0  preop   31.16  0.26  30.64  31.68\n1    6wk   35.29  0.28  34.75  35.83\n2    3mo   40.99  0.29  40.43  41.55\n3    1yr   44.87  0.30  44.28  45.45\n```\n\n\n:::\n:::\n\n:::\n\nThe mixed model uses all 600 joint replacements (2052 scores) instead of the 328 with all four scores. Its visit means, 31.2, 35.3, 41.0 and 44.9, are almost the same as page 9's means for those 328 (31.2, 34.9, 41.0 and 44.9): in this synthetic cohort visits were missed almost entirely at random, so dropping incomplete cases cost precision rather than accuracy.\n:::\n\n**3.** Does knee recovery differ by age group (under 65, 65 to 74, 75 and over)? Fit the visit × age group model and write the Results sentence.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_knees <- knees |>\n  mutate(age_group = cut(age, c(0, 64, 74, Inf), labels = c(\"under 65\", \"65 to 74\", \"75 and over\")))\nage_model <- lmer(prom_score ~ visit * age_group + (1 | case_id), data = age_knees)\nanova(age_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nType III Analysis of Variance Table with Satterthwaite's method\n                Sum Sq Mean Sq NumDF  DenDF  F value  Pr(>F)    \nvisit           147625   49208     3 832.26 669.5499 < 2e-16 ***\nage_group          608     304     2 330.31   4.1342 0.01685 *  \nvisit:age_group    443      74     6 831.31   1.0035 0.42163    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nage_knees = knees.copy()\nage_knees[\"age_group\"] = pd.cut(age_knees[\"age\"], [0, 64, 74, 200], labels=[\"under 65\", \"65 to 74\", \"75 and over\"])\nage_model = smf.mixedlm(\"prom_score ~ visit * age_group\", age_knees, groups=\"case_id\").fit(reml=True)\nage_terms = [name for name in age_model.fe_params.index if \":\" in name]     # the six visit x age group terms\nage_wald = age_model.wald_test(\" = 0, \".join(age_terms) + \" = 0\", scalar=True)\nprint(age_wald.statistic, age_wald.pvalue)                                          # chi-square on 6 df, p-value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n6.019943389602123 0.42095972160286327\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** For the visit × age group interaction in KOOS JR, F(6, 831) = 1.00 (p = 0.422).\n\nThere's no clear evidence that knees recover differently by age group.\n:::\n",
    "supporting": [
      "16-mixed-models_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}