{
  "hash": "f7a5cf66bc0c41affafa2cfbe8830251",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"11 · Predict a value from another variable\"\ndescription: \"Simple linear and nonlinear regression, nonparametric regression, simple logistic regression and Cox regression: how an outcome changes with one predictor.\"\nengine: knitr\ntoc-depth: 2\n---\n\n\n\n<!-- data-checksum: 4529d3cf9635f629d8833c0139272a34 -->\n\nA correlation ([page 10](10-association.qmd)) says how strongly two things go together. **Regression** says **how much the outcome changes for each unit of the predictor**, and lets you predict the outcome for a new patient. Which regression depends on the outcome: a measurement on a straight line or a curve, a measurement that isn't normal, a yes/no outcome, or time until an event. With several predictors at once, see [page 12](12-predict-from-several.qmd).\n\n::: {.callout-note}\n## 💡 How every section on this page works\nEach section answers one question about the practice cohort. Its first code block loads the packages and the data, so you can jump straight to the section you need. Run that section's blocks in order, top to bottom.\n\nTo keep the code short, the examples use every case, including the 80 patients who had both sides operated on. In a real study, decide how to handle them ([page 3](../foundations/03-distributions.qmd#paired)) and say what you did.\n:::\n\n## Simple linear regression {#linear-regression}\n\n**The question:** How much longer does the operation take for each extra point of BMI?\n\n### When to use it\n\n- The outcome is a **measurement**, and you want to know how much it changes **per unit of one predictor**, or to predict it.\n- The relationship is roughly a **straight line**, and each patient's outcome is independent of the others'.\n- The **residuals** (each patient's distance from the line) are roughly normal, with a similar spread all along the line. Check them after fitting.\n- If the relationship curves → [nonlinear regression](#nonlinear-regression). If the outcome is skewed or has a ceiling → [nonparametric regression](#nonparametric-regression). If it's yes/no → [logistic regression](#logistic-regression).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\n\nggplot(cohort, aes(bmi, op_time_min)) +\n  geom_point(alpha = 0.4) +\n  geom_smooth(method = \"lm\", se = FALSE) +   # the least-squares line\n  labs(x = \"BMI, kg/m²\", y = \"Operative time, minutes\")\n```\n\n::: {.cell-output-display}\n![](11-predict-from-one_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport statsmodels.formula.api as smf\n\ncohort = pd.read_csv(\"data/cohort.csv\")\n\nfig, ax = plt.subplots(figsize=(6, 3.5))\nax.scatter(cohort[\"bmi\"], cohort[\"op_time_min\"], alpha=0.4)\nslope, intercept = np.polyfit(cohort[\"bmi\"], cohort[\"op_time_min\"], deg=1)   # the least-squares line\nbmi_range = np.array([cohort[\"bmi\"].min(), cohort[\"bmi\"].max()])\nax.plot(bmi_range, intercept + slope * bmi_range)\nax.set_xlabel(\"BMI, kg/m²\")\nax.set_ylabel(\"Operative time, minutes\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](11-predict-from-one_files/figure-html/unnamed-chunk-4-1.png)\n:::\n:::\n\n:::\n\nThe points scatter around a rising straight line, with no curve and no extreme outliers.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmi_model <- lm(op_time_min ~ bmi, data = cohort)   # outcome ~ predictor\nsummary(bmi_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = op_time_min ~ bmi, data = cohort)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-38.736 -10.543   0.038  10.009  41.858 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  42.8324     3.4156   12.54   <2e-16 ***\nbmi           1.3680     0.1105   12.38   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 14.68 on 598 degrees of freedom\nMultiple R-squared:  0.2041,\tAdjusted R-squared:  0.2028 \nF-statistic: 153.4 on 1 and 598 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(bmi_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %    97.5 %\n(Intercept) 36.124433 49.540461\nbmi          1.151082  1.584929\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nbmi_model = smf.ols(\"op_time_min ~ bmi\", data=cohort).fit()   # outcome ~ predictor\nprint(bmi_model.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:            op_time_min   R-squared:                       0.204\nModel:                            OLS   Adj. R-squared:                  0.203\nMethod:                 Least Squares   F-statistic:                     153.4\nDate:                Tue, 06 Oct 2026   Prob (F-statistic):           1.60e-31\nTime:                        21:27:42   Log-Likelihood:                -2462.0\nNo. Observations:                 600   AIC:                             4928.\nDf Residuals:                     598   BIC:                             4937.\nDf Model:                           1                                         \nCovariance Type:            nonrobust                                         \n==============================================================================\n                 coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------\nIntercept     42.8324      3.416     12.540      0.000      36.124      49.540\nbmi            1.3680      0.110     12.385      0.000       1.151       1.585\n==============================================================================\nOmnibus:                        3.848   Durbin-Watson:                   2.026\nProb(Omnibus):                  0.146   Jarque-Bera (JB):                3.005\nSkew:                           0.035   Prob(JB):                        0.223\nKurtosis:                       2.660   Cond. No.                         176.\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **Intercept = 42.8:** the predicted operative time at a BMI of 0. That's impossible, so on its own it means nothing; it anchors the line.\n- **bmi = 1.37:** the **slope**. Each extra kg/m² of BMI goes with 1.37 more minutes of operative time, on average.\n- **Std. Error 0.11, t = 12.4, p < 0.001:** the slope's uncertainty, and the test of whether it's zero (no relationship).\n- **95% CI 1.15 to 1.58** (R's `confint()`; Python's `[0.025 0.975]` columns).\n- **R-squared = 0.20:** BMI accounts for a fifth of the variation in operative time, the same as r² on [page 10](10-association.qmd#pearson).\n- **Residual standard error 14.7** (R only): the typical distance of a patient's operative time from the line, in minutes.\n\nBefore trusting the line, plot the residuals against the fitted values: they should form a band of even width around 0, with no curve.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(fitted = fitted(bmi_model), residual = resid(bmi_model)) |>\n  ggplot(aes(fitted, residual)) +\n  geom_point(alpha = 0.4) +\n  geom_hline(yintercept = 0) +\n  labs(x = \"Fitted operative time, minutes\", y = \"Residual, minutes\")\n```\n\n::: {.cell-output-display}\n![](11-predict-from-one_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfig, ax = plt.subplots(figsize=(6, 3))\nax.scatter(bmi_model.fittedvalues, bmi_model.resid, alpha=0.4)\nax.axhline(0, color=\"black\")\nax.set_xlabel(\"Fitted operative time, minutes\")\nax.set_ylabel(\"Residual, minutes\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](11-predict-from-one_files/figure-html/unnamed-chunk-10-1.png)\n:::\n:::\n\n:::\n\nThey do here: an even band, with no curve and no funnel shape.\n\n### Effect size and 95% CI\n\nThe **slope** with its 95% CI is the effect size: 1.37 minutes per kg/m² (95% CI 1.15 to 1.58). Scale it to a difference that matters clinically: 5 kg/m² of BMI goes with 6.8 more minutes (95% CI 5.8 to 7.9). **R² = 0.20** says how much of the variation the line explains.\n\n### How to report it\n\n> **Methods:** Operative time was modeled on BMI with simple linear regression.\n>\n> **Results:** The slope of operative time on BMI was 1.37 minutes per kg/m² (95% CI 1.15 to 1.58; p < 0.001; R² = 0.20), or 6.8 minutes (95% CI 5.8 to 7.9) per 5 kg/m².\n\n::: {.callout-warning}\n## ⚠️ Watch out: the line is an average, and only inside your data\nThe line predicts the **average** operative time at each BMI. Individual patients scatter around it by about 15 minutes either way (the residual standard error), so it's a poor tool for scheduling one patient's case. And BMI here runs from 18.0 to 44.5: don't use the line to predict outside that range.\n:::\n\n## Nonlinear regression {#nonlinear-regression}\n\n**The question:** How quickly does KOOS JR recover after knee replacement, and where does it level off?\n\n### When to use it\n\n- The outcome follows a **curve whose shape you know in advance**, and the curve's numbers mean something: here a starting score, a plateau and a recovery rate.\n- You supply the formula and rough starting guesses, and the program finds the values that fit best (nonlinear least squares).\n- If you don't know the shape → [splines](12-predict-from-several.qmd#multiple-nonlinear-regression) or [LOWESS](#nonparametric-regression). If it's a straight line → [linear regression](#linear-regression).\n\nThe recovery curve used here:\n\n$$\\text{score} = \\text{plateau} - (\\text{plateau} - \\text{start}) \\times e^{-\\text{days}/\\tau}$$\n\n- **start:** the score on the day of surgery.\n- **plateau:** the level the score settles at.\n- **τ (tau):** the time constant. After τ days patients have made 63% of their eventual gain, and half of it after τ × ln 2 ≈ 0.69 τ days.\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nproms <- read_csv(\"data/proms_long.csv\", show_col_types = FALSE)\n\nkoos <- proms |>\n  filter(instrument == \"KOOS JR\", !is.na(prom_score)) |>\n  mutate(days = pmax(visit_days, 0))   # pre-op visits (1-27 days before surgery) count as day 0\n\nggplot(koos, aes(days, prom_score)) +\n  geom_point(alpha = 0.2) +\n  labs(x = \"Days since surgery\", y = \"KOOS JR\")\n```\n\n::: {.cell-output-display}\n![](11-predict-from-one_files/figure-html/unnamed-chunk-11-3.png){width=672}\n:::\n\n```{.r .cell-code}\nnrow(koos)                # scores\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1146\n```\n\n\n:::\n\n```{.r .cell-code}\nn_distinct(koos$case_id)  # knees\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 330\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom scipy import stats\nfrom scipy.optimize import curve_fit\n\nproms = pd.read_csv(\"data/proms_long.csv\")\n\nkoos = proms[proms[\"instrument\"] == \"KOOS JR\"].dropna(subset=[\"prom_score\"]).copy()\nkoos[\"days\"] = koos[\"visit_days\"].clip(lower=0)   # pre-op visits (1-27 days before surgery) count as day 0\n\nfig, ax = plt.subplots(figsize=(6, 3.5))\nax.scatter(koos[\"days\"], koos[\"prom_score\"], alpha=0.2)\nax.set_xlabel(\"Days since surgery\")\nax.set_ylabel(\"KOOS JR\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](11-predict-from-one_files/figure-html/unnamed-chunk-12-1.png)\n:::\n\n```{.python .cell-code}\nprint(len(koos), koos[\"case_id\"].nunique())   # scores, knees\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1146 330\n```\n\n\n:::\n:::\n\n:::\n\n1146 scores from 330 knees. The scores climb steeply over the first 3 months, then more slowly toward 1 year: a curve that levels off, not a straight line.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrecovery <- nls(prom_score ~ plateau - (plateau - start) * exp(-days / tau),\n                data = koos,\n                start = list(plateau = 85, start = 50, tau = 100))   # rough guesses read off the plot\nsummary(recovery)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFormula: prom_score ~ plateau - (plateau - start) * exp(-days/tau)\n\nParameters:\n        Estimate Std. Error t value Pr(>|t|)    \nplateau  84.2061     0.8381  100.47   <2e-16 ***\nstart    49.8278     0.6788   73.41   <2e-16 ***\ntau      80.8641     5.5675   14.52   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 12.33 on 1143 degrees of freedom\n\nNumber of iterations to convergence: 4 \nAchieved convergence tolerance: 1.032e-06\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef recovery_curve(days, plateau, start, tau):\n    return plateau - (plateau - start) * np.exp(-days / tau)\n\nestimates, covariance = curve_fit(recovery_curve, koos[\"days\"], koos[\"prom_score\"],\n                                  p0=[85, 50, 100])   # rough guesses read off the plot\nstandard_errors = np.sqrt(np.diag(covariance))\nprint(pd.DataFrame({\"estimate\": estimates, \"std_error\": standard_errors}, index=[\"plateau\", \"start\", \"tau\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          estimate  std_error\nplateau  84.206114   0.838082\nstart    49.827751   0.678777\ntau      80.864061   5.567142\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **plateau = 84.2:** KOOS JR levels off at about 84 points.\n- **start = 49.8:** the estimated score on the day of surgery.\n- **tau = 80.9:** the time constant in days.\n- **Std. Error:** each estimate's uncertainty. The t values and p-values test whether each number is zero, which nobody doubts here; ignore them.\n- **Residual standard error 12.33 on 1143 degrees of freedom** (R only): individual scores scatter about 12 points around the curve.\n\n### Effect size and 95% CI\n\nThe curve's numbers, with their 95% CIs, are the effect sizes. Half of the eventual gain comes after τ × ln 2 days.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(recovery)                       # profile CIs; see the R vs Python box\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            2.5%    97.5%\nplateau 82.60453 85.86557\nstart   48.50027 51.15240\ntau     70.98023 92.53621\n```\n\n\n:::\n\n```{.r .cell-code}\nlog(2) * coef(recovery)[[\"tau\"]]        # days to half of the eventual gain\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 56.0507\n```\n\n\n:::\n\n```{.r .cell-code}\nlog(2) * confint(recovery)[\"tau\", ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5%    97.5% \n49.19974 64.14121 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nt_crit = stats.t.ppf(0.975, df=len(koos) - 3)   # 3 parameters\nprint(pd.DataFrame({\"low\": estimates - t_crit * standard_errors, \"high\": estimates + t_crit * standard_errors},\n                   index=[\"plateau\", \"start\", \"tau\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               low       high\nplateau  82.561762  85.850467\nstart    48.495962  51.159541\ntau      69.941098  91.787025\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(np.log(2) * estimates[2])                  # days to half of the eventual gain\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n56.05069619705848\n```\n\n\n:::\n:::\n\n:::\n\nKOOS JR rose from about 49.8 points (95% CI 48.5 to 51.2) on the day of surgery toward a plateau of 84.2 (95% CI 82.6 to 85.9). Half of the gain came by about 56 days, 8 weeks (95% CI 49 to 64).\n\n### How to report it\n\n> **Methods:** KOOS JR was modeled against days since surgery with an exponential recovery curve fitted by nonlinear least squares, counting the pre-op score as the score on the day of surgery.\n>\n> **Results:** In 330 knees (1146 scores), the fitted curve gave an estimated KOOS JR of 49.8 points (95% CI 48.5 to 51.2) at surgery and a plateau of 84.2 points (95% CI 82.6 to 85.9); half of the change was reached at about 56 days (95% CI 49 to 64).\n\n::: {.callout-warning}\n## ⚠️ Watch out: each knee appears up to four times\nNonlinear least squares treats the 1146 scores as 1146 independent patients, but they come from 330 knees, and scores from the same knee are related. So these CIs can't be trusted: depending on the number, they may be too narrow or too wide. A mixed model ([page 16](../beyond/16-mixed-models.qmd#random-intercept)) accounts for this. And if the fit fails to converge, try starting guesses closer to what the plot shows.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: two kinds of CI\n- R's `nls()` and scipy's `curve_fit()` use different fitting algorithms but find the same estimates and standard errors.\n- R's `confint()` **profiles** the fit: it moves each number away from its estimate until the fit gets significantly worse. scipy gives only the standard errors, so the Python code uses estimate ± t × standard error. The two CIs differ slightly; here τ's CI runs from 71.0 to 92.5 days in R and 69.9 to 91.8 in Python. Either is fine; say which you used.\n:::\n\n## Nonparametric regression {#nonparametric-regression}\n\n**The question:** How does KOOS JR at 1 year depend on KOOS JR before surgery, when many patients reach the ceiling of 100?\n\n### When to use it\n\n- The outcome is a measurement that **isn't normal**: it has a ceiling, a skew or outliers, so the residuals of a straight line won't be normal.\n- **LOWESS** (locally weighted smoothing) draws the shape without a formula: it fits many small lines, each to the points near it, and joins them into a smooth curve. It gives a picture, not a p-value.\n- The **Theil-Sen slope** is the median of the slopes between every pair of patients. A few extreme patients barely move it, and its CI comes from ranks, not from normal residuals.\n- If the residuals are roughly normal → [linear regression](#linear-regression).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nproms <- read_csv(\"data/proms_long.csv\", show_col_types = FALSE)\n\nkoos_wide <- proms |>\n  filter(instrument == \"KOOS JR\", visit %in% c(\"preop\", \"1yr\")) |>\n  select(case_id, visit, prom_score) |>\n  pivot_wider(names_from = visit, values_from = prom_score) |>   # one row per knee\n  rename(one_year = `1yr`) |>\n  filter(!is.na(preop), !is.na(one_year))\n\nsmooth <- lowess(koos_wide$preop, koos_wide$one_year)   # LOWESS curve, R's defaults\n\nggplot(koos_wide, aes(preop, one_year)) +\n  geom_point(alpha = 0.4) +\n  geom_line(data = tibble(preop = smooth$x, one_year = smooth$y), linewidth = 1) +\n  labs(x = \"KOOS JR before surgery\", y = \"KOOS JR at 1 year\")\n```\n\n::: {.cell-output-display}\n![](11-predict-from-one_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n\n```{.r .cell-code}\nnrow(koos_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 246\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(koos_wide$one_year == 100)   # at the ceiling\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 37\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom scipy import stats\nfrom statsmodels.nonparametric.smoothers_lowess import lowess\n\nproms = pd.read_csv(\"data/proms_long.csv\")\n\nkoos_wide = (proms[(proms[\"instrument\"] == \"KOOS JR\") & proms[\"visit\"].isin([\"preop\", \"1yr\"])]\n             .pivot(index=\"case_id\", columns=\"visit\", values=\"prom_score\")   # one row per knee\n             .dropna(subset=[\"preop\", \"1yr\"]))\n\nsmooth = lowess(koos_wide[\"1yr\"], koos_wide[\"preop\"], frac=2/3, it=3,\n                delta=0.01 * np.ptp(koos_wide[\"preop\"]))   # R's lowess() defaults\n\nfig, ax = plt.subplots(figsize=(6, 3.5))\nax.scatter(koos_wide[\"preop\"], koos_wide[\"1yr\"], alpha=0.4)\nax.plot(smooth[:, 0], smooth[:, 1], linewidth=2)\nax.set_xlabel(\"KOOS JR before surgery\")\nax.set_ylabel(\"KOOS JR at 1 year\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](11-predict-from-one_files/figure-html/unnamed-chunk-20-1.png)\n:::\n\n```{.python .cell-code}\nprint(len(koos_wide), (koos_wide[\"1yr\"] == 100).sum())   # knees, at the ceiling\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n246 37\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n246 knees have both scores, and 37 of them (15.0%) score the maximum of 100 at 1 year. The LOWESS curve rises steadily from about 70 to about 99 across the range of pre-op scores.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- koos_wide$preop\ny <- koos_wide$one_year\nn <- length(x)\n\npairs <- combn(n, 2)                                  # every pair of knees\ndx <- x[pairs[2, ]] - x[pairs[1, ]]\ndy <- y[pairs[2, ]] - y[pairs[1, ]]\nslopes <- sort(dy[dx != 0] / dx[dx != 0])             # pairs with the same pre-op score have no slope\nts_slope <- median(slopes)\nts_intercept <- median(y - ts_slope * x)\n\n# Sen's 95% CI: step in from both ends of the sorted slopes by an amount set by the\n# variance of Kendall's S, corrected for tied scores (the same method as scipy)\ntie_term <- function(v) { counts <- table(v); sum(counts * (counts - 1) * (2 * counts + 5)) }\nvar_s <- (n * (n - 1) * (2 * n + 5) - tie_term(x) - tie_term(y)) / 18\nstep <- qnorm(0.975) * sqrt(var_s)\nm <- length(slopes)\nts_ci <- c(slopes[max(round((m - step) / 2), 1)], slopes[min(round((m + step) / 2) + 1, m)])\n\nc(intercept = ts_intercept, slope = ts_slope, low = ts_ci[1], high = ts_ci[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n intercept      slope        low       high \n65.3917949  0.3948718  0.2741117  0.5186441 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nkoos_slope = stats.theilslopes(koos_wide[\"1yr\"], koos_wide[\"preop\"], method=\"joint\")   # see the R vs Python box\nprint(koos_slope)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTheilslopesResult(slope=np.float64(0.394871794871795), intercept=np.float64(65.39179487179487), low_slope=np.float64(0.2741116751269039), high_slope=np.float64(0.5186440677966101))\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **slope = 0.39:** each extra point before surgery goes with 0.39 more points at 1 year (the median of all the pairwise slopes).\n- **intercept = 65.4:** the predicted 1-year score for a pre-op score of 0; it anchors the line.\n- **low, high** (R) or **low_slope, high_slope** (Python): the 95% CI for the slope, 0.27 to 0.52.\n\n### Effect size and 95% CI\n\nThe **Theil-Sen slope** with its CI is the effect size: 0.39 points at 1 year per pre-op point (95% CI 0.27 to 0.52). An ordinary least-squares line gives 0.43; the two would differ more if a few unusual patients pulled the least-squares line.\n\n### How to report it\n\n> **Methods:** Because 1-year KOOS JR clustered at the ceiling, its relationship with pre-op KOOS JR was described with a LOWESS smoother and summarized with the Theil-Sen slope.\n>\n> **Results:** Among 246 knees, 37 (15.0%) scored 100 at 1 year. The Theil-Sen slope of the 1-year KOOS JR on the pre-op KOOS JR was 0.39 points per point (95% CI 0.27 to 0.52).\n\n::: {.callout-warning}\n## ⚠️ Watch out: robust isn't ceiling-proof\nTheil-Sen resists outliers, but nothing can see above a ceiling: the 37 knees at 100 might have scored higher on a longer scale, so the true slope at the top of the range is unknown. And a LOWESS curve is least reliable at its two ends, where it rests on few patients.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: Theil-Sen in R, and LOWESS settings\n- **Theil-Sen in R:** some R packages get the CI wrong when scores are tied, as PROM scores always are (deming 1.4-1 misapplies its tie correction; mblm's CI is far too narrow). So the R code computes the slope and Sen's CI directly, the same way scipy does, and the two agree exactly.\n- **Intercept:** scipy's default (`method=\"separate\"`) computes it as median(y) − slope × median(x). The R code computes median(y − slope × x), which scipy calls `method=\"joint\"`. The slope is the same either way.\n- **LOWESS:** R's `lowess()` and statsmodels' `lowess()` run the same algorithm, but statsmodels' defaults differ (it sets `delta` to 0), so the Python code spells out R's settings. ggplot2's `geom_smooth()` uses a different smoother, `loess()`, which draws a similar but not identical curve.\n:::\n\n## Simple logistic regression {#logistic-regression}\n\n**The question:** Does the risk of a complication within 90 days rise with age?\n\n### When to use it\n\n- The outcome is **yes/no** (complication or not), and you want the **odds ratio** per unit of one predictor.\n- It assumes the log odds change in a straight line with the predictor: each extra decade multiplies the odds by the same amount.\n- You need enough patients with the outcome: a common rule of thumb is at least 10 per predictor.\n- If the outcome is time until an event → [Cox regression](#cox).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE) |>\n  mutate(age_10 = age / 10)   # age in decades, so the odds ratio is per 10 years\n\nby_age <- cohort |>\n  mutate(age_band = cut(age, breaks = c(-Inf, 59, 69, 79, Inf), labels = c(\"under 60\", \"60-69\", \"70-79\", \"80+\"))) |>\n  group_by(age_band) |>\n  summarise(n = n(), complications = sum(complication_90d), percent = 100 * mean(complication_90d))\nby_age\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  age_band     n complications percent\n  <fct>    <int>         <dbl>   <dbl>\n1 under 60   151             5    3.31\n2 60-69      249            20    8.03\n3 70-79      147            12    8.16\n4 80+         53            14   26.4 \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(by_age, aes(age_band, percent)) +\n  geom_col() +\n  labs(x = \"Age at surgery\", y = \"Complications within 90 days, %\")\n```\n\n::: {.cell-output-display}\n![](11-predict-from-one_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport statsmodels.formula.api as smf\n\ncohort = pd.read_csv(\"data/cohort.csv\")\ncohort[\"age_10\"] = cohort[\"age\"] / 10   # age in decades, so the odds ratio is per 10 years\n\nbands = pd.cut(cohort[\"age\"], bins=[-np.inf, 59, 69, 79, np.inf], labels=[\"under 60\", \"60-69\", \"70-79\", \"80+\"])\nby_age = cohort.groupby(bands, observed=True)[\"complication_90d\"].agg(n=\"count\", complications=\"sum\", percent=\"mean\")\nby_age[\"percent\"] = 100 * by_age[\"percent\"]\nprint(by_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            n  complications    percent\nage                                    \nunder 60  151              5   3.311258\n60-69     249             20   8.032129\n70-79     147             12   8.163265\n80+        53             14  26.415094\n```\n\n\n:::\n\n```{.python .cell-code}\nfig, ax = plt.subplots(figsize=(6, 3))\nbars = ax.bar(by_age.index.astype(str), by_age[\"percent\"])\nax.set_xlabel(\"Age at surgery\")\nax.set_ylabel(\"Complications within 90 days, %\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](11-predict-from-one_files/figure-html/unnamed-chunk-28-1.png)\n:::\n:::\n\n:::\n\nComplications followed 5 of 151 procedures (3.3%) in patients under 60 and 14 of 53 (26.4%) in patients aged 80 or more; 51 of 600 overall.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_model <- glm(complication_90d ~ age_10, family = binomial, data = cohort)   # binomial = yes/no outcome\nsummary(age_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = complication_90d ~ age_10, family = binomial, data = cohort)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -7.4870     1.2083  -6.196 5.78e-10 ***\nage_10        0.7498     0.1698   4.415 1.01e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 348.98  on 599  degrees of freedom\nResidual deviance: 327.77  on 598  degrees of freedom\nAIC: 331.77\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nage_model = smf.logit(\"complication_90d ~ age_10\", data=cohort).fit(disp=False)   # disp=False: no fitting messages\nprint(age_model.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                           Logit Regression Results                           \n==============================================================================\nDep. Variable:       complication_90d   No. Observations:                  600\nModel:                          Logit   Df Residuals:                      598\nMethod:                           MLE   Df Model:                            1\nDate:                Tue, 06 Oct 2026   Pseudo R-squ.:                 0.06076\nTime:                        21:27:44   Log-Likelihood:                -163.89\nconverged:                       True   LL-Null:                       -174.49\nCovariance Type:            nonrobust   LLR p-value:                 4.132e-06\n==============================================================================\n                 coef    std err          z      P>|z|      [0.025      0.975]\n------------------------------------------------------------------------------\nIntercept     -7.4870      1.208     -6.196      0.000      -9.856      -5.119\nage_10         0.7498      0.170      4.415      0.000       0.417       1.083\n==============================================================================\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **age_10 = 0.75:** the change in the **log odds** of a complication per 10 years of age. Log odds are hard to read, so turn the coefficient into an odds ratio (next step).\n- **Std. Error 0.17, z = 4.42, p < 0.001:** the test of whether age matters at all.\n- **Intercept = −7.49:** the log odds at age 0, which only anchors the line.\n- **Null and residual deviance** (R) or **LLR p-value** (Python): how much better the model fits with age than without it.\n\n### Effect size and 95% CI\n\nThe **odds ratio** is e raised to the coefficient.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(cbind(odds_ratio = coef(age_model), confint(age_model)))   # profile CIs; see the R vs Python box\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              odds_ratio        2.5 %      97.5 %\n(Intercept) 0.0005603016 4.787677e-05 0.005519935\nage_10      2.1164824677 1.527746e+00 2.977538015\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nodds_ratios = np.exp(pd.concat([age_model.params, age_model.conf_int()], axis=1))   # Wald CIs\nodds_ratios.columns = [\"odds_ratio\", \"low\", \"high\"]\nprint(odds_ratios)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           odds_ratio       low      high\nIntercept    0.000560  0.000052  0.005985\nage_10       2.116483  1.517255  2.952369\n```\n\n\n:::\n:::\n\n:::\n\nEach 10 years of age multiplied the odds of a complication by 2.12 (95% CI 1.53 to 2.98).\n\n### How to report it\n\n> **Methods:** The association between age and complications within 90 days was estimated with logistic regression, with age in 10-year units.\n>\n> **Results:** Complications followed 51 of 600 procedures (8.5%). The odds ratio for a complication per 10 years of age was 2.12 (95% CI 1.53 to 2.98; p < 0.001).\n\n::: {.callout-warning}\n## ⚠️ Watch out: a straight line on the log-odds scale is an assumption\nThe model says each decade multiplies the odds by the same 2.12. The table above suggests otherwise: the rate barely changes between the 60s and the 70s, then jumps after 80. Check the shape before trusting a single odds ratio; [splines](12-predict-from-several.qmd#multiple-nonlinear-regression) let the effect bend. And an odds ratio isn't a risk ratio: the two are close only when the outcome is rare, as it is here (8.5%).\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: profile and Wald CIs\nR's `confint()` on a `glm()` **profiles** the likelihood, which is more accurate in small samples. statsmodels' `conf_int()` uses the simpler **Wald** method (estimate ± 1.96 standard errors), which gives 1.52 to 2.95 here; R's `confint.default()` does the same. Say which you used.\n:::\n\n## Cox regression {#cox}\n\n**The question:** Does the hazard of revision rise with age at surgery?\n\n### When to use it\n\n- The outcome is **time until an event** (revision), and the predictor is a **measurement** (age).\n- Cox regression gives a **hazard ratio per unit** of the predictor. Choose a unit that means something: per 10 years, not per year.\n- It assumes the hazard ratio stays the same over time (**proportional hazards**) and that the log hazard changes in a straight line with age. [Page 14](../survival/14-cox-regression.qmd) shows how to check both and covers Cox regression in full.\n\n### Look at the data first\n\nSplitting age in two is only for the picture; the model uses age as a number.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(survival)\nlibrary(ggsurvfit)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE) |>\n  mutate(age_10 = age / 10,                                                  # age in decades\n         age_group = if_else(age >= 70, \"70 or older\", \"under 70\"))          # for the plot only\n\nsurvfit2(Surv(followup_years, revised) ~ age_group, data = cohort, conf.type = \"log-log\") |>\n  ggsurvfit() +\n  add_risktable() +\n  scale_ggsurvfit() +\n  labs(x = \"Years since surgery\", y = \"Revision-free survival\")\n```\n\n::: {.cell-output-display}\n![](11-predict-from-one_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom lifelines import KaplanMeierFitter, CoxPHFitter\nfrom lifelines.plotting import add_at_risk_counts\n\ncohort = pd.read_csv(\"data/cohort.csv\")\ncohort[\"age_10\"] = cohort[\"age\"] / 10                                         # age in decades\ncohort[\"age_group\"] = cohort[\"age\"].map(lambda age: \"70 or older\" if age >= 70 else \"under 70\")   # for the plot only\n\nfig, ax = plt.subplots(figsize=(7, 4.5))\ncurves = []\nfor group_name, group in cohort.groupby(\"age_group\"):\n    km = KaplanMeierFitter(label=group_name).fit(group[\"followup_years\"], group[\"revised\"])\n    km.plot_survival_function(ax=ax, ci_show=False)\n    curves.append(km)\nax.set_xlabel(\"Years since surgery\")\nax.set_ylabel(\"Revision-free survival\")\nadd_at_risk_counts(*curves, ax=ax)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](11-predict-from-one_files/figure-html/unnamed-chunk-36-1.png)\n:::\n:::\n\n:::\n\n29 of 200 procedures in patients aged 70 or older were revised, against 52 of 400 in younger patients. The curves separate a little, with wide overlap.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_cox <- coxph(Surv(followup_years, revised) ~ age_10, data = cohort)\nsummary(age_cox)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(followup_years, revised) ~ age_10, data = cohort)\n\n  n= 600, number of events= 81 \n\n         coef exp(coef) se(coef)    z Pr(>|z|)  \nage_10 0.2216    1.2480   0.1238 1.79   0.0734 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n       exp(coef) exp(-coef) lower .95 upper .95\nage_10     1.248     0.8013    0.9792     1.591\n\nConcordance= 0.559  (se = 0.035 )\nLikelihood ratio test= 3.23  on 1 df,   p=0.07\nWald test            = 3.2  on 1 df,   p=0.07\nScore (logrank) test = 3.21  on 1 df,   p=0.07\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nage_cox = CoxPHFitter().fit(cohort[[\"followup_years\", \"revised\", \"age_10\"]],\n                            duration_col=\"followup_years\", event_col=\"revised\")\nprint(age_cox.summary[[\"exp(coef)\", \"exp(coef) lower 95%\", \"exp(coef) upper 95%\", \"p\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           exp(coef)  exp(coef) lower 95%  exp(coef) upper 95%         p\ncovariate                                                               \nage_10       1.24801             0.979206             1.590605  0.073426\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(age_cox.log_likelihood_ratio_test().test_statistic)   # overall likelihood ratio test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3.2264967970797898\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **exp(coef) = 1.25:** the hazard ratio per 10 years of age: the hazard of revision is 1.25 times higher for a patient 10 years older.\n- **lower .95 / upper .95 = 0.98 to 1.59:** the 95% CI, which includes 1 (no difference).\n- **Pr(>|z|) = 0.073:** the p-value for age.\n- **Likelihood ratio test = 3.23 on 1 df, p = 0.07:** the overall test; with one predictor it says the same as the p-value for age.\n- **Concordance = 0.56** (R only): how often the model ranks two patients' revision times correctly. 0.5 is a coin toss, so age alone predicts revision poorly.\n\n### Effect size and 95% CI\n\nThe **hazard ratio per 10 years**, 1.25 (95% CI 0.98 to 1.59), is the effect size. The CI is wide: the data fit a small decrease in hazard with age as well as a 59% increase per decade.\n\n### How to report it\n\n> **Methods:** The association between age at surgery and revision was estimated with Cox proportional hazards regression, with age in 10-year units.\n>\n> **Results:** The hazard ratio for revision per 10 years of age was 1.25 (95% CI 0.98 to 1.59; p = 0.073).\n\n::: {.callout-warning}\n## ⚠️ Watch out: older patients die before they can be revised\nDeaths are treated as censored here, so the hazard ratio describes the revision rate among patients still alive. That's a fair answer to its own question. But older patients die sooner, so fewer of them live long enough to need a revision: an older patient's actual chance of being revised is smaller than the hazard ratio suggests. To describe that chance, use the cumulative incidence ([page 13](../survival/13-kaplan-meier.qmd#competing-risks)) or a Fine-Gray model ([page 14](../survival/14-cox-regression.qmd#fine-gray)).\n:::\n\n\n\n## Exercises {#exercises}\n\nThe solutions use the packages and data loaded in the sections above, so run the page from the top first.\n\n**1.** How much does operative time change with **age**? Fit a simple linear regression and report the slope with its 95% CI.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_time <- lm(op_time_min ~ age, data = cohort)\nsummary(age_time)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Estimate Std. Error   t value     Pr(>|t|)\n(Intercept) 68.5167664 4.66904176 14.674696 7.264537e-42\nage          0.2436391 0.07053491  3.454163 5.910612e-04\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(age_time)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %     97.5 %\n(Intercept) 59.3470537 77.6864791\nage          0.1051128  0.3821654\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(age_time)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01956162\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nage_time = smf.ols(\"op_time_min ~ age\", data=cohort).fit()\nprint(age_time.params, age_time.conf_int(), age_time.rsquared, sep=\"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIntercept    68.516766\nage           0.243639\ndtype: float64\n                   0          1\nIntercept  59.347054  77.686479\nage         0.105113   0.382165\n0.019561620543887215\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** The slope of operative time on age was 0.24 minutes per year (95% CI 0.11 to 0.38; p < 0.001; R² = 0.02).\n\nThat's about 2.4 minutes per decade, and age explains only 2% of the variation, against 20% for BMI.\n:::\n\n**2.** A colleague asks whether older patients are more likely to be discharged to a rehabilitation clinic rather than home. Which regression would you use, and what do you find?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nThe outcome is yes/no (rehabilitation clinic or home) and the predictor is a measurement: **simple logistic regression**. Only 30 patients went to a rehabilitation clinic, enough for one predictor.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrehab_model <- glm(I(discharge == \"rehabilitation clinic\") ~ age_10, family = binomial, data = cohort)\nexp(cbind(odds_ratio = coef(rehab_model), confint(rehab_model)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              odds_ratio        2.5 %      97.5 %\n(Intercept) 0.0003775003 1.631361e-05 0.006698018\nage_10      2.0601884482 1.366752e+00 3.171939431\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(rehab_model)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Estimate Std. Error   z value     Pr(>|z|)\n(Intercept) -7.8819392  1.5299687 -5.151700 2.581362e-07\nage_10       0.7227975  0.2140111  3.377382 7.317923e-04\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ncohort[\"rehab\"] = (cohort[\"discharge\"] == \"rehabilitation clinic\").astype(int)\nrehab_model = smf.logit(\"rehab ~ age_10\", data=cohort).fit(disp=False)\nrehab_ors = np.exp(pd.concat([rehab_model.params, rehab_model.conf_int()], axis=1))\nrehab_ors.columns = [\"odds_ratio\", \"low\", \"high\"]\nprint(rehab_ors, rehab_model.pvalues, sep=\"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           odds_ratio       low      high\nIntercept    0.000378  0.000019  0.007572\nage_10       2.060188  1.354377  3.133821\nIntercept    2.581679e-07\nage_10       7.318259e-04\ndtype: float64\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** The odds ratio for discharge to a rehabilitation clinic per 10 years of age was 2.06 (95% CI 1.37 to 3.17; p < 0.001).\n\nThe CI is R's profile CI.\n:::\n\n**3.** Fit the recovery curve to **HOOS JR** (hip replacements) and write the Results sentence.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhoos <- proms |>\n  filter(instrument == \"HOOS JR\", !is.na(prom_score)) |>\n  mutate(days = pmax(visit_days, 0))\nhip_recovery <- nls(prom_score ~ plateau - (plateau - start) * exp(-days / tau),\n                    data = hoos, start = list(plateau = 85, start = 50, tau = 100))\ncoef(hip_recovery)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n plateau    start      tau \n87.86341 45.57326 53.37406 \n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(hip_recovery)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            2.5%    97.5%\nplateau 86.30515 89.44539\nstart   44.20477 46.94044\ntau     47.70662 59.52986\n```\n\n\n:::\n\n```{.r .cell-code}\nlog(2) * confint(hip_recovery)[\"tau\", ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5%    97.5% \n33.06771 41.26295 \n```\n\n\n:::\n\n```{.r .cell-code}\nc(scores = nrow(hoos), hips = n_distinct(hoos$case_id))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nscores   hips \n   906    270 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nhoos = proms[proms[\"instrument\"] == \"HOOS JR\"].dropna(subset=[\"prom_score\"]).copy()\nhoos[\"days\"] = hoos[\"visit_days\"].clip(lower=0)\nhip_estimates, hip_covariance = curve_fit(recovery_curve, hoos[\"days\"], hoos[\"prom_score\"], p0=[85, 50, 100])\nprint(hip_estimates, np.sqrt(np.diag(hip_covariance)), np.log(2) * hip_estimates[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[87.86341771 45.573262   53.37411762] [0.7979894  0.69658005 2.98712232] 36.996119141613114\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(len(hoos), hoos[\"case_id\"].nunique())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n906 270\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** In 270 hips (906 scores), the fitted curve gave an estimated HOOS JR of 45.6 points (95% CI 44.2 to 46.9) at surgery and a plateau of 87.9 points (95% CI 86.3 to 89.4); half of the change was reached at about 37 days (95% CI 33 to 41).\n\nHips seem to recover faster than knees (half the gain by about 5 weeks, against 8). To test that difference, fit both in one model ([page 12](12-predict-from-several.qmd#multiple-nonlinear-regression)).\n:::\n",
    "supporting": [
      "11-predict-from-one_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}