{
  "hash": "c4ae1b916e545d36924351d0e2a958a7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"5 · Compare one group to a hypothetical value\"\ndescription: \"One-sample t test, Wilcoxon signed-rank test, chi-square goodness-of-fit test and binomial test: is our group different from a target or published value?\"\nengine: knitr\ntoc-depth: 2\n---\n\n\n\n<!-- data-checksum: 7318dedd9cebb731bf62c12faf3ff8ee -->\n\nSometimes there is only one group of patients, and the comparison is with a number that comes from **outside** your data: a target set by the hospital, a value published by a registry, a benchmark in a quality report. Is our group different from that number?\n\n::: {.callout-note}\n## 💡 How every section on this page works\nEach section answers one question about the practice cohort. Its first code block loads the packages and the data, so you can jump straight to the section you need. Run that section's blocks in order, top to bottom. The \"hypothetical\" values below are made up for teaching; they aren't real registry figures.\n\nTo keep the code short, the examples use every case, including the 80 patients who had both sides operated on. In a real study, decide how to handle them ([page 3](../foundations/03-distributions.qmd#paired)) and say what you did.\n:::\n\n::: {.callout-warning}\n## ⚠️ Watch out: the value must come from outside your data\nChoose the hypothetical value **before** you look at your data, and say where it came from. A value picked after seeing the results (\"our mean is 84; let's test against 90\") makes the p-value meaningless. If the comparison value comes from another group of patients whose data you have, compare the two groups instead ([page 6](06-two-unpaired-groups.qmd)).\n:::\n\n## One-sample t test {#one-sample-t}\n\n**The question:** The operating room books 90 minutes for every primary joint replacement. Is our average operative time different from 90 minutes?\n\n### When to use it\n\n- The outcome is a **measurement** (minutes, kg/m², points).\n- It's **roughly normal**, or the sample is large (about 30 or more) and not badly skewed ([page 3](../foundations/03-distributions.qmd#robustness)).\n- Each patient is counted once and patients are independent of each other.\n- If the data are skewed, bounded or ordinal → the [Wilcoxon signed-rank test](#wilcoxon-signed-rank).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\n\nggplot(cohort, aes(op_time_min)) +\n  geom_histogram(binwidth = 5) +\n  geom_vline(xintercept = 90, linetype = \"dashed\") +   # the booked time\n  labs(x = \"Operative time, minutes\", y = \"Patients\")\n```\n\n::: {.cell-output-display}\n![](05-one-group-vs-hypothetical_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom scipy import stats\n\ncohort = pd.read_csv(\"data/cohort.csv\")\n\nfig, ax = plt.subplots(figsize=(6, 3))\nax.hist(cohort[\"op_time_min\"], bins=range(45, 145, 5))\nax.axvline(90, linestyle=\"--\")                        # the booked time\nax.set_xlabel(\"Operative time, minutes\")\nax.set_ylabel(\"Patients\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](05-one-group-vs-hypothetical_files/figure-html/unnamed-chunk-4-1.png)\n:::\n:::\n\n:::\n\nA roughly symmetric hump, centered a little to the left of the dashed line at 90 minutes.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nop_test <- t.test(cohort$op_time_min, mu = 90)   # mu = the hypothetical mean\nop_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  cohort$op_time_min\nt = -8.2265, df = 599, p-value = 1.204e-15\nalternative hypothesis: true mean is not equal to 90\n95 percent confidence interval:\n 83.1622 85.7978\nsample estimates:\nmean of x \n    84.48 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nop_test = stats.ttest_1samp(cohort[\"op_time_min\"], popmean=90)   # popmean = the hypothetical mean\nprint(op_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTtestResult(statistic=np.float64(-8.226498476022671), pvalue=np.float64(1.2039160411565963e-15), df=np.int64(599))\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(cohort[\"op_time_min\"].mean(), op_test.confidence_interval())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n84.48 ConfidenceInterval(low=np.float64(83.162196800282), high=np.float64(85.797803199718))\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **t = −8.23:** the observed mean is 8.2 standard errors below 90. The sign says which side.\n- **df = 599:** degrees of freedom, n − 1.\n- **p < 0.001:** a mean this far from 90 would be very unlikely if the true average were 90 minutes.\n- **mean of x = 84.48:** our average operative time.\n- **95% CI 83.2 to 85.8:** the CI for our **mean**, not for the difference from 90.\n\n### Effect size and 95% CI\n\nThe effect size is simply the difference from the hypothetical value: subtract 90 from the mean and from both ends of its CI.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nop_test$estimate - 90    # mean difference\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean of x \n    -5.52 \n```\n\n\n:::\n\n```{.r .cell-code}\nop_test$conf.int - 90    # its 95% CI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -6.837803 -4.202197\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(cohort[\"op_time_min\"].mean() - 90)                        # mean difference\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-5.519999999999996\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(op_test.confidence_interval().low - 90, op_test.confidence_interval().high - 90)   # its 95% CI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-6.837803199717996 -4.202196800281996\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nOperations took 5.5 minutes less than the booked 90 on average (95% CI 4.2 to 6.8 minutes less). Whether that matters is a scheduling question, not a statistical one: over a day of four joints, it adds up to about 20 minutes.\n\n### How to report it\n\n> **Methods:** Mean operative time was compared with the 90 minutes booked per case using a one-sample t test.\n>\n> **Results:** Mean operative time was 84.5 minutes (SD 16.4); the booked time was 90 minutes (difference −5.5 minutes, 95% CI −6.8 to −4.2; p < 0.001).\n\n::: {.callout-warning}\n## ⚠️ Watch out: a published mean has its own uncertainty\nA one-sample test treats the hypothetical value as exact. A registry mean is itself an estimate with a CI. If you're comparing your patients with a published series and its CI is wide, say so, and don't over-read a small difference.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: what the CI is a CI for\nBoth R's `t.test(x, mu = 90)` and scipy's `ttest_1samp(x, popmean=90)` report the CI for the **mean** (83.2 to 85.8), not for the difference from 90. Subtract the hypothetical value yourself, as above.\n:::\n\n## Wilcoxon signed-rank test {#wilcoxon-signed-rank}\n\n**The question:** Suppose our practice's target is a 1-year KOOS JR of 80 points after knee replacement. Is our typical patient's score different from 80?\n\n### When to use it\n\n- The outcome is **skewed** or has a **ceiling or floor**, so a mean isn't a fair summary ([page 3](../foundations/03-distributions.qmd#transform)).\n- It ranks how far each patient is above or below the hypothetical value. It doesn't assume a normal distribution, but it does need distances that can be compared, so the outcome must be a measurement.\n- For an **ordinal** scale (satisfaction from 1 to 5), count the patients above and below the value and compare the two counts with a [binomial test](#binomial-test). This is called the **sign test**.\n- Strictly, it tests the **pseudomedian** (the Hodges-Lehmann estimate below), which equals the median only for a symmetric distribution. With a ceiling the two differ a little; report both.\n- If the data are roughly normal → the [one-sample t test](#one-sample-t) is more familiar and slightly more powerful.\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nproms <- read_csv(\"data/proms_long.csv\", show_col_types = FALSE)\nkoos_1yr <- proms |>\n  filter(instrument == \"KOOS JR\", visit == \"1yr\", !is.na(prom_score)) |>\n  pull(prom_score)\n\nggplot(tibble(score = koos_1yr), aes(score)) +\n  geom_histogram(binwidth = 2.5) +\n  geom_vline(xintercept = 80, linetype = \"dashed\") +   # the target\n  labs(x = \"KOOS JR at 1 year (100 = best)\", y = \"Patients\")\n```\n\n::: {.cell-output-display}\n![](05-one-group-vs-hypothetical_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport pingouin as pg\nimport matplotlib.pyplot as plt\nfrom scipy import stats\n\nproms = pd.read_csv(\"data/proms_long.csv\")\nkoos_1yr = proms.loc[(proms[\"instrument\"] == \"KOOS JR\") & (proms[\"visit\"] == \"1yr\"),\n                     \"prom_score\"].dropna()\n\nfig, ax = plt.subplots(figsize=(6, 3))\nax.hist(koos_1yr, bins=np.arange(35, 102.5, 2.5))\nax.axvline(80, linestyle=\"--\")                         # the target\nax.set_xlabel(\"KOOS JR at 1 year (100 = best)\")\nax.set_ylabel(\"Patients\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](05-one-group-vs-hypothetical_files/figure-html/unnamed-chunk-14-1.png)\n:::\n:::\n\n:::\n\nA ceiling at 100 and a long tail to the left: the rank-based test is the safer choice.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkoos_test <- wilcox.test(koos_1yr, mu = 80,\n                         exact = FALSE, correct = FALSE,   # see the R vs Python box\n                         conf.int = TRUE)                  # adds the Hodges-Lehmann estimate and CI\nkoos_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank test\n\ndata:  koos_1yr\nV = 22698, p-value = 2.293e-06\nalternative hypothesis: true location is not equal to 80\n95 percent confidence interval:\n 82.74996 86.10002\nsample estimates:\n(pseudo)median \n      84.35003 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# pg.wilcoxon() runs scipy's test and adds the rank-biserial effect size\nkoos_test = pg.wilcoxon(koos_1yr - 80, method=\"approx\", correction=False)   # see the R vs Python box\nprint(koos_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            W_val alternative     p_val       RBC  CLES\nWilcoxon  11231.5   two-sided  0.000002  0.337961   NaN\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **V = 22698** (R) or **W_val = 11231.5** (Python): the test statistic, a sum of ranks. The two programs report different sums (see the R vs Python box); the p-values are the same.\n- **p < 0.001:** scores this far from 80 would be very unlikely if the typical patient really scored 80.\n- **(pseudo)median 84.35, 95% CI 82.7 to 86.1** (R only): the Hodges-Lehmann estimate of the center of the scores, with its CI.\n- **RBC = 0.34** (Python): the rank-biserial effect size, below.\n\n### Effect size and 95% CI\n\nTwo effect sizes are useful here:\n\n- The **Hodges-Lehmann estimate** (the pseudomedian): a center of the scores, in points. It's the median of all the averages of pairs of scores, so it's less affected by the ceiling than a mean.\n- The **rank-biserial correlation (r)**: from −1 (every patient below 80) through 0 (balanced) to +1 (every patient above 80). As a rough guide, 0.1 is small, 0.3 moderate and 0.5 large.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkoos_test$estimate                                   # Hodges-Lehmann estimate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(pseudo)median \n      84.35003 \n```\n\n\n:::\n\n```{.r .cell-code}\nkoos_test$conf.int                                   # its 95% CI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 82.74996 86.10002\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::rank_biserial(koos_1yr, mu = 80)         # rank-biserial r and 95% CI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nr (rank biserial) |       95% CI\n--------------------------------\n0.34              | [0.21, 0.46]\n\n- Deviation from a difference of 80.\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Hodges-Lehmann estimate: the median of the averages of every pair of scores\ndef hodges_lehmann(x):\n    x = np.asarray(x)\n    i, j = np.triu_indices(len(x))          # every pair, including each score with itself\n    return np.median((x[i] + x[j]) / 2)\n\nprint(hodges_lehmann(koos_1yr))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n84.35\n```\n\n\n:::\n\n```{.python .cell-code}\n# scipy has no CI for it, so use a bootstrap: recompute it on 9999 resampled datasets\nboot = stats.bootstrap((koos_1yr.to_numpy(),), hodges_lehmann, vectorized=False,\n                       rng=np.random.default_rng(2026))\nprint(boot.confidence_interval)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfidenceInterval(low=np.float64(82.69999999999999), high=np.float64(86.05))\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(koos_test[\"RBC\"])                               # rank-biserial r\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWilcoxon    0.337961\nName: RBC, dtype: float64\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nThe typical 1-year score was about 4 points above the target (Hodges-Lehmann estimate 84.4), and the rank-biserial r of 0.34 is a moderate effect: noticeably more patients scored above 80 than below.\n\n### How to report it\n\n> **Methods:** Because 1-year KOOS JR scores showed a ceiling effect, they were compared with the 80-point target using a Wilcoxon signed-rank test, with the Hodges-Lehmann estimate and its 95% CI as the effect size.\n>\n> **Results:** The median 1-year KOOS JR was 85.8 points (IQR 74.7 to 93.9); the target was 80 points (Hodges-Lehmann estimate 84.4, 95% CI 82.7 to 86.1; rank-biserial r = 0.34; p < 0.001).\n\n::: {.callout-warning}\n## ⚠️ Watch out: two different \"Wilcoxon\" tests\nThe **Wilcoxon signed-rank test** (this one) compares one group with a value, or two **paired** measurements ([page 7](07-two-paired-groups.qmd#wilcoxon-signed-rank)). The **Wilcoxon rank-sum test** compares two **independent** groups; it's the same as the [Mann-Whitney test](06-two-unpaired-groups.qmd#mann-whitney). Always write the full name.\n\nAlso: patients who score **exactly** 80 carry no information about the direction and are dropped from the test.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: Wilcoxon defaults\n- **The statistic.** R reports V, the sum of the ranks of patients **above** 80 (22698.5, printed as 22698). scipy (and pingouin) report the **smaller** of the two sums (11231.5). The two sums always add up to n(n + 1)/2, here 260 × 261 / 2 = 33,930, so they carry the same information and give the same p-value.\n- **Exact or approximate.** For small samples without ties, both programs compute an exact p-value; otherwise they use a normal approximation. R adds a **continuity correction** to the approximation by default; scipy doesn't. We set `exact = FALSE, correct = FALSE` in R and `method=\"approx\", correction=False` in Python so they match.\n- **The Hodges-Lehmann CI.** R computes it by inverting the test. scipy has no function for it, so the Python code uses a bootstrap, a different method, so the two CIs differ slightly (82.75 to 86.10 in R, 82.70 to 86.05 from the bootstrap).\n:::\n\n## Chi-square goodness-of-fit test {#chi-square-gof}\n\n**The question:** Suppose a national registry reports that its patients are 10% ASA class 1, 55% class 2, 33% class 3 and 2% class 4. Is our mix of ASA classes the same?\n\n### When to use it\n\n- The outcome is **categorical** with two or more categories, and you have hypothetical proportions for every category.\n- Each patient falls in exactly one category, and is counted once.\n- The **expected count** in every category (total × hypothetical proportion) should be at least 5. Otherwise combine small categories, or with only two categories use the [binomial test](#binomial-test).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\nregistry <- c(0.10, 0.55, 0.33, 0.02)                 # the hypothetical proportions, ASA 1 to 4\n\nasa_counts <- table(cohort$asa)\ntibble(asa = names(asa_counts), observed = as.vector(asa_counts),\n       expected = sum(asa_counts) * registry)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  asa   observed expected\n  <chr>    <int>    <dbl>\n1 1           36       60\n2 2          300      330\n3 3          246      198\n4 4           18       12\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nfrom scipy import stats\n\ncohort = pd.read_csv(\"data/cohort.csv\")\nregistry = [0.10, 0.55, 0.33, 0.02]                   # the hypothetical proportions, ASA 1 to 4\n\nasa_counts = cohort[\"asa\"].value_counts().sort_index()\nprint(pd.DataFrame({\"observed\": asa_counts, \"expected\": asa_counts.sum() * pd.Series(registry, index=asa_counts.index)}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     observed  expected\nasa                    \n1          36      60.0\n2         300     330.0\n3         246     198.0\n4          18      12.0\n```\n\n\n:::\n:::\n\n:::\n\nAll four expected counts are at least 5 (the smallest is 12). We have fewer ASA 1 and more ASA 3 patients than the registry would predict.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nasa_test <- chisq.test(asa_counts, p = registry)   # p = the hypothetical proportions\nasa_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  asa_counts\nX-squared = 26.964, df = 3, p-value = 5.992e-06\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nexpected = asa_counts.sum() * pd.Series(registry, index=asa_counts.index)\nasa_test = stats.chisquare(asa_counts, f_exp=expected)   # f_exp = the expected COUNTS\nprint(asa_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPower_divergenceResult(statistic=np.float64(26.96363636363636), pvalue=np.float64(5.99160920120808e-06))\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **X-squared = 26.96:** the chi-square statistic, adding up how far each observed count is from its expected count.\n- **df = 3:** degrees of freedom, the number of categories minus 1.\n- **p < 0.001:** a mix this different from the registry's would be very unlikely if our patients came from the same mix.\n\n### Effect size and 95% CI\n\nThe test says the mix differs, not where. Look at each category's observed percentage, with a 95% CI, next to the registry's.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nasa_ci <- sapply(asa_counts, function(k) prop.test(k, sum(asa_counts), correct = FALSE)$conf.int)\n\ntibble(asa = names(asa_counts),\n       observed_pct = 100 * as.vector(asa_counts) / sum(asa_counts),\n       ci_low = 100 * asa_ci[1, ], ci_high = 100 * asa_ci[2, ],   # Wilson CIs, as on page 4\n       registry_pct = 100 * registry)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  asa   observed_pct ci_low ci_high registry_pct\n  <chr>        <dbl>  <dbl>   <dbl>        <dbl>\n1 1                6   4.37    8.19           10\n2 2               50  46.0    54.0            55\n3 3               41  37.1    45.0            33\n4 4                3   1.91    4.69            2\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nn = asa_counts.sum()\ncis = [stats.binomtest(int(k), int(n)).proportion_ci(method=\"wilson\") for k in asa_counts]\n\nprint(pd.DataFrame({\n    \"observed_pct\": 100 * asa_counts / n,\n    \"ci_low\": [100 * ci.low for ci in cis],                     # Wilson CIs, as on page 4\n    \"ci_high\": [100 * ci.high for ci in cis],\n    \"registry_pct\": [100 * p for p in registry],\n}, index=asa_counts.index))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     observed_pct     ci_low    ci_high  registry_pct\nasa                                                  \n1             6.0   4.365143   8.194687          10.0\n2            50.0  46.011986  53.988014          55.0\n3            41.0  37.133962  44.980549          33.0\n4             3.0   1.905926   4.692074           2.0\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nASA 3 makes the biggest difference: 41.0% of our patients (95% CI 37.1% to 45.0%) against 33% in the registry. The CI doesn't include 33%.\n\n### How to report it\n\n> **Methods:** The distribution of ASA classes was compared with the registry's using a chi-square goodness-of-fit test.\n>\n> **Results:** ASA class 3 accounted for 41.0% of our patients (95% CI 37.1% to 45.0%) and 33% of the registry's, and ASA class 1 for 6.0% and 10% (χ² = 27.0, df = 3, p < 0.001).\n\n::: {.callout-warning}\n## ⚠️ Watch out: counts, not percentages\nThe test needs the **counts** of patients in each category. Feeding it percentages (\"6, 50, 41, 3\") gives a wrong p-value, because the test's precision depends on how many patients there are.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: proportions or counts\nR's `chisq.test(counts, p = ...)` takes the hypothetical **proportions** (they must add up to 1). scipy's `chisquare(counts, f_exp=...)` takes the expected **counts** (they must add up to the observed total). Same test, different inputs.\n:::\n\n## Binomial test {#binomial-test}\n\n**The question:** Suppose a state quality report gives a 90-day readmission rate of 6% after primary joint replacement. Is our rate different?\n\n### When to use it\n\n- The outcome is **yes/no**, and you're comparing one group's proportion with a hypothetical proportion.\n- Each patient is counted once.\n- The binomial test is **exact**: it works for any sample size, including small numbers of events. (The chi-square goodness-of-fit test with two categories is its large-sample approximation.)\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\n\ncount(cohort, readmit_90d)   # 1 = readmitted within 90 days\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  readmit_90d     n\n        <dbl> <int>\n1           0   573\n2           1    27\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nfrom scipy import stats\n\ncohort = pd.read_csv(\"data/cohort.csv\")\n\nprint(cohort[\"readmit_90d\"].value_counts(dropna=False))   # 1 = readmitted within 90 days\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nreadmit_90d\n0    573\n1     27\nName: count, dtype: int64\n```\n\n\n:::\n:::\n\n:::\n\n27 readmissions after 600 procedures, with no missing values.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreadmitted <- sum(cohort$readmit_90d == 1)\npatients   <- nrow(cohort)\n\nreadmit_test <- binom.test(readmitted, patients, p = 0.06)   # p = the hypothetical proportion\nreadmit_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  readmitted and patients\nnumber of successes = 27, number of trials = 600, p-value = 0.143\nalternative hypothesis: true probability of success is not equal to 0.06\n95 percent confidence interval:\n 0.02986148 0.06479979\nsample estimates:\nprobability of success \n                 0.045 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nreadmitted = int((cohort[\"readmit_90d\"] == 1).sum())\npatients = len(cohort)\n\nreadmit_test = stats.binomtest(readmitted, patients, p=0.06)   # p = the hypothetical proportion\nprint(readmit_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBinomTestResult(k=27, n=600, alternative='two-sided', statistic=0.045, pvalue=0.14295280432514018)\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(readmit_test.proportion_ci(method=\"exact\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfidenceInterval(low=np.float64(0.029861476429590028), high=np.float64(0.06479978975045417))\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **number of successes = 27, number of trials = 600:** 27 readmissions (\"successes\" is just the software's word for the outcome you counted).\n- **p = 0.143:** a rate this far from 6% wouldn't be unusual if our true rate were 6%.\n- **probability of success = 0.045:** our readmission rate, 4.5%.\n- **95% CI 0.030 to 0.065:** our true rate is plausibly anywhere from 3.0% to 6.5%. This is the exact (Clopper-Pearson) interval.\n\n### Effect size and 95% CI\n\nThe effect size is the difference from the hypothetical rate: 4.5% − 6% = −1.5 percentage points. Its 95% CI is the CI for our rate minus 6%: −3.0 to +0.5 percentage points. It includes 0, which matches the p-value above 0.05.\n\n### How to report it\n\n> **Methods:** The 90-day readmission rate was compared with the state benchmark of 6% using an exact binomial test. 95% CIs for proportions are exact (Clopper-Pearson).\n>\n> **Results:** Readmission within 90 days followed 27 of 600 procedures (4.5%; 95% CI 3.0% to 6.5%); the benchmark was 6% (binomial test p = 0.143).\n\n::: {.callout-warning}\n## ⚠️ Watch out: \"not significantly different\" doesn't mean \"the same\"\nOur rate could be as low as 3.0% (half the benchmark) or as high as 6.5%. The data are compatible with being better than the benchmark *and* with being about the same. Don't write \"our readmission rate was equivalent to the benchmark\", and don't write \"lower\" either; report the CI and let it speak.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: exact CIs\nR's `binom.test()` and scipy's `binomtest()` agree on the p-value. R prints the exact (Clopper-Pearson) CI automatically; in scipy, ask for it with `proportion_ci(method=\"exact\")`. It's a little wider than the Wilson interval on [page 4](04-describe-one-group.qmd#proportion) (3.1% to 6.5% for the same 27 patients). Either is fine; say which you used.\n:::\n\n\n\n## Exercises {#exercises}\n\nThe solutions use the packages and data loaded in the sections above, so run the page from the top first.\n\n**1.** Suppose a registry reports a mean age of 66 years at primary joint replacement. Is our patients' mean age different? Run the test and report the mean difference with its 95% CI.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_test <- t.test(cohort$age, mu = 66)\nage_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  cohort$age\nt = -1.2461, df = 599, p-value = 0.2132\nalternative hypothesis: true mean is not equal to 66\n95 percent confidence interval:\n 64.76351 66.27649\nsample estimates:\nmean of x \n    65.52 \n```\n\n\n:::\n\n```{.r .cell-code}\nage_test$conf.int - 66\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.2364949  0.2764949\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nage_test = stats.ttest_1samp(cohort[\"age\"], popmean=66)\nprint(age_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTtestResult(statistic=np.float64(-1.2461253956353107), pvalue=np.float64(0.21320549841639244), df=np.int64(599))\n```\n\n\n:::\n\n```{.python .cell-code}\nci = age_test.confidence_interval()\nprint(cohort[\"age\"].mean() - 66, ci.low - 66, ci.high - 66)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-0.480000000000004 -1.2364948782807943 0.27649487828078634\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Mean age was 65.5 years; the registry's was 66 years (difference −0.5 years, 95% CI −1.2 to 0.3; p = 0.213).\n\nThe CI includes 0 and rules out a difference of more than about a year in either direction.\n:::\n\n**2.** Suppose a national registry reports that 90% of joint replacement patients go home rather than to a rehabilitation clinic. After 570 of our 600 procedures, the patient went home. Which test would you use, and what do you conclude?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nA yes/no outcome compared with a hypothetical proportion: the **binomial test**.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinom.test(570, 600, p = 0.90)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  570 and 600\nnumber of successes = 570, number of trials = 600, p-value = 1.184e-05\nalternative hypothesis: true probability of success is not equal to 0.9\n95 percent confidence interval:\n 0.9293886 0.9660145\nsample estimates:\nprobability of success \n                  0.95 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nhome = stats.binomtest(570, 600, p=0.90)\nprint(home.pvalue, home.proportion_ci(method=\"exact\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1.1844241573497358e-05 ConfidenceInterval(low=np.float64(0.9293885939673254), high=np.float64(0.9660144527846245))\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Discharge home followed 570 of 600 procedures (95.0%; 95% CI 92.9% to 96.6%); the state report gives 90% (binomial test p < 0.001).\n:::\n\n**3.** Suppose a survey of joint replacement patients found 50% never smokers, 40% former smokers and 10% current smokers. Test whether our smoking mix differs, and write the Results sentence.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmoking <- table(factor(cohort$smoker, levels = c(\"never\", \"former\", \"current\")))\nsmoking\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  never  former current \n    321     230      49 \n```\n\n\n:::\n\n```{.r .cell-code}\nchisq.test(smoking, p = c(0.50, 0.40, 0.10))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  smoking\nX-squared = 3.9033, df = 2, p-value = 0.142\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nsmoking = cohort[\"smoker\"].value_counts()[[\"never\", \"former\", \"current\"]]\nprint(smoking)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsmoker\nnever      321\nformer     230\ncurrent     49\nName: count, dtype: int64\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(stats.chisquare(smoking, f_exp=smoking.sum() * pd.Series([0.50, 0.40, 0.10], index=smoking.index)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPower_divergenceResult(statistic=np.float64(3.9033333333333333), pvalue=np.float64(0.14203714562701292))\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Of our patients, 53.5% had never smoked, 38.3% were former and 8.2% current smokers; the survey's figures were 50%, 40% and 10% (χ² = 3.9, df = 2, p = 0.142).\n:::\n",
    "supporting": [
      "05-one-group-vs-hypothetical_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}