{
  "hash": "76152cf29d712930639c3a4411e0eaf7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"2 · Demographics (Table 1)\"\ndescription: \"Build a publication-ready Table 1 for one group or several: choosing summaries, comparing groups, standardized mean differences, missing data, and exporting to Word.\"\nengine: knitr\n---\n\n\n\n<!-- data-checksum: ffc54e2ad996e1e61ad10ca520e4d588 -->\n\nAlmost every clinical paper starts with **Table 1**: who was studied. Reviewers read it first, to decide whether your patients look like theirs and whether your groups were comparable to begin with. This page builds one from scratch.\n\n::: {.callout-note}\n## 💡 In plain language\nTable 1 *describes* your patients. It doesn't answer your research question. Its job is to let a reader judge who your results apply to, and whether your groups started out alike.\n:::\n\n## Load the data and pick the variables {#setup}\n\nWe'll describe the practice cohort: 600 primary hip and knee replacements (THA and TKA). Table 1 usually holds the characteristics measured *before* surgery.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(gtsummary)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE) |>\n  mutate(asa = factor(asa))   # ASA class is a category, not a number\n\ntable1_vars <- c(\"age\", \"sex\", \"bmi\", \"asa\", \"diabetes\", \"smoker\", \"los_days\")\n\nlabels <- list(age ~ \"Age, years\", sex ~ \"Sex\", bmi ~ \"BMI, kg/m²\", asa ~ \"ASA class\",\n               diabetes ~ \"Diabetes\", smoker ~ \"Smoking status\",\n               los_days ~ \"Length of stay, days\")\n```\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nfrom tableone import TableOne\n\ncohort = pd.read_csv(\"data/cohort.csv\")\ncohort[\"asa\"] = cohort[\"asa\"].astype(str)   # ASA class is a category, not a number\n\ntable1_vars = [\"age\", \"sex\", \"bmi\", \"asa\", \"diabetes\", \"smoker\", \"los_days\"]\ncategorical = [\"sex\", \"asa\", \"diabetes\", \"smoker\"]\n\nlabels = {\"age\": \"Age, years\", \"sex\": \"Sex\", \"bmi\": \"BMI, kg/m²\", \"asa\": \"ASA class\",\n          \"diabetes\": \"Diabetes\", \"smoker\": \"Smoking status\",\n          \"los_days\": \"Length of stay, days\"}\n```\n:::\n\n:::\n\n::: {.callout-warning}\n## ⚠️ Watch out: one row per procedure, not per patient\nThe cohort has one row per *procedure*. 80 patients had both sides done, so 600 procedures come from 520 patients. Say which one your table counts, for example in a footnote: \"600 procedures in 520 patients\". The two procedures of a bilateral patient are not independent (same person, same age, sex and health), so tests that treat every row as a separate patient are slightly overconfident. [Distributions & choosing a test](03-distributions.qmd#paired) explains the options.\n:::\n\n## One group {#one-group}\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable_one <- cohort |>\n  select(all_of(table1_vars)) |>\n  tbl_summary(\n    type      = list(los_days ~ \"continuous\"),          # few distinct values, but still a number\n    statistic = list(all_continuous() ~ \"{mean} ({sd})\",\n                     los_days ~ \"{median} ({p25}–{p75})\"),\n    digits    = list(all_continuous() ~ 1, los_days ~ 0),   # 65.5 (9.4); whole days\n    label     = labels\n  )\ntable_one\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"boixebygzu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#boixebygzu table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#boixebygzu thead, #boixebygzu tbody, #boixebygzu tfoot, #boixebygzu tr, #boixebygzu td, #boixebygzu th {\n  border-style: none;\n}\n\n#boixebygzu p {\n  margin: 0;\n  padding: 0;\n}\n\n#boixebygzu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#boixebygzu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#boixebygzu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#boixebygzu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#boixebygzu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#boixebygzu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#boixebygzu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#boixebygzu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#boixebygzu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#boixebygzu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#boixebygzu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#boixebygzu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#boixebygzu .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#boixebygzu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#boixebygzu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#boixebygzu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#boixebygzu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#boixebygzu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#boixebygzu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#boixebygzu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#boixebygzu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#boixebygzu .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#boixebygzu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#boixebygzu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#boixebygzu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#boixebygzu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#boixebygzu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#boixebygzu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#boixebygzu .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#boixebygzu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#boixebygzu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#boixebygzu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#boixebygzu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#boixebygzu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#boixebygzu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#boixebygzu .gt_left {\n  text-align: left;\n}\n\n#boixebygzu .gt_center {\n  text-align: center;\n}\n\n#boixebygzu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#boixebygzu .gt_font_normal {\n  font-weight: normal;\n}\n\n#boixebygzu .gt_font_bold {\n  font-weight: bold;\n}\n\n#boixebygzu .gt_font_italic {\n  font-style: italic;\n}\n\n#boixebygzu .gt_super {\n  font-size: 65%;\n}\n\n#boixebygzu .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#boixebygzu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#boixebygzu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#boixebygzu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#boixebygzu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#boixebygzu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#boixebygzu .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#boixebygzu .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#boixebygzu div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_0\"><span data-qmd-base64=\"KipOID0gNjAwKio=\"><span class='gt_from_md'><strong>N = 600</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Age, years</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">65.5 (9.4)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Sex</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">343 (57%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">257 (43%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">BMI, kg/m²</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">30.4 (5.4)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">ASA class</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">36 (6.0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">300 (50%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">246 (41%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    4</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">18 (3.0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Diabetes</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">56 (9.3%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Smoking status</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    current</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">49 (8.2%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    former</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">230 (38%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    never</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">321 (54%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Length of stay, days</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1 (0–1)</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"2\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVhbiAoU0QpOyBuICglKTsgTWVkaWFuIChRMeKAk1EzKQ==\"><span class='gt_from_md'>Mean (SD); n (%); Median (Q1–Q3)</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ntable_one = TableOne(\n    cohort,\n    columns=table1_vars,\n    categorical=categorical,\n    nonnormal=[\"los_days\"],      # report median [Q1, Q3] instead of mean (SD)\n    rename=labels,\n)\nprint(table_one.tabulate(tablefmt=\"github\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n|                                      |         |   Missing | Overall       |\n|--------------------------------------|---------|-----------|---------------|\n| n                                    |         |           | 600           |\n| Age, years, mean (SD)                |         |         0 | 65.5 (9.4)    |\n| Sex, n (%)                           | Female  |           | 343 (57.2)    |\n|                                      | Male    |           | 257 (42.8)    |\n| BMI, kg/m², mean (SD)                |         |         0 | 30.4 (5.4)    |\n| ASA class, n (%)                     | 1       |           | 36 (6.0)      |\n|                                      | 2       |           | 300 (50.0)    |\n|                                      | 3       |           | 246 (41.0)    |\n|                                      | 4       |           | 18 (3.0)      |\n| Diabetes, n (%)                      | 0       |           | 544 (90.7)    |\n|                                      | 1       |           | 56 (9.3)      |\n| Smoking status, n (%)                | current |           | 49 (8.2)      |\n|                                      | former  |           | 230 (38.3)    |\n|                                      | never   |           | 321 (53.5)    |\n| Length of stay, days, median [Q1,Q3] |         |         0 | 1.0 [0.0,1.0] |\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n::: {.callout-warning}\n## ⚠️ Watch out: tell the software what each variable is\nSoftware guesses variable types, and the guesses are often wrong:\n\n- **ASA class** looks like a number, so it gets averaged (\"mean ASA 2.4\"). It's a category.\n- **Length of stay** has only a few distinct values, so gtsummary treats it as a category and lists \"0 days, 1 day, 2 days…\". It's a count.\n- **0/1 columns** such as `diabetes`: gtsummary shows a single row (how many are 1, i.e. yes), while tableone shows both the 0 and the 1 row. In a paper, show just the \"yes\" row.\n\nSet the type of every variable yourself (`type =` in R, `categorical =` in Python).\n:::\n\n## Mean (SD) or median (IQR)? {#which-summary}\n\n- **Roughly symmetric** continuous variables (age, BMI): mean (SD).\n- **Skewed or bounded** variables (length of stay, most PROMs): median (IQR). One patient with a 30-day stay drags the mean far more than the median.\n- **Categories**: n (%).\n\nHow do you know whether a variable is skewed? Look at it: [Distributions & choosing a test](03-distributions.qmd) shows how. Length of stay is strongly right-skewed, which is why it gets a median.\n\n::: {.callout-tip}\n## 🔀 R vs Python: quartiles\ngtsummary and tableone use different formulas for quartiles (in R's terms, `quantile()` types 2 and 7). With whole-number data the results can differ. With whole-number data like length of stay you can see the difference: the THA upper quartile is 2 days in R and 1.8 in Python. Neither is wrong. Say in your Methods which software you used.\n:::\n\n## Comparing groups {#by-group}\n\nMost studies compare groups. Here: THA vs TKA.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nby_procedure <- cohort |>\n  select(procedure, all_of(table1_vars)) |>\n  tbl_summary(\n    by        = procedure,\n    type      = list(los_days ~ \"continuous\"),\n    statistic = list(all_continuous() ~ \"{mean} ({sd})\",\n                     los_days ~ \"{median} ({p25}–{p75})\"),\n    digits    = list(all_continuous() ~ 1, los_days ~ 0),\n    label     = labels\n  ) |>\n  add_overall() |>\n  add_p(test = list(all_continuous() ~ \"t.test\",        # Welch's t test\n                    los_days ~ \"kruskal.test\",           # rank-based, for the skewed variable\n                    all_categorical() ~ \"chisq.test\"),   # chi-square\n        pvalue_fun = label_style_pvalue(digits = 3))     # p to three decimals\nby_procedure\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ebpsipftxj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ebpsipftxj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ebpsipftxj thead, #ebpsipftxj tbody, #ebpsipftxj tfoot, #ebpsipftxj tr, #ebpsipftxj td, #ebpsipftxj th {\n  border-style: none;\n}\n\n#ebpsipftxj p {\n  margin: 0;\n  padding: 0;\n}\n\n#ebpsipftxj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ebpsipftxj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ebpsipftxj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ebpsipftxj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ebpsipftxj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ebpsipftxj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ebpsipftxj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ebpsipftxj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ebpsipftxj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ebpsipftxj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ebpsipftxj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ebpsipftxj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ebpsipftxj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ebpsipftxj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ebpsipftxj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ebpsipftxj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ebpsipftxj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ebpsipftxj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ebpsipftxj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ebpsipftxj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ebpsipftxj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ebpsipftxj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ebpsipftxj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ebpsipftxj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ebpsipftxj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ebpsipftxj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ebpsipftxj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ebpsipftxj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ebpsipftxj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ebpsipftxj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ebpsipftxj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ebpsipftxj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ebpsipftxj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ebpsipftxj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ebpsipftxj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ebpsipftxj .gt_left {\n  text-align: left;\n}\n\n#ebpsipftxj .gt_center {\n  text-align: center;\n}\n\n#ebpsipftxj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ebpsipftxj .gt_font_normal {\n  font-weight: normal;\n}\n\n#ebpsipftxj .gt_font_bold {\n  font-weight: bold;\n}\n\n#ebpsipftxj .gt_font_italic {\n  font-style: italic;\n}\n\n#ebpsipftxj .gt_super {\n  font-size: 65%;\n}\n\n#ebpsipftxj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ebpsipftxj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ebpsipftxj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ebpsipftxj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ebpsipftxj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ebpsipftxj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ebpsipftxj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ebpsipftxj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ebpsipftxj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_0\"><span data-qmd-base64=\"KipPdmVyYWxsKiogIApOID0gNjAw\"><span class='gt_from_md'><strong>Overall</strong><br />\nN = 600</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"KipUSEEqKiAgCk4gPSAyNzA=\"><span class='gt_from_md'><strong>THA</strong><br />\nN = 270</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"KipUS0EqKiAgCk4gPSAzMzA=\"><span class='gt_from_md'><strong>TKA</strong><br />\nN = 330</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Age, years</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">65.5 (9.4)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">66.1 (9.5)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">65.1 (9.4)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.203</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Sex</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">343 (57%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">177 (66%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">166 (50%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">257 (43%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">93 (34%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">164 (50%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">BMI, kg/m²</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">30.4 (5.4)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">29.5 (5.3)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">31.2 (5.4)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">ASA class</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.564</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">36 (6.0%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">14 (5.2%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">22 (6.7%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">300 (50%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">143 (53%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">157 (48%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">246 (41%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">106 (39%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">140 (42%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    4</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">18 (3.0%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">7 (2.6%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">11 (3.3%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Diabetes</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">56 (9.3%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">25 (9.3%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">31 (9.4%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">>0.999</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Smoking status</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.192</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    current</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">49 (8.2%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">28 (10%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">21 (6.4%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    former</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">230 (38%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">99 (37%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">131 (40%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    never</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">321 (54%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">143 (53%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">178 (54%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Length of stay, days</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1 (0–1)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1 (0–2)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1 (0–1)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.344</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVhbiAoU0QpOyBuICglKTsgTWVkaWFuIChRMeKAk1EzKQ==\"><span class='gt_from_md'>Mean (SD); n (%); Median (Q1–Q3)</span></span></td>\n    </tr>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> <span data-qmd-base64=\"V2VsY2ggVHdvIFNhbXBsZSB0LXRlc3Q7IFBlYXJzb24ncyBDaGktc3F1YXJlZCB0ZXN0OyBLcnVza2FsLVdhbGxpcyByYW5rIHN1bSB0ZXN0\"><span class='gt_from_md'>Welch Two Sample t-test; Pearson’s Chi-squared test; Kruskal-Wallis rank sum test</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nby_procedure = TableOne(\n    cohort,\n    columns=table1_vars,\n    categorical=categorical,\n    nonnormal=[\"los_days\"],\n    groupby=\"procedure\",\n    pval=True,               # Welch's t test, Kruskal-Wallis, chi-square\n    htest_name=True,         # show which test produced each p-value\n    rename=labels,\n)\nprint(by_procedure.tabulate(tablefmt=\"github\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n|                                      |         |   Missing | Overall       | THA           | TKA           | P-Value   | Test           |\n|--------------------------------------|---------|-----------|---------------|---------------|---------------|-----------|----------------|\n| n                                    |         |           | 600           | 270           | 330           |           |                |\n| Age, years, mean (SD)                |         |         0 | 65.5 (9.4)    | 66.1 (9.5)    | 65.1 (9.4)    | 0.203     | Welch’s T-test |\n| Sex, n (%)                           | Female  |           | 343 (57.2)    | 177 (65.6)    | 166 (50.3)    | <0.001    | Chi-squared    |\n|                                      | Male    |           | 257 (42.8)    | 93 (34.4)     | 164 (49.7)    |           |                |\n| BMI, kg/m², mean (SD)                |         |         0 | 30.4 (5.4)    | 29.5 (5.3)    | 31.2 (5.4)    | <0.001    | Welch’s T-test |\n| ASA class, n (%)                     | 1       |           | 36 (6.0)      | 14 (5.2)      | 22 (6.7)      | 0.564     | Chi-squared    |\n|                                      | 2       |           | 300 (50.0)    | 143 (53.0)    | 157 (47.6)    |           |                |\n|                                      | 3       |           | 246 (41.0)    | 106 (39.3)    | 140 (42.4)    |           |                |\n|                                      | 4       |           | 18 (3.0)      | 7 (2.6)       | 11 (3.3)      |           |                |\n| Diabetes, n (%)                      | 0       |           | 544 (90.7)    | 245 (90.7)    | 299 (90.6)    | 1.000     | Chi-squared    |\n|                                      | 1       |           | 56 (9.3)      | 25 (9.3)      | 31 (9.4)      |           |                |\n| Smoking status, n (%)                | current |           | 49 (8.2)      | 28 (10.4)     | 21 (6.4)      | 0.192     | Chi-squared    |\n|                                      | former  |           | 230 (38.3)    | 99 (36.7)     | 131 (39.7)    |           |                |\n|                                      | never   |           | 321 (53.5)    | 143 (53.0)    | 178 (53.9)    |           |                |\n| Length of stay, days, median [Q1,Q3] |         |         0 | 1.0 [0.0,1.0] | 1.0 [0.0,1.8] | 1.0 [0.0,1.0] | 0.344     | Kruskal-Wallis |\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nEach p-value comes from a test you'll meet in the catalog: [Welch's t test](../catalog/06-two-unpaired-groups.qmd#unpaired-t) for the symmetric continuous variables, a [rank-based test](../catalog/06-two-unpaired-groups.qmd#mann-whitney) for length of stay (Kruskal-Wallis with two groups is the Mann-Whitney test), and the [chi-square test](../catalog/06-two-unpaired-groups.qmd#fisher-chi-square) for the categories.\n\n## p-values or standardized mean differences? {#smd}\n\nLook at sex in the table above: 66% of THA patients are women against 50% of TKA patients, p < 0.001. Is that a real difference between hip and knee patients?\n\nIn this practice dataset we know the answer, because we wrote the program that made it: sex was drawn **completely independently** of procedure. The difference is pure chance. (In real arthroplasty cohorts, TKA patients are usually *more* often female.) That's the first problem with p-values in Table 1: across a long table, chance differences turn up.\n\nThe second problem is that a p-value mixes up *how big* a difference is with *how many patients* you have. With 6,000 patients a trivial difference gets p < 0.001. With 30, a large one doesn't.\n\nThe **standardized mean difference (SMD)** measures only the size of the imbalance, in standard-deviation units, whatever the sample size. A common rule of thumb: |SMD| below 0.1 is negligible.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbalance <- cohort |>\n  select(procedure, all_of(table1_vars)) |>\n  tbl_summary(\n    by        = procedure,\n    type      = list(los_days ~ \"continuous\"),\n    statistic = list(all_continuous() ~ \"{mean} ({sd})\",\n                     los_days ~ \"{median} ({p25}–{p75})\"),\n    digits    = list(all_continuous() ~ 1, los_days ~ 0),\n    label     = labels\n  ) |>\n  add_difference(test = everything() ~ \"smd\")\nbalance\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"dayjmvlxxe\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dayjmvlxxe table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dayjmvlxxe thead, #dayjmvlxxe tbody, #dayjmvlxxe tfoot, #dayjmvlxxe tr, #dayjmvlxxe td, #dayjmvlxxe th {\n  border-style: none;\n}\n\n#dayjmvlxxe p {\n  margin: 0;\n  padding: 0;\n}\n\n#dayjmvlxxe .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dayjmvlxxe .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dayjmvlxxe .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dayjmvlxxe .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dayjmvlxxe .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dayjmvlxxe .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dayjmvlxxe .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dayjmvlxxe .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dayjmvlxxe .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dayjmvlxxe .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dayjmvlxxe .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dayjmvlxxe .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dayjmvlxxe .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dayjmvlxxe .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dayjmvlxxe .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dayjmvlxxe .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dayjmvlxxe .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dayjmvlxxe .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dayjmvlxxe .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dayjmvlxxe .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dayjmvlxxe .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dayjmvlxxe .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dayjmvlxxe .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dayjmvlxxe .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dayjmvlxxe .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dayjmvlxxe .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dayjmvlxxe .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dayjmvlxxe .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dayjmvlxxe .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dayjmvlxxe .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dayjmvlxxe .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dayjmvlxxe .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dayjmvlxxe .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dayjmvlxxe .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dayjmvlxxe .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dayjmvlxxe .gt_left {\n  text-align: left;\n}\n\n#dayjmvlxxe .gt_center {\n  text-align: center;\n}\n\n#dayjmvlxxe .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dayjmvlxxe .gt_font_normal {\n  font-weight: normal;\n}\n\n#dayjmvlxxe .gt_font_bold {\n  font-weight: bold;\n}\n\n#dayjmvlxxe .gt_font_italic {\n  font-style: italic;\n}\n\n#dayjmvlxxe .gt_super {\n  font-size: 65%;\n}\n\n#dayjmvlxxe .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dayjmvlxxe .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dayjmvlxxe .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dayjmvlxxe .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dayjmvlxxe .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dayjmvlxxe .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dayjmvlxxe .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#dayjmvlxxe .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#dayjmvlxxe div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"KipUSEEqKiAgCk4gPSAyNzA=\"><span class='gt_from_md'><strong>THA</strong><br />\nN = 270</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"KipUS0EqKiAgCk4gPSAzMzA=\"><span class='gt_from_md'><strong>TKA</strong><br />\nN = 330</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipEaWZmZXJlbmNlKio=\"><span class='gt_from_md'><strong>Difference</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Age, years</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">66.1 (9.5)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">65.1 (9.4)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.10</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.06, 0.27</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Sex</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.31</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.15, 0.47</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">177 (66%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">166 (50%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">93 (34%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">164 (50%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">BMI, kg/m²</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">29.5 (5.3)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">31.2 (5.4)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-0.33</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.50, -0.17</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">ASA class</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.12</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.04, 0.28</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">14 (5.2%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">22 (6.7%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">143 (53%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">157 (48%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">106 (39%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">140 (42%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    4</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">7 (2.6%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">11 (3.3%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Diabetes</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">25 (9.3%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">31 (9.4%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.00</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.17, 0.16</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Smoking status</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.15</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.01, 0.31</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    current</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">28 (10%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">21 (6.4%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    former</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">99 (37%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">131 (40%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    never</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">143 (53%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">178 (54%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Length of stay, days</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1 (0–2)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1 (0–1)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.07</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.09, 0.23</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVhbiAoU0QpOyBuICglKTsgTWVkaWFuIChRMeKAk1EzKQ==\"><span class='gt_from_md'>Mean (SD); n (%); Median (Q1–Q3)</span></span></td>\n    </tr>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> <span data-qmd-base64=\"U3RhbmRhcmRpemVkIE1lYW4gRGlmZmVyZW5jZQ==\"><span class='gt_from_md'>Standardized Mean Difference</span></span></td>\n    </tr>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"5\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uOiBDSSA9IENvbmZpZGVuY2UgSW50ZXJ2YWw=\"><span class='gt_from_md'>Abbreviation: CI = Confidence Interval</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nbalance = TableOne(\n    cohort,\n    columns=table1_vars,\n    categorical=categorical,\n    nonnormal=[\"los_days\"],\n    groupby=\"procedure\",\n    smd=True,\n    rename=labels,\n)\nprint(balance.smd_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         SMD (THA,TKA)\nvariable              \nage          -0.104586\nbmi           0.333603\nlos_days     -0.070965\nsex           0.312714\nasa           0.117597\ndiabetes      0.004631\nsmoker        0.147952\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nSex (SMD 0.31) and BMI (0.33) are the clear imbalances. Age (0.10), ASA class (0.12) and smoking (0.15) are just over 0.1: worth a sentence, not alarm. Diabetes and length of stay are negligible.\n\n::: {.callout-tip}\n## 🔀 R vs Python: SMDs differ slightly\n- **Sign.** gtsummary subtracts TKA from THA; tableone subtracts THA from TKA. Report the absolute value, or say which group was subtracted from which.\n- **Fourth decimal.** For continuous variables, R's `smd` package divides the variances by *n*, while tableone divides by *n − 1* (the usual textbook formula). Age comes out as 0.1048 in R and 0.1046 in Python. Categorical SMDs match exactly.\n:::\n\n**Which should you report?**\n\n- **Matched or weighted cohorts** (propensity-score studies, such as a matched study of patients over 80): SMDs only. The matching made the groups alike on purpose, so a test of \"did they differ?\" makes no sense.\n- **Other observational comparisons**: many journals still expect p-values. Give SMDs alongside, and discuss differences by their size, not their p-value.\n\n## Missing data {#missing}\n\nThe tidy version of the messy workbook from [page 1](01-tidy-data.qmd) has a few BMIs, ASA classes and lengths of stay that the abstractor couldn't find. Missing values must show up in Table 1. Never drop them silently.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabstraction <- read_csv(\"data/answer-keys/abstraction_workbook_tidy.csv\", show_col_types = FALSE) |>\n  mutate(asa = factor(asa))\n\nabstraction |>\n  select(site, age, bmi, asa, los_days) |>\n  tbl_summary(by = site, type = list(los_days ~ \"continuous\"),\n              statistic = list(all_continuous() ~ \"{mean} ({sd})\",\n                               los_days ~ \"{median} ({p25}–{p75})\"),\n              digits = list(all_continuous() ~ 1, los_days ~ 0),\n              missing_text = \"Missing\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qzwwiiyfcr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qzwwiiyfcr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qzwwiiyfcr thead, #qzwwiiyfcr tbody, #qzwwiiyfcr tfoot, #qzwwiiyfcr tr, #qzwwiiyfcr td, #qzwwiiyfcr th {\n  border-style: none;\n}\n\n#qzwwiiyfcr p {\n  margin: 0;\n  padding: 0;\n}\n\n#qzwwiiyfcr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qzwwiiyfcr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qzwwiiyfcr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qzwwiiyfcr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qzwwiiyfcr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qzwwiiyfcr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qzwwiiyfcr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qzwwiiyfcr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qzwwiiyfcr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qzwwiiyfcr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qzwwiiyfcr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qzwwiiyfcr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qzwwiiyfcr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qzwwiiyfcr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qzwwiiyfcr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qzwwiiyfcr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qzwwiiyfcr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qzwwiiyfcr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qzwwiiyfcr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qzwwiiyfcr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qzwwiiyfcr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qzwwiiyfcr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qzwwiiyfcr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qzwwiiyfcr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qzwwiiyfcr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qzwwiiyfcr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qzwwiiyfcr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qzwwiiyfcr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qzwwiiyfcr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qzwwiiyfcr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qzwwiiyfcr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qzwwiiyfcr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qzwwiiyfcr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qzwwiiyfcr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qzwwiiyfcr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qzwwiiyfcr .gt_left {\n  text-align: left;\n}\n\n#qzwwiiyfcr .gt_center {\n  text-align: center;\n}\n\n#qzwwiiyfcr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qzwwiiyfcr .gt_font_normal {\n  font-weight: normal;\n}\n\n#qzwwiiyfcr .gt_font_bold {\n  font-weight: bold;\n}\n\n#qzwwiiyfcr .gt_font_italic {\n  font-style: italic;\n}\n\n#qzwwiiyfcr .gt_super {\n  font-size: 65%;\n}\n\n#qzwwiiyfcr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qzwwiiyfcr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qzwwiiyfcr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qzwwiiyfcr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qzwwiiyfcr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qzwwiiyfcr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qzwwiiyfcr .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#qzwwiiyfcr .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#qzwwiiyfcr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"KipTaXRlIEEqKiAgCk4gPSA2MA==\"><span class='gt_from_md'><strong>Site A</strong><br />\nN = 60</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"KipTaXRlIEIqKiAgCk4gPSA2MA==\"><span class='gt_from_md'><strong>Site B</strong><br />\nN = 60</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">age</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">65.1 (8.5)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">64.2 (8.9)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">bmi</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">29.5 (5.2)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">29.7 (5.3)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Missing</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">5</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">3</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">asa</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">6 (10%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">6 (10%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">30 (52%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">31 (53%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">22 (38%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">22 (37%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Missing</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">los_days</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1 (0–2)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1 (0–1)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Missing</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">2</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"3\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVhbiAoU0QpOyBuICglKTsgTWVkaWFuIChRMeKAk1EzKQ==\"><span class='gt_from_md'>Mean (SD); n (%); Median (Q1–Q3)</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nabstraction = pd.read_csv(\"data/answer-keys/abstraction_workbook_tidy.csv\")\nabstraction[\"asa\"] = abstraction[\"asa\"].astype(\"Int64\").astype(\"string\")   # a category; blanks stay missing\n\nmissing_table = TableOne(abstraction, columns=[\"age\", \"bmi\", \"asa\", \"los_days\"],\n                         categorical=[\"asa\"], nonnormal=[\"los_days\"],\n                         groupby=\"site\", missing=True,\n                         include_null=False)   # count blanks as missing, not as a \"None\" category\nprint(missing_table.tabulate(tablefmt=\"github\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n|                          |    |   Missing | Overall       | Site A        | Site B        |\n|--------------------------|----|-----------|---------------|---------------|---------------|\n| n                        |    |           | 120           | 60            | 60            |\n| age, mean (SD)           |    |         0 | 64.7 (8.7)    | 65.1 (8.5)    | 64.2 (8.9)    |\n| bmi, mean (SD)           |    |         8 | 29.6 (5.2)    | 29.5 (5.2)    | 29.7 (5.3)    |\n| asa, n (%)               |  1 |         3 | 12 (10.3)     | 6 (10.3)      | 6 (10.2)      |\n|                          |  2 |           | 61 (52.1)     | 30 (51.7)     | 31 (52.5)     |\n|                          |  3 |           | 44 (37.6)     | 22 (37.9)     | 22 (37.3)     |\n| los_days, median [Q1,Q3] |    |         3 | 1.0 [0.0,2.0] | 1.0 [0.0,2.0] | 1.0 [0.0,1.0] |\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nR adds a \"Missing\" row under each variable that has any. Python adds a \"Missing\" column. Either way, the percentages are of the patients with a value, and the reader can see how many were left out.\n\n## Exporting to Word {#export}\n\nJournals want Table 1 in Word. Save it into your `scratch/` folder (git ignores it), open it, and paste it into the manuscript.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nby_procedure |>\n  as_flex_table() |>\n  flextable::save_as_docx(path = \"scratch/table1.docx\")\n```\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom docx import Document\n\ntable = by_procedure.tableone.reset_index()\nheaders = [\" \".join(str(part) for part in col if part).strip() for col in table.columns]\n\ndoc = Document()\ngrid = doc.add_table(rows=1, cols=len(headers))\nfor cell, header in zip(grid.rows[0].cells, headers):\n    cell.text = header\nfor _, row in table.iterrows():\n    for cell, value in zip(grid.add_row().cells, row):\n        cell.text = \"\" if pd.isna(value) else str(value)\ndoc.save(\"scratch/table1-python.docx\")\n```\n:::\n\n:::\n\nIn Word, tidy the formatting to the journal's style: usually no vertical lines, and a footnote that says which statistics are shown (\"mean (SD); median (IQR); n (%)\") and which tests produced the p-values.\n\n\n\n\n\n## Exercises {#exercises}\n\n**1.** Make a Table 1 comparing **Site A with Site B** instead of THA with TKA. Which variable differs most between sites, by SMD?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohort |>\n  select(site, all_of(table1_vars)) |>\n  tbl_summary(by = site, type = list(los_days ~ \"continuous\"),\n              statistic = list(all_continuous() ~ \"{mean} ({sd})\",\n                               los_days ~ \"{median} ({p25}–{p75})\"),\n              digits = list(all_continuous() ~ 1, los_days ~ 0),\n              label = labels) |>\n  add_difference(test = everything() ~ \"smd\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"fsvbhngdtx\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fsvbhngdtx table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fsvbhngdtx thead, #fsvbhngdtx tbody, #fsvbhngdtx tfoot, #fsvbhngdtx tr, #fsvbhngdtx td, #fsvbhngdtx th {\n  border-style: none;\n}\n\n#fsvbhngdtx p {\n  margin: 0;\n  padding: 0;\n}\n\n#fsvbhngdtx .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fsvbhngdtx .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fsvbhngdtx .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fsvbhngdtx .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fsvbhngdtx .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fsvbhngdtx .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fsvbhngdtx .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fsvbhngdtx .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fsvbhngdtx .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fsvbhngdtx .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fsvbhngdtx .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fsvbhngdtx .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fsvbhngdtx .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fsvbhngdtx .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fsvbhngdtx .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fsvbhngdtx .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fsvbhngdtx .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fsvbhngdtx .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fsvbhngdtx .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsvbhngdtx .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fsvbhngdtx .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fsvbhngdtx .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fsvbhngdtx .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsvbhngdtx .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fsvbhngdtx .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fsvbhngdtx .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fsvbhngdtx .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsvbhngdtx .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fsvbhngdtx .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fsvbhngdtx .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fsvbhngdtx .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fsvbhngdtx .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fsvbhngdtx .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsvbhngdtx .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fsvbhngdtx .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsvbhngdtx .gt_left {\n  text-align: left;\n}\n\n#fsvbhngdtx .gt_center {\n  text-align: center;\n}\n\n#fsvbhngdtx .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fsvbhngdtx .gt_font_normal {\n  font-weight: normal;\n}\n\n#fsvbhngdtx .gt_font_bold {\n  font-weight: bold;\n}\n\n#fsvbhngdtx .gt_font_italic {\n  font-style: italic;\n}\n\n#fsvbhngdtx .gt_super {\n  font-size: 65%;\n}\n\n#fsvbhngdtx .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fsvbhngdtx .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fsvbhngdtx .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fsvbhngdtx .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fsvbhngdtx .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fsvbhngdtx .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fsvbhngdtx .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#fsvbhngdtx .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#fsvbhngdtx div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"KipTaXRlIEEqKiAgCk4gPSAyOTA=\"><span class='gt_from_md'><strong>Site A</strong><br />\nN = 290</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"KipTaXRlIEIqKiAgCk4gPSAzMTA=\"><span class='gt_from_md'><strong>Site B</strong><br />\nN = 310</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipEaWZmZXJlbmNlKio=\"><span class='gt_from_md'><strong>Difference</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Age, years</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">65.6 (9.6)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">65.4 (9.3)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.02</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.14, 0.18</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Sex</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.06</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.10, 0.22</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">170 (59%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">173 (56%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">120 (41%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">137 (44%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">BMI, kg/m²</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">30.5 (5.6)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">30.4 (5.3)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.03</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.13, 0.19</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">ASA class</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.10</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.06, 0.26</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">14 (4.8%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">22 (7.1%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">144 (50%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">156 (50%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">123 (42%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">123 (40%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    4</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">9 (3.1%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">9 (2.9%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Diabetes</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">23 (7.9%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">33 (11%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-0.09</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.25, 0.07</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Smoking status</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.23</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.07, 0.39</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    current</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">31 (11%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">18 (5.8%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    former</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">98 (34%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">132 (43%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    never</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">161 (56%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">160 (52%)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Length of stay, days</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1 (0–2)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0 (0–1)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.22</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.06, 0.39</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVhbiAoU0QpOyBuICglKTsgTWVkaWFuIChRMeKAk1EzKQ==\"><span class='gt_from_md'>Mean (SD); n (%); Median (Q1–Q3)</span></span></td>\n    </tr>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> <span data-qmd-base64=\"U3RhbmRhcmRpemVkIE1lYW4gRGlmZmVyZW5jZQ==\"><span class='gt_from_md'>Standardized Mean Difference</span></span></td>\n    </tr>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"5\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uOiBDSSA9IENvbmZpZGVuY2UgSW50ZXJ2YWw=\"><span class='gt_from_md'>Abbreviation: CI = Confidence Interval</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nby_site = TableOne(cohort, columns=table1_vars, categorical=categorical,\n                   nonnormal=[\"los_days\"], groupby=\"site\", smd=True, rename=labels)\nprint(by_site.smd_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         SMD (Site A,Site B)\nvariable                    \nage                -0.019922\nbmi                -0.027907\nlos_days           -0.224577\nsex                 0.056903\nasa                 0.103498\ndiabetes            0.093607\nsmoker              0.229484\n```\n\n\n:::\n:::\n\n:::\n\nSmoking status (0.23) and length of stay (0.22) differ most between sites, and their 95% CIs exclude zero. Yet site was assigned completely at random in this dataset, independent of everything else. With seven variables, a couple of chance imbalances above 0.1 are to be expected: judge each SMD by its size and by whether it could plausibly matter, not by whether it is \"significant\".\n:::\n\n**2.** A fellow is comparing patients aged 80 or older with younger patients, matched on sex, BMI and ASA class. Should the baseline table show p-values or SMDs? Why?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nSMDs. The matching was designed to make the groups alike, so testing whether they differ answers a question nobody asked, and with matched data the p-value mostly reflects sample size. SMDs show how well the matching worked: aim for |SMD| below 0.1 on every matching variable.\n:::\n\n**3.** Write the first sentence of the Results describing this cohort, using the reporting conventions from [How to use this site](../getting-started/using-this-site.qmd).\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\"We included 600 primary arthroplasties (270 THA and 330 TKA) in 520 patients. Mean age was 65.5 (SD 9.4) years and 343 procedures (57%) were in women. Median length of stay was 1 (IQR 0–1) day.\"\n\nCheck every number against your own table: mean and SD for age, n (%) for sex, median (IQR) for length of stay.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}