{
  "hash": "4bca2e905519dcc4ddf9790c138ab500",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"8 · Compare three or more unmatched groups\"\ndescription: \"One-way ANOVA, Kruskal-Wallis test, chi-square test and Cox regression: three or more groups of different patients.\"\nengine: knitr\ntoc-depth: 2\n---\n\n\n\n<!-- data-checksum: 9e548efb7ad4232927ffa99aa2cdeca7 -->\n\nThree or more groups of **different** patients: the four ASA classes, the three surgeons, implants A, B and C. You could compare every pair of groups with the tests on [page 6](06-two-unpaired-groups.qmd), but each extra test is another chance of a false positive. The tests on this page ask one question first: **is there any difference among the groups at all?** If the answer is yes, [Which groups differ?](#which-groups-differ) explains the next step.\n\n::: {.callout-note}\n## 💡 How every section on this page works\nEach section answers one question about the practice cohort. Its first code block loads the packages and the data, so you can jump straight to the section you need. Run that section's blocks in order, top to bottom.\n\nTo keep the code short, the examples use every case, including the 80 patients who had both sides operated on. In a real study, decide how to handle them ([page 3](../foundations/03-distributions.qmd#paired)) and say what you did.\n:::\n\n## One-way ANOVA {#one-way-anova}\n\n**The question:** Does age at surgery differ across ASA classes 1 to 4?\n\n### When to use it\n\n- The outcome is a **measurement**, compared across **three or more independent groups**.\n- Within **each group** it's roughly normal, or each group is reasonably large and not badly skewed ([page 3](../foundations/03-distributions.qmd#within-groups)).\n- The groups have **similar spreads**: as a rule of thumb, the largest SD is no more than about twice the smallest. If not, use **Welch's ANOVA** (see the R vs Python box), especially when the group sizes are unequal.\n- If the outcome is skewed, bounded or ordinal → the [Kruskal-Wallis test](#kruskal-wallis).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE) |>\n  mutate(asa = factor(asa))   # ASA class is a group, not a number\n\nggplot(cohort, aes(asa, age)) +\n  geom_boxplot() +\n  labs(x = \"ASA class\", y = \"Age at surgery, years\")\n```\n\n::: {.cell-output-display}\n![](08-three-plus-unmatched_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncohort |>\n  group_by(asa) |>\n  summarise(n = n(), mean = mean(age), sd = sd(age))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  asa       n  mean    sd\n  <fct> <int> <dbl> <dbl>\n1 1        36  59.8  8.66\n2 2       300  63.4  9.08\n3 3       246  68.4  8.77\n4 4        18  73.7  9.31\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport pingouin as pg\nimport matplotlib.pyplot as plt\nfrom scipy import stats\n\ncohort = pd.read_csv(\"data/cohort.csv\")\nages = [group[\"age\"] for asa, group in cohort.groupby(\"asa\")]   # one list of ages per ASA class\n\nfig, ax = plt.subplots(figsize=(6, 3))\nparts = ax.boxplot(ages, tick_labels=[\"1\", \"2\", \"3\", \"4\"])   # naming the result keeps it out of the output\nax.set_xlabel(\"ASA class\")\nax.set_ylabel(\"Age at surgery, years\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](08-three-plus-unmatched_files/figure-html/unnamed-chunk-4-1.png)\n:::\n\n```{.python .cell-code}\nprint(cohort.groupby(\"asa\")[\"age\"].agg([\"count\", \"mean\", \"std\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     count       mean       std\nasa                            \n1       36  59.750000  8.663140\n2      300  63.396667  9.082637\n3      246  68.357724  8.767873\n4       18  73.666667  9.305280\n```\n\n\n:::\n:::\n\n:::\n\nAge rises steadily with ASA class. The SDs are all close to 9 years, so the spreads are similar. The groups are very different in size, though: 300 procedures in ASA 2, only 18 in ASA 4.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_anova <- aov(age ~ asa, data = cohort)   # aov() fits the classic one-way ANOVA\nsummary(age_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value   Pr(>F)    \nasa           3   5727  1908.9    23.9 1.28e-14 ***\nResiduals   596  47599    79.9                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nage_anova = pg.anova(data=cohort, dv=\"age\", between=\"asa\", detailed=True)   # classic one-way ANOVA\nprint(age_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Source            SS   DF           MS          F         p_unc       np2\n0     asa   5726.693008    3  1908.897669  23.901792  1.284107e-14  0.107391\n1  Within  47599.066992  596    79.864206        NaN           NaN       NaN\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **asa row:** the variation **between** the group means. **Df = 3** (four groups minus one), **Sum Sq = 5727**.\n- **Residuals** (R) or **Within** (Python): the variation of patients **within** their groups. **Df = 596** (600 procedures minus four groups).\n- **F = 23.9:** the between-group variation divided by the within-group variation, each per degree of freedom. If the groups had the same mean, F would be close to 1.\n- **p < 0.001** (R prints `1.28e-14`): ages this different across groups would be very unlikely if every ASA class had the same mean age.\n\n### Effect size and 95% CI\n\n**Omega squared (ω²)** is the share of the variation in age that ASA class accounts for, corrected for the small upward bias of the simpler eta squared (η²). As a rough guide, 0.01 is small, 0.06 medium and 0.14 large.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffectsize::omega_squared(age_anova, partial = FALSE)   # plain (not partial) omega squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA (Type I)\n\nParameter | Omega2 |       95% CI\n---------------------------------\nasa       |   0.10 | [0.06, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# omega squared from the ANOVA table: (SS between - df between × MS within) / (SS total + MS within)\nss_between, ss_within = age_anova.loc[0, \"SS\"], age_anova.loc[1, \"SS\"]\ndf_between, ms_within = age_anova.loc[0, \"DF\"], age_anova.loc[1, \"MS\"]\nomega2 = (ss_between - df_between * ms_within) / (ss_between + ss_within + ms_within)\nprint(omega2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.10274386772151635\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nω² = 0.10: ASA class accounts for about a tenth of the variation in age, a medium effect. R also prints a one-sided 95% CI (0.06 to 1.00): ω² can't be negative, so only its lower bound is informative. scipy and pingouin don't compute this CI. The ANOVA doesn't say *which* classes differ: see [Which groups differ?](#which-groups-differ).\n\n### How to report it\n\n> **Methods:** Age was compared across ASA classes with one-way analysis of variance (ANOVA), with omega squared (ω²) as the effect size.\n>\n> **Results:** Mean age was 59.8 years (SD 8.7) in ASA 1 and 73.7 years (SD 9.3) in ASA 4 (one-way ANOVA, F(3, 596) = 23.9, p < 0.001; ω² = 0.10, one-sided 95% CI 0.06 to 1.00).\n\n::: {.callout-warning}\n## ⚠️ Watch out: ANOVA doesn't tell you which groups differ\nA significant ANOVA means at least one group mean differs from another, not that every group differs from every other. Don't follow it with a string of unadjusted t tests: that brings back the false-positive problem the ANOVA was meant to avoid. Use a post-hoc test ([page 15](../beyond/15-post-hoc.qmd#after-anova)).\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: classic or Welch's ANOVA\n- **Classic ANOVA** assumes the groups have the same spread. R's `aov()`, scipy's `f_oneway()` and pingouin's `anova()` all run it by default.\n- **Welch's ANOVA** doesn't assume equal spreads. R's `oneway.test()` runs **Welch's** version by default (add `var.equal = TRUE` for the classic one), the opposite of `aov()`. In Python use `pg.welch_anova()` or `stats.f_oneway(..., equal_var=False)`.\n- Here the SDs are similar, and Welch's ANOVA agrees: F = 23.5, p < 0.001.\n:::\n\n\n\n\n\n## Kruskal-Wallis test {#kruskal-wallis}\n\n**The question:** Does satisfaction 1 year after surgery differ between surgeons S1, S2 and S3?\n\n### When to use it\n\n- The outcome is **ordinal** (satisfaction from 1 to 5), **skewed**, or has a **ceiling or floor**, compared across **three or more independent groups**.\n- Like the [Mann-Whitney test](06-two-unpaired-groups.qmd#mann-whitney), it works on ranks: it asks whether values in some groups tend to be larger than in others.\n- With two groups it gives essentially the same result as the Mann-Whitney test.\n- If the outcome is a roughly normal measurement → [one-way ANOVA](#one-way-anova).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\nsatisfied <- cohort |> filter(!is.na(satisfaction_1yr))   # patients who answered\n\ncount(satisfied, surgeon, satisfaction_1yr) |>\n  pivot_wider(names_from = satisfaction_1yr, values_from = n)   # one row per surgeon\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 6\n  surgeon   `1`   `2`   `3`   `4`   `5`\n  <chr>   <int> <int> <int> <int> <int>\n1 S1          4     8    21    68    91\n2 S2          6    13    18    50    90\n3 S3          5     2    13    44    69\n```\n\n\n:::\n\n```{.r .cell-code}\nsatisfied |>\n  group_by(surgeon) |>\n  summarise(n = n(), median = median(satisfaction_1yr),\n            q1 = quantile(satisfaction_1yr, 0.25), q3 = quantile(satisfaction_1yr, 0.75))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  surgeon     n median    q1    q3\n  <chr>   <int>  <dbl> <dbl> <dbl>\n1 S1        192      4     4     5\n2 S2        177      5     4     5\n3 S3        133      5     4     5\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nfrom scipy import stats\n\ncohort = pd.read_csv(\"data/cohort.csv\")\nsatisfied = cohort.dropna(subset=[\"satisfaction_1yr\"])   # patients who answered\n\nprint(pd.crosstab(satisfied[\"surgeon\"], satisfied[\"satisfaction_1yr\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsatisfaction_1yr  1.0  2.0  3.0  4.0  5.0\nsurgeon                                  \nS1                  4    8   21   68   91\nS2                  6   13   18   50   90\nS3                  5    2   13   44   69\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(satisfied.groupby(\"surgeon\")[\"satisfaction_1yr\"].describe()[[\"count\", \"25%\", \"50%\", \"75%\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         count  25%  50%  75%\nsurgeon                      \nS1       192.0  4.0  4.0  5.0\nS2       177.0  4.0  5.0  5.0\nS3       133.0  4.0  5.0  5.0\n```\n\n\n:::\n:::\n\n:::\n\nSatisfaction was reported for 502 of the 600 procedures. Most were satisfied (4) or very satisfied (5) with every surgeon, and the three distributions look much alike.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsatisfaction_test <- kruskal.test(satisfaction_1yr ~ surgeon, data = satisfied)\nsatisfaction_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  satisfaction_1yr by surgeon\nKruskal-Wallis chi-squared = 0.67685, df = 2, p-value = 0.7129\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nscores = [group[\"satisfaction_1yr\"] for surgeon, group in satisfied.groupby(\"surgeon\")]   # one list per surgeon\nsatisfaction_test = stats.kruskal(*scores)\nprint(satisfaction_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKruskalResult(statistic=np.float64(0.6768533761048873), pvalue=np.float64(0.7128910409037716))\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **Kruskal-Wallis chi-squared = 0.68** (R) or **statistic** (Python): the H statistic. It measures how far apart the groups' average ranks are. Both programs correct it for the many tied scores.\n- **df = 2:** three groups minus one.\n- **p = 0.713:** satisfaction this similar, or less, would be very common if the surgeons' patients were equally satisfied.\n\n### Effect size and 95% CI\n\n**Epsilon squared (ε²)** is the rank-based counterpart of ω²: the share of the variation in the ranks that the groups account for, from 0 to 1. It is H divided by (n − 1).\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)   # its CI comes from a bootstrap (random resampling); a seed makes it repeatable\neffectsize::rank_epsilon_squared(satisfaction_1yr ~ surgeon, data = satisfied)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEpsilon2 (rank) |       95% CI\n------------------------------\n1.35e-03        | [0.00, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nepsilon2 = satisfaction_test.statistic / (len(satisfied) - 1)   # H / (n - 1)\nprint(epsilon2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.0013510047427243259\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nε² = 0.001: surgeon accounts for essentially none of the variation in satisfaction. R's one-sided CI runs from 0.00 to 1.00; it comes from a bootstrap, which is why the code sets a seed. scipy has no function for it.\n\n### How to report it\n\n> **Methods:** Satisfaction at 1 year (a 5-point ordinal scale) was compared across surgeons with the Kruskal-Wallis test, with epsilon squared (ε²) as the effect size.\n>\n> **Results:** Of 600 procedures, 502 had a satisfaction score at 1 year. The median was 4 (IQR 4 to 5) for surgeon S1 and 5 (IQR 4 to 5) for surgeons S2 and S3 (Kruskal-Wallis H = 0.68, df = 2, p = 0.713; ε² = 0.001, one-sided 95% CI 0.00 to 1.00).\n\n::: {.callout-warning}\n## ⚠️ Watch out: missing answers aren't random\nSatisfaction is missing for 98 procedures. If unhappy patients were less likely to answer, every surgeon looks better than they are, and the comparison can be biased too. Always report how many answered in each group, and consider whether non-response differs between groups.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: ties and the data format\nBoth `kruskal.test()` and `stats.kruskal()` correct H for ties, so they agree even with a 5-point scale full of tied scores. R takes a formula (`outcome ~ group`); scipy takes one list of values per group, which is why the Python code builds `scores` first.\n:::\n\n## Chi-square test {#chi-square}\n\n**The question:** Do 90-day complication rates differ between surgeons S1, S2 and S3?\n\n### When to use it\n\n- The outcome is **categorical** (here yes/no), compared across **three or more independent groups**: an r × c table.\n- Every **expected** count should be at least 5. If not, combine categories that make sense together, or use Fisher's exact test, which R's `fisher.test()` runs exactly on larger tables too. scipy's `stats.fisher_exact()` accepts larger tables but estimates their p-value by random resampling, so it changes a little from run to run.\n- With two groups and a yes/no outcome → [Fisher's exact test](06-two-unpaired-groups.qmd#fisher-chi-square).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\n\ncomplication_table <- table(\n  surgeon      = cohort$surgeon,\n  complication = factor(cohort$complication_90d, levels = c(1, 0), labels = c(\"yes\", \"no\"))\n)\ncomplication_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       complication\nsurgeon yes  no\n     S1  15 217\n     S2  24 187\n     S3  12 145\n```\n\n\n:::\n\n```{.r .cell-code}\nprop.table(complication_table, margin = 1)   # row percentages: complications per surgeon\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       complication\nsurgeon        yes         no\n     S1 0.06465517 0.93534483\n     S2 0.11374408 0.88625592\n     S3 0.07643312 0.92356688\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nfrom scipy import stats\nfrom scipy.stats.contingency import association\n\ncohort = pd.read_csv(\"data/cohort.csv\")\n\ncomplication_table = pd.crosstab(cohort[\"surgeon\"], cohort[\"complication_90d\"]).loc[:, [1, 0]]   # \"yes\" first\nprint(complication_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncomplication_90d   1    0\nsurgeon                  \nS1                15  217\nS2                24  187\nS3                12  145\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.crosstab(cohort[\"surgeon\"], cohort[\"complication_90d\"], normalize=\"index\"))   # row percentages\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncomplication_90d         0         1\nsurgeon                             \nS1                0.935345  0.064655\nS2                0.886256  0.113744\nS3                0.923567  0.076433\n```\n\n\n:::\n:::\n\n:::\n\nComplications followed 6.5% of S1's procedures, 11.4% of S2's and 7.6% of S3's.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomplication_test <- chisq.test(complication_table)\ncomplication_test$expected      # all at least 5, so the chi-square test is valid\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       complication\nsurgeon    yes      no\n     S1 19.720 212.280\n     S2 17.935 193.065\n     S3 13.345 143.655\n```\n\n\n:::\n\n```{.r .cell-code}\ncomplication_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  complication_table\nX-squared = 3.6243, df = 2, p-value = 0.1633\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ncomplication_test = stats.chi2_contingency(complication_table)\nprint(complication_test.expected_freq)   # all at least 5, so the chi-square test is valid\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[ 19.72  212.28 ]\n [ 17.935 193.065]\n [ 13.345 143.655]]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(complication_test.statistic, complication_test.dof, complication_test.pvalue)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3.6243376193045225 2 0.16329958674594236\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **Expected counts:** what each cell would hold if complication rates were the same for every surgeon. The smallest is 13.3, so the test is valid.\n- **X-squared = 3.62, df = 2:** the chi-square statistic, with (3 surgeons − 1) × (2 outcomes − 1) = 2 degrees of freedom.\n- **p = 0.163:** differences like these would be fairly common if the three surgeons had the same complication rate.\n\n### Effect size and 95% CI\n\n**Cramér's V** measures the strength of association in a table, from 0 (none) to 1 (perfect). For a table with 2 columns, about 0.1 is small, 0.3 medium and 0.5 large.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffectsize::cramers_v(complication_table, adjust = FALSE)   # see the R vs Python box\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCramer's V |       95% CI\n-------------------------\n0.08       | [0.00, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprint(association(complication_table, method=\"cramer\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.0777210569848408\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nV = 0.08, a small association. For yes/no outcomes, the complication rate in each group (with its CI, as on [page 4](04-describe-one-group.qmd#proportion)) is usually more informative than V.\n\n### How to report it\n\n> **Methods:** Complication rates were compared across surgeons with the chi-square test, with Cramér's V as the effect size.\n>\n> **Results:** Complications within 90 days followed 15 of 232 procedures by surgeon S1 (6.5%), 24 of 211 by S2 (11.4%) and 12 of 157 by S3 (7.6%) (χ² = 3.62, df = 2, p = 0.163; Cramér's V = 0.08, one-sided 95% CI 0.00 to 1.00).\n\n::: {.callout-warning}\n## ⚠️ Watch out: no Yates' correction here, and check the expected counts\nYates' continuity correction ([page 6](06-two-unpaired-groups.qmd#fisher-chi-square)) only applies to 2 × 2 tables, so both programs skip it for this 3 × 2 table. The expected-count rule still applies: Exercise 3 shows a table that breaks it, and what to do.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: two versions of Cramér's V\neffectsize's `cramers_v()` applies a small-sample **bias correction** by default (0.05 here). scipy's `association()` doesn't (0.08). We set `adjust = FALSE` in R so the two match. Either is acceptable; say which you report.\n:::\n\n## Cox regression {#cox}\n\n**The question:** Does the risk of revision differ between implants A, B and C?\n\n### When to use it\n\n- The outcome is **time until an event** (revision), compared across **three or more independent groups**.\n- The **log-rank test** extends to three or more groups and answers \"do the curves differ?\". **Cox regression** also gives a hazard ratio for each group against a reference group, and can adjust for other variables.\n- It assumes each group's risk is a steady multiple of the reference group's over time (**proportional hazards**). [Page 14](../survival/14-cox-regression.qmd#proportional-hazards) shows how to check that and covers Cox regression in full.\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(survival)\nlibrary(ggsurvfit)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\n\nsurvfit2(Surv(followup_years, revised) ~ implant, data = cohort, conf.type = \"log-log\") |>\n  ggsurvfit() +\n  add_risktable() +\n  scale_ggsurvfit() +\n  labs(x = \"Years since surgery\", y = \"Revision-free survival\")\n```\n\n::: {.cell-output-display}\n![](08-three-plus-unmatched_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom lifelines import KaplanMeierFitter, CoxPHFitter\nfrom lifelines.statistics import multivariate_logrank_test\nfrom lifelines.plotting import add_at_risk_counts\n\ncohort = pd.read_csv(\"data/cohort.csv\")\n\nfig, ax = plt.subplots(figsize=(7, 4.5))\ncurves = []\nfor implant, group in cohort.groupby(\"implant\"):\n    km = KaplanMeierFitter(label=implant).fit(group[\"followup_years\"], group[\"revised\"])\n    km.plot_survival_function(ax=ax, ci_show=False)\n    curves.append(km)\nax.set_xlabel(\"Years since surgery\")\nax.set_ylabel(\"Revision-free survival\")\nadd_at_risk_counts(*curves, ax=ax)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](08-three-plus-unmatched_files/figure-html/unnamed-chunk-36-1.png)\n:::\n:::\n\n:::\n\nImplants A and B track each other closely; implant C falls away from both.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimplant_cox <- coxph(Surv(followup_years, revised) ~ implant, data = cohort)   # implant A is the reference\nsummary(implant_cox)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(followup_years, revised) ~ implant, data = cohort)\n\n  n= 600, number of events= 81 \n\n            coef exp(coef) se(coef)      z Pr(>|z|)    \nimplantB -0.2020    0.8171   0.3092 -0.653    0.514    \nimplantC  1.1208    3.0673   0.2579  4.345 1.39e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n         exp(coef) exp(-coef) lower .95 upper .95\nimplantB    0.8171      1.224    0.4458     1.498\nimplantC    3.0673      0.326    1.8502     5.085\n\nConcordance= 0.659  (se = 0.03 )\nLikelihood ratio test= 27.64  on 2 df,   p=1e-06\nWald test            = 29.63  on 2 df,   p=4e-07\nScore (logrank) test = 33.48  on 2 df,   p=5e-08\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimplant_cox = CoxPHFitter().fit(\n    cohort[[\"followup_years\", \"revised\", \"implant\"]],\n    duration_col=\"followup_years\", event_col=\"revised\", formula=\"implant\",   # implant A is the reference\n    fit_options={\"precision\": 1e-9},   # stop only when fully converged; see the R vs Python box\n)\nprint(implant_cox.summary[[\"exp(coef)\", \"exp(coef) lower 95%\", \"exp(coef) upper 95%\", \"p\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              exp(coef)  exp(coef) lower 95%  exp(coef) upper 95%         p\ncovariate                                                                  \nimplant[T.B]   0.817091             0.445762             1.497745  0.513515\nimplant[T.C]   3.067344             1.850158             5.085296  0.000014\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(implant_cox.log_likelihood_ratio_test().test_statistic)            # overall test, all implants\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n27.63546691821921\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(multivariate_logrank_test(cohort[\"followup_years\"], cohort[\"implant\"], cohort[\"revised\"]).test_statistic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n33.46861907356945\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **exp(coef):** the hazard ratio of each implant against implant A, the reference. Implant B: 0.82; implant C: 3.07.\n- **lower .95 / upper .95:** the 95% CIs. Implant B's (0.45 to 1.50) includes 1, so the data are compatible with no difference from A. Implant C's (1.85 to 5.09) doesn't.\n- **Pr(>|z|):** the p-value for each implant against A (p = 0.514 for B, p < 0.001 for C).\n- **Likelihood ratio test = 27.6 on 2 df, p < 0.001:** the overall test that implant matters at all, the Cox counterpart of the ANOVA's F test. Python prints it as the second number.\n- **Score (logrank) test = 33.5:** the log-rank test for all three implants, which Python prints last. (The Cox score test and the log-rank test handle tied revision times slightly differently, so they agree to one decimal, not exactly.)\n\n### Effect size and 95% CI\n\nThe **hazard ratios** with their 95% CIs are the effect sizes: implant C carried about three times the hazard of revision of implant A (3.07, 95% CI 1.85 to 5.09), while implant B didn't differ clearly from A (0.82, 95% CI 0.45 to 1.50).\n\n### How to report it\n\n> **Methods:** Revision-free survival was compared across implants with Cox proportional hazards regression, with implant A as the reference.\n>\n> **Results:** Compared with implant A, the hazard ratio for revision was 3.07 (95% CI 1.85 to 5.09) for implant C and 0.82 (95% CI 0.45 to 1.50) for implant B (likelihood ratio test for implant type, χ² = 27.6, df = 2, p < 0.001).\n\n::: {.callout-warning}\n## ⚠️ Watch out: the reference group shapes the story\nEvery hazard ratio here is relative to implant A, so the output doesn't compare B with C directly. Choose the reference group on purpose (the standard implant, the largest group) and say which it is. And as on [page 4](04-describe-one-group.qmd#kaplan-meier), deaths here are treated as censored; [page 13](../survival/13-kaplan-meier.qmd#competing-risks) covers competing risks.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: convergence and the reference group\nBoth programs use the first group alphabetically (A) as the reference and handle tied revision times with Efron's method. lifelines' default convergence rule stops a little early here (a hazard ratio of 0.81713 for implant B instead of 0.81709), so we tighten it with `fit_options={\"precision\": 1e-9}`.\n:::\n\n## Which groups differ? {#which-groups-differ}\n\nThe tests above answer \"is there any difference among the groups?\". When the answer is yes, the next question is which groups differ from which. Comparing every pair with an ordinary test inflates the chance of a false positive: with four ASA classes there are six pairs, and six tests at p < 0.05 give roughly a one-in-four chance of at least one false alarm even when nothing is going on.\n\n**Post-hoc tests** compare the pairs while keeping that overall error rate at 5%:\n\n| After | Use | Page |\n|---|---|---|\n| One-way ANOVA | Tukey's HSD (Games-Howell if the spreads differ) | [15](../beyond/15-post-hoc.qmd#after-anova) |\n| Kruskal-Wallis | Dunn's test with Holm's adjustment | [15](../beyond/15-post-hoc.qmd#after-kruskal-wallis) |\n| Chi-square | Pairwise Fisher or chi-square tests with Holm's adjustment | [15](../beyond/15-post-hoc.qmd#after-chi-square) |\n| Cox regression | Hazard ratios against a chosen reference, or contrasts between groups | [14](../survival/14-cox-regression.qmd) |\n\nTukey's HSD controls false positives on its own, and so do Dunn's test and other pairwise tests once Holm's adjustment is applied, so none of them needs a significant overall test first. Decide before you see the data which comparisons you'll make, and say so in your Methods ([page 15](../beyond/15-post-hoc.qmd#overall-test-first)).\n\n\n\n## Exercises {#exercises}\n\nThe solutions use the packages and data loaded in the sections above, so run the page from the top first.\n\n**1.** Does **BMI** differ across ASA classes? Run a one-way ANOVA and report ω².\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmi_data <- cohort |> mutate(asa = factor(asa))\nbmi_anova <- aov(bmi ~ asa, data = bmi_data)\nsummary(bmi_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \nasa           3   2388   795.9   31.08 <2e-16 ***\nResiduals   596  15265    25.6                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::omega_squared(bmi_anova, partial = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA (Type I)\n\nParameter | Omega2 |       95% CI\n---------------------------------\nasa       |   0.13 | [0.09, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n\n```{.r .cell-code}\nbmi_data |> group_by(asa) |> summarise(mean = mean(bmi), sd = sd(bmi))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  asa    mean    sd\n  <fct> <dbl> <dbl>\n1 1      26.3  4.88\n2 2      29.2  5.16\n3 3      32.1  5.07\n4 4      36.2  3.29\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nbmi_anova = pg.anova(data=cohort, dv=\"bmi\", between=\"asa\", detailed=True)\nprint(bmi_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Source            SS   DF          MS          F         p_unc       np2\n0     asa   2387.716479    3  795.905493  31.076001  1.125923e-18  0.135264\n1  Within  15264.501921  596   25.611580        NaN           NaN       NaN\n```\n\n\n:::\n\n```{.python .cell-code}\nss_b, ss_w, df_b, ms_w = bmi_anova.loc[0, \"SS\"], bmi_anova.loc[1, \"SS\"], bmi_anova.loc[0, \"DF\"], bmi_anova.loc[1, \"MS\"]\nprint((ss_b - df_b * ms_w) / (ss_b + ss_w + ms_w))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.1307220253138767\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(cohort.groupby(\"asa\")[\"bmi\"].agg([\"mean\", \"std\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          mean       std\nasa                     \n1    26.322222  4.878765\n2    29.197000  5.155459\n3    32.146748  5.070931\n4    36.200000  3.293130\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Mean BMI was 26.3 kg/m² (SD 4.9) in ASA 1 and 36.2 kg/m² (SD 3.3) in ASA 4 (F(3, 596) = 31.1, p < 0.001; ω² = 0.13, one-sided 95% CI 0.09 to 1.00).\n\nThat's no surprise: obesity is one of the things anesthesiologists weigh when they assign an ASA class.\n:::\n\n**2.** A colleague asks whether **length of stay** differs between the three surgeons. Which test would you use, and what do you find?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nLength of stay is strongly right-skewed with many ties ([page 3](../foundations/03-distributions.qmd#transform)), and there are three independent groups: the **Kruskal-Wallis test**.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(los_days ~ surgeon, data = cohort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  los_days by surgeon\nKruskal-Wallis chi-squared = 0.73189, df = 2, p-value = 0.6935\n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(2026)\neffectsize::rank_epsilon_squared(los_days ~ surgeon, data = cohort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEpsilon2 (rank) |       95% CI\n------------------------------\n1.22e-03        | [0.00, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nstays = [group[\"los_days\"] for surgeon, group in cohort.groupby(\"surgeon\")]\nlos_test = stats.kruskal(*stays)\nprint(los_test, los_test.statistic / (len(cohort) - 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKruskalResult(statistic=np.float64(0.7318931330974262), pvalue=np.float64(0.6935398584479409)) 0.0012218583190274227\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Across the three surgeons, Kruskal-Wallis H = 0.73 (df = 2, p = 0.694; ε² = 0.001, one-sided 95% CI 0.00 to 1.00).\n\nThere's no clear evidence that length of stay differs between the surgeons.\n:::\n\n**3.** Test whether 90-day complications differ across the four **ASA classes**. Check the expected counts first. What do you do, and what do you find?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# R also warns here: \"Chi-squared approximation may be incorrect\"\nchisq.test(table(cohort$asa, cohort$complication_90d))$expected   # two expected counts are below 5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   \n         0     1\n  1  32.94  3.06\n  2 274.50 25.50\n  3 225.09 20.91\n  4  16.47  1.53\n```\n\n\n:::\n\n```{.r .cell-code}\nasa_grouped <- table(\n  asa          = factor(ifelse(cohort$asa >= 3, \"ASA 3-4\", \"ASA 1-2\"), levels = c(\"ASA 3-4\", \"ASA 1-2\")),\n  complication = factor(cohort$complication_90d, levels = c(1, 0), labels = c(\"yes\", \"no\"))\n)\nasa_grouped\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         complication\nasa       yes  no\n  ASA 3-4  30 234\n  ASA 1-2  21 315\n```\n\n\n:::\n\n```{.r .cell-code}\nfisher.test(asa_grouped)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  asa_grouped\np-value = 0.02762\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n 1.034232 3.626792\nsample estimates:\nodds ratio \n  1.920984 \n```\n\n\n:::\n\n```{.r .cell-code}\nprop.test(asa_grouped, correct = FALSE)$conf.int   # risk difference, ASA 3-4 minus ASA 1-2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.004924702 0.097348026\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom scipy.stats.contingency import odds_ratio\nfrom statsmodels.stats.proportion import confint_proportions_2indep\n\nprint(stats.chi2_contingency(pd.crosstab(cohort[\"asa\"], cohort[\"complication_90d\"])).expected_freq)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[ 32.94   3.06]\n [274.5   25.5 ]\n [225.09  20.91]\n [ 16.47   1.53]]\n```\n\n\n:::\n\n```{.python .cell-code}\ncohort[\"asa_group\"] = cohort[\"asa\"].map(lambda asa: \"ASA 3-4\" if asa >= 3 else \"ASA 1-2\")\nasa_grouped = pd.crosstab(cohort[\"asa_group\"], cohort[\"complication_90d\"]).loc[[\"ASA 3-4\", \"ASA 1-2\"], [1, 0]]\nprint(asa_grouped)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncomplication_90d   1    0\nasa_group                \nASA 3-4           30  234\nASA 1-2           21  315\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(stats.fisher_exact(asa_grouped).pvalue)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.027624840198071487\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(odds_ratio(asa_grouped.to_numpy(), kind=\"conditional\").confidence_interval())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfidenceInterval(low=1.0342268694270842, high=3.626948806900833)\n```\n\n\n:::\n\n```{.python .cell-code}\nhigh_yes, high_no = asa_grouped.loc[\"ASA 3-4\"]\nlow_yes, low_no = asa_grouped.loc[\"ASA 1-2\"]\nprint(confint_proportions_2indep(high_yes, high_yes + high_no, low_yes, low_yes + low_no, method=\"wald\", compare=\"diff\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(np.float64(0.004924701725186151), np.float64(0.09734802554754111))\n```\n\n\n:::\n:::\n\n:::\n\nASA 1 and ASA 4 each have an expected count of complications below 5 (3.1 and 1.5), so the chi-square test isn't reliable; R says so itself, with the warning \"Chi-squared approximation may be incorrect\". Combining classes into ASA 1–2 and ASA 3–4 makes clinical sense and gives a 2 × 2 table for Fisher's exact test:\n\n> **Results:** Complications within 90 days followed 30 of 264 procedures (11.4%) in ASA 3–4 patients and 21 of 336 (6.2%) in ASA 1–2 patients (risk difference 5.1 percentage points, 95% CI 0.5 to 9.7; odds ratio 1.92, 95% CI 1.03 to 3.63; p = 0.028).\n\nSay in your Methods that you combined the classes, and why.\n:::\n",
    "supporting": [
      "08-three-plus-unmatched_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}