{
  "hash": "fa2fc62c1b64a24ce353114540d3db09",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"14 · Cox proportional hazards regression\"\ndescription: \"Hazard ratios, choosing covariates, univariable and multivariable Cox models, checking straight-line effects and proportional hazards, remedies, stratified Cox for matched sets and bilateral patients, Fine-Gray regression, and reporting.\"\nengine: knitr\n---\n\n\n\n<!-- data-checksum: 9e548efb7ad4232927ffa99aa2cdeca7 -->\n\n[Page 13](13-kaplan-meier.qmd) compared survival curves. **Cox regression** goes further: it gives each group or predictor a **hazard ratio** with a 95% CI, and it can adjust for several predictors at once. Pages [8](../catalog/08-three-plus-unmatched.qmd#cox), [11](../catalog/11-predict-from-one.qmd#cox) and [12](../catalog/12-predict-from-several.qmd#cox) each fitted a Cox model in a few steps. This page covers the whole job:\n- what a hazard ratio means\n- how to choose covariates\n- how to check the model's assumptions, and what to do when one fails\n- how to handle matched sets and bilateral patients\n- how to model competing risks\n- how to report the result\n\n::: {.callout-note}\n## 💡 How this page works\nRun the code blocks in order, from the top: later blocks use the packages, data and models made earlier.\n\nUntil the section on [bilateral patients](#stratified-cox), the examples use every case as if it were a separate patient, including the 80 patients who had both sides operated on.\n:::\n\n## The hazard ratio {#hazard-ratio}\n\nThe **hazard** is the rate of revision at a given moment among the implants still in place: the chance that an unrevised implant is revised in the next short interval. It can rise or fall over time. The **hazard ratio** (HR) divides one group's hazard by another's. A Cox model assumes that this ratio stays the same over the whole follow-up, even if the hazards themselves change: the hazards are **proportional**.\n\nHere is the Cox model for implant alone, with implant A as the reference:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(survival)\nlibrary(ggsurvfit)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE) |>\n  mutate(age_10 = age / 10,                 # hazard ratios per 10 years of age\n         bmi_5 = bmi / 5)                   # and per 5 kg/m² of BMI\n\nimplant_model <- coxph(Surv(followup_years, revised) ~ implant, data = cohort)\nsummary(implant_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(followup_years, revised) ~ implant, data = cohort)\n\n  n= 600, number of events= 81 \n\n            coef exp(coef) se(coef)      z Pr(>|z|)    \nimplantB -0.2020    0.8171   0.3092 -0.653    0.514    \nimplantC  1.1208    3.0673   0.2579  4.345 1.39e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n         exp(coef) exp(-coef) lower .95 upper .95\nimplantB    0.8171      1.224    0.4458     1.498\nimplantC    3.0673      0.326    1.8502     5.085\n\nConcordance= 0.659  (se = 0.03 )\nLikelihood ratio test= 27.64  on 2 df,   p=1e-06\nWald test            = 29.63  on 2 df,   p=4e-07\nScore (logrank) test = 33.48  on 2 df,   p=5e-08\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom lifelines import CoxPHFitter, KaplanMeierFitter\n\ncohort = pd.read_csv(\"data/cohort.csv\")\ncohort[\"age_10\"] = cohort[\"age\"] / 10       # hazard ratios per 10 years of age\ncohort[\"bmi_5\"] = cohort[\"bmi\"] / 5         # and per 5 kg/m² of BMI\n\nimplant_model = CoxPHFitter().fit(\n    cohort[[\"followup_years\", \"revised\", \"implant\"]],\n    duration_col=\"followup_years\", event_col=\"revised\", formula=\"implant\",\n    fit_options={\"precision\": 1e-12},        # stop only when fully converged; see the R vs Python box\n)\nprint(implant_model.summary[[\"coef\", \"exp(coef)\", \"se(coef)\", \"exp(coef) lower 95%\",\n                             \"exp(coef) upper 95%\", \"z\", \"p\"]].round(3).to_string())   # to_string(): show every column\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               coef  exp(coef)  se(coef)  exp(coef) lower 95%  exp(coef) upper 95%      z      p\ncovariate                                                                                       \nimplant[T.B] -0.202      0.817     0.309                0.446                1.498 -0.653  0.514\nimplant[T.C]  1.121      3.067     0.258                1.850                5.085  4.345  0.000\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(implant_model.concordance_index_)                              # concordance\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.6591952831027229\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(implant_model.log_likelihood_ratio_test().test_statistic)     # overall likelihood ratio test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n27.63546691821921\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nReading the output, line by line:\n- **n = 600, number of events = 81:** the procedures and the revisions. The revisions, not the procedures, set how much a Cox model can learn.\n- **coef:** the log hazard ratio. Nobody reports it; it's what the model estimates.\n- **exp(coef):** the **hazard ratio**. Implant C: 3.07. At any moment during follow-up, an unrevised implant C was revised at about three times the rate of an unrevised implant A. Implant B: 0.82.\n- **se(coef), z, Pr(>|z|):** the standard error of the coefficient, and the Wald test of whether the hazard ratio differs from 1 (p < 0.001 for C, p = 0.514 for B).\n- **lower .95 / upper .95:** the 95% CI of each hazard ratio: 1.85 to 5.09 for C, 0.45 to 1.50 for B.\n- **Concordance = 0.659:** how often, in pairs of patients, the one revised sooner had the higher predicted risk. 0.5 is a coin toss and 1 is perfect.\n- **Likelihood ratio, Wald and score tests:** three versions of the overall test that implant matters at all. With enough events they agree; the likelihood ratio test (27.6 on 2 df, p < 0.001) is the most reliable. Python prints the concordance and then this test under the table.\n\n::: {.callout-tip}\n## 🔀 R vs Python: convergence and the printout\nBoth programs handle tied revision times with Efron's method and use the first group alphabetically (A) as the reference. lifelines' default rule for when to stop iterating stops slightly early, so its hazard ratios can differ from R's in the fifth or sixth digit. Every Python model on this page tightens it with `fit_options={\"precision\": 1e-12}`. R's `summary()` prints the concordance and three overall tests; lifelines keeps them in `concordance_index_` and `log_likelihood_ratio_test()`. (lifelines' `print_summary()` shows everything at once, including the time the model was fitted.)\n:::\n\n::: {.callout-warning}\n## ⚠️ Watch out: a hazard ratio isn't a risk ratio\n\"Three times the hazard\" doesn't mean three times as many revisions by 5 years. By 5 years, 28.9% of implant C knees and hips had been revised (1 − Kaplan-Meier), against 10.1% of implant A: 2.85 times as many, not 3.07. The two ratios are close when revisions are rare and drift apart as they become common. Report the hazard ratio as a ratio of rates, and give the cumulative risks separately.\n:::\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkm_by_implant <- survfit(Surv(followup_years, revised) ~ implant, data = cohort)\n1 - summary(km_by_implant, times = 5)$surv    # revised by 5 years: A, B, C\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.10143478 0.07591293 0.28862332\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfor implant, group in cohort.groupby(\"implant\"):\n    implant_km = KaplanMeierFitter().fit(group[\"followup_years\"], group[\"revised\"])\n    print(implant, round(1 - implant_km.survival_function_at_times(5).iloc[0], 3))   # revised by 5 years\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nA 0.101\nB 0.076\nC 0.289\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n## Choosing covariates {#choosing-covariates}\n\nA study comparing implants has one question: does implant C carry a higher revision risk than implant A? The other predictors in the model are there to make that comparison fair. These **covariates** are chosen before you look at the results, for a reason you can write down:\n\n- **Adjust for confounders:** factors that affect both which implant a patient gets and their risk of revision. Age, sex and BMI are the usual ones in arthroplasty: surgeons may choose implants differently for older, heavier or female patients, and these factors can change revision risk.\n- **Don't adjust for what the implant causes.** A dislocation or a reoperation that follows the implant choice is part of the implant's effect, not a reason for it. Adjusting for it hides the effect you're trying to measure.\n- **Don't choose covariates from the data.** Keeping only the predictors with p < 0.2 in univariable models, or letting a stepwise procedure pick them, makes p-values and CIs look more certain than they are and gives different answers in every sample.\n\n**Events limit the model.** A Cox model needs about **10 events per term**, where a term is one coefficient: a two-level predictor like sex is one term, implant (B and C against A) is two, and a spline with 3 degrees of freedom is three. The practice cohort has 81 revisions, enough for about eight terms. Implant, age, sex and BMI use five, about 16 events per term. With fewer events, adjust for fewer things, and say so.\n\n## From univariable to multivariable {#univariable-multivariable}\n\nA **univariable** (or unadjusted) model has one predictor, like the implant model above. A **multivariable** (or adjusted) model has several; each hazard ratio is then that predictor's effect with the others held fixed.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadjusted_model <- coxph(Surv(followup_years, revised) ~ implant + age_10 + sex + bmi_5, data = cohort)\nsummary(adjusted_model)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         exp(coef) exp(-coef) lower .95 upper .95\nimplantB 0.8291156  1.2061044 0.4520297 1.5207687\nimplantC 3.1884365  0.3136333 1.9209701 5.2921840\nage_10   1.2246225  0.8165782 0.9574440 1.5663582\nsexMale  0.5065688  1.9740655 0.3153674 0.8136921\nbmi_5    1.0308436  0.9700793 0.8386246 1.2671206\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ncox_data = cohort[[\"followup_years\", \"revised\", \"implant\", \"age_10\", \"sex\", \"bmi_5\"]]\nadjusted_model = CoxPHFitter().fit(cox_data, duration_col=\"followup_years\", event_col=\"revised\",\n                                   formula=\"implant + age_10 + sex + bmi_5\", fit_options={\"precision\": 1e-12})\nprint(adjusted_model.summary[[\"exp(coef)\", \"exp(coef) lower 95%\", \"exp(coef) upper 95%\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              exp(coef)  exp(coef) lower 95%  exp(coef) upper 95%\ncovariate                                                        \nimplant[T.B]   0.829116             0.452030             1.520769\nimplant[T.C]   3.188436             1.920970             5.292184\nage_10         1.224622             0.957444             1.566358\nsex[T.Male]    0.506569             0.315367             0.813692\nbmi_5          1.030844             0.838625             1.267121\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nImplant C's hazard ratio moved from 3.07 unadjusted to **3.19 adjusted** (95% CI 1.92 to 5.29). Age, sex and BMI don't explain the difference between the implants. When an adjusted estimate moves a lot, the covariates were probably confounding the unadjusted one; say so in the Discussion. Small moves mean little: a hazard ratio shifts a bit whenever a strong predictor is added, even without confounding.\n\n::: {.callout-warning}\n## ⚠️ Watch out: the covariates' own hazard ratios aren't findings\nThe model also prints hazard ratios for age, sex and BMI. Men's hazard of revision was about half of women's (0.51, 95% CI 0.32 to 0.81). It's tempting to report that as a second result, but the model wasn't built to answer it: nobody chose covariates that would make the comparison of men and women fair. Report the covariates' estimates in the table, and describe any you discuss as exploratory, as [page 12](../catalog/12-predict-from-several.qmd#cox) does.\n:::\n\n## Is the effect a straight line? {#linearity}\n\nA measured predictor like age enters the model as a straight line: each extra 10 years multiplies the hazard by the same amount, whether from 50 to 60 or from 75 to 85. To check, let the effect bend with a **natural cubic spline** ([page 12](../catalog/12-predict-from-several.qmd#multiple-nonlinear-regression) explains splines) and compare the two models with a likelihood ratio test:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(splines)\n\nage_spline_model <- coxph(Surv(followup_years, revised) ~ implant + ns(age, df = 3) + sex + bmi_5,\n                          data = cohort)\nanova(adjusted_model, age_spline_model)    # likelihood ratio test: does the bend help?\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n Cox model: response is  Surv(followup_years, revised)\n Model 1: ~ implant + age_10 + sex + bmi_5\n Model 2: ~ implant + ns(age, df = 3) + sex + bmi_5\n   loglik  Chisq Df Pr(>|Chi|)\n1 -461.26                     \n2 -461.11 0.2935  2     0.8635\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport patsy\nfrom scipy.stats import chi2\n\nage_knots = list(cohort[\"age\"].quantile([1/3, 2/3]))       # the same knots R's ns(df = 3) uses\nage_low, age_high = cohort[\"age\"].min(), cohort[\"age\"].max()\nage_spline = patsy.dmatrix(\"cr(age, knots=age_knots, lower_bound=age_low, upper_bound=age_high,\"\n                           \" constraints='center') - 1\", cohort, return_type=\"dataframe\")\nage_spline.columns = [\"age_1\", \"age_2\", \"age_3\"]           # three spline terms\n\nspline_data = pd.concat([cox_data.drop(columns=\"age_10\"), age_spline], axis=1)\nage_spline_model = CoxPHFitter().fit(spline_data, duration_col=\"followup_years\", event_col=\"revised\",\n                                     formula=\"implant + age_1 + age_2 + age_3 + sex + bmi_5\",\n                                     fit_options={\"precision\": 1e-12})\n\nlr_stat = 2 * (age_spline_model.log_likelihood_ - adjusted_model.log_likelihood_)\nprint(lr_stat, chi2.sf(lr_stat, df=2))     # likelihood ratio test: 3 spline terms vs 1 straight line\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.29350381805818415 0.8635081794270494\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nThe spline didn't clearly improve the fit (χ² = 0.29, df = 2, p = 0.864), so the straight line for age stands. Report the check in the Methods. (Exercise 2 checks BMI.)\n\n## Checking proportional hazards {#proportional-hazards}\n\nThe Cox model assumes each hazard ratio stays the same over the whole follow-up. The standard check uses **Schoenfeld residuals**. At each revision, the model compares the revised patient's predictors with those of everyone still at risk. Rescaled and added to the model's coefficient, each residual estimates the log hazard ratio at that moment. If the hazard ratio is constant, these estimates scatter around a flat line; if they drift with time, the assumption fails.\n\n**First, the adjusted model.**\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncox.zph(adjusted_model)    # one test per predictor, and a global test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         chisq df    p\nimplant 2.3906  2 0.30\nage_10  0.0977  1 0.75\nsex     0.1107  1 0.74\nbmi_5   2.6106  1 0.11\nGLOBAL  5.4935  5 0.36\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom lifelines.statistics import proportional_hazard_test\n\nph_test = proportional_hazard_test(adjusted_model, cox_data, time_transform=\"km\")\nprint(ph_test.summary[[\"test_statistic\", \"p\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              test_statistic         p\nage_10              0.034565  0.852511\nbmi_5               2.705518  0.100002\nimplant[T.B]        2.437343  0.118477\nimplant[T.C]        0.089494  0.764822\nsex[T.Male]         0.127087  0.721472\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nNo predictor's hazard ratio clearly changed over time (global test p = 0.359; BMI had the smallest p-value, 0.106). That's no clear evidence against proportional hazards, which isn't the same as proof that they hold: with 81 revisions, the test can miss a modest change.\n\n**Now a real violation.** The practice data have one built in: in total hips, the posterior approach has a much higher revision rate in the first months after surgery (early dislocation), and no higher rate after that. [Page 13](13-kaplan-meier.qmd#log-rank) showed the curves crossing.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntha <- cohort |> filter(procedure == \"THA\")\napproach_model <- coxph(Surv(followup_years, revised) ~ approach, data = tha)\napproach_zph <- cox.zph(approach_model)\napproach_zph\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         chisq df       p\napproach  11.3  1 0.00078\nGLOBAL    11.3  1 0.00078\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(approach_zph, resid = TRUE, se = TRUE)          # the log hazard ratio over time\nabline(h = coef(approach_model), lty = 2)            # the single hazard ratio the model assumes\n```\n\n::: {.cell-output-display}\n![](14-cox-regression_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom statsmodels.nonparametric.smoothers_lowess import lowess\n\ntha = cohort[cohort[\"procedure\"] == \"THA\"]\ntha_data = tha[[\"followup_years\", \"revised\", \"approach\"]]\napproach_model = CoxPHFitter().fit(tha_data, duration_col=\"followup_years\", event_col=\"revised\",\n                                   formula=\"approach\", fit_options={\"precision\": 1e-12})\nprint(proportional_hazard_test(approach_model, tha_data, time_transform=\"km\").summary[[\"test_statistic\", \"p\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       test_statistic         p\napproach[T.posterior]       11.183262  0.000825\n```\n\n\n:::\n\n```{.python .cell-code}\n# scaled Schoenfeld residuals, one per revision; adding the coefficient gives the log hazard ratio over time\nresiduals = approach_model.compute_residuals(tha_data, kind=\"scaled_schoenfeld\")\nlog_hr = residuals[\"approach[T.posterior]\"] + approach_model.params_[\"approach[T.posterior]\"]\nyears = tha_data.loc[log_hr.index, \"followup_years\"]\n\nfig, ax = plt.subplots(figsize=(7, 4))\nax.scatter(years, log_hr, s=12)\ntrend = lowess(log_hr, np.log(years), frac=2/3, it=0)     # smooth trend; it=0 keeps every point's full weight\nax.plot(np.exp(trend[:, 0]), trend[:, 1])\nax.axhline(approach_model.params_[\"approach[T.posterior]\"], linestyle=\"--\")   # the single hazard ratio the model assumes\nax.set_xscale(\"log\")                                       # spreads out the early revisions\nax.set_xticks([0.1, 0.5, 1, 2, 5], labels=[\"0.1\", \"0.5\", \"1\", \"2\", \"5\"])\nax.set_xlabel(\"Years since surgery (log scale)\")\nax.set_ylabel(\"Log hazard ratio, posterior vs anterior\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](14-cox-regression_files/figure-html/unnamed-chunk-24-1.png)\n:::\n:::\n\n:::\n\n\n\n\n\n- **The test:** p < 0.001 (R's χ² = 11.3 on 1 df). The posterior approach's hazard ratio isn't constant.\n- **The points:** one per revision. Points near +2 are posterior hips and points near −2 are anterior hips, so early on almost every point sits high.\n- **The solid line** smooths the points into an estimate of the log hazard ratio at each time. It starts high in the first months, when posterior hips were revised far more often, then falls below the dashed line, which marks the model's single hazard ratio of 1.37 (log hazard ratio 0.31).\n\nThat single hazard ratio (1.37, 95% CI 0.72 to 2.61) mixes a large early effect with the years after, when there's no clear difference. It describes no actual moment of follow-up, so don't report it.\n\n::: {.callout-warning}\n## ⚠️ Watch out: test and look\nWith many events, the test flags changes too small to matter; with few, it misses real ones. Always look at the plot too. And report a non-significant test as \"no clear evidence that the hazard ratios changed over time\", never as proof that the assumption holds.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: two versions of the test\nR's `cox.zph()` (survival 3.0 and later) computes the full score test, one per predictor, with implant's two terms tested together. lifelines' `proportional_hazard_test()` uses Grambsch and Therneau's simpler original approximation and tests every column separately (implant B and implant C each get their own line). The statistics differ slightly (11.3 in R, 11.2 in Python for the approach) and lead to the same conclusions here. lifelines' scaled Schoenfeld residuals leave out the coefficient that R adds, so the Python code adds it back. R's plot spaces the revisions evenly along the time axis (its \"km\" scale); the Python plot uses a log scale for the same reason: to keep the many early revisions from piling up at zero.\n:::\n\n## When hazards aren't proportional {#remedies}\n\nThere are two common fixes. Which one fits depends on whether you need the hazard ratio of the predictor that breaks the assumption.\n\n**1. Stratify, when it's only an adjustment.** Suppose the question is implant, in total hips, and approach is just a covariate. A Cox model **stratified** by approach gives each approach its own baseline hazard, of any shape, and estimates the implant hazard ratios within approaches. Approach gets no hazard ratio of its own, so its non-proportional effect no longer matters.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstratified_model <- coxph(Surv(followup_years, revised) ~ implant + strata(approach), data = tha)\nsummary(stratified_model)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         exp(coef) exp(-coef) lower .95 upper .95\nimplantB 0.5425943  1.8429976 0.2292543  1.284201\nimplantC 2.1139073  0.4730576 1.0163758  4.396606\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nstratified_model = CoxPHFitter().fit(tha[[\"followup_years\", \"revised\", \"implant\", \"approach\"]],\n                                     duration_col=\"followup_years\", event_col=\"revised\", formula=\"implant\",\n                                     strata=[\"approach\"], fit_options={\"precision\": 1e-12})\nprint(stratified_model.summary[[\"exp(coef)\", \"exp(coef) lower 95%\", \"exp(coef) upper 95%\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              exp(coef)  exp(coef) lower 95%  exp(coef) upper 95%\ncovariate                                                        \nimplant[T.B]   0.542594             0.229254             1.284201\nimplant[T.C]   2.113907             1.016376             4.396606\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nIn total hips, with approach as a stratum, implant C's hazard ratio was 2.11 (95% CI 1.02 to 4.40) against implant A.\n\n**2. Split the follow-up, when you need the effect.** If the approach *is* the question, give it one hazard ratio for the first 6 months and another for the time after. Each patient followed beyond 6 months gets two rows, one per period; the model then estimates the approach's effect separately in each:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# one row per patient per period: (0, 0.5] years and (0.5, end of follow-up]\ntha_split <- survSplit(Surv(followup_years, revised) ~ ., data = tha, cut = 0.5, episode = \"period\") |>\n  mutate(posterior_early = as.numeric(approach == \"posterior\" & period == 1),\n         posterior_late  = as.numeric(approach == \"posterior\" & period == 2))\n\nsplit_model <- coxph(Surv(tstart, followup_years, revised) ~ posterior_early + posterior_late,\n                     data = tha_split)\nsummary(split_model)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                exp(coef) exp(-coef) lower .95 upper .95\nposterior_early 8.4719845  0.1180361 1.9253393 37.278895\nposterior_late  0.4262855  2.3458458 0.1561268  1.163921\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom lifelines import CoxTimeVaryingFitter\n\nhips = tha.reset_index(drop=True)\nhips[\"id\"] = hips.index                                   # one ID per hip, shared by its rows\n\nearly = hips.copy()                                       # row 1: surgery to 6 months\nearly[\"start\"] = 0.0\nearly[\"stop\"] = early[\"followup_years\"].clip(upper=0.5)\nearly[\"event\"] = ((early[\"followup_years\"] <= 0.5) & (early[\"revised\"] == 1)).astype(int)\nearly[\"period\"] = 1\n\nlate = hips[hips[\"followup_years\"] > 0.5].copy()          # row 2: 6 months onward, if followed that long\nlate[\"start\"] = 0.5\nlate[\"stop\"] = late[\"followup_years\"]\nlate[\"event\"] = late[\"revised\"]\nlate[\"period\"] = 2\n\ntha_split = pd.concat([early, late])\ntha_split[\"posterior_early\"] = ((tha_split[\"approach\"] == \"posterior\") & (tha_split[\"period\"] == 1)).astype(int)\ntha_split[\"posterior_late\"] = ((tha_split[\"approach\"] == \"posterior\") & (tha_split[\"period\"] == 2)).astype(int)\n\nsplit_model = CoxTimeVaryingFitter().fit(\n    tha_split[[\"id\", \"start\", \"stop\", \"event\", \"posterior_early\", \"posterior_late\"]],\n    id_col=\"id\", event_col=\"event\", start_col=\"start\", stop_col=\"stop\", fit_options={\"precision\": 1e-12})\nprint(split_model.summary[[\"exp(coef)\", \"exp(coef) lower 95%\", \"exp(coef) upper 95%\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 exp(coef)  exp(coef) lower 95%  exp(coef) upper 95%\ncovariate                                                           \nposterior_early   8.471984             1.925339            37.278895\nposterior_late    0.426285             0.156127             1.163921\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nIn the first 6 months, the hazard of revision was 8.47 times higher after the posterior approach (95% CI 1.93 to 37.3). After 6 months the estimate was 0.43 (95% CI 0.16 to 1.16), which is imprecise. The CI for the early effect is wide because it rests on 16 early revisions.\n\nChoose the cut point before you look, from clinical reasoning: here, the period of highest dislocation risk after hip replacement. Trying several cut points until one gives a striking result is data dredging. R can also let a hazard ratio change smoothly with time (the `tt()` argument of `coxph()`), which avoids choosing a cut point.\n\n> **Methods:** Proportional hazards were checked with scaled Schoenfeld residuals. Because the effect of surgical approach changed over time, its hazard ratio was estimated separately for the first 6 months after surgery and thereafter.\n>\n> **Results:** The hazard ratio for revision with the posterior approach compared with the anterior approach was 8.47 (95% CI 1.93 to 37.3) in the first 6 months and 0.43 (95% CI 0.16 to 1.16) after 6 months.\n\n## Stratified Cox: matched sets and bilateral patients {#stratified-cox}\n\nA Cox model assumes every row is an independent patient. Two common designs break that.\n\n**Matched sets.** When each implant C patient is matched with similar patients who got other implants, the matched patients belong together. A Cox model **stratified by matched set**, `strata(set_id)`, compares implants only within sets. The decision table calls this *conditional proportional hazards regression*. [Page 7](../catalog/07-two-paired-groups.qmd#stratified-cox) works through matched pairs and [page 9](../catalog/09-three-plus-matched.qmd#stratified-cox) matched sets of three.\n\n**Bilateral patients.** 80 patients in the cohort had both sides replaced. Their two joints share the same patient's bone, activity and surgeon, so their outcomes aren't independent, and treating them as independent makes the CIs too narrow. There are three common choices:\n\n- **Keep both joints and use robust standard errors** clustered on patient. The hazard ratios don't change; the CIs allow for the pairing. This is the usual choice.\n- **Stratify by patient**, `strata(patient_id)`, to compare the two sides of each patient. Only patients whose two joints differ in the predictor, and who had a revision, contribute anything, so it's rarely precise enough.\n- **Keep one joint per patient**, such as the first one operated on. Simple, but it throws away data.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclustered_model <- coxph(Surv(followup_years, revised) ~ implant + age_10 + sex + bmi_5,\n                         data = cohort, cluster = patient_id)    # robust SEs, clustered on patient\nsummary(clustered_model)$coefficients[, c(\"exp(coef)\", \"se(coef)\", \"robust se\", \"Pr(>|z|)\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         exp(coef)  se(coef) robust se     Pr(>|z|)\nimplantB 0.8291156 0.3095014 0.3106780 5.463870e-01\nimplantC 3.1884365 0.2585253 0.2575808 6.743766e-06\nage_10   1.2246225 0.1255741 0.1234440 1.006948e-01\nsexMale  0.5065688 0.2418013 0.2414236 4.847144e-03\nbmi_5    1.0308436 0.1052925 0.1044996 7.712846e-01\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(clustered_model)$conf.int[\"implantC\", ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n exp(coef) exp(-coef)  lower .95  upper .95 \n 3.1884365  0.3136333  1.9245297  5.2823958 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nclustered_model = CoxPHFitter().fit(\n    cohort[[\"followup_years\", \"revised\", \"implant\", \"age_10\", \"sex\", \"bmi_5\", \"patient_id\"]],\n    duration_col=\"followup_years\", event_col=\"revised\", formula=\"implant + age_10 + sex + bmi_5\",\n    cluster_col=\"patient_id\",                              # robust SEs, clustered on patient\n    fit_options={\"precision\": 1e-12},\n)\nprint(clustered_model.summary[[\"exp(coef)\", \"se(coef)\", \"exp(coef) lower 95%\", \"exp(coef) upper 95%\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              exp(coef)  se(coef)  exp(coef) lower 95%  exp(coef) upper 95%\ncovariate                                                                  \nimplant[T.B]   0.829116  0.310788             0.450891             1.524608\nimplant[T.C]   3.188436  0.257544             1.924668             5.282016\nage_10         1.224622  0.123504             0.961336             1.560017\nsex[T.Male]    0.506569  0.241419             0.315604             0.813082\nbmi_5          1.030844  0.104463             0.839988             1.265063\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n- **exp(coef):** unchanged: implant C's hazard ratio is still 3.19.\n- **se(coef) / robust se:** R prints both; lifelines prints only the robust one when you cluster. Here they're almost the same (0.259 and 0.258 for implant C), so the CI barely moves (1.92 to 5.28). Only 20 of the 80 bilateral patients had a revision, so the pairing matters little in this cohort. It can matter much more in yours: check, and say in the Methods what you did.\n\n::: {.callout-tip}\n## 🔀 R vs Python: robust standard errors\nBoth programs compute the same robust (\"sandwich\") standard errors. When follow-up times are tied, R also applies Efron's tie correction inside the robust variance and lifelines doesn't, so the two differ in the fourth significant figure.\n:::\n\n## Competing risks regression: Fine-Gray (R only) {#fine-gray}\n\nEvery Cox model above treated death as censoring. That's a **cause-specific** Cox model: its hazard ratios describe the revision rate among patients still alive, which is the right question for whether an implant performs worse. But as [page 13](13-kaplan-meier.qmd#competing-risks) showed, deaths also stop revisions from ever happening. For \"which patients will actually be revised?\" use the **Fine-Gray** model, which models the cumulative incidence of revision directly. Its effect sizes are **subdistribution hazard ratios** (SHR).\n\nFine-Gray regression has no mature Python implementation, so this section is R only. tidycmprsk's `crr()` takes the same three-level status as page 13's cumulative incidence:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidycmprsk)\n\ncohort <- cohort |>\n  mutate(status = factor(event_status, levels = c(0, 1, 2),\n                         labels = c(\"censored\", \"revision\", \"death\")))   # censored must come first\n\nfine_gray <- crr(Surv(followup_years, status) ~ implant + age_10 + sex + bmi_5,\n                 data = cohort, failcode = \"revision\")\nfine_gray\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nVariable   Coef     SE      HR     95% CI       p-value    \nimplantB   -0.232   0.307   0.79   0.43, 1.45   0.45       \nimplantC   1.13     0.259   3.09   1.86, 5.14   <0.001     \nage_10     0.067    0.113   1.07   0.86, 1.33   0.55       \nsexMale    -0.630   0.240   0.53   0.33, 0.85   0.009      \nbmi_5      0.023    0.103   1.02   0.84, 1.25   0.82       \n```\n\n\n:::\n:::\n\n\nCompare it with the cause-specific model:\n- **Implant C:** SHR 3.09 (95% CI 1.86 to 5.14), close to the cause-specific HR of 3.19. Death rates didn't clearly differ between implants (Gray's test on [page 13](13-kaplan-meier.qmd#competing-risks)), so allowing for death changes little.\n- **Age:** SHR 1.07 per 10 years (95% CI 0.86 to 1.33), against a cause-specific HR of 1.22. Older patients may be revised at a somewhat higher rate while alive, but more of them die before they can be revised, so the subdistribution estimate is closer to 1: there's no clear evidence that age changes how many patients are actually revised.\n\nReport the cause-specific model to compare implants, and the Fine-Gray model when the question is how many patients will be revised. Many papers report both, and say which is which.\n\n`crr()` can't allow for patients who had both sides replaced. If many of yours did, survival's `finegray()` function prepares the data for a Fine-Gray model that `coxph()` can fit with `cluster = patient_id`.\n\n::: {.callout-warning}\n## ⚠️ Watch out: a subdistribution hazard ratio isn't a hazard ratio\nThe SHR has no simple meaning as a rate: patients who have died stay in its \"at risk\" group. Read it only as \"higher or lower cumulative incidence\", and call it a subdistribution hazard ratio in the text and tables.\n:::\n\n## Reporting a Cox model {#reporting}\n\nMost papers present Cox models as a table: one row per predictor, with the univariable and the multivariable hazard ratios side by side. Both columns use robust standard errors clustered on patient ([above](#stratified-cox)), so their CIs allow for the bilateral patients.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gtsummary)\n\nhr_labels <- list(implant ~ \"Implant\", age_10 ~ \"Age (per 10 years)\", sex ~ \"Sex\",\n                  bmi_5 ~ \"BMI (per 5 kg/m²)\")\n\nunivariable_table <- cohort |>\n  select(followup_years, revised, implant, age_10, sex, bmi_5, patient_id) |>\n  tbl_uvregression(method = coxph, y = Surv(followup_years, revised), exponentiate = TRUE,\n                   include = c(implant, age_10, sex, bmi_5),\n                   method.args = list(cluster = patient_id),       # robust SEs, clustered on patient\n                   label = hr_labels, pvalue_fun = label_style_pvalue(digits = 3))\nmultivariable_table <- clustered_model |>                   # robust SEs, for the bilateral patients\n  tbl_regression(exponentiate = TRUE, label = hr_labels, pvalue_fun = label_style_pvalue(digits = 3))\n\ntbl_merge(list(univariable_table, multivariable_table),\n          tab_spanner = c(\"**Univariable**\", \"**Multivariable**\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xxyxyzoyqg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xxyxyzoyqg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xxyxyzoyqg thead, #xxyxyzoyqg tbody, #xxyxyzoyqg tfoot, #xxyxyzoyqg tr, #xxyxyzoyqg td, #xxyxyzoyqg th {\n  border-style: none;\n}\n\n#xxyxyzoyqg p {\n  margin: 0;\n  padding: 0;\n}\n\n#xxyxyzoyqg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xxyxyzoyqg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xxyxyzoyqg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xxyxyzoyqg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xxyxyzoyqg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xxyxyzoyqg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xxyxyzoyqg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xxyxyzoyqg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xxyxyzoyqg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xxyxyzoyqg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xxyxyzoyqg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xxyxyzoyqg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xxyxyzoyqg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xxyxyzoyqg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xxyxyzoyqg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xxyxyzoyqg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xxyxyzoyqg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xxyxyzoyqg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xxyxyzoyqg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xxyxyzoyqg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xxyxyzoyqg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xxyxyzoyqg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xxyxyzoyqg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xxyxyzoyqg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xxyxyzoyqg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xxyxyzoyqg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xxyxyzoyqg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xxyxyzoyqg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xxyxyzoyqg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xxyxyzoyqg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xxyxyzoyqg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xxyxyzoyqg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xxyxyzoyqg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xxyxyzoyqg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xxyxyzoyqg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xxyxyzoyqg .gt_left {\n  text-align: left;\n}\n\n#xxyxyzoyqg .gt_center {\n  text-align: center;\n}\n\n#xxyxyzoyqg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xxyxyzoyqg .gt_font_normal {\n  font-weight: normal;\n}\n\n#xxyxyzoyqg .gt_font_bold {\n  font-weight: bold;\n}\n\n#xxyxyzoyqg .gt_font_italic {\n  font-style: italic;\n}\n\n#xxyxyzoyqg .gt_super {\n  font-size: 65%;\n}\n\n#xxyxyzoyqg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xxyxyzoyqg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xxyxyzoyqg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xxyxyzoyqg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xxyxyzoyqg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xxyxyzoyqg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xxyxyzoyqg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xxyxyzoyqg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xxyxyzoyqg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"4\" scope=\"colgroup\" id=\"level 1; stat_n_1\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipVbml2YXJpYWJsZSoq\"><span class='gt_from_md'><strong>Univariable</strong></span></span></div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"level 1; estimate_2\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipNdWx0aXZhcmlhYmxlKio=\"><span class='gt_from_md'><strong>Multivariable</strong></span></span></div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_n_1\"><span data-qmd-base64=\"KipOKio=\"><span class='gt_from_md'><strong>N</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate_1\"><span data-qmd-base64=\"KipIUioq\"><span class='gt_from_md'><strong>HR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low_1\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value_1\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate_2\"><span data-qmd-base64=\"KipIUioq\"><span class='gt_from_md'><strong>HR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low_2\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value_2\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Implant</td>\n<td headers=\"stat_n_1\" class=\"gt_row gt_center\">600</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    A</td>\n<td headers=\"stat_n_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    B</td>\n<td headers=\"stat_n_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">0.82</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">0.45, 1.49</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\">0.511</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">0.83</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">0.45, 1.52</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\">0.546</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    C</td>\n<td headers=\"stat_n_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">3.07</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">1.87, 5.04</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><0.001</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">3.19</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">1.92, 5.28</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Age (per 10 years)</td>\n<td headers=\"stat_n_1\" class=\"gt_row gt_center\">600</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">1.25</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">0.98, 1.58</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\">0.068</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">1.22</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">0.96, 1.56</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\">0.101</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Sex</td>\n<td headers=\"stat_n_1\" class=\"gt_row gt_center\">600</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"stat_n_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"stat_n_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">0.54</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">0.34, 0.86</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\">0.009</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">0.51</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">0.32, 0.81</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\">0.005</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">BMI (per 5 kg/m²)</td>\n<td headers=\"stat_n_1\" class=\"gt_row gt_center\">600</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">1.05</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">0.87, 1.28</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\">0.600</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">1.03</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">0.84, 1.27</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\">0.771</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"8\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBIUiA9IEhhemFyZCBSYXRpbw==\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, HR = Hazard Ratio</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndef hr_with_ci(model):\n    \"\"\"Each term's hazard ratio and 95% CI as text, like '3.19 (1.92 to 5.29)'.\"\"\"\n    rows = model.summary\n    return (rows[\"exp(coef)\"].map(\"{:.2f}\".format) + \" (\" + rows[\"exp(coef) lower 95%\"].map(\"{:.2f}\".format)\n            + \" to \" + rows[\"exp(coef) upper 95%\"].map(\"{:.2f}\".format) + \")\")\n\nunivariable = []\nfor term in [\"implant\", \"age_10\", \"sex\", \"bmi_5\"]:\n    one_predictor = CoxPHFitter().fit(cohort[[\"followup_years\", \"revised\", term, \"patient_id\"]],\n                                      duration_col=\"followup_years\", event_col=\"revised\", formula=term,\n                                      cluster_col=\"patient_id\",      # robust SEs, clustered on patient\n                                      fit_options={\"precision\": 1e-12})\n    univariable.append(hr_with_ci(one_predictor))\n\nhr_table = pd.DataFrame({\"Univariable HR (95% CI)\": pd.concat(univariable),\n                         \"Multivariable HR (95% CI)\": hr_with_ci(clustered_model)})   # robust SEs, for the bilateral patients\nprint(hr_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Univariable HR (95% CI) Multivariable HR (95% CI)\ncovariate                                                     \nimplant[T.B]     0.82 (0.45 to 1.49)       0.83 (0.45 to 1.52)\nimplant[T.C]     3.07 (1.87 to 5.04)       3.19 (1.92 to 5.28)\nage_10           1.25 (0.98 to 1.58)       1.22 (0.96 to 1.56)\nsex[T.Male]      0.54 (0.34 to 0.86)       0.51 (0.32 to 0.81)\nbmi_5            1.05 (0.87 to 1.28)       1.03 (0.84 to 1.27)\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n> **Methods:** The association between implant and revision for any reason was estimated with Cox proportional hazards regression, with time from surgery as the time scale and implant A as the reference. Age, sex and body mass index were chosen in advance as covariates. Age entered the model as a linear term after a natural cubic spline showed no clear evidence of non-linearity. Proportional hazards were checked with scaled Schoenfeld residuals. In the Cox models, robust standard errors clustered on patient accounted for patients who had both sides replaced. A Fine-Gray model, treating death as a competing risk, was fitted as a sensitivity analysis.\n>\n> **Results:** During follow-up, 81 of 600 procedures (13.5%) were revised. After adjustment for age, sex and body mass index, the hazard ratio for revision compared with implant A was 3.19 (95% CI 1.92 to 5.28) for implant C and 0.83 (95% CI 0.45 to 1.52) for implant B (test of proportional hazards, global p = 0.359). With death treated as a competing risk, the subdistribution hazard ratio for implant C was 3.09 (95% CI 1.86 to 5.14).\n\nBefore you submit, check that the paper states:\n- the number of patients, procedures and events\n- time zero and the event definition ([page 13](13-kaplan-meier.qmd#time-zero))\n- which covariates were adjusted for, and why\n- how continuous predictors were modeled, and how proportional hazards were checked\n- how bilateral patients and deaths were handled\n\n\n\n## Exercises {#exercises}\n\nThe solutions use the packages, data and models made in the sections above, so run the page from the top first.\n\n**1.** Fit a univariable Cox model for ASA class (as a number, 1 to 4) and write the Results sentence.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nasa_model <- coxph(Surv(followup_years, revised) ~ asa, data = cohort)\nsummary(asa_model)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    exp(coef) exp(-coef) lower .95 upper .95\nasa  1.379391  0.7249577 0.9869659  1.927847\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(asa_model)$coefficients[, \"Pr(>|z|)\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05968004\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nasa_model = CoxPHFitter().fit(cohort[[\"followup_years\", \"revised\", \"asa\"]], duration_col=\"followup_years\",\n                              event_col=\"revised\", fit_options={\"precision\": 1e-12})\nprint(asa_model.summary[[\"exp(coef)\", \"exp(coef) lower 95%\", \"exp(coef) upper 95%\", \"p\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           exp(coef)  exp(coef) lower 95%  exp(coef) upper 95%        p\ncovariate                                                              \nasa         1.379391             0.986966             1.927847  0.05968\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** The hazard ratio for revision per ASA class was 1.38 (95% CI 0.99 to 1.93; p = 0.060).\n\nThe estimate is imprecise: the data are compatible with no association and with a near doubling of the hazard per class.\n:::\n\n**2.** Check whether BMI's effect in the adjusted model is a straight line, using a natural cubic spline with 3 degrees of freedom.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmi_spline_model <- coxph(Surv(followup_years, revised) ~ implant + age_10 + sex + ns(bmi, df = 3),\n                          data = cohort)\nanova(adjusted_model, bmi_spline_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n Cox model: response is  Surv(followup_years, revised)\n Model 1: ~ implant + age_10 + sex + bmi_5\n Model 2: ~ implant + age_10 + sex + ns(bmi, df = 3)\n   loglik  Chisq Df Pr(>|Chi|)\n1 -461.26                     \n2 -459.94 2.6436  2     0.2666\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nbmi_knots = list(cohort[\"bmi\"].quantile([1/3, 2/3]))\nbmi_low, bmi_high = cohort[\"bmi\"].min(), cohort[\"bmi\"].max()\nbmi_spline = patsy.dmatrix(\"cr(bmi, knots=bmi_knots, lower_bound=bmi_low, upper_bound=bmi_high,\"\n                           \" constraints='center') - 1\", cohort, return_type=\"dataframe\")\nbmi_spline.columns = [\"bmi_1\", \"bmi_2\", \"bmi_3\"]\n\nbmi_data = pd.concat([cox_data.drop(columns=\"bmi_5\"), bmi_spline], axis=1)\nbmi_spline_model = CoxPHFitter().fit(bmi_data, duration_col=\"followup_years\", event_col=\"revised\",\n                                     formula=\"implant + age_10 + sex + bmi_1 + bmi_2 + bmi_3\",\n                                     fit_options={\"precision\": 1e-12})\nbmi_lr = 2 * (bmi_spline_model.log_likelihood_ - adjusted_model.log_likelihood_)\nprint(bmi_lr, chi2.sf(bmi_lr, df=2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2.6436426624027263 0.2666492029134558\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Comparing a natural cubic spline for BMI with a straight line gave a likelihood ratio χ² of 2.64 (df = 2, p = 0.267).\n\nThere's no clear evidence that BMI's effect bends, so the straight line stands.\n:::\n\n**3.** Total hips and total knees may have different baseline revision rates. Refit the adjusted model stratified by procedure. Does implant C's hazard ratio change? Write the Results sentence.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprocedure_model <- coxph(Surv(followup_years, revised) ~ implant + age_10 + sex + bmi_5 + strata(procedure),\n                         data = cohort)\nsummary(procedure_model)$conf.int[\"implantC\", ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n exp(coef) exp(-coef)  lower .95  upper .95 \n 3.1570524  0.3167512  1.9021586  5.2398257 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nprocedure_model = CoxPHFitter().fit(cohort[[\"followup_years\", \"revised\", \"implant\", \"age_10\", \"sex\", \"bmi_5\", \"procedure\"]],\n                                    duration_col=\"followup_years\", event_col=\"revised\",\n                                    formula=\"implant + age_10 + sex + bmi_5\", strata=[\"procedure\"],\n                                    fit_options={\"precision\": 1e-12})\nprint(procedure_model.summary.loc[\"implant[T.C]\", [\"exp(coef)\", \"exp(coef) lower 95%\", \"exp(coef) upper 95%\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nexp(coef)              3.157052\nexp(coef) lower 95%    1.902159\nexp(coef) upper 95%    5.239826\nName: implant[T.C], dtype: float64\n```\n\n\n:::\n:::\n\n:::\n\nBarely.\n\n> **Results:** In a Cox model stratified by procedure and adjusted for age, sex and BMI, the hazard ratio for revision with implant C compared with implant A was 3.16 (95% CI 1.90 to 5.24); without stratification it was 3.19.\n:::\n",
    "supporting": [
      "14-cox-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}