{
  "hash": "19d9837073f582c92ad1af5e9cd19d9d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"13 · Kaplan-Meier & the log-rank test\"\ndescription: \"Censoring, time zero, Kaplan-Meier curves with numbers at risk, survivorship at 2, 5 and 10 years, median follow-up, the log-rank test, and competing risks.\"\nengine: knitr\n---\n\n\n\n<!-- data-checksum: ffc54e2ad996e1e61ad10ca520e4d588 -->\n\n\"How long do the implants last?\" is the central question of arthroplasty research, and it needs its own methods. Patients join the study over several years and are followed for different lengths of time, and most of them are never revised. **Survival analysis** uses every patient's follow-up for as long as it lasts.\n\nPages [4](../catalog/04-describe-one-group.qmd#kaplan-meier), [6](../catalog/06-two-unpaired-groups.qmd#log-rank) and [8](../catalog/08-three-plus-unmatched.qmd#cox) each showed one survival method in a few steps. This page covers the whole method:\n- what censoring is\n- how to set up the data\n- how to read and report a Kaplan-Meier curve\n- how long the patients were followed\n- how to compare groups\n- what to do when patients die before they can be revised\n\n[Page 14](14-cox-regression.qmd) covers Cox regression.\n\n::: {.callout-note}\n## 💡 How this page works\nRun the code blocks in order, from the top: later blocks use the packages and data loaded earlier.\n\nTo keep the code short, the examples use every case, including the 80 patients who had both sides operated on. In a real study, decide how to handle them ([page 14](14-cox-regression.qmd#stratified-cox)) and say what you did.\n:::\n\n## What censoring means {#censoring}\n\nPicture six patients, each followed from surgery until either a revision or the end of their follow-up:\n\n| Patient | Years followed | Revised? |\n|---|---|---|\n| A | 1 | yes |\n| B | 2 | no: the study closed |\n| C | 3 | yes |\n| D | 4 | no: moved away |\n| E | 5 | yes |\n| F | 6 | no: the study closed |\n\nPatients B, D and F are **censored**. We know they went *at least* that long without a revision, but not what happened afterwards. Censoring isn't missing data: it's partial information, and survival methods use all of it.\n\nTwo simple summaries both get this wrong:\n- **\"3 of 6 (50%) were revised\"** ignores time. Patient B was followed for only 2 years, so B's implant never had the chance to fail at 4 or 5 years.\n- **Dropping the censored patients** (\"3 of 3 were revised\") throws away the years B, D and F spent without a revision.\n\nThe **Kaplan-Meier** method gets it right. It moves through time and recalculates at each revision, using only the patients still being followed (**at risk**) at that moment:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(survival)\nlibrary(ggsurvfit)\n\ntoy <- tibble(\n  patient = c(\"A\", \"B\", \"C\", \"D\", \"E\", \"F\"),\n  years   = c(1, 2, 3, 4, 5, 6),\n  revised = c(1, 0, 1, 0, 1, 0)        # 1 = revised, 0 = censored\n)\n\ntoy_km <- survfit(Surv(years, revised) ~ 1, data = toy)\nsummary(toy_km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(years, revised) ~ 1, data = toy)\n\n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    1      6       1    0.833   0.152       0.5827            1\n    3      4       1    0.625   0.213       0.3200            1\n    5      2       1    0.312   0.245       0.0671            1\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom lifelines import KaplanMeierFitter\n\ntoy = pd.DataFrame({\n    \"patient\": [\"A\", \"B\", \"C\", \"D\", \"E\", \"F\"],\n    \"years\":   [1, 2, 3, 4, 5, 6],\n    \"revised\": [1, 0, 1, 0, 1, 0],     # 1 = revised, 0 = censored\n})\n\ntoy_km = KaplanMeierFitter().fit(toy[\"years\"], event_observed=toy[\"revised\"])\nprint(toy_km.event_table[[\"at_risk\", \"observed\", \"censored\"]])   # observed = revisions\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          at_risk  observed  censored\nevent_at                             \n0.0             6         0         0\n1.0             6         1         0\n2.0             5         0         1\n3.0             4         1         0\n4.0             3         0         1\n5.0             2         1         0\n6.0             1         0         1\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(toy_km.survival_function_)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          KM_estimate\ntimeline             \n0.0          1.000000\n1.0          0.833333\n2.0          0.833333\n3.0          0.625000\n4.0          0.625000\n5.0          0.312500\n6.0          0.312500\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nReading the output, one revision at a time:\n- **Year 1:** 6 patients at risk, 1 revised. Survival = 5/6 = 0.833.\n- **Year 2:** B is censored. Nothing happens to the curve, but the at-risk group shrinks to 4.\n- **Year 3:** 4 at risk, 1 revised. Survival = 0.833 × 3/4 = 0.625.\n- **Year 5:** 2 at risk (D was censored at year 4), 1 revised. Survival = 0.625 × 1/2 = 0.3125.\n\nSo the estimated chance of a revision by 5 years is 1 − 0.3125 = 69%, not 50%. Each censored patient counts fully while they're followed and then leaves the at-risk group.\n\n::: {.callout-note collapse=\"true\"}\n## 🔍 Under the hood: the product-limit formula\nAt each time $t_i$ when at least one revision happens, with $n_i$ patients at risk and $d_i$ revisions, the chance of getting past $t_i$ unrevised is $1 - d_i/n_i$. Kaplan-Meier survival at time $t$ multiplies these together for every revision time up to $t$:\n\n$$\\hat S(t) = \\prod_{t_i \\le t} \\left(1 - \\frac{d_i}{n_i}\\right)$$\n\nThis is why the method is also called the **product-limit** estimator. Censored patients appear only in the $n_i$ of the revision times before they leave.\n:::\n\n::: {.callout-warning}\n## ⚠️ Watch out: censoring must be unrelated to the outcome\nKaplan-Meier assumes a censored patient has the same future risk as the patients still being followed. That's reasonable when follow-up ends because the study closed. It isn't when patients stop coming back *because* their hip hurts, or stay away because it's perfect. If many patients are lost to follow-up, say how many and why.\n:::\n\n## Time zero and the event {#time-zero}\n\nEvery survival analysis needs two definitions, fixed before you look at the results:\n\n- **Time zero**, when the clock starts. For implant survival it's the **date of surgery**: every patient starts at the same clinical moment. Starting at the first clinic visit instead would ignore revisions that happened before that visit.\n- **The event**, what stops the clock. Here it's **revision for any reason**: any reoperation that removes or exchanges a component. Other studies use aseptic revision, or any reoperation. Choose one in advance and define it in the Methods.\n\nReal data rarely arrive as \"years followed\" and \"revised: yes/no\". You build those columns from dates. The practice cohort already has them: `followup_years` and `event_status`, where 0 means censored, 1 means revised and 2 means died without a revision. Here's how to make them from a table of dates, for four made-up patients:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndates <- tibble(\n  patient       = c(\"P1\", \"P2\", \"P3\", \"P4\"),\n  surgery_date  = as.Date(c(\"2016-03-14\", \"2018-11-05\", \"2020-06-30\", \"2017-01-09\")),\n  revision_date = as.Date(c(\"2019-07-02\", NA, NA, \"2017-04-18\")),\n  death_date    = as.Date(c(\"2023-02-11\", \"2022-01-20\", NA, NA)),\n  last_seen     = as.Date(c(\"2022-10-03\", \"2021-12-02\", \"2025-11-17\", \"2024-08-15\"))\n)\n\nfollow_up <- dates |>\n  mutate(\n    # the first event wins: a revision, else a death, else censored at the last visit\n    event_status = case_when(!is.na(revision_date) ~ 1,\n                             !is.na(death_date)    ~ 2,\n                             .default = 0),\n    end_date = case_when(event_status == 1 ~ revision_date,\n                         event_status == 2 ~ death_date,\n                         .default = last_seen),\n    followup_years = as.numeric(end_date - surgery_date) / 365.25\n  )\n\nfollow_up |> select(patient, event_status, end_date, followup_years)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  patient event_status end_date   followup_years\n  <chr>          <dbl> <date>              <dbl>\n1 P1                 1 2019-07-02          3.30 \n2 P2                 2 2022-01-20          3.21 \n3 P3                 0 2025-11-17          5.38 \n4 P4                 1 2017-04-18          0.271\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ndates = pd.DataFrame({\n    \"patient\":       [\"P1\", \"P2\", \"P3\", \"P4\"],\n    \"surgery_date\":  [\"2016-03-14\", \"2018-11-05\", \"2020-06-30\", \"2017-01-09\"],\n    \"revision_date\": [\"2019-07-02\", None, None, \"2017-04-18\"],\n    \"death_date\":    [\"2023-02-11\", \"2022-01-20\", None, None],\n    \"last_seen\":     [\"2022-10-03\", \"2021-12-02\", \"2025-11-17\", \"2024-08-15\"],\n})\nfor column in [\"surgery_date\", \"revision_date\", \"death_date\", \"last_seen\"]:\n    dates[column] = pd.to_datetime(dates[column])\n\n# the first event wins: a revision, else a death, else censored at the last visit\ndates[\"event_status\"] = np.select([dates[\"revision_date\"].notna(), dates[\"death_date\"].notna()],\n                                  [1, 2], default=0)\ndates[\"end_date\"] = dates[\"revision_date\"].fillna(dates[\"death_date\"]).fillna(dates[\"last_seen\"])\ndates[\"followup_years\"] = (dates[\"end_date\"] - dates[\"surgery_date\"]).dt.days / 365.25\n\nprint(dates[[\"patient\", \"event_status\", \"end_date\", \"followup_years\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  patient  event_status   end_date  followup_years\n0      P1             1 2019-07-02        3.299110\n1      P2             2 2022-01-20        3.208761\n2      P3             0 2025-11-17        5.382615\n3      P4             1 2017-04-18        0.271047\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n- **P1** was revised in 2019 and died in 2023. The revision came first, so P1's follow-up ends at the revision, 3.30 years after surgery.\n- **P2** died 3.21 years after surgery without a revision. Death ends the follow-up: P2 can never be revised. (The section on [competing risks](#competing-risks) explains why that matters.)\n- **P3** was alive and unrevised at the last visit: censored at 5.38 years.\n- **P4** was revised 99 days after surgery, at 0.27 years.\n\n::: {.callout-warning}\n## ⚠️ Watch out: follow-up ends at the last visit, not today\nDon't set every unrevised patient's end date to the date you pulled the data. A patient last seen in 2021 might have been revised elsewhere since. Censor at the last date you *know* the implant was in place. And check that no event date comes before the surgery date: it's always a data-entry error.\n:::\n\n## The Kaplan-Meier curve {#kaplan-meier}\n\nNow the practice cohort: 600 procedures, each followed from surgery to revision, death or the last visit.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\n\nkm <- survfit2(Surv(followup_years, revised) ~ 1, data = cohort,\n               conf.type = \"log-log\")              # the CI method lifelines uses\n\nkm |>\n  ggsurvfit() +\n  add_confidence_interval() +\n  add_censor_mark(size = 1, alpha = 0.4) +         # a tick for each censored patient\n  add_risktable(times = c(0, 2, 4, 6, 8, 10)) +\n  scale_ggsurvfit(x_scales = list(breaks = c(0, 2, 4, 6, 8, 10))) +\n  labs(x = \"Years since surgery\", y = \"Revision-free survival\")\n```\n\n::: {.cell-output-display}\n![](13-kaplan-meier_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom lifelines.plotting import add_at_risk_counts\n\ncohort = pd.read_csv(\"data/cohort.csv\")\n\nkm = KaplanMeierFitter(label=\"All procedures\").fit(cohort[\"followup_years\"], event_observed=cohort[\"revised\"])\n\nfig, ax = plt.subplots(figsize=(7, 4.5))\nkm.plot_survival_function(ax=ax, show_censors=True,                # a tick for each censored patient\n                          censor_styles={\"ms\": 3, \"alpha\": 0.4}, legend=False)\nax.set_xlabel(\"Years since surgery\")\nax.set_ylabel(\"Revision-free survival\")\nadd_at_risk_counts(km, ax=ax, xticks=[0, 2, 4, 6, 8, 10], rows_to_show=[\"At risk\", \"Events\"])\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](13-kaplan-meier_files/figure-html/unnamed-chunk-12-1.png)\n:::\n:::\n\n:::\n\n\n\n\n\nHow to read it:\n- **The steps:** the curve starts at 100% and drops at each revision. The drops get bigger later on, because each revision is then a bigger share of the fewer patients still at risk.\n- **The ticks** mark censored patients. They don't move the curve; they leave the at-risk group.\n- **The shaded band** is the 95% CI. It widens as patients leave.\n- **The table below the plot** gives the number of patients still being followed (**at risk**) at each time, 600 at surgery, 332 at 4 years and 84 at 8 years, and the revisions so far. Always publish the numbers at risk with the curve: they tell the reader how much to trust each part of it.\n\n::: {.callout-warning}\n## ⚠️ Watch out: the tail of the curve\nBy 10 years only 21 procedures are still followed, so each late revision moves the curve a lot. Don't draw conclusions from the far right-hand end. A common rule of thumb is to stop drawing the curve once fewer than about 10% of patients (here, 60) remain at risk.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: the confidence band\nR's `survfit()` uses a \"log\" CI by default; lifelines uses \"log-log\". We set `conf.type = \"log-log\"` in R so the two match, as on [page 4](../catalog/04-describe-one-group.qmd#kaplan-meier). The numbers at risk can differ by one or two: R counts the patients followed for *at least* 4 years, lifelines those followed for *more than* 4 years, so a patient censored at exactly 4.00 years is in R's count only. lifelines' `add_at_risk_counts()` also adds a row of censored patients unless you choose rows with `rows_to_show`.\n:::\n\n## Survivorship at 2, 5 and 10 years {#survivorship}\n\nPapers report the curve at fixed times: the **survivorship**, the percentage of implants still unrevised.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(km, times = c(2, 5, 10))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(followup_years, revised) ~ 1, data = cohort, \n    conf.type = \"log-log\")\n\n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    2    496      35    0.939 0.00996        0.916        0.956\n    5    263      31    0.863 0.01617        0.828        0.892\n   10     21      15    0.780 0.02579        0.725        0.826\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfor years in [2, 5, 10]:\n    estimate = km.survival_function_at_times(years).iloc[0]\n    ci = km.confidence_interval_survival_function_.loc[:years].iloc[-1]   # last step at or before that time\n    at_risk = (cohort[\"followup_years\"] >= years).sum()\n    print(years, round(estimate, 3), ci.round(3).to_list(), at_risk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2 0.939 [0.916, 0.956] 496\n5 0.863 [0.828, 0.892] 263\n10 0.78 [0.725, 0.826] 21\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n- **survival:** 0.939 at 2 years, 0.863 at 5 years and 0.780 at 10 years.\n- **lower 95% CI / upper 95% CI:** the CI around each one. The 10-year CI (0.725 to 0.826) is the widest.\n- **n.risk:** 496 procedures still followed at 2 years, 263 at 5 years and only 21 at 10 years.\n- **n.event:** the revisions *since the previous time shown*, not the running total.\n\n> **Methods:** Implant survivorship was estimated with the Kaplan-Meier method, with revision for any reason as the end point and the date of surgery as time zero. Patients were censored at death or at their last follow-up. Confidence intervals used the log-log transformation.\n>\n> **Results:** Survivorship free of revision was 93.9% (95% CI 91.6% to 95.6%) at 2 years, 86.3% (95% CI 82.8% to 89.2%) at 5 years and 78.0% (95% CI 72.5% to 82.6%) at 10 years, when 21 procedures remained at risk.\n\n::: {.callout-warning}\n## ⚠️ Watch out: \"86% survival\" needs its time point, CI and numbers at risk\nA survivorship figure means nothing without the time it refers to. Give the 95% CI, and the number still at risk at the time you quote, so readers can see how much data the estimate rests on.\n:::\n\n## How long were patients followed? {#follow-up}\n\nEvery survival paper reports the **median follow-up**. The obvious way to calculate it is wrong:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedian(cohort$followup_years)        # misleading: revisions and deaths cut follow-up short\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.365\n```\n\n\n:::\n\n```{.r .cell-code}\n# reverse Kaplan-Meier: treat \"still followed at the end\" as the event\nreverse_km <- survfit(Surv(followup_years, event_status == 0) ~ 1, data = cohort)\nquantile(reverse_km, probs = c(0.25, 0.5, 0.75), conf.int = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  25   50   75 \n3.52 5.62 7.93 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom lifelines.utils import qth_survival_times\n\nprint(cohort[\"followup_years\"].median())   # misleading: revisions and deaths cut follow-up short\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n4.365\n```\n\n\n:::\n\n```{.python .cell-code}\n# reverse Kaplan-Meier: treat \"still followed at the end\" as the event\nreverse_km = KaplanMeierFitter().fit(cohort[\"followup_years\"],\n                                     event_observed=(cohort[\"event_status\"] == 0))\nprint(qth_survival_times([0.75, 0.5, 0.25], reverse_km.survival_function_))   # 25th, 50th, 75th percentiles\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      KM_estimate\n0.75         3.52\n0.50         5.62\n0.25         7.93\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nThe plain median, 4.4 years, mixes two things: how long the study watched patients, and how soon they were revised or died. A patient revised at 1 year wasn't \"followed for 1 year\" in the sense readers care about. The study would have kept watching them.\n\nThe **reverse Kaplan-Meier** method answers the real question: how long would patients have been followed if nothing had happened to them? It swaps the roles: being censored at the end of follow-up becomes the \"event\", and revisions and deaths become the censored observations. The median follow-up is **5.62 years** (IQR 3.52 to 7.93).\n\n> **Methods:** Median follow-up was estimated with the reverse Kaplan-Meier method.\n>\n> **Results:** The median follow-up was 5.62 years (IQR 3.52 to 7.93).\n\n## Comparing groups: the log-rank test {#log-rank}\n\nThe **log-rank test** asks whether two or more survival curves differ. At every revision time it compares each group's observed revisions with the number expected if all groups had the same risk, then adds up the differences across the whole follow-up. It's the same test as the **Mantel-Haenszel** (or Mantel-Cox) test in the decision table.\n\n**Two groups.** In total hips, does the surgical approach (anterior or posterior) affect revision?\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntha <- cohort |> filter(procedure == \"THA\")        # approach applies to hips only\n\nsurvfit2(Surv(followup_years, revised) ~ approach, data = tha, conf.type = \"log-log\") |>\n  ggsurvfit() +\n  add_confidence_interval() +\n  add_risktable() +\n  scale_ggsurvfit() +\n  labs(x = \"Years since surgery\", y = \"Revision-free survival\")\n```\n\n::: {.cell-output-display}\n![](13-kaplan-meier_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n\n```{.r .cell-code}\napproach_logrank <- survdiff(Surv(followup_years, revised) ~ approach, data = tha)\napproach_logrank\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nsurvdiff(formula = Surv(followup_years, revised) ~ approach, \n    data = tha)\n\n                     N Observed Expected (O-E)^2/E (O-E)^2/V\napproach=anterior  145       18     20.9     0.397     0.912\napproach=posterior 125       19     16.1     0.513     0.912\n\n Chisq= 0.9  on 1 degrees of freedom, p= 0.3 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom lifelines.statistics import logrank_test\n\ntha = cohort[cohort[\"procedure\"] == \"THA\"]                # approach applies to hips only\nanterior = tha[tha[\"approach\"] == \"anterior\"]\nposterior = tha[tha[\"approach\"] == \"posterior\"]\n\nfig, ax = plt.subplots(figsize=(7, 4.5))\nkm_anterior = KaplanMeierFitter(label=\"anterior\").fit(anterior[\"followup_years\"], anterior[\"revised\"])\nkm_posterior = KaplanMeierFitter(label=\"posterior\").fit(posterior[\"followup_years\"], posterior[\"revised\"])\nkm_anterior.plot_survival_function(ax=ax)\nkm_posterior.plot_survival_function(ax=ax)\nax.set_xlabel(\"Years since surgery\")\nax.set_ylabel(\"Revision-free survival\")\nadd_at_risk_counts(km_anterior, km_posterior, ax=ax, rows_to_show=[\"At risk\", \"Events\"])\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](13-kaplan-meier_files/figure-html/unnamed-chunk-24-1.png)\n:::\n\n```{.python .cell-code}\napproach_logrank = logrank_test(anterior[\"followup_years\"], posterior[\"followup_years\"],\n                                event_observed_A=anterior[\"revised\"], event_observed_B=posterior[\"revised\"])\nprint(approach_logrank.test_statistic, approach_logrank.p_value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.9116386659614966 0.33968000597546394\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n- **Observed / Expected:** the posterior hips had 19 revisions where 16.1 were expected; the anterior hips had 18 where 20.9 were expected.\n- **Chisq = 0.9 on 1 degree of freedom, p = 0.340:** no clear evidence that the curves differ over the whole follow-up.\n\nBut look at the plot. The posterior curve drops sharply in the first months, then the two curves come together (late on they even cross, where the CIs overlap widely). The early revisions are real: by 6 months, survivorship was 88.7% after the posterior approach and 98.6% after the anterior approach.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(survfit(Surv(followup_years, revised) ~ approach, data = tha, conf.type = \"log-log\"), times = 0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(followup_years, revised) ~ approach, data = tha, \n    conf.type = \"log-log\")\n\n                approach=anterior \n        time       n.risk      n.event     survival      std.err lower 95% CI \n      0.5000     137.0000       2.0000       0.9859       0.0099       0.9448 \nupper 95% CI \n      0.9965 \n\n                approach=posterior \n        time       n.risk      n.event     survival      std.err lower 95% CI \n      0.5000     108.0000      14.0000       0.8871       0.0284       0.8168 \nupper 95% CI \n      0.9315 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfor curve in [km_anterior, km_posterior]:\n    ci = curve.confidence_interval_survival_function_.loc[:0.5].iloc[-1]\n    print(curve.label, round(curve.survival_function_at_times(0.5).iloc[0], 3), ci.round(3).to_list())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nanterior 0.986 [0.945, 0.996]\nposterior 0.887 [0.817, 0.932]\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nThe log-rank test adds up the differences over the whole follow-up. A large difference in the first months gets diluted by the years after, when the groups differ little, and the test can miss a real difference. [Page 14](14-cox-regression.qmd#proportional-hazards) shows how to detect this and how to model it.\n\n**Three or more groups.** The same test compares any number of groups. Does revision differ between implants A, B and C?\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimplant_logrank <- survdiff(Surv(followup_years, revised) ~ implant, data = cohort)\nimplant_logrank\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nsurvdiff(formula = Surv(followup_years, revised) ~ implant, data = cohort)\n\n            N Observed Expected (O-E)^2/E (O-E)^2/V\nimplant=A 246       25     34.0      2.40      4.15\nimplant=B 217       18     30.0      4.81      7.65\nimplant=C 137       38     16.9     26.17     33.18\n\n Chisq= 33.5  on 2 degrees of freedom, p= 5e-08 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom lifelines.statistics import multivariate_logrank_test\n\nimplant_logrank = multivariate_logrank_test(cohort[\"followup_years\"], cohort[\"implant\"], cohort[\"revised\"])\nprint(implant_logrank.test_statistic, implant_logrank.degrees_of_freedom, implant_logrank.p_value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n33.46861907356945 2 5.399850171504637e-08\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n- **Observed / Expected:** implant C had 38 revisions where 16.9 were expected. Implants A (25 vs 34.0) and B (18 vs 30.0) had fewer than expected.\n- **Chisq = 33.5 on 2 degrees of freedom, p < 0.001:** at least one implant's curve differs from the others. The test doesn't say which; [page 15](../beyond/15-post-hoc.qmd#after-log-rank) covers comparing pairs of groups. [Page 8](../catalog/08-three-plus-unmatched.qmd#cox) gives each implant's hazard ratio.\n\n> **Methods:** Revision-free survival was compared between groups with the log-rank test.\n>\n> **Results:** The log-rank test for revision-free survival across implants gave χ² = 33.5 (df = 2, p < 0.001). In total hip arthroplasty, survivorship at 6 months was 88.7% (95% CI 81.7% to 93.2%) after the posterior approach and 98.6% (95% CI 94.5% to 99.6%) after the anterior approach (log-rank test over the whole follow-up, χ² = 0.9, df = 1, p = 0.340).\n\n::: {.callout-warning}\n## ⚠️ Watch out: always plot the curves before you trust the test\nThe log-rank test is most powerful when one group's risk is a steady multiple of the other's over time. When the curves cross, as with the surgical approach here, a non-significant test can hide a real difference. And don't compare groups at one hand-picked time point to get a significant result: decide your time points before you look.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: one function or two\nR's `survdiff()` takes a formula and handles two groups or more. lifelines has `logrank_test()` for two groups, which takes each group's data separately, and `multivariate_logrank_test()` for any number, which takes a grouping column. They give identical results.\n:::\n\n## Competing risks: when patients die first {#competing-risks}\n\nSo far, patients who died were treated as censored. That assumes they would have gone on to be revised at the same rate as everyone else. They can't: a patient who has died can never be revised. Death is a **competing risk**.\n\nWith death treated as censored, 1 − Kaplan-Meier estimates the risk of revision in an imaginary world where nobody dies. In an older population, where many patients die during follow-up, it **overstates** the real proportion who will be revised. The **cumulative incidence function** (CIF), estimated with the **Aalen-Johansen** method, gives the real proportion: the chance of being revised by a given time, allowing for the chance of dying first.\n\nThe data need one status column with three values. In the cohort, `event_status` is 0 for censored, 1 for revised and 2 for died.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohort <- cohort |>\n  mutate(status = factor(event_status, levels = c(0, 1, 2),\n                         labels = c(\"censored\", \"revision\", \"death\")))   # censored must come first\n\n# with a three-level status, survfit() estimates the cumulative incidences (Aalen-Johansen)\ncif <- survfit2(Surv(followup_years, status) ~ 1, data = cohort, conf.type = \"log-log\")\n\ncif |>\n  ggcuminc(outcome = c(\"revision\", \"death\")) +\n  add_confidence_interval() +\n  scale_ggsurvfit() +\n  labs(x = \"Years since surgery\", y = \"Cumulative incidence\")\n```\n\n::: {.cell-output-display}\n![](13-kaplan-meier_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntidy_survfit(cif, times = c(2, 5, 10)) |>\n  select(outcome, time, estimate, conf.low, conf.high)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  outcome   time estimate conf.low conf.high\n  <chr>    <dbl>    <dbl>    <dbl>     <dbl>\n1 death        2   0.0530   0.0369    0.0733\n2 death        5   0.142    0.112     0.174 \n3 death       10   0.240    0.193     0.290 \n4 revision     2   0.0595   0.0423    0.0806\n5 revision     5   0.128    0.100     0.159 \n6 revision    10   0.193    0.153     0.237 \n```\n\n\n:::\n\n```{.r .cell-code}\n1 - summary(km, times = c(2, 5, 10))$surv    # 1 − Kaplan-Meier, for comparison\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.06071255 0.13690651 0.21968772\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfrom scipy.stats import norm\nfrom statsmodels.duration.survfunc import CumIncidenceRight\n\n# event_status: 0 = censored, 1 = revision, 2 = death\ncif = CumIncidenceRight(cohort[\"followup_years\"], cohort[\"event_status\"])\nrevision = pd.DataFrame({\"cif\": cif.cinc[0], \"se\": cif.cinc_se[0]}, index=cif.times)   # event type 1\ndeath = pd.DataFrame({\"cif\": cif.cinc[1], \"se\": cif.cinc_se[1]}, index=cif.times)      # event type 2\n\nfig, ax = plt.subplots(figsize=(7, 4.5))\nax.step(revision.index, revision[\"cif\"], where=\"post\", label=\"revision\")\nax.step(death.index, death[\"cif\"], where=\"post\", label=\"death\")\nax.set_xlabel(\"Years since surgery\")\nax.set_ylabel(\"Cumulative incidence\")\nlegend = ax.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](13-kaplan-meier_files/figure-html/unnamed-chunk-36-1.png)\n:::\n\n```{.python .cell-code}\nz = norm.ppf(0.975)\nfor years in [2, 5, 10]:\n    row = revision.loc[:years].iloc[-1]                                  # last step at or before that time\n    spread = np.exp(z * row[\"se\"] / (row[\"cif\"] * np.log(row[\"cif\"])))   # the log-log CI, as in R\n    print(years, round(row[\"cif\"], 3), round(row[\"cif\"] ** (1 / spread), 3), round(row[\"cif\"] ** spread, 3),\n          round(1 - km.survival_function_at_times(years).iloc[0], 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2 0.059 0.042 0.081 0.061\n5 0.128 0.1 0.159 0.137\n10 0.193 0.153 0.237 0.22\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nReading it:\n- **The revision curve** is the cumulative incidence of revision: 5.9% at 2 years, 12.8% at 5 years and 19.3% at 10 years.\n- **The death curve** rises faster: 24.0% of patients had died without a revision by 10 years.\n- **1 − Kaplan-Meier** says 22.0% by 10 years. It overstates the real proportion revised by 2.7 percentage points, because it pretends the patients who died could still have been revised.\n\nThe gap grows with the number of deaths. It's small at 2 years, when few patients have died, and largest in older patients (see exercise 2).\n\n**Comparing groups: Gray's test (R only).** Gray's test is the competing-risks counterpart of the log-rank test: it compares cumulative incidence curves between groups. The tidycmprsk package runs it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidycmprsk)\n\ncif_by_implant <- cuminc(Surv(followup_years, status) ~ implant, data = cohort)\nglance(cif_by_implant) |>\n  select(outcome_1, statistic_1, p.value_1, outcome_2, statistic_2, p.value_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  outcome_1 statistic_1   p.value_1 outcome_2 statistic_2 p.value_2\n  <chr>           <dbl>       <dbl> <chr>           <dbl>     <dbl>\n1 revision         31.5 0.000000142 death           0.969     0.616\n```\n\n\n:::\n:::\n\n\nThe cumulative incidence of revision differed between implants (Gray's test χ² = 31.5, df = 2, p < 0.001); there was no clear evidence that the cumulative incidence of death differed (χ² = 0.97, p = 0.616).\n\n> **Methods:** The cumulative incidence of revision was estimated with the Aalen-Johansen method, treating death as a competing risk, and compared between implants with Gray's test.\n>\n> **Results:** The cumulative incidence of revision was 12.8% (95% CI 10.0% to 15.9%) at 5 years and 19.3% (95% CI 15.3% to 23.7%) at 10 years, when the cumulative incidence of death was 24.0% (95% CI 19.3% to 29.0%). Gray's test for the cumulative incidence of revision across implants gave χ² = 31.5 (df = 2, p < 0.001).\n\n::: {.callout-warning}\n## ⚠️ Watch out: which number answers your question?\nBoth estimates are useful, but they answer different questions:\n- **1 − Kaplan-Meier** answers \"how well does the implant perform while patients are alive?\" It's the usual measure for comparing implants, and registries report it.\n- **The cumulative incidence** answers \"what proportion of patients will actually be revised?\" Use it to counsel patients or plan services, especially for older patients.\n\nSay which one you report. Never call 1 − Kaplan-Meier \"the proportion of patients revised\" when many patients died.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: which tools\n- **The cumulative incidence:** R's `survfit()` estimates it whenever the status has more than two levels. In Python, use statsmodels' `CumIncidenceRight()`: it gives the estimates and their standard errors but no CI, so the code builds the same log-log CI as R. lifelines also has an `AalenJohansenFitter`, but it moves tied follow-up times by a small random amount, which can shift an estimate read at exactly 5 or 10 years, so we don't use it.\n- **Gray's test:** Python has no mature implementation of Gray's test. Plot the curves in Python, but run the test in R. tidycmprsk's `cuminc()` also gives the cumulative incidences, with a slightly different CI method.\n- **Fine-Gray regression** models the cumulative incidence with several predictors at once; it's R only too ([page 14](14-cox-regression.qmd#fine-gray)).\n:::\n\n\n\n## Exercises {#exercises}\n\nThe solutions use the packages and data loaded in the sections above, so run the page from the top first.\n\n**1.** Compare revision-free survival between total hips (THA) and total knees (TKA). Give each procedure's survivorship at 5 years with its 95% CI, and the log-rank test.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(survfit(Surv(followup_years, revised) ~ procedure, data = cohort, conf.type = \"log-log\"), times = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(followup_years, revised) ~ procedure, \n    data = cohort, conf.type = \"log-log\")\n\n                procedure=THA \n        time       n.risk      n.event     survival      std.err lower 95% CI \n      5.0000     121.0000      29.0000       0.8688       0.0236       0.8145 \nupper 95% CI \n      0.9081 \n\n                procedure=TKA \n        time       n.risk      n.event     survival      std.err lower 95% CI \n      5.0000     142.0000      37.0000       0.8586       0.0222       0.8086 \nupper 95% CI \n      0.8964 \n```\n\n\n:::\n\n```{.r .cell-code}\nsurvdiff(Surv(followup_years, revised) ~ procedure, data = cohort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nsurvdiff(formula = Surv(followup_years, revised) ~ procedure, \n    data = cohort)\n\n                N Observed Expected (O-E)^2/E (O-E)^2/V\nprocedure=THA 270       37     36.6   0.00342   0.00624\nprocedure=TKA 330       44     44.4   0.00282   0.00624\n\n Chisq= 0  on 1 degrees of freedom, p= 0.9 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfor procedure, group in cohort.groupby(\"procedure\"):\n    curve = KaplanMeierFitter().fit(group[\"followup_years\"], group[\"revised\"])\n    ci = curve.confidence_interval_survival_function_.loc[:5].iloc[-1]\n    print(procedure, round(curve.survival_function_at_times(5).iloc[0], 3), ci.round(3).to_list())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTHA 0.869 [0.814, 0.908]\nTKA 0.859 [0.809, 0.896]\n```\n\n\n:::\n\n```{.python .cell-code}\nhips = cohort[cohort[\"procedure\"] == \"THA\"]\nknees = cohort[cohort[\"procedure\"] == \"TKA\"]\nprocedure_logrank = logrank_test(hips[\"followup_years\"], knees[\"followup_years\"],\n                                 event_observed_A=hips[\"revised\"], event_observed_B=knees[\"revised\"])\nprint(procedure_logrank.test_statistic, procedure_logrank.p_value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.006243321559239711 0.9370209370375034\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Survivorship free of revision at 5 years was 86.9% (95% CI 81.4% to 90.8%) after THA and 85.9% (95% CI 80.9% to 89.6%) after TKA (log-rank χ² = 0.01, df = 1, p = 0.937).\n:::\n\n**2.** A surgeon asks: \"Of my patients aged 75 and over, what proportion will need a revision within 5 years?\" Which estimate answers that question? Calculate it, and compare it with 1 − Kaplan-Meier.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nThe surgeon wants the real proportion of patients revised, and many patients over 75 die during follow-up. That's the **cumulative incidence**, with death as a competing risk.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nold <- cohort |> filter(age >= 75)\ncount(old, status)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  status       n\n  <fct>    <int>\n1 censored    46\n2 revision    13\n3 death       41\n```\n\n\n:::\n\n```{.r .cell-code}\nsurvfit2(Surv(followup_years, status) ~ 1, data = old, conf.type = \"log-log\") |>\n  tidy_survfit(times = 5) |>\n  select(outcome, estimate, conf.low, conf.high)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  outcome  estimate conf.low conf.high\n  <chr>       <dbl>    <dbl>     <dbl>\n1 death       0.397   0.288      0.504\n2 revision    0.139   0.0777     0.218\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - summary(survfit(Surv(followup_years, revised) ~ 1, data = old), times = 5)$surv\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1646173\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nold = cohort[cohort[\"age\"] >= 75]\nprint(old[\"event_status\"].value_counts().sort_index())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nevent_status\n0    46\n1    13\n2    41\nName: count, dtype: int64\n```\n\n\n:::\n\n```{.python .cell-code}\nold_cif = CumIncidenceRight(old[\"followup_years\"], old[\"event_status\"])\nold_revision = pd.DataFrame({\"cif\": old_cif.cinc[0], \"se\": old_cif.cinc_se[0]}, index=old_cif.times)\nrow = old_revision.loc[:5].iloc[-1]\nspread = np.exp(z * row[\"se\"] / (row[\"cif\"] * np.log(row[\"cif\"])))\nprint(round(row[\"cif\"], 3), round(row[\"cif\"] ** (1 / spread), 3), round(row[\"cif\"] ** spread, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.139 0.078 0.218\n```\n\n\n:::\n\n```{.python .cell-code}\nold_km = KaplanMeierFitter().fit(old[\"followup_years\"], old[\"revised\"])\nprint(1 - old_km.survival_function_at_times(5).iloc[0])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.16461732152861452\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Of the 100 procedures in patients aged 75 and over, 41 ended in death and 13 in revision. The cumulative incidence of revision at 5 years was 13.9% (95% CI 7.8% to 21.8%); 1 − Kaplan-Meier at 5 years was 16.5%.\n\n1 − Kaplan-Meier overstates the real proportion revised by about a fifth.\n:::\n\n**3.** Estimate the cumulative incidence of revision at 5 years for each implant, with death as a competing risk, and write the Results sentence, including Gray's test.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvfit2(Surv(followup_years, status) ~ implant, data = cohort, conf.type = \"log-log\") |>\n  tidy_survfit(times = 5) |>\n  filter(outcome == \"revision\") |>\n  select(strata, estimate, conf.low, conf.high)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  strata estimate conf.low conf.high\n  <fct>     <dbl>    <dbl>     <dbl>\n1 A        0.0967   0.0616     0.141\n2 B        0.0681   0.0368     0.112\n3 C        0.273    0.195      0.356\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfor implant, group in cohort.groupby(\"implant\"):\n    implant_cif = CumIncidenceRight(group[\"followup_years\"], group[\"event_status\"])\n    implant_revision = pd.DataFrame({\"cif\": implant_cif.cinc[0], \"se\": implant_cif.cinc_se[0]}, index=implant_cif.times)\n    row = implant_revision.loc[:5].iloc[-1]\n    spread = np.exp(z * row[\"se\"] / (row[\"cif\"] * np.log(row[\"cif\"])))\n    print(implant, round(row[\"cif\"], 3), round(row[\"cif\"] ** (1 / spread), 3), round(row[\"cif\"] ** spread, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nA 0.097 0.062 0.141\nB 0.068 0.037 0.112\nC 0.273 0.195 0.356\n```\n\n\n:::\n:::\n\n\nPython has no Gray's test; take it from R.\n:::\n\n> **Results:** The cumulative incidence of revision at 5 years, with death as a competing risk, was 9.7% (95% CI 6.2% to 14.1%) with implant A, 6.8% (95% CI 3.7% to 11.2%) with implant B and 27.3% (95% CI 19.5% to 35.6%) with implant C (Gray's test χ² = 31.5, df = 2, p < 0.001).\n:::\n",
    "supporting": [
      "13-kaplan-meier_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}