{
  "hash": "ce2720e9c4666f1b072cf41715a9f3cd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"6 · Compare two unpaired groups\"\ndescription: \"Unpaired (Welch's) t test, Mann-Whitney test, Fisher's exact and chi-square tests, and the log-rank test, each with an effect size and 95% CI.\"\nengine: knitr\ntoc-depth: 2\n---\n\n\n\n<!-- data-checksum: 9e548efb7ad4232927ffa99aa2cdeca7 -->\n\nTwo groups of **different** patients: THA vs TKA, men vs women, implant A vs implant C. This is the most common comparison in clinical research. If the same patients are measured twice, or patients were matched in pairs, use [page 7](07-two-paired-groups.qmd) instead.\n\n::: {.callout-note}\n## 💡 How every section on this page works\nEach section answers one question about the practice cohort. Its first code block loads the packages and the data, so you can jump straight to the section you need. Run that section's blocks in order, top to bottom.\n\nTo keep the code short, the examples use every case, including the 80 patients who had both sides operated on. In a real study, decide how to handle them ([page 3](../foundations/03-distributions.qmd#paired)) and say what you did.\n:::\n\n## Unpaired t test {#unpaired-t}\n\n**The question:** Do TKA patients have a higher BMI than THA patients?\n\n### When to use it\n\n- The outcome is a **measurement**, compared between **two independent groups**.\n- Within **each group** it's roughly normal, or each group is large (about 30 or more) and not badly skewed ([page 3](../foundations/03-distributions.qmd#within-groups)).\n- Use **Welch's** version, which doesn't assume the two groups have the same spread. It's R's default, but not Python's (see the R vs Python box).\n- If the outcome is skewed, bounded or ordinal → the [Mann-Whitney test](#mann-whitney).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE) |>\n  mutate(procedure = factor(procedure, levels = c(\"TKA\", \"THA\")))   # TKA first: differences are TKA minus THA\n\nggplot(cohort, aes(bmi)) +\n  geom_histogram(binwidth = 1) +\n  facet_wrap(~ procedure, ncol = 1) +\n  labs(x = \"BMI, kg/m²\", y = \"Patients\")\n```\n\n::: {.cell-output-display}\n![](06-two-unpaired-groups_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncohort |>\n  group_by(procedure) |>\n  summarise(n = n(), mean = mean(bmi), sd = sd(bmi))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  procedure     n  mean    sd\n  <fct>     <int> <dbl> <dbl>\n1 TKA         330  31.2  5.42\n2 THA         270  29.5  5.28\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport pingouin as pg\nimport matplotlib.pyplot as plt\nfrom scipy import stats\n\ncohort = pd.read_csv(\"data/cohort.csv\")\ntka = cohort.loc[cohort[\"procedure\"] == \"TKA\", \"bmi\"]\ntha = cohort.loc[cohort[\"procedure\"] == \"THA\", \"bmi\"]\n\nfig, axes = plt.subplots(2, 1, figsize=(6, 4), sharex=True)\naxes[0].hist(tka, bins=range(18, 46))\naxes[0].set_title(\"TKA\")\naxes[1].hist(tha, bins=range(18, 46))\naxes[1].set_title(\"THA\")\naxes[1].set_xlabel(\"BMI, kg/m²\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](06-two-unpaired-groups_files/figure-html/unnamed-chunk-4-1.png)\n:::\n\n```{.python .cell-code}\nprint(cohort.groupby(\"procedure\")[\"bmi\"].agg([\"count\", \"mean\", \"std\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           count       mean       std\nprocedure                            \nTHA          270  29.461852  5.283550\nTKA          330  31.247576  5.421253\n```\n\n\n:::\n:::\n\n:::\n\nBoth groups are roughly bell-shaped with similar spreads, and both are large. TKA patients sit a little to the right.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbmi_test <- t.test(bmi ~ procedure, data = cohort)   # Welch's t test is R's default\nbmi_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  bmi by procedure\nt = 4.0705, df = 580.09, p-value = 5.341e-05\nalternative hypothesis: true difference in means between group TKA and group THA is not equal to 0\n95 percent confidence interval:\n 0.924101 2.647347\nsample estimates:\nmean in group TKA mean in group THA \n         31.24758          29.46185 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nbmi_test = stats.ttest_ind(tka, tha, equal_var=False)   # equal_var=False: Welch's t test\nprint(bmi_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTtestResult(statistic=np.float64(4.070541962914736), pvalue=np.float64(5.341044518168615e-05), df=np.float64(580.0943286106819))\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(tka.mean() - tha.mean(), bmi_test.confidence_interval())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1.7857239057239127 ConfidenceInterval(low=np.float64(0.9241010021357129), high=np.float64(2.6473468093121126))\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **t = 4.07:** the difference between the means is about 4 standard errors.\n- **df = 580.09:** Welch's test adjusts the degrees of freedom for unequal spreads, so they aren't a whole number.\n- **p < 0.001:** a difference this large would be very unlikely if the two groups had the same mean BMI.\n- **95% CI 0.92 to 2.65:** the CI for the **difference in means**, TKA minus THA.\n- **mean in group TKA 31.2, mean in group THA 29.5:** the two means.\n\n### Effect size and 95% CI\n\n- The **mean difference** with its CI is the effect size readers understand best: 1.8 kg/m² (95% CI 0.9 to 2.6).\n- **Hedges' g** expresses the difference in standard deviations, which lets you compare effects measured on different scales. As a rough guide, 0.2 is small, 0.5 medium and 0.8 large.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffectsize::hedges_g(bmi ~ procedure, data = cohort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHedges' g |       95% CI\n------------------------\n0.33      | [0.17, 0.49]\n\n- Estimated using pooled SD.\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ng = pg.compute_effsize(tka, tha, eftype=\"hedges\")\nprint(g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.3327551259636297\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pg.compute_esci(stat=g, nx=len(tka), ny=len(tha), eftype=\"hedges\", decimals=3))   # its 95% CI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[0.17  0.495]\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nHedges' g is 0.33: TKA patients' BMI is about a third of a standard deviation higher, a small effect.\n\n### How to report it\n\n> **Methods:** BMI was compared between procedures with Welch's unpaired t test.\n>\n> **Results:** Mean BMI was 31.2 kg/m² after TKA and 29.5 kg/m² after THA (difference 1.8 kg/m², 95% CI 0.9 to 2.6; Hedges' g = 0.33; p < 0.001).\n\n::: {.callout-warning}\n## ⚠️ Watch out: don't test the variances first\nAn old habit is to run a test of equal variances (such as Levene's) and then choose Student's or Welch's t test depending on the result. Don't: the two-step procedure distorts the p-value. Use Welch's test from the start. When the variances really are equal, it gives almost the same answer as Student's.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: Student's or Welch's?\n- **The default differs.** R's `t.test()` runs **Welch's** test unless you add `var.equal = TRUE`. scipy's `ttest_ind()` runs **Student's** test unless you add `equal_var=False`. Always set it explicitly in Python.\n- **The order of the groups.** R subtracts in the order of the factor levels (we put TKA first); scipy subtracts the second argument from the first.\n- **The CI for Hedges' g.** effectsize uses an exact method and pingouin an approximation, so the CIs can differ slightly (0.17 to 0.49 in R, 0.17 to 0.495 in Python). The estimates agree.\n:::\n\n## Mann-Whitney test {#mann-whitney}\n\n**The question:** Do men and women report different KOOS JR scores 1 year after knee replacement?\n\n### When to use it\n\n- The outcome is **skewed**, has a **ceiling or floor**, or is **ordinal**, and you're comparing **two independent groups**.\n- It asks whether values in one group tend to be **larger** than in the other: if you picked one patient from each group at random, how likely is the first to score higher?\n- It's the same test as the **Wilcoxon rank-sum test**. R calls it `wilcox.test()`.\n- If the outcome is roughly normal within each group → the [unpaired t test](#unpaired-t).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\nproms  <- read_csv(\"data/proms_long.csv\", show_col_types = FALSE)\n\nkoos_1yr <- proms |>\n  filter(instrument == \"KOOS JR\", visit == \"1yr\", !is.na(prom_score)) |>\n  left_join(select(cohort, case_id, sex), by = \"case_id\") |>\n  mutate(sex = factor(sex, levels = c(\"Male\", \"Female\")))   # men first: differences are men minus women\n\nggplot(koos_1yr, aes(sex, prom_score)) +\n  geom_boxplot(outlier.shape = NA) +\n  geom_jitter(width = 0.2, alpha = 0.4) +\n  labs(x = NULL, y = \"KOOS JR at 1 year\")\n```\n\n::: {.cell-output-display}\n![](06-two-unpaired-groups_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\nkoos_1yr |>\n  group_by(sex) |>\n  summarise(n = n(), median = median(prom_score),\n            q1 = quantile(prom_score, 0.25), q3 = quantile(prom_score, 0.75))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  sex        n median    q1    q3\n  <fct>  <int>  <dbl> <dbl> <dbl>\n1 Male     130   87.0  75.5  93.6\n2 Female   130   85    72.5  94.0\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport pingouin as pg\nimport matplotlib.pyplot as plt\nfrom scipy import stats\n\ncohort = pd.read_csv(\"data/cohort.csv\")\nproms = pd.read_csv(\"data/proms_long.csv\")\n\nkoos_1yr = proms[(proms[\"instrument\"] == \"KOOS JR\") & (proms[\"visit\"] == \"1yr\")].dropna(subset=[\"prom_score\"])\nkoos_1yr = koos_1yr.merge(cohort[[\"case_id\", \"sex\"]], on=\"case_id\")\nmen = koos_1yr.loc[koos_1yr[\"sex\"] == \"Male\", \"prom_score\"]\nwomen = koos_1yr.loc[koos_1yr[\"sex\"] == \"Female\", \"prom_score\"]\n\nfig, ax = plt.subplots(figsize=(5, 3))\nparts = ax.boxplot([men, women], tick_labels=[\"Male\", \"Female\"])   # naming the result keeps it out of the output\nax.set_ylabel(\"KOOS JR at 1 year\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![](06-two-unpaired-groups_files/figure-html/unnamed-chunk-14-1.png)\n:::\n\n```{.python .cell-code}\nprint(koos_1yr.groupby(\"sex\")[\"prom_score\"].describe()[[\"count\", \"25%\", \"50%\", \"75%\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        count     25%    50%     75%\nsex                                 \nFemale  130.0  72.525  85.00  93.975\nMale    130.0  75.500  86.95  93.650\n```\n\n\n:::\n:::\n\n:::\n\nBoth groups pile up toward the ceiling of 100, so medians are the fair summary. They're within 2 points of each other.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkoos_test <- wilcox.test(prom_score ~ sex, data = koos_1yr,\n                         exact = FALSE, correct = TRUE,   # see the R vs Python box\n                         conf.int = TRUE)                 # adds the Hodges-Lehmann estimate and CI\nkoos_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  prom_score by sex\nW = 8926.5, p-value = 0.4317\nalternative hypothesis: true location shift is not equal to 0\n95 percent confidence interval:\n -1.600048  4.399991\nsample estimates:\ndifference in location \n             0.8000403 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# pg.mwu() runs scipy's Mann-Whitney test and adds the rank-biserial effect size\nkoos_test = pg.mwu(men, women, method=\"asymptotic\", use_continuity=True)   # see the R vs Python box\nprint(koos_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      U_val alternative     p_val       RBC      CLES\nMWU  8926.5   two-sided  0.431661  0.056391  0.528195\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **W = 8926.5** (R) or **U_val = 8926.5** (Python): the Mann-Whitney U statistic for men, the number of (man, woman) pairs in which the man scored higher, counting ties as half. R calls it W.\n- **p = 0.432:** a difference like this would be common if men and women had the same distribution of scores.\n- **difference in location 0.80, 95% CI −1.60 to 4.40** (R only): the Hodges-Lehmann estimate, below.\n- **RBC = 0.056** (Python): the rank-biserial effect size, below.\n\n### Effect size and 95% CI\n\n- The **Hodges-Lehmann estimate** is the median of the differences between every man's score and every woman's score: a typical difference, in points.\n- The **rank-biserial correlation (r)** runs from −1 (every woman scored higher than every man) to +1 (the reverse). 0 means no tendency either way.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkoos_test$estimate                                       # Hodges-Lehmann estimate, men minus women\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndifference in location \n             0.8000403 \n```\n\n\n:::\n\n```{.r .cell-code}\nkoos_test$conf.int                                       # its 95% CI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.600048  4.399991\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::rank_biserial(prom_score ~ sex, data = koos_1yr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nr (rank biserial) |        95% CI\n---------------------------------\n0.06              | [-0.08, 0.19]\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# Hodges-Lehmann estimate: the median of every man-minus-woman difference\ndef hodges_lehmann(x, y):\n    return np.median(np.subtract.outer(np.asarray(x), np.asarray(y)))\n\nprint(hodges_lehmann(men, women))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.7999999999999972\n```\n\n\n:::\n\n```{.python .cell-code}\n# scipy has no CI for it, so use a bootstrap: recompute it on 9999 resampled datasets\nboot = stats.bootstrap((men.to_numpy(), women.to_numpy()), hodges_lehmann, vectorized=False,\n                       rng=np.random.default_rng(2026))\nprint(boot.confidence_interval)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfidenceInterval(low=np.float64(-1.7000000000000028), high=np.float64(4.400000000000006))\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(koos_test[\"RBC\"])                                  # rank-biserial r\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMWU    0.056391\nName: RBC, dtype: float64\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nMen scored 0.8 points higher (95% CI 1.6 points lower to 4.4 points higher), and r = 0.06 is close to zero. A difference of a few points either way is compatible with the data; a large one isn't.\n\n### How to report it\n\n> **Methods:** Because 1-year KOOS JR scores showed a ceiling effect, they were compared between men and women with the Mann-Whitney test, with the Hodges-Lehmann estimate of the difference and its 95% CI as the effect size.\n>\n> **Results:** KOOS JR at 1 year was a median of 87.0 points (IQR 75.5 to 93.7) in men and 85.0 (IQR 72.5 to 94.0) in women (Hodges-Lehmann difference 0.8 points, 95% CI −1.6 to 4.4; rank-biserial r = 0.06; p = 0.432).\n\n::: {.callout-warning}\n## ⚠️ Watch out: it isn't a test of medians\nThe Mann-Whitney test asks whether one group's values **tend to be larger**, not whether the medians differ. Two groups can have the same median and a significant Mann-Whitney test (if their shapes differ), or different medians and a non-significant one. Report the medians to describe the groups, but don't write \"the medians differed significantly\".\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: Mann-Whitney defaults\n- **Exact or approximate.** With ties (as here) both programs use a normal approximation. Without ties, R computes an exact p-value for groups under 50, scipy only for very small groups. We set `exact = FALSE` in R and `method=\"asymptotic\"` in Python so they always match.\n- **Continuity correction.** Both programs apply it by default for the approximation; we set it explicitly anyway.\n- **The Hodges-Lehmann CI.** R computes it by inverting the test; the Python code uses a bootstrap, a different method, so the two CIs differ slightly (−1.60 to 4.40 in R, −1.70 to 4.40 from the bootstrap).\n:::\n\n## Fisher's exact test and chi-square {#fisher-chi-square}\n\n**The question:** Are men more likely than women to be readmitted within 90 days?\n\n### When to use it\n\n- The outcome is **yes/no**, compared between **two independent groups**: a 2 × 2 table.\n- **Fisher's exact test** is valid for any sample size. The **chi-square test** is a large-sample approximation: use it only when every *expected* count is at least 5. When in doubt, use Fisher's test.\n- If patients were followed for different lengths of time and the event can happen at any time → the [log-rank test](#log-rank).\n\n### Look at the data first\n\nFor two yes/no variables, \"looking\" means the 2 × 2 table, with the percentage in each group.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\n\n# Put the comparison group first and the outcome \"yes\" first\nreadmit_table <- table(\n  sex        = factor(cohort$sex, levels = c(\"Male\", \"Female\")),\n  readmitted = factor(cohort$readmit_90d, levels = c(1, 0), labels = c(\"yes\", \"no\"))\n)\nreadmit_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        readmitted\nsex      yes  no\n  Male    12 245\n  Female  15 328\n```\n\n\n:::\n\n```{.r .cell-code}\nprop.table(readmit_table, margin = 1)    # row percentages: readmitted within each sex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        readmitted\nsex             yes         no\n  Male   0.04669261 0.95330739\n  Female 0.04373178 0.95626822\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nfrom scipy import stats\nfrom scipy.stats.contingency import odds_ratio\nfrom statsmodels.stats.proportion import confint_proportions_2indep\n\ncohort = pd.read_csv(\"data/cohort.csv\")\n\n# Put the comparison group first and the outcome \"yes\" (1) first\nreadmit_table = pd.crosstab(cohort[\"sex\"], cohort[\"readmit_90d\"]).loc[[\"Male\", \"Female\"], [1, 0]]\nprint(readmit_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nreadmit_90d   1    0\nsex                 \nMale         12  245\nFemale       15  328\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(pd.crosstab(cohort[\"sex\"], cohort[\"readmit_90d\"], normalize=\"index\"))   # row percentages\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nreadmit_90d         0         1\nsex                            \nFemale       0.956268  0.043732\nMale         0.953307  0.046693\n```\n\n\n:::\n:::\n\n:::\n\n12 of 257 men (4.7%) and 15 of 343 women (4.4%) were readmitted.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreadmit_fisher <- fisher.test(readmit_table)\nreadmit_fisher\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  readmit_table\np-value = 1\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n 0.4489199 2.5005234\nsample estimates:\nodds ratio \n  1.070895 \n```\n\n\n:::\n\n```{.r .cell-code}\nchisq.test(readmit_table)$expected       # all at least 5, so chi-square is also fine\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        readmitted\nsex         yes      no\n  Male   11.565 245.435\n  Female 15.435 327.565\n```\n\n\n:::\n\n```{.r .cell-code}\nreadmit_chisq <- chisq.test(readmit_table)\nreadmit_chisq\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  readmit_table\nX-squared = 2.249e-32, df = 1, p-value = 1\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nreadmit_fisher = stats.fisher_exact(readmit_table)\nprint(readmit_fisher.pvalue)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1.0\n```\n\n\n:::\n\n```{.python .cell-code}\nreadmit_chisq = stats.chi2_contingency(readmit_table)   # includes the expected counts\nprint(readmit_chisq.expected_freq)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[ 11.565 245.435]\n [ 15.435 327.565]]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(readmit_chisq.statistic, readmit_chisq.pvalue)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.0 1.0\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **Fisher's test, p-value = 1:** this table is exactly what you'd most expect if readmission were unrelated to sex. We report it as p > 0.999.\n- **odds ratio 1.07, 95% CI 0.45 to 2.50** (R): the effect size, below.\n- **Expected counts:** what each cell would hold if readmission were unrelated to sex. All are at least 5 (the smallest is 11.6), so the chi-square test is valid too.\n- **X-squared ≈ 0, p-value = 1:** the chi-square test, with Yates' continuity correction, agrees.\n\n::: {.callout-note collapse=\"true\"}\n## 🔍 Under the hood: Yates' continuity correction\nThe chi-square test treats counts as if they could take any value, but counts are whole numbers. For a 2 × 2 table, **Yates' correction** subtracts 0.5 from each |observed − expected| difference before squaring, which makes the p-value a little larger (more cautious) and closer to Fisher's. Here the observed counts are within 0.5 of the expected counts, so the corrected statistic is 0. Both R's `chisq.test()` and scipy's `chi2_contingency()` apply it to 2 × 2 tables by default; without it (`correct = FALSE`, `correction=False`) p = 0.863. Either is acceptable if you say which you used; with small counts, prefer Fisher's test.\n:::\n\n### Effect size and 95% CI\n\nTwo effect sizes, and it's worth reporting both:\n\n- The **risk difference**: the difference between the two percentages, in percentage points. It's what patients and clinicians understand.\n- The **odds ratio**: the odds of readmission for men divided by the odds for women. It's what logistic regression reports ([page 11](11-predict-from-one.qmd#logistic-regression)), so it's useful for comparing with other studies.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreadmit_fisher$estimate                  # odds ratio, men vs women\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nodds ratio \n  1.070895 \n```\n\n\n:::\n\n```{.r .cell-code}\nreadmit_fisher$conf.int                  # its 95% CI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4489199 2.5005234\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\nrisk <- prop.test(readmit_table, correct = FALSE)\nrisk$estimate                            # readmission rate in men, then in women\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    prop 1     prop 2 \n0.04669261 0.04373178 \n```\n\n\n:::\n\n```{.r .cell-code}\nrisk$conf.int                            # 95% CI for the risk difference, men minus women\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.03070963  0.03663129\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nreadmit_or = odds_ratio(readmit_table.to_numpy(), kind=\"conditional\")   # the same odds ratio as R\nprint(readmit_or.statistic, readmit_or.confidence_interval())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1.0708974256981205 ConfidenceInterval(low=0.44891984226859166, high=2.5006221137020836)\n```\n\n\n:::\n\n```{.python .cell-code}\nmen_yes, men_no = readmit_table.loc[\"Male\"]\nwomen_yes, women_no = readmit_table.loc[\"Female\"]\nprint(men_yes / (men_yes + men_no), women_yes / (women_yes + women_no))   # readmission rates\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.04669260700389105 0.043731778425655975\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(confint_proportions_2indep(men_yes, men_yes + men_no, women_yes, women_yes + women_no,\n                                 method=\"wald\", compare=\"diff\"))           # 95% CI, men minus women\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(np.float64(-0.03070963084956807), np.float64(0.03663128800603822))\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nMen's readmission rate was 0.3 percentage points higher (95% CI 3.1 points lower to 3.7 points higher), an odds ratio of 1.07 (95% CI 0.45 to 2.50).\n\n### How to report it\n\n> **Methods:** Categorical outcomes were compared with Fisher's exact test. Effect sizes are reported as risk differences with Wald 95% CIs and as odds ratios with exact 95% CIs.\n>\n> **Results:** Ninety-day readmission followed 4.7% of procedures in men and 4.4% in women (risk difference 0.3 percentage points, 95% CI −3.1 to 3.7; odds ratio 1.07, 95% CI 0.45 to 2.50; p > 0.999).\n\n::: {.callout-warning}\n## ⚠️ Watch out: \"no difference\" needs a narrow CI\nThe p-value is as large as it can be, but the odds ratio's CI runs from 0.45 to 2.50: the data are compatible with men having half the odds of readmission, or two and a half times the odds. With only 27 readmissions, this study can't tell. \"No significant difference\" is the honest wording; \"men and women have the same risk\" isn't.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: two different odds ratios\nscipy's `fisher_exact()` reports the simple **sample** odds ratio (a × d) / (b × c), 1.0710 here. R's `fisher.test()` reports the **conditional maximum-likelihood** odds ratio, 1.0709, which goes with its exact CI. Use `scipy.stats.contingency.odds_ratio(..., kind=\"conditional\")` to get R's number and CI. The two are always close; say which you report.\n:::\n\n## Log-rank test {#log-rank}\n\n**The question:** Is revision-free survival different between implant A and implant C?\n\n### When to use it\n\n- The outcome is **time until an event** (revision), patients were followed for different lengths of time, and you're comparing **two independent groups**.\n- It compares the whole survival curves, not the survival at one time point.\n- The **Mantel-Haenszel test** (or Mantel-Cox test) in the decision table is the same test under another name.\n- It's most powerful when one group's risk is a steady multiple of the other's over time (proportional hazards). If the curves cross, see [page 14](../survival/14-cox-regression.qmd#proportional-hazards).\n- To compare three or more groups, or to adjust for other variables → [Cox regression](08-three-plus-unmatched.qmd#cox).\n\n### Look at the data first\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(survival)\nlibrary(ggsurvfit)\n\ncohort <- read_csv(\"data/cohort.csv\", show_col_types = FALSE)\na_vs_c <- cohort |> filter(implant %in% c(\"A\", \"C\"))   # two groups; page 8 compares all three\n\nsurvfit2(Surv(followup_years, revised) ~ implant, data = a_vs_c, conf.type = \"log-log\") |>\n  ggsurvfit() +\n  add_confidence_interval() +\n  add_risktable() +\n  scale_ggsurvfit() +\n  labs(x = \"Years since surgery\", y = \"Revision-free survival\")\n```\n\n::: {.cell-output-display}\n![](06-two-unpaired-groups_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom lifelines import KaplanMeierFitter, CoxPHFitter\nfrom lifelines.statistics import logrank_test\nfrom lifelines.plotting import add_at_risk_counts\n\ncohort = pd.read_csv(\"data/cohort.csv\")\na_vs_c = cohort[cohort[\"implant\"].isin([\"A\", \"C\"])]   # two groups; page 8 compares all three\na = a_vs_c[a_vs_c[\"implant\"] == \"A\"]\nc = a_vs_c[a_vs_c[\"implant\"] == \"C\"]\n\nfig, ax = plt.subplots(figsize=(7, 4.5))\nkm_a = KaplanMeierFitter(label=\"A\").fit(a[\"followup_years\"], a[\"revised\"])\nkm_c = KaplanMeierFitter(label=\"C\").fit(c[\"followup_years\"], c[\"revised\"])\nkm_a.plot_survival_function(ax=ax)\nkm_c.plot_survival_function(ax=ax)\nax.set_xlabel(\"Years since surgery\")\nax.set_ylabel(\"Revision-free survival\")\nadd_at_risk_counts(km_a, km_c, ax=ax)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output-display}\n![](06-two-unpaired-groups_files/figure-html/unnamed-chunk-34-1.png)\n:::\n:::\n\n:::\n\nImplant C's curve falls faster from the start, and the gap keeps growing.\n\n### Run it\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimplant_logrank <- survdiff(Surv(followup_years, revised) ~ implant, data = a_vs_c)\nimplant_logrank\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nsurvdiff(formula = Surv(followup_years, revised) ~ implant, data = a_vs_c)\n\n            N Observed Expected (O-E)^2/E (O-E)^2/V\nimplant=A 246       25     41.9      6.84      20.5\nimplant=C 137       38     21.1     13.62      20.5\n\n Chisq= 20.5  on 1 degrees of freedom, p= 6e-06 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimplant_logrank = logrank_test(a[\"followup_years\"], c[\"followup_years\"],\n                               event_observed_A=a[\"revised\"], event_observed_B=c[\"revised\"])\nprint(implant_logrank.test_statistic, implant_logrank.p_value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n20.534618183417702 5.856248429692094e-06\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### Read the output\n\n- **N:** patients in each group (246 with implant A, 137 with C).\n- **Observed / Expected:** the revisions each group had, and the number it would have had if both implants carried the same risk. Implant C had 38 revisions where 21.1 were expected; implant A had 25 where 41.9 were expected.\n- **Chisq = 20.5 on 1 degree of freedom, p < 0.001:** curves this different would be very unlikely if the implants had the same revision risk.\n\n### Effect size and 95% CI\n\nThe log-rank test has no effect size of its own. The usual one is the **hazard ratio** from a Cox model: how many times higher the risk of revision is, at any moment, with implant C than with implant A. [Page 14](../survival/14-cox-regression.qmd) explains Cox regression in full.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimplant_cox <- coxph(Surv(followup_years, revised) ~ implant, data = a_vs_c)\nsummary(implant_cox)$conf.int    # exp(coef) is the hazard ratio, C vs A\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         exp(coef) exp(-coef) lower .95 upper .95\nimplantC  3.039405  0.3290118  1.833133  5.039449\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimplant_cox = CoxPHFitter().fit(a_vs_c[[\"followup_years\", \"revised\", \"implant\"]],\n                                duration_col=\"followup_years\", event_col=\"revised\", formula=\"implant\")\nprint(implant_cox.summary[[\"exp(coef)\", \"exp(coef) lower 95%\", \"exp(coef) upper 95%\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              exp(coef)  exp(coef) lower 95%  exp(coef) upper 95%\ncovariate                                                        \nimplant[T.C]   3.039403             1.833132             5.039447\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\nThe hazard of revision was about three times higher with implant C (hazard ratio 3.04, 95% CI 1.83 to 5.04).\n\nThe Results sentence also gives each implant's revision-free survival at 5 years, with its CI:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvival_5 <- summary(survfit(Surv(followup_years, revised) ~ implant, data = a_vs_c,\n                              conf.type = \"log-log\"), times = 5)\nsurvival_5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(followup_years, revised) ~ implant, data = a_vs_c, \n    conf.type = \"log-log\")\n\n                implant=A \n        time       n.risk      n.event     survival      std.err lower 95% CI \n      5.0000     104.0000      21.0000       0.8986       0.0214       0.8475 \nupper 95% CI \n      0.9332 \n\n                implant=C \n        time       n.risk      n.event     survival      std.err lower 95% CI \n      5.0000      52.0000      33.0000       0.7114       0.0442       0.6146 \nupper 95% CI \n      0.7880 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nfor km in [km_a, km_c]:\n    ci_5 = km.confidence_interval_survival_function_.loc[:5].iloc[-1]   # last step at or before 5 years\n    print(km.label, km.survival_function_at_times(5).iloc[0], ci_5.to_list())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nA 0.898565220702258 [0.8474849510472157, 0.9332064896432269]\nC 0.7113766756342532 [0.6145981267706867, 0.7880063762308811]\n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n\n### How to report it\n\n> **Methods:** Revision-free survival was estimated with the Kaplan-Meier method and compared between implants with the log-rank test. Hazard ratios were estimated with Cox proportional hazards regression.\n>\n> **Results:** Revision-free survival at 5 years was 71.1% (95% CI 61.5% to 78.8%) with implant C and 89.9% (95% CI 84.7% to 93.3%) with implant A (log-rank p < 0.001; hazard ratio 3.04, 95% CI 1.83 to 5.04).\n\n::: {.callout-warning}\n## ⚠️ Watch out: overlapping CIs aren't a test\nComparing the two curves' CIs at one time point (\"the 5-year CIs overlap, so there's no difference\") isn't a valid test, and neither is comparing the crude percentages revised. Use the log-rank test on the whole curves. And as on [page 4](04-describe-one-group.qmd#kaplan-meier), deaths here are treated as censored; [page 13](../survival/13-kaplan-meier.qmd#competing-risks) covers competing risks.\n:::\n\n::: {.callout-tip}\n## 🔀 R vs Python: one formula or two groups\nR's `survdiff()` takes a formula with a grouping variable. lifelines' `logrank_test()` takes each group's follow-up times and events separately (`multivariate_logrank_test()` takes a grouping column). They compute the same test. Both Cox models handle tied revision times with Efron's method, so the hazard ratios agree.\n:::\n\n\n\n## Exercises {#exercises}\n\nThe solutions use the packages and data loaded in the sections above, so run the page from the top first.\n\n**1.** Compare **operative time** between TKA and THA with Welch's t test. Report the mean difference with its 95% CI.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nop_data <- cohort |> mutate(procedure = factor(procedure, levels = c(\"TKA\", \"THA\")))   # TKA first\nt.test(op_time_min ~ procedure, data = op_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  op_time_min by procedure\nt = 6.5619, df = 584.5, p-value = 1.172e-10\nalternative hypothesis: true difference in means between group TKA and group THA is not equal to 0\n95 percent confidence interval:\n  5.966969 11.064681\nsample estimates:\nmean in group TKA mean in group THA \n         88.31212          79.79630 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nop_tka = cohort.loc[cohort[\"procedure\"] == \"TKA\", \"op_time_min\"]\nop_tha = cohort.loc[cohort[\"procedure\"] == \"THA\", \"op_time_min\"]\nop_test = stats.ttest_ind(op_tka, op_tha, equal_var=False)\nprint(op_test, op_tka.mean() - op_tha.mean(), op_test.confidence_interval())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTtestResult(statistic=np.float64(6.561902572082705), pvalue=np.float64(1.1720541401070868e-10), df=np.float64(584.4986684475243)) 8.515824915824922 ConfidenceInterval(low=np.float64(5.966969137476641), high=np.float64(11.064680694173202))\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Mean operative time was 88.3 minutes for TKA and 79.8 minutes for THA (difference 8.5 minutes, 95% CI 6.0 to 11.1; p < 0.001).\n:::\n\n**2.** A colleague wants to know whether **length of stay** differs between Site A and Site B. Which test would you choose, and what do you find?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nLength of stay is strongly skewed, with most patients going home on day 0 or 1: the **Mann-Whitney test**.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlos_test <- wilcox.test(los_days ~ site, data = cohort, exact = FALSE, correct = TRUE)\nlos_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  los_days by site\nW = 49516, p-value = 0.02023\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::rank_biserial(los_days ~ site, data = cohort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nr (rank biserial) |       95% CI\n--------------------------------\n0.10              | [0.01, 0.19]\n```\n\n\n:::\n\n```{.r .cell-code}\ncohort |> group_by(site) |> summarise(median = median(los_days),\n                                      q1 = quantile(los_days, 0.25), q3 = quantile(los_days, 0.75))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  site   median    q1    q3\n  <chr>   <dbl> <dbl> <dbl>\n1 Site A      1     0     2\n2 Site B      0     0     1\n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nsite_a = cohort.loc[cohort[\"site\"] == \"Site A\", \"los_days\"]\nsite_b = cohort.loc[cohort[\"site\"] == \"Site B\", \"los_days\"]\nprint(pg.mwu(site_a, site_b, method=\"asymptotic\", use_continuity=True))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       U_val alternative     p_val       RBC      CLES\nMWU  49516.5   two-sided  0.020227  0.101591  0.550795\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(cohort.groupby(\"site\")[\"los_days\"].describe()[[\"25%\", \"50%\", \"75%\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        25%  50%  75%\nsite                 \nSite A  0.0  1.0  2.0\nSite B  0.0  0.0  1.0\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** The median length of stay was 1 day (IQR 0 to 2) at Site A and 0 days (IQR 0 to 1) at Site B (rank-biserial r = 0.10; p = 0.020).\n\nNotice that we didn't report a Hodges-Lehmann estimate. With whole days and so many ties, a third of the Site A − Site B differences are exactly 0 days (34%), and fewer than half are positive (38%; 28% are negative), so the middle difference, and with it the estimate, is 0 even though Site A's stays tend to run longer. For data like these, the medians with IQRs and the rank-biserial r describe the difference better.\n:::\n\n**3.** Is the 90-day complication rate different after general and spinal anesthesia? Choose the test, run it, and write the Results sentence with the risk difference and odds ratio.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\nYes/no outcome, two independent groups: **Fisher's exact test**.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomp_table <- table(anesthesia = factor(cohort$anesthesia, levels = c(\"general\", \"spinal\")),\n                    complication = factor(cohort$complication_90d, levels = c(1, 0), labels = c(\"yes\", \"no\")))\ncomp_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          complication\nanesthesia yes  no\n   general  18 132\n   spinal   33 417\n```\n\n\n:::\n\n```{.r .cell-code}\nfisher.test(comp_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  comp_table\np-value = 0.09028\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n 0.8817979 3.2681160\nsample estimates:\nodds ratio \n  1.721379 \n```\n\n\n:::\n\n```{.r .cell-code}\nprop.test(comp_table, correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  comp_table\nX-squared = 3.1501, df = 1, p-value = 0.07592\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.01064384  0.10397718\nsample estimates:\n    prop 1     prop 2 \n0.12000000 0.07333333 \n```\n\n\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\ncomp_table = pd.crosstab(cohort[\"anesthesia\"], cohort[\"complication_90d\"]).loc[[\"general\", \"spinal\"], [1, 0]]\nprint(comp_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncomplication_90d   1    0\nanesthesia               \ngeneral           18  132\nspinal            33  417\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(stats.fisher_exact(comp_table).pvalue)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.09028001108050204\n```\n\n\n:::\n\n```{.python .cell-code}\ncomp_or = odds_ratio(comp_table.to_numpy(), kind=\"conditional\")\nprint(comp_or.statistic, comp_or.confidence_interval())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1.7214088498869067 ConfidenceInterval(low=0.8818085597179384, high=3.268052684960482)\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(confint_proportions_2indep(18, 150, 33, 450, method=\"wald\", compare=\"diff\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(np.float64(-0.01064384473491671), np.float64(0.10397717806825003))\n```\n\n\n:::\n:::\n\n:::\n\n> **Results:** Complications within 90 days followed 12.0% of procedures under general and 7.3% under spinal anesthesia (risk difference 4.7 percentage points, 95% CI −1.1 to 10.4; odds ratio 1.72, 95% CI 0.88 to 3.27; p = 0.090).\n:::\n",
    "supporting": [
      "06-two-unpaired-groups_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}